"use client";
import { useEffect, useMemo, useState } from "react";
import { academyLessonCount } from "@/data/academy";
import { detectiveCases } from "@/data/detective/cases";
import { missions } from "@/data/missions";
import { moneyFlowScenarios } from "@/data/money-flow/scenarios";
import { loadAcademyProgress } from "@/lib/academy/progress";
import { createArenaProfile, loadArenaProfile, skillIds } from "@/lib/arena/profile";
import { loadDetectiveProgress } from "@/lib/storage/detective";
import { loadMissionsProgress } from "@/lib/storage/missions";
import { loadMoneyFlowProgress } from "@/lib/storage/money-flow";
import type { ArenaProfile, Locale } from "@/types";

type Snapshot={arena:ArenaProfile;lessons:number;missions:number;detective:number;flows:number};
const blank:Snapshot={arena:createArenaProfile(),lessons:0,missions:0,detective:0,flows:0};
export function ProgressDashboard({locale}:{locale:Locale}){const ar=locale==='ar',[snapshot,setSnapshot]=useState(blank);useEffect(()=>{const academy=loadAcademyProgress(),mission=loadMissionsProgress(),detective=loadDetectiveProgress(),flow=loadMoneyFlowProgress();setSnapshot({arena:loadArenaProfile(),lessons:academy.completedLessonIds.length,missions:Object.values(mission.records).filter(x=>x.completed).length,detective:Object.values(detective.records).filter(x=>x.solved).length,flows:Object.values(flow.records).filter(x=>x.completed).length});},[]);const skills=useMemo(()=>skillIds.map(id=>snapshot.arena.skills[id]).sort((a,b)=>b.score-a.score),[snapshot]);const completed=snapshot.lessons+snapshot.missions+snapshot.detective+snapshot.flows+snapshot.arena.uniqueCases,total=academyLessonCount+missions.length+detectiveCases.length+moneyFlowScenarios.length+Math.max(snapshot.arena.uniqueCases,1),overall=Math.round((completed/Math.max(total,1))*100),xp=snapshot.arena.attempts.reduce((sum,item)=>sum+item.score,0)+snapshot.lessons*50+snapshot.missions*100+snapshot.detective*150+snapshot.flows*100;return <section className="dc-progress"><header><span>{ar?'ملف المتعلم':'LEARNER PROFILE'}</span><h1>{ar?'تقدمك المحاسبي':'Your accounting progress'}</h1><p>{ar?'صورة موحدة لما تعلمته وما أتقنته وما يحتاج إلى تدريب إضافي.':'One view of what you learned, mastered, and should practice next.'}</p></header><div className="dc-progress-grid"><article><small>{ar?'النتيجة الكلية':'Overall score'}</small><strong>{overall}%</strong></article><article><small>XP</small><strong>{xp}</strong></article><article><small>{ar?'السلسلة':'Streak'}</small><strong>{snapshot.arena.currentStreak}</strong></article><article><small>{ar?'جاهزية العمل':'Readiness'}</small><strong>{snapshot.arena.professionalScore}/1000</strong></article><article><small>{ar?'دروس مكتملة':'Lessons'}</small><strong>{snapshot.lessons}/{academyLessonCount}</strong></article><article><small>{ar?'مهام مكتملة':'Missions'}</small><strong>{snapshot.missions}/{missions.length}</strong></article><article><small>{ar?'قضايا محلولة':'Cases'}</small><strong>{snapshot.detective}/{detectiveCases.length}</strong></article><article><small>{ar?'تدفقات مكتملة':'Money flows'}</small><strong>{snapshot.flows}/{moneyFlowScenarios.length}</strong></article></div><div className="dc-progress-panels"><section className="dc-progress-panel"><h2>{ar?'أقوى المهارات':'Strong areas'}</h2>{skills.slice(0,5).map(skill=><div key={skill.id}><span>{skill.id.replaceAll('-',' ')}</span><b>{skill.score}%</b><i><span style={{width:`${skill.score}%`}}/></i></div>)}</section><section className="dc-progress-panel"><h2>{ar?'تحتاج تدريبًا':'Needs practice'}</h2>{skills.slice(-5).reverse().map(skill=><div key={skill.id}><span>{skill.id.replaceAll('-',' ')}</span><b>{skill.score}%</b><i><span style={{width:`${skill.score}%`}}/></i></div>)}</section></div></section>}
