import { w } from '@/lib/campaign/model';
import {supplierInvoiceWork,supplierTotal} from './supplier-invoice-work';
import type { AccountingCaseDefinition } from './model';

export const FIRST_SHIFT_SCENARIO_VERSION=1;
export const FIRST_SHIFT_RUBRIC_VERSION=1;

export const firstShiftCases:AccountingCaseDefinition[]=[
 {id:'supplier-invoice',chapterId:1,scenarioVersion:1,title:w('Supplier invoice review','مراجعة فاتورة مورد'),businessContext:w('Alpha Supplies delivered office furniture on credit. Accounts Payable needs your review before recording the liability.','ورد أثاث مكتبي من Alpha Supplies على الحساب. حسابات الموردين تحتاج مراجعتك قبل إثبات الالتزام.'),managerRequest:w('Match the invoice with the approved order and receiving report. Check the company policy, prepare a defensible entry, then decide whether to post or stop.','طابق الفاتورة مع أمر الشراء وإذن الاستلام. راجع سياسة الشركة وجهّز قيدًا يمكن تبريره ثم قرر الترحيل أو الإيقاف.'),primaryDocumentId:'supplier-invoice',requiresJournal:true,accountingReference:supplierInvoiceWork.invoiceNumber,managerGuidance:[w('Start with the receiving report. It establishes what physically arrived.','ابدأ بإذن الاستلام؛ هو الدليل على الكميات التي وصلت فعليًا.'),w('Compare each quantity and price with the approved order before you commit a liability.','قارن كل كمية وسعر بأمر الشراء قبل إثبات التزام على الشركة.')],documents:[
  {id:'supplier-invoice',kind:'source',title:w('Supplier Invoice INV-1048','فاتورة المورد INV-1048'),reference:'INV-1048',summary:w(`Alpha Supplies requests EGP ${supplierTotal().toLocaleString('en-US')} for three desks and five chairs, payable in 30 days.`,`تطلب Alpha Supplies مبلغ ${supplierTotal().toLocaleString('ar-EG')} جنيه مقابل ثلاثة مكاتب وخمسة كراسٍ، يستحق خلال ٣٠ يومًا.`),required:true,facts:[{label:w('Supplier','المورد'),value:w('Alpha Supplies','Alpha Supplies')},{label:w('Purchase order','أمر الشراء'),value:w('PO-771','PO-771')},{label:w('Desks','المكاتب'),value:w('3 × EGP 30,000','٣ × ٣٠٬٠٠٠ جنيه')},{label:w('Chairs','الكراسي'),value:w('5 × EGP 2,000','٥ × ٢٬٠٠٠ جنيه')},{label:w('Total','الإجمالي'),value:w('EGP 100,000','١٠٠٬٠٠٠ جنيه')},{label:w('Payment','السداد'),value:w('Net 30','آجل ٣٠ يومًا')}]},
  {id:'po-771',kind:'purchase_order',title:w('Purchase Order PO-771','أمر شراء PO-771'),reference:'PO-771',summary:w('Approved order for three desks and five chairs from Alpha Supplies.','أمر معتمد لشراء ٣ مكاتب و٥ كراسٍ من Alpha Supplies.'),required:true,facts:[{label:w('Supplier','المورد'),value:w('Alpha Supplies','Alpha Supplies')},{label:w('Approved lines','البنود المعتمدة'),value:w('3 desks × 30,000 · 5 chairs × 2,000','٣ مكاتب × ٣٠٬٠٠٠ · ٥ كراسٍ × ٢٬٠٠٠')},{label:w('Approved total','الإجمالي المعتمد'),value:w('EGP 100,000','١٠٠٬٠٠٠ جنيه')},{label:w('Payment','السداد'),value:w('30 days after receipt','بعد الاستلام بـ٣٠ يومًا')}]},
  {id:'grn-771',kind:'goods_receipt',title:w('Goods Receipt GRN-771','إذن استلام GRN-771'),reference:'GRN-771',summary:w('Warehouse confirmed all desks and chairs were received in good condition.','المخزن أكد استلام كل المكاتب والكراسي بحالة جيدة.'),required:true,facts:[{label:w('Related order','أمر الشراء المرتبط'),value:w('PO-771','PO-771')},{label:w('Received','المستلم'),value:w('3 desks · 5 chairs','٣ مكاتب · ٥ كراسٍ')},{label:w('Warehouse status','حالة المخزن'),value:w('Accepted in full','مقبول بالكامل')}]},
  {id:'supplier-policy',kind:'policy',title:w('Purchasing control policy','سياسة رقابة المشتريات'),reference:'POL-AP-01',summary:w('A supplier liability needs an approved PO, receiving evidence and a valid invoice. Tax and freight are not charged on this introductory source file; do not invent them.','إثبات التزام المورد يتطلب أمر شراء معتمدًا وإذن استلام وفاتورة صحيحة. لا تتضمن هذه الحالة التمهيدية ضريبة أو شحنًا؛ لا تُنشئ مبلغًا غير موجود.'),required:false,facts:[{label:w('PO and GRN','أمر الشراء والاستلام'),value:w('Both required before posting','كلاهما مطلوب قبل الترحيل')},{label:w('Invoice amount','مبلغ الفاتورة'),value:w('EGP 100,000 net; no VAT or freight lines','١٠٠٬٠٠٠ جنيه؛ دون بنود ضريبة أو شحن')}]}
 ],matchingFields:[
  {id:'supplier',label:w('Supplier identity','هوية المورد'),documentIds:['supplier-invoice','po-771'],expected:'matched',detail:w('The invoice and approved PO both name Alpha Supplies.','الفاتورة وأمر الشراء المعتمد يحملان اسم Alpha Supplies.')},
  {id:'order-reference',label:w('Order reference','مرجع أمر الشراء'),documentIds:['supplier-invoice','po-771','grn-771'],expected:'matched',detail:w('Invoice and receiving report both reference PO-771.','تشير الفاتورة وإذن الاستلام إلى PO-771.')},
  {id:'quantities',label:w('Ordered and received quantities','الكميات المطلوبة والمستلمة'),documentIds:['supplier-invoice','po-771','grn-771'],expected:'matched',detail:w('Three desks and five chairs appear on all three documents.','تظهر ٣ مكاتب و٥ كراسٍ في المستندات الثلاثة.')},
  {id:'price',label:w('Price and total','السعر والإجمالي'),documentIds:['supplier-invoice','po-771'],expected:'matched',detail:w('3 × 30,000 + 5 × 2,000 = EGP 100,000. No tax or freight is billed.','٣ × ٣٠٬٠٠٠ + ٥ × ٢٬٠٠٠ = ١٠٠٬٠٠٠ جنيه. لا توجد ضريبة أو شحن بالفاتورة.')},
 ],actions:[{id:'post',label:w('Post the liability','سجّل العملية'),description:w('The reviewed file and your journal workpaper support the liability.','المستندات والقيد المُعد يدعمان إثبات الالتزام.')},{id:'hold',label:w('Hold the invoice','أوقف العملية مؤقتًا'),description:w('Protect the ledger while an inconsistency is investigated.','احمِ الدفتر إلى حين فحص الاختلاف.')},{id:'request_information',label:w('Request information','اطلب معلومات'),description:w('Ask Procurement or the warehouse for missing support.','اطلب من المشتريات أو المخزن مستندًا أو توضيحًا ناقصًا.')},{id:'escalate',label:w('Escalate to Kareem','صعّد للمدير'),description:w('Send a material control issue to Kareem for review.','أرسل مشكلة رقابية جوهرية إلى كريم للمراجعة.')}]},
 {id:'customer-receipt',chapterId:1,scenarioVersion:1,title:w('Customer receipt allocation','تسوية تحصيل عميل'),businessContext:w('A bank transfer arrived from Elite Stores. Receivables needs to know which open item it settles.','وصل تحويل بنكي من إيليت ستورز. حسابات العملاء محتاجة تعرف التحويل بيسدد أي رصيد مفتوح.'),managerRequest:w('Match the transfer to the customer file before you clear the receivable. Do not treat a collection as new revenue.','طابق التحويل مع ملف العميل قبل ما تقفل المديونية. ما تعتبرش التحصيل إيراد جديد.'),primaryDocumentId:'customer-receipt',requiresJournal:true,accountingReference:'REC-4587',managerGuidance:[w('Check the bank advice for the payment reference.','راجع إشعار البنك عشان تعرف مرجع التحويل.'),w('Match that reference to the customer invoice and outstanding balance.','طابق المرجع مع فاتورة العميل والرصيد المستحق.')],documents:[
  {id:'customer-receipt',kind:'source',title:w('Customer Receipt REC-4587','سند قبض العميل REC-4587'),reference:'REC-4587',summary:w('Receipt prepared for an EGP 75,000 bank transfer from Elite Stores.','سند قبض لتحويل بنكي بقيمة ٧٥٬٠٠٠ جنيه من إيليت ستورز.'),required:true,facts:[{label:w('Method','الطريقة'),value:w('Bank transfer','تحويل بنكي')},{label:w('Amount','المبلغ'),value:w('EGP 75,000','٧٥٬٠٠٠ جنيه')}]},
  {id:'bank-advice-312',kind:'bank_advice',title:w('Bank Advice BA-312','إشعار البنك BA-312'),reference:'BA-312',summary:w('The bank credited Mizan Trading and included invoice SI-2041 as the payment reference.','البنك أضاف المبلغ لحساب ميزان وذكر الفاتورة SI-2041 كمرجع للسداد.'),required:true,facts:[{label:w('Value date','تاريخ القيمة'),value:w('12 Mar 2024','١٢ مارس ٢٠٢٤')},{label:w('Reference','المرجع'),value:w('SI-2041','SI-2041')}]},
  {id:'sales-invoice-2041',kind:'customer_invoice',title:w('Customer Invoice SI-2041','فاتورة العميل SI-2041'),reference:'SI-2041',summary:w('Elite Stores has one open invoice for exactly EGP 75,000.','لدى إيليت ستورز فاتورة واحدة مفتوحة بقيمة ٧٥٬٠٠٠ جنيه بالضبط.'),required:true,facts:[{label:w('Open balance','الرصيد المفتوح'),value:w('EGP 75,000','٧٥٬٠٠٠ جنيه')},{label:w('Status','الحالة'),value:w('Unpaid before transfer','غير مسددة قبل التحويل')}]}
 ],actions:[{id:'post',label:w('Allocate and post','خصص ورحّل'),description:w('Clear the matched receivable against the bank receipt.','اقفل رصيد العميل المطابق مقابل التحصيل البنكي.')},{id:'hold',label:w('Hold as unidentified cash','أوقفه كتحصيل غير معرف'),description:w('Keep the receipt unallocated until its owner is confirmed.','احتفظ بالتحصيل دون تخصيص لحين تأكيد صاحبه.')},{id:'contact_customer',label:w('Contact the customer','تواصل مع العميل'),description:w('Ask which invoice the transfer was intended to settle.','اسأل العميل عن الفاتورة المقصود سدادها.')}]},
 {id:'office-expense',chapterId:1,scenarioVersion:1,title:w('Petty cash expense review','مراجعة مصروف صندوق'),businessContext:w('A petty-cash voucher and store receipt arrived from Administration. The expense needs classification in the current month.','وصل سند صرف وإيصال متجر من الإدارة. المصروف محتاج تصنيف في الشهر الحالي.'),managerRequest:w('Check what was bought, who paid, and whether the cost belongs to this month before you post it.','راجع إيه اللي اتشترى، واتدفع منين، وهل التكلفة تخص الشهر ده قبل الترحيل.'),primaryDocumentId:'office-expense',requiresJournal:true,accountingReference:'PV-2201',managerGuidance:[w('The cash voucher tells you which payment source moved.','سند الصرف يوضح مصدر الدفع اللي اتحرك.'),w('The receipt and expense policy tell you whether this is an asset or a current office expense.','الإيصال وسياسة المصروفات يوضحوا هل دي أصل ولا مصروف مكتب حالي.')],documents:[
  {id:'office-expense',kind:'source',title:w('Office Expense PV-2201','مصروف المكتب PV-2201'),reference:'PV-2201',summary:w('Administration submitted stationery and office tools for EGP 2,500.','الإدارة قدمت أدوات كتابية ومكتبية بقيمة ٢٬٥٠٠ جنيه.'),required:true,facts:[{label:w('Period','الفترة'),value:w('Current month','الشهر الحالي')},{label:w('Amount','المبلغ'),value:w('EGP 2,500','٢٬٥٠٠ جنيه')}]},
  {id:'petty-cash-2201',kind:'cash_voucher',title:w('Petty Cash Voucher PC-2201','سند صرف صندوق PC-2201'),reference:'PC-2201',summary:w('Cashier paid QuickMart immediately from petty cash.','أمين الصندوق دفع لكويك مارت فورًا من العهدة النقدية.'),required:true,facts:[{label:w('Paid by','الدافع'),value:w('Petty cash cashier','أمين الصندوق')},{label:w('Status','الحالة'),value:w('Paid','مدفوع')}]},
  {id:'expense-policy',kind:'policy',title:w('Expense Classification Note','مذكرة تصنيف المصروفات'),reference:'POL-OFFICE-01',summary:w('Consumable stationery below the capitalization threshold is expensed when used.','الأدوات المكتبية المستهلكة الأقل من حد الرسملة تحمل كمصروف عند الاستخدام.'),required:true,facts:[{label:w('Capitalization threshold','حد الرسملة'),value:w('EGP 10,000','١٠٬٠٠٠ جنيه')},{label:w('Category','التصنيف'),value:w('Office supplies','أدوات مكتبية')}]}
 ],actions:[{id:'post',label:w('Post the expense','رحّل المصروف'),description:w('Classify the current-period cost and clear petty cash.','صنف تكلفة الفترة الحالية واقفل حركة الصندوق.')},{id:'hold',label:w('Hold the voucher','أوقف سند الصرف'),description:w('Stop processing because support is incomplete.','أوقف المعالجة لأن المستندات غير مكتملة.')},{id:'request_information',label:w('Request information','اطلب معلومات'),description:w('Ask Administration for missing business context.','اطلب من الإدارة بيانات العمل الناقصة.')}]}
];

export const getFirstShiftCase=(id:string)=>firstShiftCases.find(item=>item.id===id);
