import type { GameState,Words } from '@/lib/campaign/model';
import { caseworkState } from './engine';
import { firstShiftCases,getFirstShiftCase } from './first-shift-cases';
import type { CasePerformance,GameplayEvent,PerformanceDimensions } from './model';

const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
const before=(events:GameplayEvent[],event:GameplayEvent|undefined,type:GameplayEvent['eventType'])=>event?events.slice(0,events.indexOf(event)).filter(item=>item.eventType===type):events.filter(item=>item.eventType===type);
export function projectCasePerformance(state:GameState,caseId:string):CasePerformance{
 const work=caseworkState(state),runtime=work.cases[caseId],definition=getFirstShiftCase(caseId),events=work.events.filter(item=>item.caseId===caseId),submissions=events.filter(item=>item.eventType==='entry_submitted'),firstSubmission=submissions[0],correct=submissions.find(item=>item.outcome==='correct'),firstPost=events.find(item=>item.eventType==='case_action_selected'&&item.payload.action==='post'),supporting=definition?.documents.filter(item=>item.kind!=='source'&&item.required)??[],inspected=new Set(events.filter(item=>item.eventType==='supporting_document_inspected').map(item=>String(item.payload.documentId))),inspectedBeforePost=new Set(before(events,firstPost,'supporting_document_inspected').map(item=>String(item.payload.documentId))),help=events.filter(item=>item.eventType==='manager_help_requested').length,blockedPosts=events.filter(item=>item.eventType==='case_action_selected'&&item.payload.action==='post'&&item.outcome==='blocked').length,otherActions=events.filter(item=>item.eventType==='case_action_selected'&&item.payload.action!=='post').length;
 const accuracy=!submissions.length?0:correct?100-(submissions.length-1)*20:0,investigation=supporting.length?inspectedBeforePost.size/supporting.length*100:100,documentation=supporting.length?inspected.size/supporting.length*100:100,independence=100-help*20,riskAwareness=blockedPosts?65:100,accountingJudgment=correct?100-blockedPosts*15-otherActions*5:Math.max(0,40-blockedPosts*10),dimensions={accuracy:clamp(accuracy),independence:clamp(independence),investigation:clamp(investigation),riskAwareness:clamp(riskAwareness),documentation:clamp(documentation),accountingJudgment:clamp(accountingJudgment)};
 return{caseId,attemptId:runtime?.attemptId??`first-shift/${caseId}/attempt-1`,...dimensions,overall:clamp(dimensions.accuracy*.3+dimensions.accountingJudgment*.25+dimensions.investigation*.2+dimensions.documentation*.1+dimensions.riskAwareness*.1+dimensions.independence*.05),submissions:submissions.length,managerAssistance:help,supportingDocumentsInspected:inspected.size,supportingDocumentsRequired:supporting.length,firstAttemptCorrect:firstSubmission?firstSubmission.outcome==='correct':null,resolved:runtime?.status==='resolved'};
}
export function projectShiftPerformance(state:GameState):PerformanceDimensions&{cases:CasePerformance[];managerAssistance:number;resolvedCases:number}{const cases=firstShiftCases.map(item=>projectCasePerformance(state,item.id)),resolved=cases.filter(item=>item.resolved),average=(key:keyof PerformanceDimensions)=>resolved.length?Math.round(resolved.reduce((sum,item)=>sum+item[key],0)/resolved.length):0;return{accuracy:average('accuracy'),independence:average('independence'),investigation:average('investigation'),riskAwareness:average('riskAwareness'),documentation:average('documentation'),accountingJudgment:average('accountingJudgment'),overall:average('overall'),cases,managerAssistance:cases.reduce((sum,item)=>sum+item.managerAssistance,0),resolvedCases:resolved.length};}
export function kareemPerformanceFeedback(state:GameState):Words{const performance=projectShiftPerformance(state);if(performance.accuracy>=90&&performance.independence>=80&&performance.investigation>=90)return{en:'You handled the files like an accountant: verify first, then post with confidence.',ar:'تعاملت مع الملفات كمحاسب: راجعت الأول، وبعدها رحّلت بثقة.'};if(performance.accuracy>=80&&performance.managerAssistance>=3)return{en:'The work is correct. Next shift, trust your file review before asking for confirmation.',ar:'الشغل صحيح. الوردية الجاية ثق أكتر في مراجعتك للملف قبل ما تطلب تأكيد.'};if(performance.accuracy>=60)return{en:'You corrected the work and protected the ledger. Slow down at the first review and follow the supporting documents.',ar:'صححت الشغل وحميت الدفتر. خد وقتك في أول مراجعة واتبع المستندات المؤيدة.'};return{en:'You completed the shift, but the review trail needs more discipline before posting.',ar:'خلصت الوردية، لكن مسار المراجعة محتاج انضباط أكتر قبل الترحيل.'};}
