import{describe,expect,it}from'vitest';
import{bootcampMissions,getBootcampMission}from'@/lib/bootcamp/catalog';
import{bootcampMissionReady,bootcampProgress,completeBootcampMission,createBootcampState,isBootcampMissionUnlocked,migrateBootcampState,recordBootcampInteraction}from'@/lib/bootcamp/engine';
import type{BootcampState}from'@/lib/bootcamp/model';

const solve=(state:BootcampState,id:BootcampState['currentMissionId'])=>{const mission=getBootcampMission(id)!;let next=state;for(const action of mission.entries??mission.interactions.filter(item=>item.correct))next=recordBootcampInteraction(next,id,action.id,true);return completeBootcampMission(next,id,0)};

describe('Accounting Bootcamp engine',()=>{
 it('defines the ten ordered practice-only missions ending with the Mizan boss',()=>{expect(bootcampMissions).toHaveLength(10);expect(bootcampMissions.map(item=>item.order)).toEqual([1,2,3,4,5,6,7,8,9,10]);expect(bootcampMissions.at(-1)?.id).toBe('mizan-boss');expect(bootcampMissions.every(item=>item.evidenceRule==='practice-only')).toBe(true)});
 it('unlocks missions sequentially and does not complete unfinished work',()=>{const state=createBootcampState();expect(isBootcampMissionUnlocked(state,'business-world')).toBe(true);expect(isBootcampMissionUnlocked(state,'missing-story')).toBe(false);expect(completeBootcampMission(state,'business-world')).toBe(state);const next=solve(state,'business-world');expect(next.completedMissionIds).toEqual(['business-world']);expect(next.currentMissionId).toBe('missing-story');expect(isBootcampMissionUnlocked(next,'missing-story')).toBe(true)});
 it('counts a wrong choice as a retry without advancing required work',()=>{const state=createBootcampState(),wrong=recordBootcampInteraction(state,'business-world','owner',false);expect(wrong.attempts['business-world']).toBe(1);expect(wrong.interactionProgress['business-world']).toBeUndefined();expect(bootcampMissionReady(wrong,'business-world')).toBe(false);expect(recordBootcampInteraction(wrong,'business-world','invented-action',true)).toBe(wrong)});
 it('requires all six boss entries before Mizan Trading unlocks',()=>{let state=createBootcampState();for(const mission of bootcampMissions.slice(0,9))state=solve(state,mission.id);expect(state.currentMissionId).toBe('mizan-boss');expect(state.mizanUnlocked).toBe(false);const boss=getBootcampMission('mizan-boss')!;for(const entry of boss.entries!.slice(0,5))state=recordBootcampInteraction(state,'mizan-boss',entry.id,true);expect(completeBootcampMission(state,'mizan-boss')).toBe(state);state=recordBootcampInteraction(state,'mizan-boss',boss.entries![5].id,true);state=completeBootcampMission(state,'mizan-boss',0);expect(state.bossCompleted).toBe(true);expect(state.mizanUnlocked).toBe(true);expect(state.completedAt).toBe('1970-01-01T00:00:00.000Z');expect(bootcampProgress(state)).toBe(100)});
 it('migrates malformed saves without inventing completion or professional evidence',()=>{const state=migrateBootcampState({version:99,currentMissionId:'unknown',completedMissionIds:['business-world','unknown'],interactionProgress:{'business-world':['owner','fake']},attempts:{'business-world':2},mizanUnlocked:true,verified:true});expect(state.version).toBe(1);expect(state.completedMissionIds).toEqual(['business-world']);expect(state.interactionProgress['business-world']).toEqual(['owner']);expect(state.mizanUnlocked).toBe(false);expect(state).not.toHaveProperty('verified')});
});
