import {describe,it,expect} from 'vitest';
import {activityRegistry,arcadeCards,getMission,missions} from '@/lib/campaign/content';
import {activeStage,answerArcade,candidateEvidence,company,continueMission,editDraft,evidenceSummary,initialState,inspectDocument,nextMission,recordHint,resumePoint,safeLoad,startArcade,startMission,streak,submitStage,unlocked,upgradeOffice} from '@/lib/campaign/director';
import type {GameState} from '@/lib/campaign/model';
function solve(s:GameState){const stage=activeStage(s)!;if(stage.kind==='inspect')for(const id of stage.documentIds!)s=inspectDocument(s,id);s=editDraft(s,stage.kind==='journal'?JSON.stringify(stage.journal):stage.answer??'');return continueMission(submitStage(s,2000),3000);}
function complete(s:GameState,id:string){s=startMission(s,id,1000);let guard=0;while(s.active&&guard++<50)s=solve(s);return s;}
describe('Mizan game director',()=>{
 it('starts with only the real first desk unlocked',()=>{const s=initialState();expect(nextMission(s)?.id).toBe('first-desk');expect(startMission(s,'month-end-file')).toBe(s);expect(s.xp).toBe(0);});
 it('has unique canonical IDs, valid dependencies and bilingual content',()=>{expect(Object.keys(activityRegistry)).toHaveLength(missions.reduce((n,m)=>n+m.stages.length,0));for(const m of missions){for(const id of m.requires)expect(getMission(id)).toBeTruthy();for(const st of m.stages){expect(st.title.ar).toBeTruthy();expect(st.prompt.en).toBeTruthy();}}});
 it('requires inspecting all three original documents',()=>{let s=startMission(initialState(),'first-desk');s=submitStage(s);expect(s.active?.passed).toBe(false);s=inspectDocument(s,'CAP-001');s=inspectDocument(s,'INV-014');expect(submitStage(s).active?.passed).toBe(false);s=inspectDocument(s,'RENT-01');expect(submitStage(s).active?.passed).toBe(true);});
 it('persists the exact draft, stage, hints and failed attempts',()=>{let s=startMission(initialState(),'first-desk');s=solve(s);s=recordHint(editDraft(s,'bad'));s=submitStage(s);const restored=safeLoad(JSON.stringify(s));expect(resumePoint(restored)).toEqual(resumePoint(s));expect(restored.active?.hints).toBe(1);expect(restored.active?.tries).toBe(1);});
 it('does not abandon a live draft to launch another mission',()=>{const s=startMission(initialState(),'first-desk');expect(startMission(s,'first-desk')).toBe(s);});
 it('never changes accepted company books for a failed draft',()=>{let s=startMission(initialState(),'first-desk');s=solve(s);s=solve(s);s=solve(s);s=editDraft(s,'[]');const bad=submitStage(s);expect(bad.journal).toHaveLength(0);expect(bad.evidence.at(-1)?.criticalErrors).toBe(1);expect(company(bad).cash).toBe(0);});
 it('changes cash only after a correctly assembled journal and saves one reward',()=>{let s=complete(initialState(),'first-desk');expect(company(s).cash).toBe(20000);expect(s.xp).toBe(80);expect(unlocked(s,getMission('clear-desk')!)).toBe(true);s=complete(s,'first-desk');expect(company(s).cash).toBe(20000);expect(s.xp).toBe(80);});
 it('XP alone never opens chapters',()=>{const s={...initialState(),xp:999999};expect(unlocked(s,getMission('month-end-file')!)).toBe(false);expect(evidenceSummary(s).readiness).toBe(0);});
 it('keeps first score and first mistakes after a perfect replay',()=>{let s=startMission(initialState(),'first-desk');s=solve(s);s=submitStage(editDraft(s,'wrong'));s=solve(s);s=solve(s);s=solve(s);const first=s.completed['first-desk'].firstScore;const accuracy=evidenceSummary(s).accuracy;s=complete(s,'first-desk');expect(s.completed['first-desk'].firstScore).toBe(first);expect(s.completed['first-desk'].bestScore).toBe(100);expect(evidenceSummary(s).accuracy).toBe(accuracy);});
 it('requires mastery after excessive hints and directs a replay',()=>{let s=startMission(initialState(),'first-desk');while(s.active){for(let i=0;i<8;i++)s=recordHint(s);s=solve(s);}expect(s.completed['first-desk'].bestScore).toBe(30);expect(nextMission(s)?.id).toBe('first-desk');expect(unlocked(s,getMission('clear-desk')!)).toBe(false);});
 it('completes all eight chapters with linked company totals and meaningful readiness',()=>{let s=initialState();for(const m of missions)s=complete(s,m.id);const c=company(s);expect(c.cash).toBe(18300);expect(c.bank).toBe(7600);expect(c.inventory).toBe(6000);expect(c.liabilities).toBe(6800);expect(c.loss).toBe(2700);expect(c.netAssets).toBe(34100);expect(c.trialDifference).toBe(0);expect(evidenceSummary(s).ready).toBe(true);expect(evidenceSummary(s).bosses).toBe(8);expect(nextMission(s)).toBeNull();expect(candidateEvidence(s).source).toBe('local-unverified');});
 it('has no arcade reward from merely pressing start',()=>{const s=startArcade(initialState(),'sort','2026-09-06',1000);expect(s.xp).toBe(0);expect(s.arcade?.finished).toBe(false);});
 it('scores actual decisions, caps timer and gives daily reward once',()=>{let s=startArcade(initialState(),'sort','sort:2026-09-06',1000);for(const c of arcadeCards)s=answerArcade(s,c.category,2000);expect(s.arcadeBest.sort).toBe(100);expect(s.xp).toBe(20);s=startArcade(s,'sort','sort:2026-09-06',3000);for(const c of arcadeCards)s=answerArcade(s,c.category,4000);expect(s.xp).toBe(20);s=startArcade(s,'rush','rush:2026-09-06',1000);s=answerArcade(s,'debit',100000);expect(s.arcade?.finished).toBe(true);expect(s.arcade?.correct).toBe(0);});
 it('supports both arcade mechanics and keeps them out of career assessment',()=>{let s=startArcade(initialState(),'rush','rush',1000);for(const c of arcadeCards)s=answerArcade(s,c.side,2000);expect(s.arcadeBest.rush).toBe(100);expect(evidenceSummary(s).readiness).toBe(0);});
 it('cannot buy duplicate or unaffordable upgrades',()=>{let s=initialState();expect(upgradeOffice(s,'lamp')).toBe(s);s={...s,coins:100};s=upgradeOffice(s,'lamp');expect(s.coins).toBe(50);expect(upgradeOffice(s,'lamp')).toBe(s);});
 it('expires stale streaks and handles damaged JSON',()=>{expect(safeLoad('{')).toEqual(initialState());expect(streak({...initialState(),activeDays:['2026-09-01']},Date.parse('2026-09-06'))).toBe(0);});
});
