import {afterEach,beforeEach,describe,it,expect} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {GameApp} from '@/components/campaign/game-app';
import {GAME_KEY,readGame} from '@/lib/campaign/store';
import {closeFirstDayDocument,completeFirstDayIntro,firstDayDocuments,submitFirstDayDocument} from '@/lib/campaign/first-day';
import {initialState} from '@/lib/campaign/director';

beforeEach(()=>localStorage.clear());afterEach(cleanup);
const enterShift=()=>fireEvent.click(screen.getByRole('button',{name:/Skip intro|تخطّي المقدمة/}));

describe('Chapter 1 cinematic First Day UI',()=>{
 it('shows only the cinematic first, with working playback controls',()=>{render(<GameApp locale="en"/>);expect(screen.getByRole('heading',{name:'FIRST DAY'})).toBeInTheDocument();expect(screen.queryByRole('heading',{name:'Three real work items are waiting'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Pause cinematic'}));expect(screen.getByRole('button',{name:'Play cinematic'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Next scene'}));expect(screen.getByRole('heading',{name:'Meet your manager'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Replay cinematic'})).toBeInTheDocument();});
 it('reveals the accounting desk and lets the player choose a real document',()=>{render(<GameApp locale="en"/>);enterShift();expect(screen.getByRole('heading',{name:'Choose where you want to start.'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Three real work items are waiting'})).toBeInTheDocument();expect(screen.getByText('Pending documents').closest('.fd-live-metric')).toHaveTextContent('3');fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));expect(screen.getByRole('dialog',{name:'Supplier Invoice'})).toHaveTextContent('INV-1048');expect(screen.getByRole('button',{name:'Record transaction'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open Accounting Manual'})).toHaveAttribute('target','_blank');});
 it('builds a correct supplier entry with account pieces and records the reward',()=>{render(<GameApp locale="en"/>);enterShift();fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));fireEvent.click(screen.getByRole('button',{name:'Record transaction'}));fireEvent.click(screen.getByRole('button',{name:/Office equipment$/}));fireEvent.click(screen.getByRole('button',{name:'DEBIT'}));fireEvent.change(screen.getByRole('spinbutton',{name:'Amount line 1'}),{target:{value:'100000'}});fireEvent.click(screen.getByRole('button',{name:'Add second line'}));fireEvent.click(screen.getByRole('button',{name:/Accounts payable$/}));fireEvent.click(screen.getAllByRole('button',{name:'CREDIT'})[1]);fireEvent.change(screen.getByRole('spinbutton',{name:'Amount line 2'}),{target:{value:'100000'}});fireEvent.click(screen.getByRole('button',{name:'Submit entry'}));expect(screen.getByRole('heading',{name:'Document recorded in Mizan’s books'})).toBeInTheDocument();expect(document.querySelector('.fd-reward-pop')).toHaveTextContent('+25 XP');expect(readGame().journal.some(item=>item.id==='first-day/supplier-invoice')).toBe(true);expect(localStorage.getItem(GAME_KEY)).toBeTruthy();});
 it('shows a company consequence and manager reaction for a wrong answer',()=>{render(<GameApp locale="en"/>);enterShift();fireEvent.click(screen.getByRole('button',{name:/Customer Receipt.*Open document/}));fireEvent.click(screen.getByRole('button',{name:'Record transaction'}));fireEvent.click(screen.getByRole('button',{name:'Submit entry'}));expect(screen.getByRole('alert')).toHaveTextContent('Bank reconciliation difference: EGP 75,000');expect(screen.getByRole('alert')).toHaveTextContent('The bank will not reconcile');expect(readGame().journal).toHaveLength(0);expect(readGame().xp).toBe(0);expect(readGame().evidence.at(-1)?.correct).toBe(false);});
 it('is Arabic-first in copy, RTL, controls and document inspection',()=>{const {container}=render(<GameApp locale="ar"/>);expect(container.querySelector('[dir="rtl"]')).toBeTruthy();expect(screen.getByRole('heading',{name:'أول يوم'})).toBeInTheDocument();enterShift();expect(screen.getByRole('heading',{name:'اختار عايز تبدأ منين.'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/مصروف مكتب.*افتح المستند/}));expect(screen.getByRole('dialog',{name:'مصروف مكتب'})).toHaveTextContent('نقدية من الصندوق');expect(screen.getByRole('button',{name:'سجّل العملية'})).toBeInTheDocument();});
 it('plays the end-of-day cinematic before revealing the locked Chapter 2 teaser',()=>{let state=completeFirstDayIntro(initialState());for(const doc of firstDayDocuments)state=submitFirstDayDocument(state,doc.id,JSON.stringify(doc.expected),1000).state;state=closeFirstDayDocument(state);localStorage.setItem(GAME_KEY,JSON.stringify(state));render(<GameApp locale="en"/>);expect(screen.getByRole('heading',{name:'The books are balanced'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Next scene'}));fireEvent.click(screen.getByRole('button',{name:'Next scene'}));expect(screen.getByRole('heading',{name:'THE FIRST SHIFT'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Finish cinematic'}));expect(screen.getByRole('button',{name:/COME BACK TOMORROW/})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/COME BACK TOMORROW/}));expect(screen.getByRole('heading',{name:'Chapter 2 — The First Shift'})).toBeInTheDocument();expect(screen.getByText('NEXT · LOCKED')).toBeInTheDocument();});
});
