import {afterEach,beforeEach,describe,it,expect} from 'vitest';
import {cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import {GameApp} from '@/components/campaign/game-app';
import {GAME_KEY,readGame} from '@/lib/campaign/store';
import {closeFirstDayDocument,completeFirstDayIntro,enterFirstDayDesk,firstDayDocuments,submitFirstDayDocument} from '@/lib/campaign/first-day';
import {initialState} from '@/lib/campaign/director';
import {markFirstShiftLedgerReviewed} from '@/lib/campaign/first-shift-hub';

beforeEach(()=>localStorage.clear());afterEach(cleanup);
const enterShift=()=>{fireEvent.click(screen.getByRole('button',{name:/START STORY|ابدأ القصة/}));fireEvent.click(screen.getByRole('button',{name:/ENTER COMPANY|ادخل الشركة/}));fireEvent.click(screen.getByRole('button',{name:/SHOW ME THE DESK|ورّيني المكتب/}));};
const investigateSupplier=()=>{fireEvent.click(screen.getByRole('tab',{name:/Purchase Order PO-771/}));fireEvent.click(screen.getByRole('tab',{name:/Goods Receipt GRN-771/}));};
const investigateCustomer=()=>{fireEvent.click(screen.getByRole('tab',{name:/Bank Advice BA-312/}));fireEvent.click(screen.getByRole('tab',{name:/Customer Invoice SI-2041/}));};
const matchSupplier=()=>{for(const row of document.querySelectorAll('.acw-match-list>div'))fireEvent.click(within(row as HTMLElement).getByRole('button',{name:'Matches'}));};
const fillEntry=(debitAccount:string,creditAccount:string,amount:string)=>{fireEvent.change(screen.getByRole('combobox',{name:'Account line 1'}),{target:{value:debitAccount}});fireEvent.change(screen.getByRole('spinbutton',{name:'Debit line 1'}),{target:{value:amount}});fireEvent.change(screen.getByRole('combobox',{name:'Account line 2'}),{target:{value:creditAccount}});fireEvent.change(screen.getByRole('spinbutton',{name:'Credit line 2'}),{target:{value:amount}});};
const choosePosting=(name:RegExp)=>fireEvent.click(screen.getByRole('button',{name}));
const seedCompletedCases=(count:number)=>{let state=enterFirstDayDesk(completeFirstDayIntro(initialState()));for(const doc of firstDayDocuments.slice(0,count))state=closeFirstDayDocument(submitFirstDayDocument(state,doc.id,JSON.stringify(doc.expected),1000).state);localStorage.setItem(GAME_KEY,JSON.stringify(state));return state;};

describe('Chapter 1 cinematic First Day UI',()=>{
 it('starts nothing automatically and labels the poster fallback honestly',()=>{render(<GameApp locale="en"/>);expect(screen.getByRole('heading',{name:'FIRST DAY'})).toBeInTheDocument();expect(screen.queryByRole('heading',{name:'Your first shift.'})).toBeNull();expect(screen.queryByRole('button',{name:/ENTER COMPANY/})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'START STORY'}));expect(screen.getByText('Cinematic introduction will be available here')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Pause|Replay/})).toBeNull();fireEvent.click(screen.getByRole('button',{name:/ENTER COMPANY/}));expect(screen.getByRole('heading',{name:'Welcome to Mizan Trading.'})).toBeInTheDocument();});
 it('reveals the original artwork, five real portal hotspots, and the connected workbench',()=>{const {container}=render(<GameApp locale="en"/>);enterShift();expect(screen.getByRole('heading',{name:'Your first shift.'})).toBeInTheDocument();expect(container.querySelector('.fsh-artwork')).toHaveAttribute('src','/game/first-shift-world-art.png');expect(screen.getByRole('region',{name:'Mizan accounting system'})).toHaveTextContent('3 files in inbox');expect(screen.getByRole('progressbar',{name:'Shift progress'})).toHaveAttribute('aria-valuenow','0');expect(document.querySelectorAll('.fsh-portal')).toHaveLength(5);expect(screen.getByRole('button',{name:'Customer Receipt · Locked'})).toBeDisabled();expect(screen.getByRole('button',{name:'Ledger · Locked'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));expect(screen.getByRole('dialog',{name:'Supplier Invoice'})).toHaveTextContent('INV-1048');expect(screen.getByRole('heading',{name:'Work inbox'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Manager instructions'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Make your decision'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Account City · inspect account'})).toHaveAttribute('href','/en/account-guide?return=first-day&document=supplier-invoice&account=2100');});
 it('requires supporting evidence and matching before a correct supplier post',()=>{render(<GameApp locale="en"/>);enterShift();fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));choosePosting(/Post the liability/);expect(screen.getByText(/Review 2 required document/)).toBeInTheDocument();investigateSupplier();choosePosting(/Post the liability/);expect(screen.getByText(/Confirm 4 comparison field/)).toBeInTheDocument();matchSupplier();fillEntry('equipment','suppliers','100000');choosePosting(/Post the liability/);expect(screen.getByRole('heading',{name:'Supplier Invoice resolved'})).toBeInTheDocument();expect(document.querySelector('.fd-company-impact')).toHaveTextContent('3 → 2');expect(document.querySelector('.fd-reward-pop')).toHaveTextContent('+100 XP');expect(readGame().journal.some(item=>item.id==='first-day/supplier-invoice')).toBe(true);expect(localStorage.getItem(GAME_KEY)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'File in Processed · return to desk'}));expect(screen.queryByRole('button',{name:/Supplier Invoice.*Open document/})).toBeNull();expect(screen.getByText('PROCESSED TRAY').closest('.fsh-processed-tray')).toHaveTextContent('1');expect(document.querySelector('.fsh-filed-toast')).toBeInTheDocument();});
 it('shows invoice, purchase order and receipt as switchable structured documents',()=>{render(<GameApp locale="en"/>);enterShift();fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));expect(screen.getByRole('region',{name:'Document viewer'})).toHaveTextContent('100,000');fireEvent.click(screen.getByRole('tab',{name:/Purchase Order PO-771/}));expect(screen.getByRole('tab',{name:/Purchase Order PO-771/})).toHaveAttribute('aria-selected','true');expect(screen.getByRole('region',{name:'Document viewer'})).toHaveTextContent('PO-771');fireEvent.click(screen.getByRole('tab',{name:/Goods Receipt GRN-771/}));expect(screen.getByRole('region',{name:'Document viewer'})).toHaveTextContent('GRN-771');});
 it('rejects an unbalanced workpaper without accepting a ledger entry',()=>{render(<GameApp locale="en"/>);enterShift();fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));investigateSupplier();matchSupplier();fireEvent.change(screen.getByRole('combobox',{name:'Account line 1'}),{target:{value:'equipment'}});fireEvent.change(screen.getByRole('spinbutton',{name:'Debit line 1'}),{target:{value:'100000'}});choosePosting(/Post the liability/);expect(document.querySelector('.acw-feedback')).toHaveTextContent('equal debit and credit totals');expect(readGame().journal).toHaveLength(0);});
 it.each([[/Hold the invoice/,'hold'],[/Request information/,'request_information'],[/Escalate to Kareem/,'escalate']] as const)('shows a protective professional consequence for %s without posting',(name,action)=>{render(<GameApp locale="en"/>);enterShift();fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));choosePosting(name);expect(screen.getByRole('heading',{name:'The case is safely paused'})).toBeInTheDocument();expect(screen.getByText('No accepted entry changed')).toBeInTheDocument();expect(readGame().journal).toHaveLength(0);expect(readGame().casework?.cases['supplier-invoice'].selectedActions).toContain(action);});
 it('records manager help and protects the ledger after a wrong balanced entry',()=>{const baseline=seedCompletedCases(1);render(<GameApp locale="en"/>);fireEvent.click(screen.getByRole('button',{name:/Customer Receipt.*Open document/}));investigateCustomer();fireEvent.click(screen.getByRole('button',{name:'Ask Kareem for guidance'}));expect(screen.getByText(/payment reference/)).toBeInTheDocument();fillEntry('equipment','suppliers','75000');choosePosting(/Allocate and post/);expect(screen.getByRole('alert')).toHaveTextContent('Posting stopped');expect(readGame().journal).toHaveLength(baseline.journal.length);expect(readGame().xp).toBe(baseline.xp);expect(readGame().evidence.at(-1)?.correct).toBe(false);expect(readGame().casework?.events.some(event=>event.eventType==='manager_help_requested')).toBe(true);});
 it('restores a posting draft and guidance after closing and reopening a case',()=>{render(<GameApp locale="en"/>);enterShift();fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));investigateSupplier();fireEvent.click(screen.getByRole('button',{name:'Ask Kareem for guidance'}));fireEvent.change(screen.getByRole('combobox',{name:'Account line 1'}),{target:{value:'equipment'}});fireEvent.change(screen.getByRole('spinbutton',{name:'Debit line 1'}),{target:{value:'100000'}});fireEvent.click(screen.getByRole('button',{name:'Close'}));fireEvent.click(screen.getByRole('button',{name:/Supplier Invoice.*Open document/}));expect(screen.getByRole('spinbutton',{name:'Debit line 1'})).toHaveValue(100000);expect(screen.getByRole('combobox',{name:'Account line 1'})).toHaveValue('equipment');expect(readGame().casework?.cases['supplier-invoice'].managerHelpCount).toBe(1);});
 it('is Arabic-first in copy, RTL, controls and case investigation',()=>{const {container}=render(<GameApp locale="ar"/>);expect(container.querySelector('[dir="rtl"]')).toBeTruthy();expect(screen.getByRole('heading',{name:'أول يوم'})).toBeInTheDocument();cleanup();seedCompletedCases(2);render(<GameApp locale="ar"/>);fireEvent.click(screen.getByRole('button',{name:/مصروف مكتب.*افتح المستند/}));expect(screen.getByRole('dialog',{name:'مصروف مكتب'})).toHaveTextContent('مراجعة مصروف صندوق');expect(screen.getByRole('heading',{name:'اتخذ قرارك'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'مدينة الحسابات · افحص الحساب'})).toHaveAttribute('href','/ar/account-guide?return=first-day&document=office-expense&account=1100');});
 it('shows computed professional results after ledger review and keeps Chapter 2 locked',()=>{let state=enterFirstDayDesk(completeFirstDayIntro(initialState()));for(const doc of firstDayDocuments)state=submitFirstDayDocument(state,doc.id,JSON.stringify(doc.expected),1000).state;state=markFirstShiftLedgerReviewed(closeFirstDayDocument(state));localStorage.setItem(GAME_KEY,JSON.stringify(state));render(<GameApp locale="en"/>);expect(screen.getByRole('heading',{name:'The files are cleared. The books are protected.'})).toBeInTheDocument();expect(screen.getByText('CLOSING WEEK — THE MONTH-END CRISIS')).toBeInTheDocument();expect(screen.getByText(/CHAPTER 2 · ARCHITECTURE READY · LOCKED/)).toBeInTheDocument();expect(document.querySelector('.fd-shift-reward')).toHaveTextContent('+300 XP');expect(screen.getByRole('link',{name:'Why did my skills change?'})).toHaveAttribute('href','/en/career-profile/skills');});
});

describe('First Shift desk objects',()=>{
 it('shows all five portal stages on mobile and opens the next unlocked case',()=>{seedCompletedCases(1);render(<GameApp locale="en"/>);expect(document.querySelectorAll('.fsh-portal')).toHaveLength(5);expect(screen.getByRole('button',{name:'Supplier Invoice · Review'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'Customer Receipt · Open document'}));expect(screen.getByRole('dialog',{name:'Customer Receipt'})).toBeInTheDocument();});
 it('uses the physical calculator and handles division by zero',()=>{render(<GameApp locale="en"/>);enterShift();fireEvent.click(screen.getByRole('button',{name:'Open calculator'}));fireEvent.change(screen.getByRole('spinbutton',{name:'First number'}),{target:{value:'30000'}});fireEvent.change(screen.getByRole('spinbutton',{name:'Second number'}),{target:{value:'3'}});fireEvent.change(screen.getByRole('combobox',{name:'Operation'}),{target:{value:'×'}});expect(screen.getByRole('status')).toHaveTextContent('90,000');fireEvent.change(screen.getByRole('combobox',{name:'Operation'}),{target:{value:'÷'}});fireEvent.change(screen.getByRole('spinbutton',{name:'Second number'}),{target:{value:'0'}});expect(screen.getByRole('status')).toHaveTextContent('Cannot divide by zero');fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull();});
 it('opens the existing journal and ledger tools after all source cases',()=>{seedCompletedCases(3);render(<GameApp locale="en"/>);fireEvent.click(screen.getByRole('button',{name:'Journal · Review'}));expect(screen.getByRole('dialog',{name:'Journal'})).toHaveTextContent('INV-1048');fireEvent.click(screen.getByRole('button',{name:'Close'}));fireEvent.click(screen.getByRole('button',{name:'Ledger · Open document'}));expect(screen.getByRole('dialog',{name:'General Ledger'})).toHaveTextContent('Supplier balance');});
});
