import{describe,expect,it}from'vitest';
import{careerContentCases,responsibilityOrder}from'@/lib/career-content/catalog';
import{adaptiveCareerCases,availableCareerCases,createCareerContentState,migrateCareerContentState,recordCareerContentAttempt,responsibilityProgressionValid}from'@/lib/career-content/engine';

describe('professional career content engine',()=>{
 it('covers all nine simulation levels with increasing professional responsibility',()=>{expect([...new Set(careerContentCases.map(item=>item.level))]).toEqual([0,1,2,3,4,5,6,7,8]);expect(responsibilityProgressionValid()).toBe(true);expect(responsibilityOrder).toEqual(['understand','record','process','reconcile','review','control','analyze','manage','decide'])});
 it('requires complete content-to-profile metadata on every case',()=>{for(const item of careerContentCases){expect(item.version).toBeGreaterThan(0);expect(item.skills.length).toBeGreaterThan(0);expect(item.roleRelevance.en).toBeTruthy();expect(item.evidenceRule).toMatch(/practice-only|eligible-practiced|eligible-demonstrated/);expect(item.reviewRequirements).toHaveLength(3);if(item.evidenceRule==='practice-only')expect(item.cvBehavior).toBeNull()}});
 it('keeps Draft and Review Required cases outside the playable approved boundary',()=>{const playable=availableCareerCases();expect(playable.length).toBeGreaterThan(0);expect(playable.every(item=>item.status==='approved')).toBe(true);expect(playable.some(item=>item.id==='l8-capex-choice')).toBe(false);expect(availableCareerCases({statuses:['draft']}).map(item=>item.id)).toContain('l8-capex-choice')});
 it('filters by responsibility level, company access, and specialist track',()=>{expect(availableCareerCases({level:4,companyTier:2,track:'treasury'}).map(item=>item.id)).toEqual(['l4-bank-reconciliation']);expect(availableCareerCases({level:7,companyTier:3})).toEqual([])});
 it('prevents repeat farming and keeps attempt IDs idempotent',()=>{const state=createCareerContentState(),attempt={attemptId:'attempt-1',caseId:'l1-first-entry',caseVersion:1,profileId:'default-local',score:88,successful:true,completedAt:'2026-09-19T00:00:00.000Z'},first=recordCareerContentAttempt(state,attempt),duplicate=recordCareerContentAttempt(first.state,attempt),repeat=recordCareerContentAttempt(first.state,{...attempt,attemptId:'attempt-2'});expect(first.rewardEligible).toBe(true);expect(duplicate.state).toBe(first.state);expect(duplicate.rewardEligible).toBe(false);expect(repeat.rewardEligible).toBe(false);expect(repeat.state.attempts).toHaveLength(2)});
 it('recommends unfinished or weak cases before completed strong cases',()=>{let state=createCareerContentState();state=recordCareerContentAttempt(state,{attemptId:'a',caseId:'l2-three-way-file',caseVersion:1,profileId:'p',score:100,successful:true,completedAt:'2026-09-19T00:00:00.000Z'}).state;expect(adaptiveCareerCases(state,2,undefined,2)[0].id).toBe('l2-unreferenced-receipt')});
 it('migrates saved attempts without accepting unknown content',()=>{const state=migrateCareerContentState({version:9,attempts:[{attemptId:'ok',caseId:'l1-first-entry',caseVersion:1,profileId:'p',score:80,successful:true,completedAt:'x'},{attemptId:'bad',caseId:'invented'}],completedCaseIds:['l1-first-entry','invented']});expect(state.attempts).toHaveLength(1);expect(state.completedCaseIds).toEqual(['l1-first-entry'])});
});
