import {beforeEach,describe,expect,it} from 'vitest';
import {careerOpportunities,careerSeasons,companyTiers,leagueTracks,placementTasks,premiumAccess} from '@/lib/career-league/catalog';
import {canAccess,careerGap,careerLeagueScore,careerReputation,careerTrainingPlan,companyUnlocked,createCareerLeagueState,evaluatePromotion,migrateCareerLeagueState,placementResult,promotionEligibility,roleForCareerGoal} from '@/lib/career-league/engine';
import {BrowserCareerLeagueRepository,CAREER_LEAGUE_KEY} from '@/lib/career-league/repository';
import type {SkillId,SkillResult,SkillStatus} from '@/lib/career/model';

const skill=(skillId:SkillId,status:SkillStatus):SkillResult=>({skillId,status,score:status==='unassessed'?null:80,confidence:status==='unassessed'?'insufficient':'developing',evidenceCount:status==='unassessed'?0:2,uniqueActivities:status==='unassessed'?0:2,successfulActivities:status==='demonstrated'?2:1});
const passport=(rows:Partial<Record<SkillId,SkillStatus>>):SkillResult[]=>(Object.entries(rows)as[SkillId,SkillStatus][]).map(([id,status])=>skill(id,status));

beforeEach(()=>localStorage.clear());
describe('Career League domain',()=>{
 it('supports the three player journeys without awarding evidence',()=>{for(const persona of ['student','graduate','working-accountant']as const){const state={...createCareerLeagueState(),persona};expect(state.persona).toBe(persona);expect(state).not.toHaveProperty('evidence')}expect(roleForCareerGoal('first-job')).toBe('junior-accountant');expect(roleForCareerGoal('bigger-company')).toBe('general-accountant')});
 it('recommends a starting tier from work-based placement answers',()=>{const correct=Object.fromEntries(placementTasks.map(task=>[task.id,task.correctIndex]));expect(placementResult(placementTasks,correct)).toEqual({score:100,recommendation:2});expect(placementResult(placementTasks,{})).toEqual({score:0,recommendation:1})});
 it('calculates role gaps and a Train For This Job path from Skill Passport state',()=>{const current=passport({'journal-entries':'demonstrated','accounts-payable':'practiced','accounts-receivable':'practiced'}),gap=careerGap('horizon-general',current),plan=careerTrainingPlan('horizon-general',current);expect(gap.strong).toContain('journal-entries');expect(gap.developing).toContain('accounts-payable');expect(gap.missing).toContain('bank-reconciliation');expect(plan.map(item=>item.skillId)).toEqual(expect.arrayContaining(['bank-reconciliation','month-end-closing']))});
 it('requires missions, skill evidence, and assessment rather than XP to unlock a company',()=>{const qualified=passport({'document-analysis':'practiced','journal-entries':'practiced'});expect(companyUnlocked('delta-commerce',qualified,['first-shift'],{})).toBe(false);expect(companyUnlocked('delta-commerce',qualified,['first-shift'],{'promotion-1':'pass'})).toBe(true);expect(companyUnlocked('delta-commerce',[],['first-shift'],{'promotion-1':'pass'})).toBe(false);expect(companyTiers).toHaveLength(5)});
 it('keeps promotion eligibility and outcome deterministic and explainable',()=>{const qualified=passport({'document-analysis':'practiced','journal-entries':'practiced'});expect(promotionEligibility('promotion-1',qualified,['first-shift']).eligible).toBe(true);expect(promotionEligibility('promotion-1',qualified,[]).missingMissions).toContain('first-shift');expect(evaluatePromotion({accuracy:90,accountingJudgment:88,investigation:90,riskAwareness:90,independence:80,documentation:85,overall:87,criticalErrors:0}).status).toBe('pass');const unsafe=evaluatePromotion({accuracy:95,accountingJudgment:80,investigation:65,riskAwareness:40,independence:90,documentation:80,overall:75,criticalErrors:1});expect(unsafe.status).toBe('needs-practice');expect(unsafe.developmentAreas).toContain('riskAwareness')});
 it('scores professional quality without XP or speed and rewards careful risk behavior',()=>{const careful=careerLeagueScore({accuracy:90,accountingJudgment:90,investigation:90,riskAwareness:95,firstAttemptQuality:90,difficulty:2,bossCompletion:100,consistency:85}),reckless=careerLeagueScore({accuracy:90,accountingJudgment:80,investigation:45,riskAwareness:30,firstAttemptQuality:90,difficulty:2,bossCompletion:100,consistency:85});expect(careful).toBeGreaterThan(reckless)});
 it('projects game-only reputation and increases audit risk after unsafe work',()=>{const careful=careerReputation({accuracy:95,accountingJudgment:90,investigation:90,riskAwareness:95,documentation:90,independence:85,overall:90,criticalErrors:0}),unsafe=careerReputation({accuracy:80,accountingJudgment:55,investigation:40,riskAwareness:25,documentation:45,independence:90,overall:55,criticalErrors:2});expect(careful.gameOnly).toBe(true);expect(careful.managerTrust).toBeGreaterThan(unsafe.managerTrust);expect(unsafe.auditRisk).toBeGreaterThan(careful.auditRisk)});
 it('centralizes Free and Pro access metadata',()=>{expect(premiumAccess.foundation).toBe('free');expect(canAccess('first-shift','free')).toBe(true);expect(canAccess('corporate-bridge','free')).toBe(false);expect(canAccess('corporate-bridge','pro')).toBe(true)});
 it('migrates legacy onboarding and persists new career state compatibly',()=>{const migrated=migrateCareerLeagueState(null,{experience:'student',goal:'career',onboardingComplete:true});expect(migrated).toMatchObject({persona:'student',goal:'first-job',onboardingComplete:true});const repo=new BrowserCareerLeagueRepository(),saved=repo.save({...migrated,targetOpportunityId:'mizan-junior'});expect(repo.get()).toEqual(saved);expect(JSON.parse(localStorage.getItem(CAREER_LEAGUE_KEY)!)).toMatchObject({version:1,targetOpportunityId:'mizan-junior'})});
 it('labels every opportunity as fictional simulation data',()=>{expect(careerOpportunities.every(item=>item.fictional)).toBe(true);expect(careerOpportunities.every(item=>item.companyName.en.length>0)).toBe(true)});
 it('keeps seasons and league tracks explicitly local demo architecture',()=>{expect(careerSeasons[0]).toMatchObject({status:'active-demo',localOnly:true});expect(leagueTracks).toHaveLength(6);expect(leagueTracks.every(item=>item.demo)).toBe(true)});
});
