import {beforeEach,describe,expect,it} from 'vitest';
import {createCareerLeagueState,migrateCareerLeagueState} from '@/lib/career-league/engine';
import {BrowserCareerLeagueRepository} from '@/lib/career-league/repository';
import {BrowserPlacementRepository} from '@/lib/placement/repository';
import {BrowserCareerProfileRepository,createDefaultProfile} from '@/lib/career/repository';
import {evaluatePlacement,migratePlacementState} from '@/lib/placement/engine';
import {tasksForPersona} from '@/lib/placement/catalog';
import {diagnosticSkillIds,nextCareerActivity,personalCareerGap,personalCareerMap,targetSkillIds} from '@/lib/career-entry/engine';
import type {SkillResult} from '@/lib/career/model';

beforeEach(()=>localStorage.clear());
const practiced=(skillId:SkillResult['skillId'],status:SkillResult['status']):SkillResult=>({skillId,status,score:82,confidence:'developing',evidenceCount:2,uniqueActivities:2,successfulActivities:1});
describe('career entry system',()=>{
 it('preserves existing career saves while migrating target roles',()=>{const old={...createCareerLeagueState(),persona:'graduate' as const,goal:'ap' as const,targetRoleId:undefined,acceptedOfferId:'offer-1',assessmentResults:{'promotion-1':'pass' as const}};const next=migrateCareerLeagueState(old);expect(next).toMatchObject({persona:'graduate',goal:'ap',targetRoleId:'ap-accountant',acceptedOfferId:'offer-1',assessmentResults:{'promotion-1':'pass'}});const repo=new BrowserCareerLeagueRepository();repo.save(next);expect(repo.get()).toEqual(expect.objectContaining({targetRoleId:'ap-accountant',acceptedOfferId:'offer-1'}))});
 it('keeps a previously selected Career Profile role during old-save migration',()=>{const profileRepo=new BrowserCareerProfileRepository();profileRepo.save({...createDefaultProfile('Mona'),'targetRoleId':'gl-accountant'});localStorage.setItem('debit-credit-career-league-v1',JSON.stringify({version:1,persona:'graduate',goal:'first-job',assessmentResults:{'promotion-1':'pass'}}));expect(new BrowserCareerLeagueRepository().get()).toMatchObject({targetRoleId:'gl-accountant',assessmentResults:{'promotion-1':'pass'}})});
 it('supports nine visible target roles including leadership without awarding a role',()=>{expect(targetSkillIds('general-accountant')).toContain('bank-reconciliation');expect(targetSkillIds('finance-manager')).toContain('financial-statements');expect(createCareerLeagueState()).not.toHaveProperty('evidence')});
 it('separates diagnostic strengths from gameplay-backed practice and gaps',()=>{const tasks=tasksForPersona('working-accountant'),answers=Object.fromEntries(tasks.map(task=>[task.id,task.correctIndex])),result=evaluatePlacement('working-accountant',answers),gap=personalCareerGap('general-accountant',[practiced('journal-entries','demonstrated'),practiced('bank-reconciliation','practiced')],result);expect(diagnosticSkillIds(result.strengths)).toContain('accounts-payable');expect(gap.strong).toContain('journal-entries');expect(gap.practiced).toContain('bank-reconciliation');expect(gap.missing).toContain('month-end-closing');expect(gap.strong).not.toContain('accounts-payable')});
 it('builds a personal map with honest available, demonstrated and planned nodes',()=>{const state={...createCareerLeagueState(),persona:'graduate' as const,targetRoleId:'general-accountant' as const},nodes=personalCareerMap(state,[practiced('journal-entries','demonstrated')],null);expect(nodes.map(node=>node.skillId)).toEqual(expect.arrayContaining(['bank-reconciliation','adjusting-entries','trial-balance','month-end-closing']));expect(nodes.find(node=>node.skillId==='journal-entries')?.status).toBe('demonstrated');expect(nodes.find(node=>node.skillId==='month-end-closing')?.status).toBe('planned');expect(nodes.map(node=>node.status)).not.toContain('verified');expect(nextCareerActivity(nodes)?.route).toBeTruthy()});
 it('preserves old placement results and never creates evidence from them',()=>{const old={version:1,persona:'student',answers:{'g-journal':0},result:evaluatePlacement('student',{}),completedAt:'2026-01-01'};expect(migratePlacementState(old).result?.grantsEvidence).toBe(false);const repo=new BrowserPlacementRepository();repo.save(migratePlacementState(old));expect(repo.get().persona).toBe('student')});
});
