import {describe,expect,it} from 'vitest';
import {caseworkState,inspectCaseDocument,openAccountingCase,recordCaseEntrySubmission,requestCaseManagerHelp,selectCaseAction,startFirstShiftCasework} from '@/lib/cases/engine';
import {projectCasePerformance,projectShiftPerformance} from '@/lib/cases/performance';
import {closingWeekMetadata} from '@/lib/cases/chapter-two';
import {revealDueConsequences,scheduleCaseConsequence} from '@/lib/cases/consequences';
import {w} from '@/lib/campaign/model';
import {initialState,safeLoad} from '@/lib/campaign/director';
import {completeFirstDayIntro,enterFirstDayDesk,firstDayCompany,firstDayDocuments,firstDayProgress,submitFirstDayDocument} from '@/lib/campaign/first-day';

describe('Phase B accounting casework',()=>{
 it('creates versioned append-only shift and received-case events once',()=>{let state=startFirstShiftCasework(initialState(),1000);state=startFirstShiftCasework(state,2000);const work=caseworkState(state);expect(work).toMatchObject({schemaVersion:1,scenarioVersion:1,rubricVersion:1,workMinutes:0});expect(work.events.filter(event=>event.eventType==='shift_started')).toHaveLength(1);expect(work.events.filter(event=>event.eventType==='case_received')).toHaveLength(3);expect(work.events.every(event=>event.schemaVersion===1&&event.eventId&&event.timestamp)).toBe(true);});
 it('moves a case deterministically through inspection, decision and resolution',()=>{let state=enterFirstDayDesk(completeFirstDayIntro(initialState()),1000);state=openAccountingCase(state,'supplier-invoice',1100);expect(caseworkState(state).cases['supplier-invoice']).toMatchObject({status:'opened',inspectedDocumentIds:['supplier-invoice']});let decision=selectCaseAction(state,'supplier-invoice','post',1200);expect(decision).toMatchObject({readyToPost:false,missingDocumentIds:['po-771','grn-771'],outcome:'blocked'});state=inspectCaseDocument(decision.state,'supplier-invoice','grn-771',1300);state=inspectCaseDocument(state,'supplier-invoice','po-771',1400);decision=selectCaseAction(state,'supplier-invoice','post',1500);expect(decision.readyToPost).toBe(true);state=recordCaseEntrySubmission(decision.state,'supplier-invoice',true,true,1600);expect(caseworkState(state).cases['supplier-invoice']).toMatchObject({status:'resolved',submissionCount:1});expect(caseworkState(state).events.map(event=>event.eventType)).toContain('case_posted');});
 it('deduplicates meaningful event identities and caps manager guidance',()=>{let state=openAccountingCase(initialState(),'customer-receipt',1000);state=inspectCaseDocument(state,'customer-receipt','bank-advice-312',1100);state=inspectCaseDocument(state,'customer-receipt','bank-advice-312',1200);state=requestCaseManagerHelp(state,'customer-receipt',1300);state=requestCaseManagerHelp(state,'customer-receipt',1400);state=requestCaseManagerHelp(state,'customer-receipt',1500);const events=caseworkState(state).events;expect(events.filter(event=>event.eventType==='supporting_document_inspected')).toHaveLength(1);expect(events.filter(event=>event.eventType==='manager_help_requested')).toHaveLength(2);expect(new Set(events.map(event=>event.eventId)).size).toBe(events.length);});
 it('derives professional performance only from recorded behavior',()=>{let state=openAccountingCase(initialState(),'office-expense',1000);state=requestCaseManagerHelp(state,'office-expense',1100);state=inspectCaseDocument(state,'office-expense','petty-cash-2201',1200);state=inspectCaseDocument(state,'office-expense','expense-policy',1300);state=selectCaseAction(state,'office-expense','post',1400).state;state=recordCaseEntrySubmission(state,'office-expense',false,true,1500);state=recordCaseEntrySubmission(state,'office-expense',true,true,1600);const score=projectCasePerformance(state,'office-expense');expect(score).toMatchObject({accuracy:80,independence:80,investigation:100,documentation:100,riskAwareness:100,submissions:2,managerAssistance:1,firstAttemptCorrect:false,resolved:true});expect(score.overall).toBeGreaterThan(80);});
 it('preserves old saves and migrates missing casework without changing accepted accounting',()=>{const old=submitFirstDayDocument(initialState(),'supplier-invoice',JSON.stringify(firstDayDocuments[0].expected),1000).state;const raw=JSON.stringify({...old,casework:undefined}),restored=safeLoad(raw);expect(firstDayProgress(restored).completed).toContain('supplier-invoice');expect(firstDayCompany(restored)).toMatchObject({pendingDocuments:2,supplierBalance:830000});expect(caseworkState(restored).cases['supplier-invoice'].status).toBe('resolved');});
 it('does not duplicate case resolution on a repeated successful callback',()=>{const draft=JSON.stringify(firstDayDocuments[0].expected),first=submitFirstDayDocument(initialState(),'supplier-invoice',draft,1000).state,second=submitFirstDayDocument(first,'supplier-invoice',draft,2000).state;expect(second).toBe(first);expect(caseworkState(second).events.filter(event=>event.eventType==='case_resolved')).toHaveLength(1);expect(projectShiftPerformance(second).resolvedCases).toBe(1);});
 it('keeps the Chapter 2 seam explicitly locked and non-routable',()=>{expect(closingWeekMetadata).toMatchObject({chapterNumber:2,status:'locked',entryRoute:null});expect(closingWeekMetadata.supportedWorkstreams).toContain('bank_reconciliation');expect(closingWeekMetadata.supportedWorkstreams).toContain('close_readiness');});
 it('can schedule and later reveal a deterministic connected-case consequence',()=>{const definition={id:'duplicate-invoice-found',timing:'after_case' as const,revealAfterCaseId:'bank-reconciliation',description:w('Duplicate found','تم اكتشاف تكرار'),affectedAccounts:['accounts-payable']};let state=scheduleCaseConsequence(initialState(),'supplier-invoice',definition,1000);state=scheduleCaseConsequence(state,'supplier-invoice',definition,1100);expect(caseworkState(state).scheduledConsequences).toHaveLength(1);state=revealDueConsequences(state,'other-case',false,1200);expect(caseworkState(state).scheduledConsequences[0].revealedAt).toBeNull();state=revealDueConsequences(state,'bank-reconciliation',false,1300);expect(caseworkState(state).scheduledConsequences[0].revealedAt).not.toBeNull();expect(caseworkState(state).events.filter(event=>event.eventType==='consequence_revealed')).toHaveLength(1);});
});
