import {describe,it,expect} from 'vitest';
import {closeFirstDayDocument,completeFirstDayIntro,DOCUMENT_REWARD,emptyFirstDay,enterFirstDayDesk,FIRST_DAY_INTRO_VERSION,firstDayCompany,firstDayDocuments,firstDayProgress,markFirstDayCompletionSeen,MISSION_REWARD,saveFirstDayDraft,selectFirstDayDocument,submitFirstDayDocument} from '@/lib/campaign/first-day';
import {firstDayIntro,firstDayOutro,storyCharacters} from '@/lib/campaign/first-day-story';
import {initialState} from '@/lib/campaign/director';

describe('First Day cinematic accounting gameplay',()=>{
 it('uses an honest poster fallback when no real cinematic file exists',()=>{expect(firstDayProgress(initialState())).toEqual(emptyFirstDay());expect(firstDayIntro.mode).toBe('video');if(firstDayIntro.mode==='video'){expect(firstDayIntro.video).toEqual({});expect(firstDayIntro.fallbackScenes).toHaveLength(5);}expect(firstDayOutro.scenes).toHaveLength(3);expect(storyCharacters['finance-manager'].name.ar).toBe('أ/ كريم');});
 it('stores manual company entry, desk entry, player choice, and return-to-desk state',()=>{let state=completeFirstDayIntro(initialState());expect(firstDayProgress(state)).toMatchObject({cinematicSeen:true,deskEntered:false,introVersion:FIRST_DAY_INTRO_VERSION});state=enterFirstDayDesk(state);expect(firstDayProgress(state).deskEntered).toBe(true);state=selectFirstDayDocument(state,'supplier-invoice');expect(firstDayProgress(state)).toMatchObject({selected:'supplier-invoice',opened:['supplier-invoice']});state=closeFirstDayDocument(state);expect(firstDayProgress(state).selected).toBeNull();});
 it('turns a wrong answer into a persistent, resolvable company consequence',()=>{const result=submitFirstDayDocument(initialState(),'supplier-invoice','[]',1000);expect(result.correct).toBe(false);expect(result.state.journal).toHaveLength(0);expect(firstDayCompany(result.state)).toMatchObject({ledgerErrors:1,unreconciledAmount:100000,pendingDocuments:3});expect(result.state.evidence[0]).toMatchObject({accuracy:0,criticalErrors:1,correct:false});});
 it('updates live cash, bank, supplier, customer, profit and progress values',()=>{let state=initialState();for(const doc of firstDayDocuments)state=submitFirstDayDocument(state,doc.id,JSON.stringify(doc.expected),1000).state;expect(firstDayCompany(state)).toEqual({assets:1347500,liabilities:830000,revenue:420000,profit:82500,cash:247500,bank:555000,supplierBalance:830000,customerBalance:245000,pendingDocuments:0,pendingEntries:0,monthEndProgress:100,ledgerErrors:0,unreconciledAmount:0});expect(state.journal).toHaveLength(3);});
 it('awards +100 XP and +50 coins per unique document, exactly once',()=>{let state=initialState();for(const doc of firstDayDocuments)state=submitFirstDayDocument(state,doc.id,JSON.stringify(doc.expected),1000).state;expect(state.xp).toBe(DOCUMENT_REWARD.xp*3+MISSION_REWARD.xp);expect(state.coins).toBe(DOCUMENT_REWARD.coins*3+MISSION_REWARD.coins);expect(state.xp).toBe(300);expect(state.coins).toBe(150);expect(firstDayProgress(state)).toMatchObject({rewarded:true,completionSeen:false});for(const doc of firstDayDocuments)state=submitFirstDayDocument(state,doc.id,JSON.stringify(doc.expected),2000).state;expect(state.xp).toBe(300);expect(state.coins).toBe(150);expect(state.journal).toHaveLength(3);});
 it('preserves an unfinished entry and hint attribution without changing old saved progress',()=>{const old={...initialState(),legacy:{'first-day':{cinematicSeen:true,deskEntered:true}}};expect(firstDayProgress(old)).toMatchObject({drafts:{},draftHints:{}});const draft=JSON.stringify([{account:'equipment',side:'debit',amount:100000}]);const saved=saveFirstDayDraft(old,'supplier-invoice',draft,true);expect(firstDayProgress(saved)).toMatchObject({drafts:{'supplier-invoice':draft},draftHints:{'supplier-invoice':true}});const completed=submitFirstDayDocument(saved,'supplier-invoice',JSON.stringify(firstDayDocuments[0].expected),1000,1).state;expect(firstDayProgress(completed).drafts).toEqual({});expect(firstDayProgress(completed).draftHints).toEqual({});});
 it('ignores a repeated successful completion callback entirely',()=>{const doc=firstDayDocuments[0],first=submitFirstDayDocument(initialState(),doc.id,JSON.stringify(doc.expected),1000).state,again=submitFirstDayDocument(first,doc.id,JSON.stringify(doc.expected),1001).state;expect(again).toBe(first);expect(again.evidence).toHaveLength(1);expect(again.journal).toHaveLength(1);expect(again.xp).toBe(100);expect(again.coins).toBe(50);});
 it('records hint use and only marks the completion cinematic seen explicitly',()=>{const doc=firstDayDocuments[0];let state=submitFirstDayDocument(initialState(),doc.id,JSON.stringify(doc.expected),1000,1).state;expect(state.evidence[0]).toMatchObject({hintsUsed:1,independentCompletion:false,score:95});for(const item of firstDayDocuments.slice(1))state=submitFirstDayDocument(state,item.id,JSON.stringify(item.expected),1000).state;expect(firstDayProgress(state).completionSeen).toBe(false);state=markFirstDayCompletionSeen(state);expect(firstDayProgress(state).completionSeen).toBe(true);expect(state.active).toBeNull();expect(state.unlocked).toEqual(['first-desk']);});
});
