import {describe,it,expect} from 'vitest';
import {emptyFirstDay,firstDayCompany,firstDayDocuments,firstDayProgress,markCinematicSeen,openFirstDayDocument,submitFirstDayDocument} from '@/lib/campaign/first-day';
import {initialState} from '@/lib/campaign/director';

describe('First Day accounting gameplay',()=>{
 it('starts as a focused three-document Chapter 1 prototype',()=>{const s=initialState();expect(firstDayProgress(s)).toEqual(emptyFirstDay());expect(firstDayDocuments.map(d=>d.id)).toEqual(['supplier-invoice','customer-receipt','office-expense']);expect(firstDayCompany(s)).toEqual({assets:1250000,liabilities:730000,revenue:420000,profit:85000});});
 it('stores cinematic and document inspection progress',()=>{let s=markCinematicSeen(initialState());s=openFirstDayDocument(s,'supplier-invoice');expect(firstDayProgress(s).cinematicSeen).toBe(true);expect(firstDayProgress(s).opened).toEqual(['supplier-invoice']);});
 it('records failed evidence but never changes company books',()=>{const result=submitFirstDayDocument(initialState(),'supplier-invoice','[]',1000);expect(result.correct).toBe(false);expect(result.state.journal).toHaveLength(0);expect(result.state.evidence[0]).toMatchObject({activityId:'first-day/supplier-invoice',accuracy:0,criticalErrors:1,correct:false});expect(firstDayCompany(result.state).assets).toBe(1250000);});
 it('updates each company metric from accepted entries only',()=>{let s=initialState();for(const doc of firstDayDocuments){const result=submitFirstDayDocument(s,doc.id,JSON.stringify(doc.expected),1000);expect(result.correct).toBe(true);s=result.state;}expect(firstDayCompany(s)).toEqual({assets:1347500,liabilities:830000,revenue:420000,profit:82500});expect(s.journal).toHaveLength(3);});
 it('awards the complete-day reward exactly once after all three entries',()=>{let s=initialState();for(const doc of firstDayDocuments)s=submitFirstDayDocument(s,doc.id,JSON.stringify(doc.expected),1000).state;expect(s.xp).toBe(100);expect(s.coins).toBe(50);expect(firstDayProgress(s).rewarded).toBe(true);for(const doc of firstDayDocuments)s=submitFirstDayDocument(s,doc.id,JSON.stringify(doc.expected),2000).state;expect(s.xp).toBe(100);expect(s.coins).toBe(50);expect(s.journal).toHaveLength(3);});
 it('keeps Chapter 2 locked and does not start the existing campaign director',()=>{let s=initialState();for(const doc of firstDayDocuments)s=submitFirstDayDocument(s,doc.id,JSON.stringify(doc.expected),1000).state;expect(s.active).toBeNull();expect(s.unlocked).toEqual(['first-desk']);expect(s.rewardKeys).toContain('first-day-complete');});
});
