import { describe,expect,it } from "vitest";
import { applyGameActivity, calculateCareerReadiness, createPlayerState, derivePlayerSnapshot, masteryBand, playerLevel } from "@/lib/game/engine";

describe("unified accounting game engine",()=>{
  it("starts with real zero evidence",()=>{const snapshot=derivePlayerSnapshot(createPlayerState());expect(snapshot).toMatchObject({xp:0,coins:0,level:1,careerReadiness:0});expect(Object.values(snapshot.skillScores).every(value=>value===0)).toBe(true)});
  it("awards the configured first-completion mission reward",()=>{const state=applyGameActivity(createPlayerState(),{kind:"mission",id:"office-supplies",score:85,skills:["business-cases","journal-entries"],completedAt:"2026-09-05T10:00:00Z"});expect(state).toMatchObject({xp:100,coins:35,streak:1});expect(state.activities["mission:office-supplies"].bestScore).toBe(85)});
  it("prevents XP farming from unchanged retries",()=>{const first=applyGameActivity(createPlayerState(),{kind:"practice",id:"entry-1",score:80,skills:["journal-entries"]});const retry=applyGameActivity(first,{kind:"practice",id:"entry-1",score:80,skills:["journal-entries"]});expect(retry.xp).toBe(first.xp);expect(retry.coins).toBe(first.coins);expect(retry.activities["practice:entry-1"].completions).toBe(2)});
  it("gives only a small reward for a new personal best",()=>{const first=applyGameActivity(createPlayerState(),{kind:"detective",id:"case-1",score:70,skills:["error-detection"]});const improved=applyGameActivity(first,{kind:"detective",id:"case-1",score:90,skills:["error-detection"]});expect(improved.xp-first.xp).toBe(16);expect(improved.coins-first.coins).toBe(5)});
  it("advances levels from a single XP scale",()=>{expect(playerLevel(0)).toBe(1);expect(playerLevel(180)).toBe(2);expect(playerLevel(4000)).toBe(8)});
  it("derives skill scores from recorded evidence",()=>{let state=createPlayerState();state=applyGameActivity(state,{kind:"practice",id:"a",score:80,skills:["journal-entries"]});state=applyGameActivity(state,{kind:"mission",id:"b",score:100,skills:["journal-entries"]});expect(derivePlayerSnapshot(state).skillScores["journal-entries"]).toBe(90);expect(masteryBand(90)).toBe("mastered")});
  it("uses real activities for career readiness",()=>{let state=createPlayerState();state=applyGameActivity(state,{kind:"mission",id:"m1",score:90,skills:["business-cases","accuracy"]});state=applyGameActivity(state,{kind:"detective",id:"d1",score:90,skills:["error-detection","accuracy"]});state=applyGameActivity(state,{kind:"arena",id:"a1",score:90,skills:["speed","accuracy"]});expect(calculateCareerReadiness(state)).toBeGreaterThan(0);expect(calculateCareerReadiness(createPlayerState())).toBe(0)});
  it("tracks consecutive days without inflating same-day streak",()=>{const first=applyGameActivity(createPlayerState(),{kind:"lesson",id:"1",score:90,skills:["fundamentals"],completedAt:"2026-09-05T10:00:00Z"});const same=applyGameActivity(first,{kind:"lesson",id:"2",score:90,skills:["fundamentals"],completedAt:"2026-09-05T12:00:00Z"});const next=applyGameActivity(same,{kind:"lesson",id:"3",score:90,skills:["fundamentals"],completedAt:"2026-09-06T10:00:00Z"});expect(same.streak).toBe(1);expect(next.streak).toBe(2)});
});

