import{beforeEach,describe,expect,it,vi}from'vitest';import{competitionScore,createOfflineResult,dailyChallenge,localDuel,verifyOfflineResult,weeklyLeague}from'@/lib/local-competition/engine';import{BrowserMultiProfileRepository,MULTI_PROFILE_KEY,PROFILE_SCOPED_KEYS,migrateMultiProfileState}from'@/lib/local-competition/repository';import type{LocalPlayerProfile}from'@/lib/local-competition/model';
beforeEach(()=>{localStorage.clear();vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-19T12:00:00Z'))});
describe('local multi-profile competition',()=>{
 it('migrates the current single-player save into Default Local Profile',()=>{const state=migrateMultiProfileState(null,{'debit-credit-world-v2':'saved'});expect(state.activeProfileId).toBe('default-local');expect(state.profiles[0].data['debit-credit-world-v2']).toBe('saved')});
 it('creates and switches isolated local profiles',()=>{localStorage.setItem(PROFILE_SCOPED_KEYS[0],'default-save');const repo=new BrowserMultiProfileRepository(),created=repo.create({displayName:'Mona',persona:'graduate',level:2,track:'ap'}),mona=created.activeProfileId;localStorage.setItem(PROFILE_SCOPED_KEYS[0],'mona-save');repo.switch('default-local');expect(localStorage.getItem(PROFILE_SCOPED_KEYS[0])).toBe('default-save');repo.switch(mona);expect(localStorage.getItem(PROFILE_SCOPED_KEYS[0])).toBe('mona-save')});
 it('exports and imports a versioned local package',()=>{const repo=new BrowserMultiProfileRepository();repo.get();const serialized=repo.export();localStorage.removeItem(MULTI_PROFILE_KEY);expect(repo.import(serialized).profiles[0].id).toBe('default-local');expect(()=>repo.import('{"schema":"remote"}')).toThrow(/Unsupported/)});
 it('generates deterministic versioned daily challenges',()=>{expect(dailyChallenge('2026-09-19',3,'ap')).toEqual(dailyChallenge('2026-09-19',3,'ap'));expect(dailyChallenge('2026-09-20',3,'ap').seed).not.toBe(dailyChallenge('2026-09-19',3,'ap').seed)});
 it('scores careful professional work above rushed assisted work',()=>{const careful=competitionScore({accuracy:95,judgment:90,investigation:95,riskAwareness:95,firstAttempt:true,difficulty:3,assistanceUsed:0}),rushed=competitionScore({accuracy:95,judgment:60,investigation:20,riskAwareness:10,firstAttempt:false,difficulty:3,assistanceUsed:3});expect(careful).toBeGreaterThan(rushed)});
 it('verifies offline result integrity and only duels the exact challenge version and seed',()=>{const challenge=dailyChallenge('2026-09-19',2,'foundation'),base={profileId:'a',displayName:'A',challenge,score:700,accuracy:90,investigation:80,riskAwareness:85,assistanceUsed:0,completedAt:'2026-09-19T10:00:00Z'},a=createOfflineResult(base),b=createOfflineResult({...base,profileId:'b',displayName:'B',score:650});expect(verifyOfflineResult(a)).toBe(true);expect(verifyOfflineResult({...a,score:999})).toBe(false);expect(localDuel(a,b)).toMatchObject({comparable:true,winnerProfileId:'a'});const other=createOfflineResult({...base,profileId:'c',challenge:dailyChallenge('2026-09-20',2,'foundation')});expect(localDuel(a,other).comparable).toBe(false)});
 it('segments weekly standings by equal level and track',()=>{const profiles:LocalPlayerProfile[]=[{id:'a',displayName:'A',persona:'graduate',level:2,track:'ap',createdAt:'x',updatedAt:'x',data:{}},{id:'b',displayName:'B',persona:'graduate',level:2,track:'gl',createdAt:'x',updatedAt:'x',data:{}}],challenge=dailyChallenge('2026-09-19',2,'ap'),result=createOfflineResult({profileId:'a',displayName:'A',challenge,score:800,accuracy:90,investigation:80,riskAwareness:90,assistanceUsed:0,completedAt:'x'});expect(weeklyLeague(profiles,[result],2,'ap').map(row=>row.profileId)).toEqual(['a'])});
});
