import{describe,expect,it}from'vitest';import{initialState}from'@/lib/campaign/director';import{ACCOUNT_META,acceptedJournal,projectLedger,projectTrialBalance}from'@/lib/platform/accounting-projection';import{destination,localizedPath,zone}from'@/lib/platform/navigation';
describe('canonical platform routing',()=>{
 it('keeps accounting tools and Nature of Accounts semantically separate',()=>{expect(destination('journal').path).toBe('/journal');expect(destination('ledger').path).toBe('/ledger');expect(destination('trial-balance').path).toBe('/trial-balance');expect(destination('financial-statements').path).toBe('/financial-statements');expect(destination('nature-of-accounts').path).toBe('/account-guide');expect(destination('ledger').path).not.toBe(destination('nature-of-accounts').path)});
 it('localizes every canonical route without legacy aliases',()=>{expect(localizedPath('ar',destination('ledger').path)).toBe('/ar/ledger');expect(localizedPath('en',destination('journal').path)).toBe('/en/journal')});
 it('maps company hotspots to dedicated zones and keeps Month End locked',()=>{expect(zone('suppliers').path).toBe('/game/suppliers');expect(zone('customers').path).toBe('/game/customers');expect(zone('bank').path).toBe('/game/bank');expect(zone('logistics').path).toBe('/game/logistics');expect(zone('month-end')).toMatchObject({path:'/game/month-end',status:'locked'})});
});
describe('accepted accounting projections',()=>{
 it('projects accepted journal lines into Ledger and Trial Balance without attempt evidence',()=>{const state=initialState();state.evidence.push({activityId:'failed/test',missionId:'test',chapterId:1,skillId:'journal',difficulty:1,accuracy:0,attempts:1,hintsUsed:0,completionTime:1,independentCompletion:false,criticalErrors:1,score:0,completedAt:'2026-01-01T00:00:00.000Z',mode:'practice',response:'bad',correct:false});state.journal.push({id:'first-day/customer-receipt',documentIds:['REC-4587'],lines:[{account:'bank',debit:75000,credit:0},{account:'customers',debit:0,credit:75000}]});expect(acceptedJournal(state)).toHaveLength(1);const bank=projectLedger(state).find(row=>row.account==='bank')!;expect(bank).toMatchObject({code:ACCOUNT_META.bank.code,debit:75000,credit:0,balance:75000});expect(bank.movements[0]).toMatchObject({entryId:'first-day/customer-receipt',documentIds:['REC-4587'],runningBalance:75000});expect(projectTrialBalance(state)).toMatchObject({totalDebit:75000,totalCredit:75000,difference:0})});
});
