import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react';
import{MarketingLanding}from'@/components/platform/marketing-landing';import{PlatformOnboarding}from'@/components/platform/onboarding';import{MobileGameNav}from'@/components/game/mobile-game-nav';import{ThemeProvider,ThemeToggle}from'@/components/platform/theme-provider';import{AcademyPlatform}from'@/components/platform/academy-platform';import{ChallengesPlatform}from'@/components/platform/challenges-platform';import{GameHub}from'@/components/platform/game-hub';import{THEME_KEY}from'@/lib/platform';import{PLATFORM_KEY}from'@/lib/platform/repository';
vi.mock('next/navigation',()=>({usePathname:()=>'/en'}));
beforeEach(()=>{localStorage.clear();document.documentElement.dataset.theme=''});afterEach(cleanup);
describe('platform UI',()=>{
 it('routes the public CTA through onboarding and labels employer preview',()=>{render(<MarketingLanding locale="en"/>);expect(screen.getByRole('heading',{name:'Learn accounting by doing real work.'})).toBeInTheDocument();expect(screen.getByRole('link',{name:/Start your accounting career/})).toHaveAttribute('href','/en/onboarding');expect(screen.getByText('EMPLOYER PREVIEW · DEMO')).toBeInTheDocument()});
 it('renders Arabic academy content and leaves Closing locked',()=>{render(<AcademyPlatform locale="ar"/>);expect(screen.getByRole('heading',{name:'اتعلّمها. تدرّب عليها. استخدمها في الشغل.'})).toBeInTheDocument();expect(screen.getByText(/الإقفال/).closest('article')).toHaveClass('locked')});
 it('exposes real challenge routes and labels the boss as locked',()=>{render(<ChallengesPlatform locale="en"/>);expect(screen.getAllByRole('link',{name:/Play challenge/})).toHaveLength(2);expect(screen.getByText('Month-End Crisis').closest('article')).toHaveClass('locked')});
 it('persists dark theme and applies it',async()=>{render(<ThemeProvider><ThemeToggle/></ThemeProvider>);fireEvent.click(screen.getByTitle('dark'));await waitFor(()=>expect(document.documentElement.dataset.theme).toBe('dark'));expect(localStorage.getItem(THEME_KEY)).toBe('dark')});
 it('restores a saved theme preference',async()=>{localStorage.setItem(THEME_KEY,'dark');render(<ThemeProvider><ThemeToggle/></ThemeProvider>);await waitFor(()=>expect(screen.getByTitle('dark')).toHaveAttribute('aria-pressed','true'))});
 it('stores onboarding choices without granting evidence',()=>{render(<PlatformOnboarding locale="en"/>);fireEvent.click(screen.getByRole('button',{name:/Accounting student/}));fireEvent.click(screen.getByRole('button',{name:/Prepare for work/}));const enter=screen.getByRole('link',{name:/Enter Game Hub/});enter.addEventListener('click',event=>event.preventDefault());fireEvent.click(enter);expect(JSON.parse(localStorage.getItem(PLATFORM_KEY)??'{}')).toMatchObject({experience:'student',goal:'career',onboardingComplete:true});expect(localStorage.getItem(PLATFORM_KEY)).not.toMatch(/verified|evidence/i)});
 it('provides five mobile game destinations in both directions',()=>{const view=render(<MobileGameNav locale="en"/>);expect(screen.getByRole('navigation',{name:'Mobile navigation'}).querySelectorAll('a')).toHaveLength(5);expect(screen.getByRole('link',{name:'Rank'})).toHaveAttribute('href','/en/leaderboard');view.rerender(<MobileGameNav locale="ar"/>);expect(screen.getByRole('navigation',{name:'تنقل الهاتف'})).toBeInTheDocument()});
 it('renders the Game Hub as an interactive company world with real routes',()=>{render(<GameHub locale="en"/>);expect(screen.getByRole('region',{name:'Interactive Mizan Trading map'})).toBeInTheDocument();expect(screen.getByRole('link',{name:/Suppliers/})).toHaveAttribute('href','/en/game/first-shift');expect(screen.getByRole('button',{name:/Month End/})).toBeDisabled();expect(screen.getByText('EMPLOYER PREVIEW · DEMO')).toBeInTheDocument()});
});
