import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react';
import{MarketingLanding}from'@/components/platform/marketing-landing';import{PlatformOnboarding}from'@/components/platform/onboarding';import{MobileGameNav}from'@/components/game/mobile-game-nav';import{ThemeProvider,ThemeToggle}from'@/components/platform/theme-provider';import{AcademyPlatform}from'@/components/platform/academy-platform';import{ChallengesPlatform}from'@/components/platform/challenges-platform';import{GameHub}from'@/components/platform/game-hub';import{THEME_KEY}from'@/lib/platform';import{PLATFORM_KEY}from'@/lib/platform/repository';
vi.mock('next/navigation',()=>({usePathname:()=>'/en'}));
beforeEach(()=>{localStorage.clear();document.documentElement.dataset.theme=''});afterEach(cleanup);
describe('platform UI',()=>{
 it('presents the complete cinematic Career League journey and its live product routes',()=>{render(<MarketingLanding locale="en"/>);expect(screen.getByRole('heading',{name:'Real competition. From anywhere.'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Start your journey'})).toHaveAttribute('href','/en/onboarding');expect(screen.getByRole('img',{name:/Two learners competing/})).toHaveAttribute('src',expect.stringContaining('career-league-hero-v2.png'));expect(screen.getByRole('heading',{name:'Your professional journey starts here'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Mizan Trading: Playable'})).toHaveAttribute('href','/en/game');expect(screen.getByRole('link',{name:'Month-End: Locked preview'})).toHaveClass('locked');expect(screen.getByRole('link',{name:'Finance Leadership: Career target'})).toHaveAttribute('href','/en/career-league/promotion');expect(screen.getByRole('link',{name:'Start competition'})).toHaveAttribute('href','/en/leaderboard');expect(screen.getByRole('link',{name:'View your CV'})).toHaveAttribute('href','/en/career-profile/cv');expect(screen.getByRole('link',{name:'Browse skills'})).toHaveAttribute('href','/en/career-profile/skills');expect(screen.getByAltText('Preview of the evidence-based ATS CV')).toBeInTheDocument();expect(screen.getByText('197')).toBeInTheDocument()});
 it('renders the Arabic landing hierarchy, career stages, and calls to action',()=>{render(<MarketingLanding locale="ar"/>);expect(screen.getByRole('heading',{name:'منافسة حقيقية من أي مكان!'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'ابدأ رحلتك الآن'})).toHaveAttribute('href','/ar/onboarding');expect(screen.getByRole('heading',{name:'رحلتك المهنية تبدأ من هنا'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'ميزان للتجارة: قابل للعب'})).toHaveAttribute('href','/ar/game');expect(screen.getByRole('link',{name:'الإقفال الشهري: معاينة مقفلة'})).toHaveClass('locked');expect(screen.getByRole('link',{name:'ابدأ المنافسة'})).toHaveAttribute('href','/ar/leaderboard');expect(screen.getByRole('link',{name:'شاهد سيرتك'})).toHaveAttribute('href','/ar/career-profile/cv');expect(screen.getByRole('link',{name:'تصفح المهارات'})).toHaveAttribute('href','/ar/career-profile/skills')});
 it('keeps competition and player stories honest about the local preview',()=>{const view=render(<MarketingLanding locale="en"/>);expect(screen.getAllByText('Local demo competition').length).toBeGreaterThan(0);expect(screen.getByText('Illustrative characters — not published reviews')).toBeInTheDocument();expect(screen.getAllByRole('img',{name:/Accounting Student|Fresh Graduate|Working Accountant/})).toHaveLength(3);expect(screen.queryByText(/students online/i)).not.toBeInTheDocument();expect(screen.queryByText(/job offer unlocked/i)).not.toBeInTheDocument();expect(screen.queryByText(/real employers/i)).not.toBeInTheDocument();expect(screen.queryByText(/Deloitte|KPMG|PwC|EY/)).not.toBeInTheDocument();view.rerender(<MarketingLanding locale="ar"/>);expect(screen.getAllByText('منافسة محلية تجريبية').length).toBeGreaterThan(0);expect(screen.getByText('شخصيات توضيحية — ليست تقييمات منشورة')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'رحلة مختلفة. تقدّم حقيقي.'})).toBeInTheDocument();expect(screen.queryByText(/طلاب متصلون/)).not.toBeInTheDocument();expect(screen.queryByText(/عرض وظيفي/)).not.toBeInTheDocument()});
 it('renders Arabic academy content and leaves Closing locked',()=>{render(<AcademyPlatform locale="ar"/>);expect(screen.getByRole('heading',{name:'اتعلّمها. تدرّب عليها. استخدمها في الشغل.'})).toBeInTheDocument();expect(screen.getByText(/الإقفال/).closest('article')).toHaveClass('locked')});
 it('exposes real challenge routes and labels the boss as locked',()=>{render(<ChallengesPlatform locale="en"/>);expect(screen.getAllByRole('link',{name:/Play challenge/})).toHaveLength(2);expect(screen.getByText('Month-End Crisis').closest('article')).toHaveClass('locked')});
 it('persists dark theme and applies it',async()=>{render(<ThemeProvider><ThemeToggle/></ThemeProvider>);fireEvent.click(screen.getByTitle('dark'));await waitFor(()=>expect(document.documentElement.dataset.theme).toBe('dark'));expect(localStorage.getItem(THEME_KEY)).toBe('dark')});
 it('restores a saved theme preference',async()=>{localStorage.setItem(THEME_KEY,'dark');render(<ThemeProvider><ThemeToggle/></ThemeProvider>);await waitFor(()=>expect(screen.getByTitle('dark')).toHaveAttribute('aria-pressed','true'))});
 it('stores student career entry and sends the foundation path to Bootcamp without granting evidence',()=>{render(<PlatformOnboarding locale="en"/>);fireEvent.click(screen.getByRole('button',{name:/Accounting Student/}));fireEvent.click(screen.getByRole('button',{name:/Get first accounting job/}));fireEvent.click(screen.getByRole('button',{name:/Start from the beginning/}));const enter=screen.getByRole('link',{name:/Enter Accounting Bootcamp/});expect(enter).toHaveAttribute('href','/en/bootcamp');enter.addEventListener('click',event=>event.preventDefault());fireEvent.click(enter);expect(JSON.parse(localStorage.getItem(PLATFORM_KEY)??'{}')).toMatchObject({experience:'student',goal:'career',onboardingComplete:true});expect(localStorage.getItem(PLATFORM_KEY)).not.toMatch(/verified|evidence/i)});
 it('provides five career-game mobile destinations in both directions',()=>{const view=render(<MobileGameNav locale="en"/>);expect(screen.getByRole('navigation',{name:'Mobile navigation'}).querySelectorAll('a')).toHaveLength(5);expect(screen.getByRole('link',{name:'League'})).toHaveAttribute('href','/en/leaderboard');expect(screen.getByRole('link',{name:'Profile'})).toHaveAttribute('href','/en/profile');view.rerender(<MobileGameNav locale="ar"/>);expect(screen.getByRole('navigation',{name:'تنقل الهاتف'})).toBeInTheDocument()});
 it('renders one full-screen Game Hub shell with canonical accounting routes',()=>{const{container}=render(<GameHub locale="en"/>);expect(container.querySelector('main')).toHaveClass('command-game');expect(container.querySelectorAll('.platform-nav')).toHaveLength(1);expect(screen.getByRole('region',{name:'Interactive Mizan Trading map'})).toBeInTheDocument();expect(screen.getByRole('link',{name:/Suppliers/})).toHaveAttribute('href','/en/game/suppliers');expect(screen.getByRole('link',{name:/Customers/})).toHaveAttribute('href','/en/game/customers');expect(screen.getByRole('link',{name:/Bank/})).toHaveAttribute('href','/en/game/bank');expect(screen.getByRole('link',{name:/Logistics/})).toHaveAttribute('href','/en/game/logistics');expect(screen.getByRole('link',{name:/Month End/})).toHaveAttribute('href','/en/game/month-end');expect(screen.getByRole('link',{name:'Ledger'})).toHaveAttribute('href','/en/ledger');expect(screen.getByRole('link',{name:'Nature of Accounts'})).toHaveAttribute('href','/en/account-guide');expect(screen.getByRole('link',{name:'Journal'})).toHaveAttribute('href','/en/journal');expect(screen.getByRole('link',{name:'Trial Balance'})).toHaveAttribute('href','/en/trial-balance');expect(screen.getByText('EMPLOYER PREVIEW · DEMO')).toBeInTheDocument()});
});
