import { accounts, arcadeCards, categories } from './content';
import { w, type Attempt, type GameState, type Line, type Skill, type Words } from './model';
export type ArcadeKind='sort'|'rush'|'entry'|'error'|'bank'|'tb'|'priority'|'classify'|'memory'|'chain';
export const arcadeModes:Record<ArcadeKind,{title:Words;skill:Skill;seconds:number;difficulty:1|2|3}>={sort:{title:w('Document Sort','فرز المستندات'),skill:'analysis',seconds:90,difficulty:1},rush:{title:w('Debit / Credit Rush','سباق المدين والدائن'),skill:'journal',seconds:90,difficulty:1},entry:{title:w('Build the Entry','ركّب القيد'),skill:'journal',seconds:180,difficulty:2},error:{title:w('Find the Error','اكتشف الخطأ'),skill:'investigation',seconds:90,difficulty:2},bank:{title:w('Bank Match','مطابقة البنك'),skill:'reconciliation',seconds:90,difficulty:2},tb:{title:w('Trial Balance Rescue','إنقاذ ميزان المراجعة'),skill:'posting',seconds:120,difficulty:2},priority:{title:w('Month-End Rush','سباق الإقفال'),skill:'adjustments',seconds:90,difficulty:3},classify:{title:w('Account Classification','تصنيف الحسابات'),skill:'analysis',seconds:90,difficulty:1},memory:{title:w('Memory Match','ذاكرة العمليات'),skill:'analysis',seconds:120,difficulty:1},chain:{title:w('Accounting Chain','سلسلة المحاسبة'),skill:'posting',seconds:120,difficulty:2}};
export type ArcadeQuestion={prompt:Words;answer:string;options?:readonly (readonly [string,Words])[];journal?:Line[];feedback:Words};
const feedback=w('Follow the business event, not just the words. Compare the source, account and direction.','اتبع العملية، مش الكلمات بس. قارن المصدر والحساب واتجاه الحركة.');
const entry=(debit:Line['account'],credit:Line['account'],amount:number)=>[{account:debit,debit:amount,credit:0},{account:credit,debit:0,credit:amount}];
export function arcadeQuestions(kind:ArcadeKind):ArcadeQuestion[]{
 if(kind==='sort'||kind==='rush')return arcadeCards.map(c=>({prompt:kind==='sort'?c.text:w(`${c.text.en}. ${c.account.en}?`,`${c.text.ar}. ${c.account.ar}؟`),answer:kind==='sort'?c.category:c.side,options:kind==='sort'?categories:[['debit',w('Debit','مدين')],['credit',w('Credit','دائن')]],feedback}));
 if(kind==='classify')return (['cash','suppliers','capital','revenue','rent','equipment'] as const).map((a,i)=>({prompt:accounts[a],answer:['asset','liability','equity','revenue','expense','asset'][i],options:[['asset',w('Asset','أصل')],['liability',w('Liability','التزام')],['equity',w('Equity','حقوق ملكية')],['revenue',w('Revenue','إيراد')],['expense',w('Expense','مصروف')]],feedback}));
 if(kind==='entry')return [
 {prompt:w('Owner invests 3,000 cash. Assemble the entry.','المالك يستثمر ٣٬٠٠٠ نقدًا. ركّب القيد.'),journal:entry('cash','capital',3000)},
 {prompt:w('Goods bought on credit, 900.','بضاعة مشتراة على الحساب، ٩٠٠.'),journal:entry('inventory','suppliers',900)},
 {prompt:w('Pay current rent 400 cash.','سداد إيجار الفترة ٤٠٠ نقدًا.'),journal:entry('rent','cash',400)},
 ].map(q=>({...q,answer:JSON.stringify(q.journal),feedback}));
 if(kind==='bank')return [
 {prompt:w('Statement: +7,500, customer Nour, reference R-11. Match the ledger item.','الكشف: +٧٬٥٠٠، العميل نور، المرجع R-11. طابق حركة الأستاذ.'),answer:'receipt',options:[['sale',w('New cash sale · S-04 · 7,500','بيع نقدي جديد · S-04 · ٧٬٥٠٠')],['receipt',w('Customer collection · R-11 · 7,500','تحصيل عميل · R-11 · ٧٬٥٠٠')],['capital',w('Owner funding · C-01 · 7,500','تمويل مالك · C-01 · ٧٬٥٠٠')]]},
 {prompt:w('Statement: −2,400 supplier Delta, P-18. Select the matching outflow.','الكشف: −٢٬٤٠٠ للمورد دلتا، P-18. اختار السداد المطابق.'),answer:'supplier',options:[['salary',w('Payroll · P-12 · 2,400','رواتب · P-12 · ٢٬٤٠٠')],['supplier',w('Supplier settlement · P-18 · 2,400','سداد مورد · P-18 · ٢٬٤٠٠')],['rent',w('Rent · P-19 · 2,400','إيجار · P-19 · ٢٬٤٠٠')]]},
 {prompt:w('Unmatched bank fee −50 appears only on the statement. What next?','رسوم بنك −٥٠ ظاهرة بالكشف بس. تعمل إيه؟'),answer:'record',options:[['record',w('Record bank fee expense and reduce bank','سجّل مصروف رسوم وخفّض البنك')],['delete',w('Delete the statement item','احذف حركة الكشف')],['revenue',w('Increase revenue','زوّد الإيراد')]]},
 ].map(q=>({...q,options:q.options as [string,Words][],feedback}));
 if(kind==='error')return [
 {prompt:w('Rent 400 cash: A) Dr Rent / Cr Cash. B) Dr Equipment / Cr Cash. Which draft is wrong?','إيجار ٤٠٠ نقدًا: أ) مدين إيجار / دائن صندوق. ب) مدين معدات / دائن صندوق. أنهي مسودة غلط؟'),answer:'b',options:[['a',w('Draft A','مسودة أ')],['b',w('Draft B — wrong account','مسودة ب — حساب غلط')]]},
 {prompt:w('Invoice D-5 for 900 appears twice in payables, and only one original exists. Identify the error.','فاتورة D-5 بـ٩٠٠ ظاهرة مرتين في الموردين، وأصلها واحد. حدد الخطأ.'),answer:'duplicate',options:[['duplicate',w('Duplicate posting','ترحيل مكرر')],['missing',w('Missing invoice','فاتورة ناقصة')],['amount',w('Original amount must be 1,800','الأصل لازم يكون ١٬٨٠٠')]]},
 {prompt:w('Cash payment 250: Dr Rent 250 / Cr Cash 520. What is wrong?','صرف نقدي ٢٥٠: مدين إيجار ٢٥٠ / دائن صندوق ٥٢٠. الغلط فين؟'),answer:'amount',options:[['amount',w('Credit amount transposed','المبلغ الدائن مقلوب')],['account',w('Cash account is forbidden','حساب الصندوق ممنوع')],['none',w('No error','مفيش خطأ')]]},
 ].map(q=>({...q,options:q.options as [string,Words][],feedback}));
 if(kind==='tb')return [
 {prompt:w('Ledger cash 5,000 copied to TB as 500. Debit total is understated by how much?','الصندوق ٥٬٠٠٠ اتنقل للميزان ٥٠٠. إجمالي المدين ناقص كام؟'),answer:'4500'},
 {prompt:w('A credit balance of 300 was placed in the debit column. What is the resulting difference?','رصيد دائن ٣٠٠ اتحط في المدين. الفرق الناتج كام؟'),answer:'600'},
 {prompt:w('Both sides of an entire 900 purchase entry were omitted. What TB difference will this cause?','طرفا قيد مشتريات ٩٠٠ اتحذفوا بالكامل. فرق الميزان هيكون كام؟'),answer:'0'},
 ].map(q=>({...q,feedback:w('A balanced trial balance does not prove completeness. A wrong-side balance creates twice the amount as a difference.','توازن الميزان مش دليل اكتمال. وضع الرصيد في الجانب الغلط يعمل فرق ضعف المبلغ.')}));
 if(kind==='priority')return [
 {prompt:w('8 tasks left. The CFO report is due in 10 minutes, payroll accrual is missing, and a payment is duplicated. First action?','٨ مهام باقية. التقرير بعد ١٠ دقايق، استحقاق الرواتب ناقص، وسداد مكرر. أول إجراء؟'),answer:'stop',options:[['decorate',w('Format the report','نسّق التقرير')],['stop',w('Stop the duplicate payment before release','أوقف السداد المكرر قبل التنفيذ')],['send',w('Send the inaccurate report now','ابعت التقرير الغلط دلوقتي')]]},
 {prompt:w('Payment stopped. Which task must precede the final trial balance?','السداد اتوقف. إيه لازم يسبق ميزان المراجعة النهائي؟'),answer:'accrue',options:[['accrue',w('Record the missing payroll accrual','أثبت استحقاق الرواتب الناقص')],['archive',w('Archive the incomplete file','أرشف الملف الناقص')],['promote',w('Request promotion','اطلب ترقية')]]},
 {prompt:w('Adjustments posted and balances checked. What happens before issuing reports?','التسويات اترحلت والأرصدة اتراجعت. إيه قبل إصدار القوائم؟'),answer:'review',options:[['review',w('Reconcile control accounts and review exceptions','طابق حسابات الرقابة وراجع الاستثناءات')],['ignore',w('Ignore unexplained differences','تجاهل الفروق')],['delete',w('Delete supporting documents','احذف المستندات')]]},
 ].map(q=>({...q,options:q.options as [string,Words][],feedback}));
 if(kind==='memory')return [
 {prompt:w('Customer pays an old invoice','عميل يسدد فاتورة قديمة'),answer:'receivable',options:[['profit',w('New profit increases','ربح جديد يزيد')],['receivable',w('Cash ↑ / Receivables ↓','النقدية ↑ / العملاء ↓')],['debt',w('Supplier debt ↑','دين المورد ↑')]]},
 {prompt:w('Owner invests cash','المالك يستثمر نقدية'),answer:'capital',options:[['sales',w('Sales revenue ↑','إيراد المبيعات ↑')],['expense',w('Expenses ↑','المصروفات ↑')],['capital',w('Cash ↑ / Capital ↑','النقدية ↑ / رأس المال ↑')]]},
 {prompt:w('Pay current rent','سداد إيجار الفترة'),answer:'rent',options:[['asset',w('Equipment ↑','المعدات ↑')],['rent',w('Expense ↑ / Cash ↓','المصروف ↑ / النقدية ↓')],['capital',w('Capital ↑','رأس المال ↑')]]},
 ].map(q=>({...q,options:q.options as [string,Words][],feedback}));
 return [
 {prompt:w('INV-014: goods received on credit. Connect to the correct entry.','INV-014: بضاعة على الحساب. صِل بالقيد الصحيح.'),answer:'journal',options:[['journal',w('Dr Inventory / Cr Payables','مدين مخزون / دائن موردين')],['cash',w('Dr Cash / Cr Revenue','مدين صندوق / دائن إيراد')]]},
 {prompt:w('The credit side of that same invoice must reach which ledger?','الطرف الدائن لنفس الفاتورة يروح لأي أستاذ؟'),answer:'ledger',options:[['profit',w('Profit directly','الربح مباشرة')],['ledger',w('Supplier ledger','أستاذ المورد')]]},
 {prompt:w('The unpaid supplier balance flows into which final report area?','رصيد المورد غير المدفوع يظهر فين في التقرير النهائي؟'),answer:'liabilities',options:[['revenue',w('Income statement revenue','إيرادات قائمة الدخل')],['liabilities',w('Financial position — liabilities','المركز المالي — الالتزامات')]]},
 ].map(q=>({...q,options:q.options as [string,Words][],feedback}));
}
export const arcadeActivityIds=Object.keys(arcadeModes).flatMap(k=>arcadeQuestions(k as ArcadeKind).map((_,i)=>`arcade/${k}/${i}`));
export function startArcadeRound(s:GameState,kind:ArcadeKind,key:string,now=Date.now()):GameState{if(s.arcade&&!s.arcade.finished)return s;return {...s,arcade:{kind,key,index:0,correct:0,combo:0,bestCombo:0,startedAt:now,answers:[],finished:false,draft:'',memoryOpen:[],memoryReviewed:false}};}
export function arcadeDraft(s:GameState,draft:string):GameState{return s.arcade&&!s.arcade.finished?{...s,arcade:{...s.arcade,draft}}:s;}
export function revealMemory(s:GameState,index:number):GameState{return s.arcade?.kind==='memory'?{...s,arcade:{...s.arcade,memoryOpen:[...new Set([...(s.arcade.memoryOpen??[]),index])]}}:s;}
export function hideMemory(s:GameState):GameState{return s.arcade?.kind==='memory'&&s.arcade.memoryOpen?.length===3?{...s,arcade:{...s.arcade,memoryReviewed:true,memoryOpen:[]}}:s;}
export function submitArcade(s:GameState,answer:string,now=Date.now()):GameState{const r=s.arcade;if(!r||r.finished)return s;const mode=arcadeModes[r.kind],qs=arcadeQuestions(r.kind),q=qs[r.index];const elapsed=Math.max(0,(now-r.startedAt)/1000);let matches=answer===q.answer;if(q.journal){try{const normalize=(lines:Line[])=>lines.map(l=>`${l.account}:${l.debit}:${l.credit}`).sort().join('|');matches=normalize(JSON.parse(answer))===normalize(q.journal);}catch{matches=false;}}
 const correct=elapsed<=mode.seconds&&matches&&(r.kind!=='memory'||Boolean(r.memoryReviewed));const combo=correct?r.combo+1:0;const run={...r,index:r.index+1,correct:r.correct+Number(correct),combo,bestCombo:Math.max(r.bestCombo,combo),answers:[...r.answers,{answer,correct,elapsed}],finished:r.index+1>=qs.length||elapsed>mode.seconds,draft:'',memoryOpen:[],memoryReviewed:false};const evidence:Attempt={activityId:`arcade/${r.kind}/${r.index}`,missionId:r.key,chapterId:0,skillId:mode.skill,difficulty:mode.difficulty,accuracy:correct?100:0,attempts:1,hintsUsed:0,completionTime:elapsed,independentCompletion:correct,criticalErrors:!correct&&q.journal?1:0,score:correct?100:0,completedAt:new Date(now).toISOString(),mode:'practice',response:answer,correct};const updated={...s,arcade:run,evidence:[...s.evidence,evidence]};if(!run.finished)return updated;const score=Math.round(run.correct/qs.length*100),key=`arcade:${r.key}`,rewarded=s.rewardKeys.includes(key)||score<70;return {...updated,arcadeBest:{...s.arcadeBest,[r.kind]:Math.max(s.arcadeBest[r.kind]??0,score)},coins:s.coins+(rewarded?0:10),xp:s.xp+(rewarded?0:20),rewardKeys:rewarded?s.rewardKeys:[...s.rewardKeys,key],activeDays:score>=70?[...new Set([...s.activeDays,new Date(now).toISOString().slice(0,10)])]:s.activeDays};}
