import { w, type Account, type Document, type Line, type Mission, type Stage } from './model';
export const accounts: Record<Account,ReturnType<typeof w>> = {cash:w('Cash','الصندوق'),bank:w('Bank','البنك'),inventory:w('Inventory','المخزون'),equipment:w('Equipment','المعدات'),customers:w('Receivables','العملاء'),suppliers:w('Payables','الموردون'),capital:w('Capital','رأس المال'),revenue:w('Revenue','الإيرادات'),rent:w('Rent expense','مصروف الإيجار'),salary:w('Salary expense','مصروف الرواتب'),accrual:w('Accrued salaries','رواتب مستحقة'),depreciation:w('Depreciation expense','مصروف الإهلاك'),accumulated:w('Accumulated depreciation','مجمع الإهلاك')};
export const documents: Document[] = [
 {id:'CAP-001',title:w('Owner deposit','إيداع المالك'),issuer:w('Mizan • Treasury','ميزان • الخزينة'),detail:w('Owner invests EGP 20,000 cash. Not a sale.','المالك أودع ٢٠٬٠٠٠ جنيه نقدًا. ليست مبيعات.'),amount:20000,category:'receipt'},
 {id:'INV-014',title:w('Supplier invoice','فاتورة المورد'),issuer:w('Delta Supplies','دلتا للتوريدات'),detail:w('Goods for resale, EGP 6,000 on credit. No VAT in this simplified case. Due at month-end.','بضاعة لإعادة البيع بـ٦٬٠٠٠ جنيه على الحساب. الحالة مبسطة بدون ضريبة. الاستحقاق آخر الشهر.'),amount:6000,category:'purchase'},
 {id:'RENT-01',title:w('Office rent receipt','إيصال إيجار المكتب'),issuer:w('Building owner','مالك العقار'),detail:w('Current month office rent, EGP 1,200 paid in cash.','إيجار المكتب للشهر الحالي، ١٬٢٠٠ جنيه نقدًا.'),amount:1200,category:'expense'},
 {id:'PETTY-07',title:w('Unfiled salary voucher','إذن صرف راتب غير مؤرشف'),issuer:w('Salma • Cashier','سلمى • أمينة الخزينة'),detail:w('Salary advance settled as current salary expense: EGP 500 paid, not yet recorded. Physical cash: EGP 18,300.','راتب عن الفترة الحالية: صُرف ٥٠٠ جنيه ولم يسجل. النقدية الفعلية: ١٨٬٣٠٠ جنيه.'),amount:500,category:'payment'},
 {id:'BANK-01',title:w('Bank statement','كشف البنك'),issuer:w('Mizan bank • closing file','بنك ميزان • ملف الإقفال'),detail:w('Owner transferred EGP 10,000 as additional capital. Statement closing balance EGP 10,000.','حوّل المالك ١٠٬٠٠٠ جنيه رأس مال إضافي. رصيد كشف البنك ١٠٬٠٠٠ جنيه.'),amount:10000,category:'receipt'},
 {id:'FIXED-01',title:w('Equipment purchase','شراء معدات'),issuer:w('Office Systems','أنظمة المكاتب'),detail:w('Paid EGP 2,400 from bank for equipment. Monthly depreciation EGP 200.','سداد ٢٬٤٠٠ جنيه من البنك لشراء معدات. إهلاك الشهر ٢٠٠ جنيه.'),amount:2400,category:'purchase'},
 {id:'HR-01',title:w('Payroll memo','مذكرة الرواتب'),issuer:w('Omar • Finance manager','عمر • المدير المالي'),detail:w('EGP 800 salaries earned this month, payable next month.','٨٠٠ جنيه رواتب تخص الشهر الحالي، تُدفع الشهر القادم.'),amount:800,category:'expense'},
];
const line=(account:Account,debit=0,credit=0):Line=>({account,debit,credit});
const choice=(id:string,title:ReturnType<typeof w>,prompt:ReturnType<typeof w>,skill:Stage['skill'],opts:[string,string,string][],answer:string,consequence:ReturnType<typeof w>,hint:ReturnType<typeof w>):Stage=>({id,kind:'choice',title,prompt,skill,options:opts.map(([id,en,ar])=>({id,label:w(en,ar)})),answer,consequence,hint});
const inspect=(id:string,ids:string[]):Stage=>({id,kind:'inspect',title:w('Open the evidence','افتح المستندات'),prompt:w('Tap every document. Check the source, amount and payment terms before accepting the file.','افتح كل مستند. راجع المصدر والمبلغ وشروط السداد قبل قبول الملف.'),skill:'analysis',documentIds:ids,consequence:w('Some evidence is still unopened.','لسه فيه مستندات لم تُفحص.'),hint:w('Inspect every tab in the document tray.','افتح كل ورقة في درج الوارد.')});
const journal=(id:string,ids:string[],lines:Line[],prompt:ReturnType<typeof w>):Stage=>({id,kind:'journal',title:w('Build the entry','ركّب القيد'),prompt,skill:'journal',documentIds:ids,journal:lines,effect:`entry:${id}`,consequence:w('This entry would misstate company balances. It stays in the draft until corrected. Compare the two accounts, sides and amount.','القيد ده هيشوّه أرصدة الشركة. هيفضل مسودة لحد التصحيح. راجع الحسابين والطرف والمبلغ.'),hint:w('Identify what increased and what financed it. Total debit must equal total credit.','حدد إيه زاد وإيه موّله. مجموع المدين لازم يساوي الدائن.')});
const number=(id:string,title:ReturnType<typeof w>,prompt:ReturnType<typeof w>,answer:number,skill:Stage['skill'],effect?:string):Stage=>({id,kind:'number',title,prompt,skill,answer:String(answer),effect,consequence:w('The control total does not agree. Recheck the evidence before approving.','رقم الرقابة مش مطابق. راجع المستندات قبل الاعتماد.'),hint:w('Use the journal and ledger on your desk. Only accepted entries affect balances.','استخدم اليومية والأستاذ على مكتبك. القيود المقبولة فقط بتغيّر الأرصدة.')});
export const chapters=[w('First Day','أول يوم'),w('The First Shift','أول وردية'),w('The Missing Money','الفلوس الناقصة'),w('The Messy Ledger','الأستاذ المتلخبط'),w('Month-End Is Coming','الإقفال قرب'),w('The Numbers Don’t Match','الأرقام مش متطابقة'),w('The CFO Wants Reports','المدير عايز التقارير'),w('The Promotion','الترقية')];
const manager=w('Omar · Finance manager','عمر · المدير المالي');
function mission(id:string,chapter:number,title:ReturnType<typeof w>,message:ReturnType<typeof w>,stages:Stage[],requires:string[],boss=false):Mission{return {id,chapter,title,message,speaker:manager,stages,requires,boss,difficulty:chapter<3?1:chapter<6?2:3,reward:{xp:boss?150:80,coins:boss?50:25},mode:boss?'assessment':'practice',origin:'mizan',companyId:'mizan'};}
export const missions:Mission[]=[
 mission('first-desk',1,w('Three papers. Your desk.','٣ ورقات. مكتبك.'),w('The previous accountant left transactions unfinished. Clear these three documents before we close the desk.','المحاسب السابق ساب عمليات ناقصة. خلّص التلات مستندات قبل ما نقفل المكتب.'),[
 inspect('arrival',['CAP-001','INV-014','RENT-01']),
 {id:'sort-tray',kind:'sort',title:w('Route the paperwork','وزّع المستندات'),prompt:w('Send each document to its correct tray.','حط كل ورقة في درجها الصحيح.'),skill:'analysis',documentIds:['CAP-001','INV-014','RENT-01'],answer:'receipt,purchase,expense',consequence:w('An owner deposit is not sales revenue. A credit invoice is a purchase, not a cash payment.','إيداع المالك مش إيراد مبيعات. فاتورة الآجل مشتريات، مش سداد نقدي.'),hint:w('Read who paid, what was acquired, and whether cash moved.','راجع مين دفع، وإيه اتشترى، وهل النقدية اتحركت.')},
 choice('capital-effect',w('Follow the money','اتبع الفلوس'),w('EGP 20,000 from the owner is now in your cash drawer. What else increases?','٢٠٬٠٠٠ جنيه من المالك دخلت الصندوق. إيه اللي بيزيد معاها؟'),'analysis',[['revenue','Sales revenue','إيراد المبيعات'],['capital','Owner’s capital','رأس مال المالك'],['suppliers','Supplier debt','مديونية المورد']], 'capital',w('Calling this revenue would overstate profit by EGP 20,000. The owner invested; no customer bought anything.','لو سجلتها إيراد هتزود الربح غلط بـ٢٠٬٠٠٠. ده استثمار مالك، مفيش عميل اشترى.'),w('This is financing from the owner.','ده تمويل من المالك.')),
 journal('capital',['CAP-001'],[line('cash',20000),line('capital',0,20000)],w('Record the owner’s cash investment of EGP 20,000.','سجّل استثمار المالك النقدي بـ٢٠٬٠٠٠ جنيه.')),
 ],[]),
 mission('clear-desk',1,w('Desk clearance · Boss','تسليم المكتب · مواجهة'),w('Now prove you can handle the remaining invoice and rent without me choosing the accounts.','ورّيني هتسجل فاتورة المورد والإيجار إزاي من غير ما أختار الحسابات مكانك.'),[
 journal('stock',['INV-014'],[line('inventory',6000),line('suppliers',0,6000)],w('Receive inventory on credit: EGP 6,000.','استلمت مخزون على الحساب بـ٦٬٠٠٠ جنيه.')),
 journal('rent',['RENT-01'],[line('rent',1200),line('cash',0,1200)],w('Current month rent paid in cash: EGP 1,200.','إيجار الشهر مدفوع نقدًا: ١٬٢٠٠ جنيه.')),
 number('drawer',w('Count the drawer','عدّ الصندوق'),w('From the accepted entries, how much cash should remain?','من القيود المقبولة، المفروض فاضل كام في الصندوق؟'),18800,'reconciliation')],['first-desk'],true),
 mission('first-shift',2,w('The supplier’s balance','رصيد المورد'),w('Delta asks how much we owe. Trace INV-014 from the invoice to its ledger before replying.','دلتا بتسأل لينا عندكم كام. تتبّع INV-014 من الفاتورة للأستاذ قبل الرد.'),[
 inspect('trace',['INV-014']),
 choice('post',w('Post INV-014','رحّل INV-014'),w('Choose the correct ledger destination for the credit side.','اختار حساب الأستاذ للطرف الدائن.'),'posting',[['cash','Cash debit','الصندوق مدين'],['suppliers','Payables credit','الموردون دائن'],['revenue','Revenue credit','الإيرادات دائن']],'suppliers',w('Posting to revenue inflates profit and hides supplier debt.','الترحيل للإيرادات يضخم الربح ويخفي دين المورد.'),w('The invoice remains unpaid.','الفاتورة لسه متسددتش.')),
 number('supplier-control',w('Supplier confirmation','مطابقة المورد'),w('How much do we owe Delta?','مديونيتنا لدلتا كام؟'),6000,'posting','post:stock')],['clear-desk']),
 mission('week-one',2,w('First shift review · Boss','مراجعة الوردية · مواجهة'),w('Before I sign, separate profit from cash and verify the accounting equation.','قبل التوقيع، افصل الربح عن النقدية وراجع المعادلة.'),[
 number('loss',w('Profit check','راجع الربح'),w('No sales yet. Enter the amount of the loss from rent.','مفيش مبيعات لسه. اكتب قيمة الخسارة الناتجة عن الإيجار.'),1200,'statements'),
 number('assets',w('Resources check','راجع الموارد'),w('Cash plus inventory: total assets?','النقدية + المخزون: إجمالي الأصول؟'),24800,'analysis')],['first-shift'],true),
 mission('missing-money',3,w('The unfiled voucher','إذن الصرف المختفي'),w('Salma counted EGP 18,300. Your books say 18,800. Find the missing EGP 500.','سلمى عدّت ١٨٬٣٠٠. الدفاتر بتقول ١٨٬٨٠٠. دور على فرق الـ٥٠٠.'),[
 inspect('evidence',['PETTY-07','RENT-01']),
 choice('cause',w('Name the cause','حدد السبب'),w('Which evidence explains the shortage?','أنهي دليل يفسر العجز؟'),'investigation',[['theft','Assume theft','افترض سرقة'],['salary','Unrecorded salary payment','راتب مصروف غير مسجل'],['rent','Record rent again','سجّل الإيجار مرة تانية']],'salary',w('Accusing theft without evidence is unsupported. Duplicating rent understates profit again.','اتهام السرقة بلا دليل غير مبرر. تكرار الإيجار يقلل الربح مرة تانية.'),w('Compare PETTY-07 with recorded entries.','قارن PETTY-07 بالقيود المسجلة.')),
 journal('salary-paid',['PETTY-07'],[line('salary',500),line('cash',0,500)],w('Record the missing salary payment, EGP 500 cash.','سجّل الراتب المصروف الناقص، ٥٠٠ جنيه نقدًا.'))],['week-one']),
 mission('save-cash',3,w('Save the drawer · Boss','إنقاذ الصندوق · مواجهة'),w('Reconcile the drawer and identify the impact on profit.','طابق الصندوق وحدد أثر التصحيح على الربح.'),[
 number('cash-close',w('Seal the drawer','اقفل الصندوق'),w('Correct closing cash?','رصيد النقدية الصحيح؟'),18300,'reconciliation','reconcile:cash'),
 number('loss-close',w('Revised loss','الخسارة المعدلة'),w('Rent plus salary expense: loss so far?','الإيجار + الرواتب: الخسارة لحد دلوقتي؟'),1700,'statements')],['missing-money'],true),
 mission('messy-ledger',4,w('The double invoice','الفاتورة المكررة'),w('A draft ledger lists INV-014 twice: 6,000 + 6,000. The original invoice is still on your desk.','مسودة الأستاذ فيها INV-014 مرتين: ٦٬٠٠٠ + ٦٬٠٠٠. الفاتورة الأصلية على مكتبك.'),[
 inspect('compare',['INV-014']),
 choice('duplicate',w('Mark the error','علّم على الخطأ'),w('One original invoice, two draft postings. What should be removed?','فاتورة أصلية واحدة وترحيلين مسودة. تحذف إيه؟'),'investigation',[['all','Both postings','الترحيلين'],['duplicate','Only the duplicate posting','الترحيل المكرر فقط'],['none','Nothing; pay 12,000','ولا حاجة؛ ادفع ١٢٬٠٠٠']],'duplicate',w('Paying both would overpay the supplier by EGP 6,000. Removing both hides the real debt.','سداد الاتنين يضيّع ٦٬٠٠٠ زيادة. حذف الاتنين يخفي الدين الحقيقي.'),w('Keep one posting per original business event.','خلي ترحيل واحد لكل عملية أصلية.'))],['save-cash']),
 mission('fix-ledger',4,w('Ledger sign-off · Boss','اعتماد الأستاذ · مواجهة'),w('Verify both sides after rejecting the duplicate.','راجع الطرفين بعد رفض التكرار.'),[
 number('inventory-control',w('Inventory control','رقابة المخزون'),w('INV-014 inventory balance?','رصيد مخزون INV-014؟'),6000,'posting'),
 number('payables-control',w('Debt control','رقابة الالتزامات'),w('Supplier balance after rejecting the duplicate?','رصيد المورد بعد رفض التكرار؟'),6000,'investigation')],['messy-ledger'],true),
 mission('month-end',5,w('Eight hundred still owed','٨٠٠ لسه مستحقة'),w('HR sent an unpaid salary memo. The expense belongs to this month.','الموارد البشرية بعتت رواتب غير مدفوعة تخص الشهر ده.'),[
 inspect('payroll',['HR-01']),journal('accrual',['HR-01'],[line('salary',800),line('accrual',0,800)],w('Accrue EGP 800 salaries; no cash payment yet.','أثبت استحقاق ٨٠٠ جنيه رواتب؛ لسه مفيش دفع نقدي.'))],['fix-ledger']),
 mission('close-period',5,w('Deadline review · Boss','مراجعة الموعد · مواجهة'),w('Do not close the period with unrecorded obligations.','متقفلش الفترة وفيه التزامات غير مسجلة.'),[
 number('liabilities',w('Liability control','رقابة الالتزامات'),w('Suppliers plus accrued salaries?','الموردون + الرواتب المستحقة؟'),6800,'adjustments'),
 number('period-loss',w('Period result','نتيجة الفترة'),w('Rent plus all salaries: loss?','الإيجار + كل الرواتب: الخسارة؟'),2500,'adjustments')],['month-end'],true),
 mission('numbers-mismatch',6,w('The copied balance','الرصيد المنسوخ غلط'),w('A draft trial balance copied inventory as 600 instead of 6,000. Investigate before approval.','مسودة ميزان المراجعة نقلت المخزون ٦٠٠ بدل ٦٬٠٠٠. حقق قبل الاعتماد.'),[
 number('difference',w('Find the difference','احسب الفرق'),w('By how much are draft debit totals understated?','إجمالي المدين في المسودة ناقص كام؟'),5400,'investigation'),
 choice('repair',w('Repair the source','صحح المصدر'),w('What correction belongs here?','إيه التصحيح المناسب؟'),'posting',[['new','Create another purchase','سجّل مشتريات جديدة'],['copy','Correct the copied TB balance only','صحح الرصيد المنقول للميزان فقط'],['cash','Reduce cash','قلل النقدية']],'copy',w('A new purchase duplicates the real transaction. This is a copying error, not a missing journal.','قيد مشتريات جديد يكرر العملية. ده خطأ نقل، مش قيد ناقص.'),w('The accepted journal and ledger already show 6,000.','اليومية والأستاذ المقبولين فيهم ٦٬٠٠٠.') )],['close-period']),
 mission('rescue-tb',6,w('Trial balance rescue · Boss','إنقاذ الميزان · مواجهة'),w('Give me both control totals, not just “it balances”.','عايز إجمالي الطرفين، مش مجرد «متوازن».'),[
 number('debits',w('Debit control','إجمالي المدين'),w('Cash 18,300 + inventory 6,000 + expenses 2,500. Total?','نقدية ١٨٬٣٠٠ + مخزون ٦٬٠٠٠ + مصروفات ٢٬٥٠٠. الإجمالي؟'),26800,'posting'),
 number('credits',w('Credit control','إجمالي الدائن'),w('Capital 20,000 + suppliers 6,000 + accruals 800. Total?','رأس مال ٢٠٬٠٠٠ + موردون ٦٬٠٠٠ + مستحقات ٨٠٠. الإجمالي؟'),26800,'investigation')],['numbers-mismatch'],true),
 mission('cfo-reports',7,w('The CFO’s envelope','ملف المدير المالي'),w('Turn the same balances into a financial story. No sales have occurred yet.','حوّل نفس الأرصدة لصورة مالية. مفيش مبيعات حصلت لسه.'),[
 number('net-assets',w('Financial position','المركز المالي'),w('Assets 24,300 less liabilities 6,800: equity?','أصول ٢٤٬٣٠٠ ناقص التزامات ٦٬٨٠٠: حقوق الملكية؟'),17500,'statements'),
 number('result',w('Income statement','قائمة الدخل'),w('How much loss reduced the original capital?','قيمة الخسارة اللي قللت رأس المال الأصلي؟'),2500,'statements')],['rescue-tb']),
 mission('cfo-review',7,w('CFO review · Boss','مراجعة المدير · مواجهة'),w('Explain why cash is not profit. Then reconcile the balance sheet.','وضح ليه النقدية مش ربح. وبعدين طابق المركز المالي.'),[
 choice('cash-profit',w('Defend the report','دافع عن التقرير'),w('Cash is positive but the company made a loss. Why?','النقدية موجبة والشركة خسرانة. ليه؟'),'statements',[['capital','Owner financing is not revenue','تمويل المالك مش إيراد'],['profit','All cash is profit','كل النقدية ربح'],['ignore','Ignore expenses','تجاهل المصروفات']],'capital',w('Treating owner financing as profit would mislead the CFO.','اعتبار تمويل المالك ربح يضلل المدير المالي.'),w('Separate financing from operating performance.','افصل التمويل عن نتيجة النشاط.')),
 number('balance-sheet',w('Sign the balance sheet','وقّع المركز المالي'),w('Liabilities 6,800 + equity 17,500: total?','التزامات ٦٬٨٠٠ + حقوق ملكية ١٧٬٥٠٠: الإجمالي؟'),24300,'statements')],['cfo-reports'],true),
 mission('month-end-file',8,w('The Month-End File · Final boss','ملف نهاية الشهر · المواجهة الأخيرة'),w('Your promotion file: review new capital, equipment and depreciation, reconcile the bank, then issue final reports. First attempts and help remain in your evidence.','ملف ترقيتك: راجع رأس المال الجديد والمعدات والإهلاك، طابق البنك وأصدر التقارير. المحاولة الأولى والمساعدة هيفضلوا في سجل الأدلة.'),[
 inspect('final-documents',['BANK-01','FIXED-01','HR-01','INV-014']),
 journal('bank-capital',['BANK-01'],[line('bank',10000),line('capital',0,10000)],w('Record EGP 10,000 additional owner capital received in bank.','سجّل ١٠٬٠٠٠ رأس مال إضافي وصل البنك.')),
 journal('equipment',['FIXED-01'],[line('equipment',2400),line('bank',0,2400)],w('Pay EGP 2,400 for equipment from bank.','ادفع ٢٬٤٠٠ جنيه معدات من البنك.')),
 number('post-equipment',w('Post and verify equipment','رحّل وراجع المعدات'),w('Equipment debit balance after posting?','رصيد المعدات المدين بعد الترحيل؟'),2400,'posting','post:equipment'),
 number('bank-reconcile',w('Reconcile the bank','طابق البنك'),w('Statement 10,000; equipment payment 2,400 not yet on statement. Adjusted bank balance?','الكشف ١٠٬٠٠٠؛ سداد المعدات ٢٬٤٠٠ لسه مظهرش بالكشف. الرصيد المعدل؟'),7600,'reconciliation','reconcile:bank'),
 number('final-tb',w('Unadjusted trial balance','ميزان قبل الإهلاك'),w('Debit total: cash 18,300 + bank 7,600 + stock 6,000 + equipment 2,400 + expenses 2,500.','إجمالي المدين: صندوق ١٨٬٣٠٠ + بنك ٧٬٦٠٠ + مخزون ٦٬٠٠٠ + معدات ٢٬٤٠٠ + مصروفات ٢٬٥٠٠.'),36800,'posting'),
 {...journal('depreciation',['FIXED-01'],[line('depreciation',200),line('accumulated',0,200)],w('Record monthly equipment depreciation EGP 200.','سجّل إهلاك المعدات للشهر ٢٠٠ جنيه.')),skill:'adjustments'},
 number('final-loss',w('Issue income statement','أصدر قائمة الدخل'),w('Total loss including depreciation?','إجمالي الخسارة شامل الإهلاك؟'),2700,'statements'),
 number('final-position',w('Issue financial position','أصدر المركز المالي'),w('Net assets: cash + bank + inventory + equipment less accumulated depreciation?','صافي الأصول: صندوق + بنك + مخزون + معدات ناقص مجمع الإهلاك؟'),34100,'statements'),
 number('final-review',w('Final review','المراجعة النهائية'),w('Assets 34,100 − liabilities 6,800 − equity 27,300. Unexplained difference?','أصول ٣٤٬١٠٠ − التزامات ٦٬٨٠٠ − حقوق ملكية ٢٧٬٣٠٠. الفرق غير المفسر؟'),0,'investigation')],['cfo-review'],true),
];
export const activityRegistry = Object.fromEntries(missions.flatMap(m=>m.stages.map(s=>[`${m.id}/${s.id}`,{mission:m,stage:s}])));
export const getMission=(id:string)=>missions.find(m=>m.id===id);
export const arcadeCards = [
 {text:w('Owner puts cash into the company','المالك يودع نقدية بالشركة'),category:'receipt',side:'debit',account:w('Cash increases','الصندوق يزيد')},
 {text:w('Goods bought on credit','بضاعة مشتراة على الحساب'),category:'purchase',side:'credit',account:w('Payables increase','الموردون يزيدون')},
 {text:w('Office rent paid','إيجار المكتب مدفوع'),category:'expense',side:'debit',account:w('Rent expense increases','مصروف الإيجار يزيد')},
 {text:w('Customer pays an old invoice','عميل يسدد فاتورة قديمة'),category:'receipt',side:'credit',account:w('Receivables decrease','العملاء يقلون')},
 {text:w('Supplier debt paid from bank','سداد دين المورد من البنك'),category:'payment',side:'credit',account:w('Bank decreases','البنك يقل')},
 {text:w('Service sold on credit','خدمة مباعة على الحساب'),category:'sale',side:'credit',account:w('Revenue increases','الإيراد يزيد')},
];
export const categories=[['purchase',w('Purchase','مشتريات')],['sale',w('Sale','مبيعات')],['expense',w('Expense','مصروف')],['receipt',w('Receipt','مقبوضات')],['payment',w('Payment','مدفوعات')]] as const;
