import { accounts, activityRegistry, getMission, missions } from './content';
import type { Account, Attempt, GameState, Line, Mission, Run, Skill, Stage } from './model';
export const initialState=():GameState=>({version:2,name:'',xp:0,coins:0,active:null,completed:{},evidence:[],journal:[],posted:[],reconciled:[],unlocked:['first-desk'],upgrades:[],activeDays:[],arcade:null,arcadeBest:{},rewardKeys:[],legacy:{}});
export const unlocked=(s:GameState,m:Mission)=>m.requires.every(id=>s.completed[id]?.bestScore>=70);
export const nextMission=(s:GameState)=>missions.find(m=>!s.completed[m.id]&&unlocked(s,m))??missions.find(m=>s.completed[m.id]?.bestScore<70&&unlocked(s,m))??null;
export function startMission(s:GameState,id:string,now=Date.now()):GameState{const m=getMission(id);if(!m||!unlocked(s,m)||s.active)return s;return {...s,active:{missionId:id,stage:0,draft:'',inspected:[],startedAt:now,stageStartedAt:now,hints:0,tries:0,passed:false,feedback:null,attempts:[]}};}
export function activeStage(s:GameState){const r=s.active;return r?getMission(r.missionId)?.stages[r.stage]:undefined;}
export function editDraft(s:GameState,draft:string):GameState{return s.active&&!s.active.passed?{...s,active:{...s.active,draft,feedback:null}}:s;}
export function inspectDocument(s:GameState,id:string):GameState{const st=activeStage(s);if(!s.active||!st?.documentIds?.includes(id))return s;return {...s,active:{...s.active,inspected:[...new Set([...s.active.inspected,id])]}};}
export function recordHint(s:GameState):GameState{return s.active&&!s.active.passed?{...s,active:{...s.active,hints:s.active.hints+1}}:s;}
function normalized(lines:Line[]){return lines.filter(l=>l.debit||l.credit).map(l=>`${l.account}:${l.debit}:${l.credit}`).sort().join('|');}
export function validate(stage:Stage,draft:string,inspected:string[]=[]){if(stage.kind==='inspect')return stage.documentIds!.every(id=>inspected.includes(id));if(stage.kind==='journal'){try{const lines=JSON.parse(draft) as Line[];return Array.isArray(lines)&&lines.every(l=>l.account in accounts&&Number.isFinite(l.debit)&&Number.isFinite(l.credit)&&l.debit>=0&&l.credit>=0)&&normalized(lines)===normalized(stage.journal!);}catch{return false;}}if(stage.kind==='number')return draft.trim()!==''&&Number(draft)===Number(stage.answer);return draft===stage.answer;}
function applyEffect(s:GameState,stage:Stage):GameState{if(stage.journal&&!s.journal.some(j=>j.id===stage.id))return {...s,journal:[...s.journal,{id:stage.id,documentIds:stage.documentIds??[],lines:stage.journal}]};if(stage.effect?.startsWith('post:'))return {...s,posted:[...new Set([...s.posted,stage.effect.slice(5)])]};if(stage.effect?.startsWith('reconcile:'))return {...s,reconciled:[...new Set([...s.reconciled,stage.effect.slice(10)])]};return s;}
export function submitStage(s:GameState,now=Date.now()):GameState{
 const r=s.active,stage=activeStage(s);if(!r||!stage||r.passed)return s;const m=getMission(r.missionId)!;const correct=validate(stage,r.draft,r.inspected);const attempt:Attempt={activityId:`${m.id}/${stage.id}`,missionId:m.id,chapterId:m.chapter,skillId:stage.skill,difficulty:m.difficulty,accuracy:correct?100:0,attempts:r.tries+1,hintsUsed:r.hints,completionTime:Math.max(0,(now-r.stageStartedAt)/1000),independentCompletion:correct&&r.hints===0&&r.tries===0,criticalErrors:correct?0:stage.kind==='journal'?1:0,score:correct?Math.max(30,100-r.tries*15-r.hints*10):0,completedAt:new Date(now).toISOString(),mode:m.mode,response:r.draft,correct};
 const updated={...s,evidence:[...s.evidence,attempt],active:{...r,tries:r.tries+1,passed:correct,feedback:correct?'correct' as const:'wrong' as const,attempts:[...r.attempts,attempt]}};return correct?applyEffect(updated,stage):updated;
}
export function continueMission(s:GameState,now=Date.now()):GameState{
 const r=s.active;if(!r?.passed)return s;const m=getMission(r.missionId)!;if(r.stage<m.stages.length-1)return {...s,active:{...r,stage:r.stage+1,draft:'',inspected:[],stageStartedAt:now,hints:0,tries:0,passed:false,feedback:null}};
 const successes=r.attempts.filter(a=>a.correct);const score=Math.round(successes.reduce((n,a)=>n+a.score,0)/m.stages.length);const prior=s.completed[m.id];const result={firstScore:prior?.firstScore??score,bestScore:Math.max(prior?.bestScore??0,score),runs:(prior?.runs??0)+1,stars:score>=95?3:score>=80?2:1,independent:prior?.independent||successes.every(a=>a.independentCompletion),completedAt:new Date(now).toISOString()};
 const rewarded=s.rewardKeys.includes(m.id);const date=new Date(now).toISOString().slice(0,10);const next={...s,active:null,completed:{...s.completed,[m.id]:result},xp:s.xp+(rewarded?0:m.reward.xp),coins:s.coins+(rewarded?0:m.reward.coins),rewardKeys:[...new Set([...s.rewardKeys,m.id])],activeDays:[...new Set([...s.activeDays,date])]};return {...next,unlocked:missions.filter(m=>unlocked(next,m)).map(m=>m.id)};
}
export function balances(s:GameState):Record<Account,number>{const b=Object.fromEntries(Object.keys(accounts).map(a=>[a,0])) as Record<Account,number>;for(const j of s.journal)for(const l of j.lines)b[l.account]+=l.debit-l.credit;return b;}
export function company(s:GameState){const b=balances(s);const processed=new Set(s.journal.flatMap(j=>j.documentIds));return {balances:b,processed:[...processed],cash:b.cash,bank:b.bank,inventory:b.inventory,liabilities:-b.suppliers-b.accrual,loss:b.rent+b.officeExpense+b.salary+b.depreciation-b.revenue,netAssets:b.cash+b.bank+b.inventory+b.equipment+b.accumulated,trialDifference:Math.abs(Object.values(b).reduce((a,b)=>a+b,0)),pendingPostings:s.journal.filter(j=>!s.posted.includes(j.id)).length};}
export function evidenceSummary(s:GameState){const scored=s.evidence.filter(a=>activityRegistry[a.activityId]&&activityRegistry[a.activityId].stage.kind!=='inspect');const first=[...new Map([...scored].reverse().map(a=>[a.activityId,a])).values()];const skills:Record<string,{score:number;count:number;independent:number;hard:number}>={};for(const skill of ['analysis','journal','posting','reconciliation','adjustments','statements','investigation'] as Skill[]){const rows=first.filter(a=>a.skillId===skill);skills[skill]={score:rows.length?Math.round(rows.reduce((n,a)=>n+a.accuracy,0)/rows.length):0,count:rows.length,independent:rows.filter(a=>a.independentCompletion).length,hard:rows.filter(a=>a.difficulty===3&&a.correct).length};}const independent=first.length?Math.round(100*first.filter(a=>a.independentCompletion).length/first.length):0;const accuracy=first.length?Math.round(first.reduce((n,a)=>n+a.accuracy,0)/first.length):0;const bosses=missions.filter(m=>m.boss&&s.completed[m.id]?.bestScore>=70).length;const final=s.completed['month-end-file'];const coverage=Object.values(skills).filter(v=>v.count>=2&&v.score>=70).length/7;const readiness=Math.min(final?.firstScore>=70?100:79,Math.round(coverage*30+independent*.2+bosses/8*20+(final?.firstScore??0)*.3));return {skills,accuracy,independent,bosses,readiness,ready:readiness>=80&&Boolean(final?.firstScore>=70),hints:s.evidence.reduce((n,a)=>n+(a.attempts===1?a.hintsUsed:0),0),first};}
export function candidateEvidence(s:GameState){return {id:'local-player',name:s.name||'Local player',companyId:'mizan',source:'local-unverified' as const,notAccredited:true,summary:evidenceSummary(s),attempts:s.evidence,completed:s.completed};}
export function streak(s:GameState,now=Date.now()){let count=0;const today=new Date(now).toISOString().slice(0,10);let day=s.activeDays.includes(today)?now:now-86400000;while(s.activeDays.includes(new Date(day).toISOString().slice(0,10))){count++;day-=86400000;}return count;}
export function upgradeOffice(s:GameState,id:string){if(!['lamp','organizer'].includes(id)||s.upgrades.includes(id)||s.coins<50)return s;return {...s,coins:s.coins-50,upgrades:[...s.upgrades,id]};}
export { startArcadeRound as startArcade, submitArcade as answerArcade } from './arcade';
export function safeLoad(raw:string|null):GameState{if(raw===null)return initialState();const recover=():GameState=>({...initialState(),storageWarning:'Saved progress could not be read. A safe new session was opened.'});try{const p=JSON.parse(raw);if(p?.version!==2||!Array.isArray(p.evidence)||!Array.isArray(p.journal)||typeof p.completed!=='object'||!Number.isFinite(p.xp)||!Number.isFinite(p.coins))return recover();const s={...initialState(),...p} as GameState;if(s.active&&(!getMission(s.active.missionId)||!activeStage(s)))s.active=null;return s;}catch{return recover();}}
export function resumePoint(s:GameState){return s.active?{missionId:s.active.missionId,stageId:activeStage(s)!.id,draft:s.active.draft}:null;}
export type EmployerChallenge={id:string;companyId:string;version:number;mission:Mission;assessmentPolicy:{maxAttempts:number;allowHints:boolean;timeLimitSeconds:number};requiredSkills:Skill[]};
export type { Run };
