// Canonical public destinations, not compatibility redirects or private/noindex pages.
// Each entry must have a physical App Router page; guarded by organization tests.
export const publicRoutes = [
  "",
  "/onboarding",
  "/bootcamp",
  "/game",
  "/game/first-shift",
  "/game/inbox",
  "/game/suppliers",
  "/game/customers",
  "/game/logistics",
  "/game/bank-reconciliation",
  "/game/month-end",
  "/academy",
  "/campaign",
  "/challenges",
  "/account-guide",
  "/journal",
  "/ledger",
  "/trial-balance",
  "/financial-statements",
  "/arena",
  "/career",
  "/career-league/map",
  "/career-league/companies",
  "/career-league/placement",
  "/career-league/gap",
  "/career-league/jobs",
  "/career-league/corporate-bridge",
  "/career-league/promotion",
  "/employers",
  "/employers/talent",
] as const;
