'use client';

import Link from 'next/link';
import Image from 'next/image';
import {useEffect,useState} from 'react';
import {Bell,BookOpen,BookMarked,BriefcaseBusiness,Building2,Calculator,Check,ChevronLeft,ClipboardCheck,FileBarChart,FileText,Home,Landmark,Lock,Map,Medal,Search,ShieldCheck,Star,Trophy,UserRound,X} from 'lucide-react';
import {useRouter} from 'next/navigation';
import type {Locale} from '@/types';
import type {GameState} from '@/lib/campaign/model';
import type {PlayerSnapshot} from '@/types/game';
import type {CareerLeagueState,VirtualCompany} from '@/lib/career-league/model';
import type {SkillEvidence,SkillId} from '@/lib/career/model';
import {companyTiers} from '@/lib/career-league/catalog';
import {companyUnlocked,careerLeagueScore} from '@/lib/career-league/engine';
import {firstDayProgress} from '@/lib/campaign/first-day';
import {projectShiftPerformance} from '@/lib/cases/performance';
import {firstShiftSkillEvidence,calculatePassport} from '@/lib/career/evidence';
import {skillCatalog} from '@/lib/career/catalog';
import {BrowserSkillEvidenceRepository,getOrCreateLocalCandidateId} from '@/lib/career/repository';
import {recordGameActivity} from '@/lib/game/progress';
import {GAME_REWARDS} from '@/lib/game/engine';
import {DemoLeaderboardRepository} from '@/lib/platform';
import {getAcademyCourse} from '@/data/academy';
import {ThemeToggle} from './theme-provider';

type Props={locale:Locale;careerState:CareerLeagueState;gameState:GameState;player:PlayerSnapshot};
const navItems=[
 {ar:'الرئيسية',en:'Home',path:'/game',icon:Home},
 {ar:'مهامي',en:'My Missions',path:'/game/inbox',icon:ClipboardCheck},
 {ar:'الشركة',en:'Company',path:'/career-league/companies',icon:Building2},
 {ar:'الأكاديمية',en:'Academy',path:'/academy',icon:BookOpen},
 {ar:'المنافسة',en:'Competition',path:'/leaderboard',icon:Trophy},
 {ar:'التوظيف',en:'Career',path:'/career',icon:BriefcaseBusiness},
 {ar:'ملفي المهني',en:'Career Profile',path:'/career-profile',icon:UserRound},
] as const;
const roadmap=[
 {ar:'أساسيات المحاسبة',en:'Accounting Foundations',path:'/academy/accounting-foundations'},
 {ar:'القيود اليومية',en:'Journal Entries',path:'/practice'},
 {ar:'دفتر الأستاذ',en:'General Ledger',path:'/ledger'},
 {ar:'ميزان المراجعة',en:'Trial Balance',path:'/trial-balance'},
 {ar:'الدورة المحاسبية',en:'Accounting Cycle',path:'/academy'},
 {ar:'القوائم المالية',en:'Financial Statements',path:'/financial-statements'},
 {ar:'المعايير المحاسبية',en:'Accounting Standards',path:null},
 {ar:'مسارات التحضير للشهادات المهنية',en:'Certification Preparation Tracks',path:null},
] as const;
const beginnerMissionId='beginner-owner-capital';
const questions=[
 {ar:'استلمت ميزان للتجارة ١٠٬٠٠٠ جنيه من المالك لبدء العمل. ماذا حدث؟',en:'Mizan Trading received EGP 10,000 from its owner to start operations. What happened?',options:[{ar:'دخل رأس مال إلى الشركة',en:'The owner invested capital'},{ar:'حققت الشركة إيراد بيع',en:'The company earned sales revenue'},{ar:'دفعت الشركة مصروفًا',en:'The company paid an expense'}],correct:0},
 {ar:'أي حسابين تأثرا؟',en:'Which two accounts changed?',options:[{ar:'النقدية ورأس المال',en:'Cash and Owner Capital'},{ar:'المبيعات والموردون',en:'Sales and Payables'},{ar:'المصروفات والبنك',en:'Expenses and Bank'}],correct:0},
 {ar:'ما أثر العملية على المعادلة المحاسبية؟',en:'What is the effect on the accounting equation?',options:[{ar:'تزيد النقدية ويزيد حق الملكية',en:'Cash and equity both increase'},{ar:'تزيد النقدية وينخفض حق الملكية',en:'Cash increases and equity decreases'},{ar:'لا شيء يتغير',en:'Nothing changes'}],correct:0},
 {ar:'هل انخفض حساب في هذه العملية؟',en:'Did any account decrease in this transaction?',options:[{ar:'لا، الحسابان زادا',en:'No, both accounts increased'},{ar:'نعم، النقدية انخفضت',en:'Yes, cash decreased'},{ar:'نعم، رأس المال انخفض',en:'Yes, capital decreased'}],correct:0},
] as const;

export function BeginnerCareerWorld({locale,careerState,gameState,player}:Props){
 const router=useRouter();
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,done=firstDayProgress(gameState).completed.length;
 const [stored,setStored]=useState<SkillEvidence[]>([]),[candidateId,setCandidateId]=useState('local-preview'),[selected,setSelected]=useState<VirtualCompany|null>(null),[missionStep,setMissionStep]=useState(-1),[missionError,setMissionError]=useState(false),[searchOpen,setSearchOpen]=useState(false),[search,setSearch]=useState(''),[noticeOpen,setNoticeOpen]=useState(false),[calculatorOpen,setCalculatorOpen]=useState(false),[expression,setExpression]=useState(''),[calcResult,setCalcResult]=useState(''),[roadmapNotice,setRoadmapNotice]=useState<number|null>(null);
 useEffect(()=>{setStored(new BrowserSkillEvidenceRepository().getAll());setCandidateId(getOrCreateLocalCandidateId())},[]);
 const projected=firstShiftSkillEvidence(gameState,candidateId);
 const deduped=new globalThis.Map([...stored.filter(row=>row.localCandidateId===candidateId),...projected].map(row=>[row.evidenceId,row]));
 const passport=calculatePassport([...deduped.values()]);
 const completedMissionIds=done===3?['first-shift']:[];
 const unlocked=companyTiers.map(company=>companyUnlocked(company.id,passport,completedMissionIds,careerState.assessmentResults));
 const currentTier=Math.max(1,...companyTiers.filter((_,index)=>unlocked[index]).map(company=>company.tier));
 const missionDone=Boolean(player.activities[`practice:${beginnerMissionId}`]);
 const performance=projectShiftPerformance(gameState);
 const rawScore=careerLeagueScore({...performance,firstAttemptQuality:done/3*100,difficulty:1,bossCompletion:done===3?100:0,consistency:done/3*100});
 const rows=new DemoLeaderboardRepository().list('weekly',{id:'local-player',nameAr:player.displayName,nameEn:player.displayName,score:rawScore,accuracy:performance.accuracy,investigation:performance.investigation,riskAwareness:performance.riskAwareness,demo:false});
 const rank=rows.findIndex(row=>row.id==='local-player')+1,above=rank>1?rows[rank-2]:null;
 const skillIds:SkillId[]=['accounting-fundamentals','account-classification','debit-credit','journal-entries','ledger-posting'];
 const foundationLessons=getAcademyCourse('accounting-foundations')?.modules.flatMap(module=>module.lessons)??[];
 const hasFoundations=foundationLessons.length>0&&foundationLessons.every(lesson=>Boolean(player.activities[`lesson:accounting-foundations/${lesson.slug}`]));
 const stage=hasFoundations?1:0;
 const stageStatus=(index:number)=>index===stage?'current':index<stage?'complete':index>=6?'planned':'locked';
 const close=()=>{setSelected(null);setMissionStep(-1);setRoadmapNotice(null)};
 const answer=(index:number)=>{if(missionStep<0)return;if(index!==questions[missionStep].correct){setMissionError(true);return}setMissionError(false);if(missionStep===questions.length-1){if(!missionDone)recordGameActivity('practice',beginnerMissionId,100,['fundamentals','transaction-analysis','account-classification']);setMissionStep(questions.length)}else setMissionStep(missionStep+1)};
 const calculate=()=>{if(!/^\s*[\d.]+\s*[+*/-]\s*[\d.]+\s*$/.test(expression)){setCalcResult(say('Enter two numbers and an operator.','أدخل رقمين وعلامة عملية.'));return}const parts=expression.match(/([\d.]+)\s*([+*/-])\s*([\d.]+)/);if(!parts)return;const a=Number(parts[1]),b=Number(parts[3]),value=parts[2]==='+'?a+b:parts[2]==='-'?a-b:parts[2]==='*'?a*b:b===0?NaN:a/b;setCalcResult(Number.isFinite(value)?String(value):say('Invalid calculation','عملية غير صالحة'))};
 return <main className="beginner-world" dir={ar?'rtl':'ltr'}>
  <header className="bcw-top"><Link href={`/${locale}/game`} className="bcw-brand"><span className="bcw-mark">◩</span><span><b>Debit & Credit</b><small>by Money Coder</small></span></Link><nav aria-label={say('Main navigation','التنقل الرئيسي')}>{navItems.map((item,index)=>{const Icon=item.icon;return <Link className={index===0?'active':''} href={`/${locale}${item.path}`} key={item.path}><Icon/><span>{item[locale]}</span></Link>})}</nav><div className="bcw-top-actions"><button aria-label={say('Search','بحث')} onClick={()=>setSearchOpen(!searchOpen)}><Search/></button><ThemeToggle compact/><button aria-label={say('Notifications','الإشعارات')} onClick={()=>setNoticeOpen(!noticeOpen)}><Bell/>{done<3&&<i>{3-done}</i>}</button><Link className="bcw-top-player" href={`/${locale}/profile`}><Image src="/platform/beginner-student-avatar.png" alt="" width={42} height={42}/><span><b>{player.displayName}</b><small>{say('Accounting Student','طالب محاسبة')}</small></span></Link></div></header>
  {searchOpen&&<div className="bcw-search"><input autoFocus aria-label={say('Search destinations','ابحث عن وجهة')} value={search} onChange={event=>setSearch(event.target.value)} placeholder={say('Search tools and destinations','ابحث في الأدوات والوجهات')}/>{navItems.filter(item=>item[locale].toLowerCase().includes(search.toLowerCase())||search==='').map(item=><Link key={item.path} href={`/${locale}${item.path}`}>{item[locale]}</Link>)}</div>}
  {noticeOpen&&<div className="bcw-notice"><b>{say('Pending work','العمل المعلق')}</b><p>{say(`${3-done} First Shift documents remain.`,`باقي ${3-done} مستندات في أول وردية.`)}</p><Link href={`/${locale}/game/inbox`}>{say('Open inbox','افتح الوارد')}</Link></div>}
  <div className="bcw-layout"><aside className="bcw-rail"><section className="bcw-identity"><Image src="/platform/beginner-student-avatar.png" alt="" width={94} height={94}/><div><small>{say('YOUR CAREER JOURNEY','رحلتك المهنية')}</small><h2>{say('Beginner Student','طالب مبتدئ')}</h2><p>{say('Accounting Student','طالب محاسبة')}</p><span>{say('Game Level','مستوى اللعبة')} {player.level}</span></div><div className="bcw-level"><i style={{width:`${player.levelProgress}%`}}/><span>{player.levelProgress}%</span></div><footer>{player.xp} XP · {say('Next level','المستوى التالي')}: {player.nextLevelXp} XP</footer></section>
   <section className="bcw-roadmap"><h2><Map/>{say('Career journey','رحلة المحاسبة')}</h2>{roadmap.map((item,index)=>{const status=stageStatus(index);return <button key={item.en} className={`bcw-roadmap-node ${status}`} onClick={()=>status==='current'||status==='complete'?item.path?router.push(`/${locale}${item.path}`):undefined:setRoadmapNotice(index)}><span className="bcw-node-num">{status==='complete'?<Check/>:index+1}</span><span><b>{item[locale]}</b><small>{say(status==='current'?'Current':status==='complete'?'Completed':status==='planned'?'Planned':'Locked',status==='current'?'الحالية':status==='complete'?'مكتملة':status==='planned'?'مخطط لها':'مقفولة')}</small></span>{status==='locked'||status==='planned'?<Lock className="bcw-lock"/>:null}</button>})}</section>
   <section className="bcw-milestone"><small>{say('NEXT MILESTONE','محطتك القادمة')}</small><b>{hasFoundations?say('Journal Fundamentals','أساسيات القيود'):say('Accounting Foundations','أساسيات المحاسبة')}</b><span>{say('In Progress','قيد التقدم')}</span></section></aside>
  <div className="bcw-main"><section className="bcw-world" aria-label={say('Career company world','عالم الشركات المهني')}><div className="bcw-world-heading"><div><h1>{say('From the beginning... to your professional future','من البداية... إلى مستقبلك المهني')}</h1><p>{say('Learn. Apply. Work. Compete. Get ready for real accounting.','تعلّم. طبّق. اعمل. تنافس. كن جاهزًا لعالم المحاسبة الحقيقي.')}</p></div><div className="bcw-mentor"><div><b>{say('Kareem · Finance Manager','أ/ كريم · المدير المالي')}</b><p>{say('Welcome to your journey. Start with the fundamentals and understand before memorizing.','مرحبًا بك في رحلتك. ابدأ من الأساسيات، وافهم قبل ما تحفظ.')}</p></div><div className="bcw-mentor-face" aria-hidden="true"/></div></div><div className="bcw-city">{companyTiers.map((company,index)=><button key={company.id} className={`bcw-company bcw-company-${index+1} ${unlocked[index]?'unlocked':'locked'}`} onClick={()=>company.tier===1?router.push(`/${locale}/game/first-shift`):setSelected(company)} title={`${company.name[locale]} · ${company.environment[locale]}`} data-details={`${say('Career level','المستوى المهني')}: ${company.tier}\n${say('Required skills','المهارات المطلوبة')}: ${company.unlock.requirements.map(req=>skillCatalog[req.skillId].label[locale]).join(', ')||say('Foundations','الأساسيات')}\n${say('Promotion','الترقية')}: ${company.unlock.promotionAssessmentId??'—'}\n${say('Status','الحالة')}: ${unlocked[index]?say('Available','متاحة'):say('Locked','مقفولة')}`}><span className="bcw-company-icon">{unlocked[index]?<Building2/>:<Lock/>}</span><b>{company.name[locale]}</b><small>{company.environment[locale]}</small><em>{say('Stage','المرحلة')} {company.tier}</em></button>)}</div><div className="bcw-map-track"><strong>{say('CAREER MAP','الخريطة المهنية')}</strong><div>{companyTiers.map((company,index)=><button key={company.id} className={unlocked[index]?'lit':''} onClick={()=>company.tier===1?router.push(`/${locale}/game/first-shift`):setSelected(company)} aria-label={company.name[locale]}>{unlocked[index]?<Check/>:index+1}<small>{company.name[locale]}</small></button>)}</div><span>{currentTier}/5</span></div></section>
   <div className="bcw-panels"><section className="bcw-panel bcw-mission"><header><h2>{say('Current mission','مهمتك الحالية')}</h2><small>{missionDone?say('Completed','مكتملة'):say('Beginner · Available','مبتدئ · متاحة')}</small></header><div className="bcw-mission-body"><div className="bcw-document"><FileText/><b>{say('Owner Capital Receipt','إيصال رأس مال المالك')}</b><span>Mizan Trading</span><strong>EGP 10,000</strong><small>{say('Source document','مستند مصدر')}</small></div><div className="bcw-mission-copy"><h3>{say('Understand the Transaction','افهم العملية')}</h3><p>{say('Investigate the owner investment. Identify the accounts and what increased before making any entry.','افحص استثمار المالك. حدّد الحسابات وما زاد قبل تسجيل أي قيد.')}</p><div><span><ShieldCheck/>{say('Accounting equation','المعادلة المحاسبية')}</span><span><Star/>{say('Transaction effect','أثر العملية')}</span></div><button onClick={()=>setMissionStep(0)}>{missionDone?say('Replay mission','أعد المهمة'):say('Start mission','ابدأ المهمة')} <ChevronLeft/></button></div></div></section>
    <section className="bcw-panel bcw-skills"><header><h2>{say('Your skills','مهاراتك الحالية')}</h2><Link href={`/${locale}/career-profile/skills`}>{say('Passport','الجواز')}</Link></header>{skillIds.map(id=>{const result=passport.find(item=>item.skillId===id)!;return <div className="bcw-skill" key={id}><span>{skillCatalog[id].label[locale]}</span><strong>{result.status==='unassessed'?say('Unassessed','لم تُقيّم'):result.status==='practiced'?say('Practiced','مُورست'):result.status==='demonstrated'?say('Demonstrated','مُثبتة'):say('Verified','موثقة')}</strong>{result.score!==null&&<i style={{width:`${result.score}%`}}/>}</div>})}</section>
    <section className="bcw-panel bcw-tools"><header><h2>{say('Accounting tools','الأدوات المحاسبية')}</h2></header><div>{[{icon:BookMarked,ar:'دفتر الأستاذ',en:'Ledger',path:'/ledger'},{icon:Landmark,ar:'ميزان المراجعة',en:'Trial Balance',path:'/trial-balance'},{icon:FileBarChart,ar:'القوائم المالية',en:'Financial Statements',path:'/financial-statements'},{icon:BookOpen,ar:'طبيعة الحسابات',en:'Nature of Accounts',path:'/account-guide'},{icon:Calculator,ar:'الحاسبة',en:'Calculator',path:null},{icon:FileText,ar:'المستندات',en:'Documents',path:'/game/inbox'}].map((tool,index)=>{const Icon=tool.icon,content=<><Icon/><span>{tool[locale]}</span></>;return tool.path?<Link className={`tool-${index}`} key={tool.en} href={`/${locale}${tool.path}`}>{content}</Link>:<button className={`tool-${index}`} key={tool.en} onClick={()=>setCalculatorOpen(true)}>{content}</button>})}</div></section>
    <section className="bcw-panel bcw-competition"><header><h2>{say('Challenges & competition','التحديات والمنافسة')}</h2><small>{say('DEMO LEAGUE','دوري تجريبي')}</small></header><div className="bcw-challenge"><Trophy/><span><b>{say('Daily challenge','تحدي اليوم')}</b><small>{say('Fix the Journal','أصلح القيد')}</small></span><strong>+{GAME_REWARDS.practice.xp} XP {say('practice','تدريب')}</strong><Link href={`/${locale}/practice`}>{say('Open','افتح')}</Link></div><div className="bcw-rank"><Medal/><span><b>#{rank} {say('local demo rank','الترتيب التجريبي المحلي')}</b><small>{rawScore} {say('performance points','نقطة أداء')}{above?` · ${Math.max(0,above.score-rawScore)} ${say('to next rank','للمركز التالي')}`:''}</small></span></div><Link href={`/${locale}/leaderboard`}>{say('View Demo League','اعرض الدوري التجريبي')}</Link></section></div></div></div>
  <nav className="bcw-mobile-nav" aria-label={say('Mobile navigation','تنقل الهاتف')}>{navItems.filter((_,index)=>[0,1,2,4,6].includes(index)).map(item=>{const Icon=item.icon;return <Link key={item.path} href={`/${locale}${item.path}`}><Icon/><span>{item[locale]}</span></Link>})}</nav>
  {selected&&<div className="bcw-modal-backdrop" onClick={close}><section className="bcw-modal" role="dialog" aria-modal="true" aria-label={selected.name[locale]} onClick={event=>event.stopPropagation()}><button className="bcw-close" aria-label={say('Close','إغلاق')} onClick={close}><X/></button><small>{say('COMPANY STAGE','مرحلة الشركة')} {selected.tier}</small><h2>{selected.name[locale]}</h2><p>{selected.environment[locale]} · {selected.simulationLabel[locale]}</p><h3>{say('What you will learn','ما ستتعلمه')}</h3><ul>{selected.characteristics.map(item=><li key={item.en}>{item[locale]}</li>)}</ul>{selected.tier>1&&<><h3>{say('Required skills','المهارات المطلوبة')}</h3><ul>{selected.unlock.requirements.map(req=>{const found=passport.find(row=>row.skillId===req.skillId);return <li key={req.skillId}>{skillCatalog[req.skillId].label[locale]} · {say(req.minimum==='practiced'?'Practiced':'Demonstrated',req.minimum==='practiced'?'مُورست':'مُثبتة')} · {found?.status===req.minimum||found?.status==='demonstrated'||found?.status==='verified'?<Check/>:<span>{say('Missing','ناقصة')}</span>}</li>})}</ul><p>{say('Promotion requirement','شرط الترقية')}: {selected.unlock.promotionAssessmentId??'—'}</p><strong className="bcw-status"><Lock/>{say('Locked until requirements are met','مقفولة حتى تتحقق الشروط')}</strong></>}{selected.tier===1&&<Link className="bcw-modal-cta" href={`/${locale}/game/first-shift`}>{say('Enter Mizan Trading','ادخل ميزان للتجارة')}</Link>}</section></div>}
  {missionStep>=0&&<div className="bcw-modal-backdrop" onClick={close}><section className="bcw-modal bcw-mission-modal" role="dialog" aria-modal="true" aria-label={say('Understand the Transaction','افهم العملية')} onClick={event=>event.stopPropagation()}><button className="bcw-close" aria-label={say('Close','إغلاق')} onClick={close}><X/></button><small>{say('MIZAN TRADING · BEGINNER CASE','ميزان للتجارة · حالة المبتدئ')}</small><h2>{say('Understand the Transaction','افهم العملية')}</h2>{missionStep<questions.length?<><p>{say('Owner Capital Receipt · EGP 10,000','إيصال رأس مال المالك · ١٠٬٠٠٠ جنيه')}</p><div className="bcw-mission-progress">{missionStep+1}/{questions.length}</div><h3>{questions[missionStep][locale]}</h3><div className="bcw-options">{questions[missionStep].options.map((option,index)=><button key={index} onClick={()=>answer(index)}>{option[locale]}</button>)}</div>{missionError&&<p role="alert">{say('Look at the source document and try again.','راجع المستند وحاول مرة أخرى.')}</p>}</>:<><Check className="bcw-success"/><h3>{say('Transaction understood','فهمت العملية')}</h3><p>{say('Cash and owner equity increased. No account decreased. This is game practice, not professional Skill Passport evidence.','زادت النقدية وحقوق المالك. لم ينخفض أي حساب. هذه ممارسة داخل اللعبة وليست دليلًا مهنيًا في جواز المهارات.')}</p><button className="bcw-modal-cta" onClick={close}>{say('Back to world','العودة للعالم')}</button></>}</section></div>}
  {roadmapNotice!==null&&<div className="bcw-modal-backdrop" onClick={close}><section className="bcw-modal" role="dialog" aria-modal="true" onClick={event=>event.stopPropagation()}><button className="bcw-close" onClick={close} aria-label={say('Close','إغلاق')}><X/></button><h2>{roadmap[roadmapNotice][locale]}</h2><p>{roadmapNotice>=6?say('Planned for a future stage. This is a preparation track, not an official certification.','مخطط لها في مرحلة مستقبلية. هذا مسار تحضير وليس شهادة رسمية.'):say('Continue the current foundation stage to unlock this milestone.','أكمل مرحلة الأساسيات الحالية لفتح هذه المحطة.')}</p></section></div>}
  {calculatorOpen&&<div className="bcw-modal-backdrop" onClick={()=>setCalculatorOpen(false)}><section className="bcw-modal" role="dialog" aria-modal="true" aria-label={say('Calculator','الحاسبة')} onClick={event=>event.stopPropagation()}><button className="bcw-close" onClick={()=>setCalculatorOpen(false)} aria-label={say('Close','إغلاق')}><X/></button><h2>{say('Calculator','الحاسبة')}</h2><input aria-label={say('Calculation','العملية الحسابية')} value={expression} onChange={event=>setExpression(event.target.value)} placeholder="10000 + 2500"/><button className="bcw-modal-cta" onClick={calculate}>{say('Calculate','احسب')}</button><output>{calcResult}</output></section></div>}
 </main>;
}
