'use client';

import Link from 'next/link';
import {ArrowLeft,ArrowRight,BadgeCheck,BarChart3,Bell,BookMarked,BookOpen,BriefcaseBusiness,Building2,Check,ChevronRight,CircleUserRound,ClipboardCheck,FileBarChart,FileText,Gamepad2,Inbox,Landmark,Lock,Search,Settings,ShieldCheck,Star,Truck,Users,WalletCards} from 'lucide-react';
import {useGame} from '@/lib/campaign/store';
import {firstDayCompany,firstDayDocuments,firstDayProgress} from '@/lib/campaign/first-day';
import {projectShiftPerformance} from '@/lib/cases/performance';
import {calculatePassport,calculateRoleReadiness,firstShiftSkillEvidence} from '@/lib/career/evidence';
import {professionalRank} from '@/lib/platform';
import {destination,localizedPath,MIZAN_ZONES,type GameDestinationId,type MizanZoneId} from '@/lib/platform/navigation';
import {usePlayer} from '@/components/game/use-player';
import type {Locale} from '@/types';
import {PlatformNav} from './platform-nav';

type IconType=typeof Gamepad2;

export function GameHub({locale}:{locale:Locale}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,Arrow=ar?ArrowLeft:ArrowRight;
 const {state}=useGame(),player=usePlayer(),progress=firstDayProgress(state),company=firstDayCompany(state),performance=projectShiftPerformance(state),evidence=firstShiftSkillEvidence(state,'local-player'),passport=calculatePassport(evidence),readiness=calculateRoleReadiness('junior-accountant',passport),careerRank=professionalRank(passport),done=progress.completed.length;
 const handledValue=firstDayDocuments.filter(document=>progress.completed.includes(document.id)).reduce((total,document)=>total+document.amount,0);
 const railIds:GameDestinationId[]=['game-hub','inbox','missions','journal','ledger','trial-balance','financial-statements','nature-of-accounts','skill-passport','career'];
 const railIcons:Record<GameDestinationId,IconType>={'game-hub':Gamepad2,inbox:Inbox,missions:ClipboardCheck,journal:BookMarked,ledger:BookOpen,'trial-balance':BarChart3,'financial-statements':FileBarChart,'nature-of-accounts':FileText,'skill-passport':ShieldCheck,career:BriefcaseBusiness,leaderboard:Star,academy:BookOpen};
 const zoneIcons:Record<MizanZoneId,IconType>={suppliers:WalletCards,customers:Users,bank:Landmark,logistics:Truck,'month-end':ClipboardCheck};
 const skills=[[say('Investigation & Analysis','التحقيق والتحليل'),performance.investigation],[say('Accounting Judgment','الحكم المحاسبي'),performance.accountingJudgment],[say('Risk Awareness','الوعي بالمخاطر'),performance.riskAwareness],[say('Documentation','التوثيق'),performance.documentation]] as const;
 return <main className="platform-page command-game"><PlatformNav locale={locale}/><section className="command-shell">
  <aside className="command-rail" aria-label={say('Game navigation','تنقل اللعبة')}><div className="command-rail-company"><Building2/><span><b>Mizan Trading</b><small>{say('Accounting simulation','محاكاة محاسبية')}</small></span></div><nav>{railIds.map((id,index)=>{const item=destination(id),Icon=railIcons[id];return <Link className={index===0?'active':''} href={localizedPath(locale,item.path)} key={id}><Icon/><span>{item.label[locale]}</span>{id==='inbox'&&company.pendingDocuments>0?<em>{company.pendingDocuments}</em>:null}</Link>})}</nav><Link className="command-rail-settings" href={`/${locale}/profile`}><Settings/>{say('Settings','الإعدادات')}</Link><blockquote>“{say('Better accountants build brighter companies.','محاسبون أفضل يبنون شركات أقوى.')}”</blockquote></aside>
  <div className="command-main"><header className="command-heading"><div><span>{say('LIVE COMPANY SIMULATION','محاكاة شركة حية')}</span><h1>Mizan Trading</h1><p>{say('Real business. Real decisions. Explainable professional evidence.','عمل حقيقي. قرارات حقيقية. أدلة مهنية قابلة للتفسير.')}</p></div><label><Search/><input aria-label={say('Search the game','ابحث داخل اللعبة')} placeholder={say('Search cases, skills, accounts…','ابحث عن حالة أو مهارة أو حساب…')}/></label></header>
   <section className="company-world" aria-label={say('Interactive Mizan Trading map','خريطة Mizan Trading التفاعلية')}><div className="company-world-title"><Building2/><span><b>Mizan Trading</b><small>{say(`${done} of 3 First Shift cases resolved`,`${done} من 3 حالات في أول وردية مكتملة`)}</small></span></div>{MIZAN_ZONES.map(item=>{const Icon=item.status==='locked'?Lock:zoneIcons[item.id];return <Link className={`world-zone world-zone-${item.id} ${item.status}`} href={localizedPath(locale,item.path)} key={item.id}><i><Icon/></i><span><b>{item.title[locale]}</b><small>{item.subtitle[locale]}</small></span><ChevronRight/></Link>})}<div className="world-health"><BadgeCheck/><span><b>{company.ledgerErrors===0?say('Books healthy','الدفاتر سليمة'):say('Review required','تحتاج مراجعة')}</b><small>{company.pendingDocuments} {say('documents pending','مستندات معلقة')}</small></span></div></section>
   <section className="operations-deck"><article className="active-cases"><header><span><Inbox/>{say('Active work','العمل الحالي')}</span><Link href={`/${locale}/game/first-shift`}>{say('Open shift','افتح الوردية')}<Arrow/></Link></header>{firstDayDocuments.map((document,index)=>{const completed=progress.completed.includes(document.id);return <Link href={`/${locale}/game/first-shift`} className={`case-line ${completed?'complete':''}`} key={document.id}><i>{completed?<Check/>:index+1}</i><span><b>{document.title[locale]}</b><small>{document.party[locale]} · {document.amount.toLocaleString(locale)} EGP</small></span><em>{completed?say('Processed','تمت المعالجة'):say('Pending','معلّق')}</em><Arrow/></Link>})}</article>
    <article className="chapter-progress"><header><span><ClipboardCheck/>{say('Chapter 1 · First Shift','الفصل 1 · أول وردية')}</span><b>{Math.round(done/3*100)}%</b></header><div className="chapter-meter"><i style={{width:`${done/3*100}%`}}/></div><ul><li className={done>0?'done':''}><i>{done>0?<Check/>:null}</i>{say('Review source documents','مراجعة المستندات')}</li><li className={done===3?'done':''}><i>{done===3?<Check/>:null}</i>{say('Post three entries','ترحيل ثلاثة قيود')}</li><li className="locked"><i><Lock/></i>{say('Chapter 2 · Locked','الفصل 2 · مقفول')}</li></ul><Link className="platform-primary" href={`/${locale}/game/first-shift`}>{done?say('Continue First Shift','أكمل أول وردية'):say('Start First Shift','ابدأ أول وردية')}<Arrow/></Link></article>
    <article className="company-impact"><header><span><BarChart3/>{say('Your company impact','أثرك داخل الشركة')}</span></header><dl><div><dt>{say('Transactions processed','معاملات معالجة')}</dt><dd>{done}</dd></div><div><dt>{say('Accuracy','الدقة')}</dt><dd>{performance.accuracy}%</dd></div><div><dt>{say('Value handled','قيمة تمت معالجتها')}</dt><dd>{handledValue.toLocaleString(locale)} <small>EGP</small></dd></div><div><dt>{say('Ledger issues','مشكلات الدفتر')}</dt><dd>{company.ledgerErrors}</dd></div></dl></article></section>
  </div>
  <aside className="command-dossier"><section className="player-dossier"><CircleUserRound/><div><b>{player.displayName}</b><small>{careerRank}</small><span>{say('Game level','مستوى اللعبة')} {player.level}</span></div><Link href={`/${locale}/profile`}>{say('Profile','الملف')}</Link><i><b style={{width:`${Math.min(100,player.levelProgress)}%`}}/></i><small>{player.xp.toLocaleString(locale)} XP · {player.coins.toLocaleString(locale)} {say('Coins','عملة')}</small></section>
   <section className="passport-panel"><header><span><ShieldCheck/>{say('Skill Passport','جواز المهارات')}</span><Link href={`/${locale}/career-profile/skills`}>{say('View all','عرض الكل')}<Arrow/></Link></header>{skills.map(([label,value])=><div className="skill-line" key={label}><i><BadgeCheck/></i><span><b>{label}</b><em><small style={{width:`${value}%`}}/></em></span><strong>{value}%</strong></div>)}<div className="passport-stats"><span><ClipboardCheck/><b>{done}</b><small>{say('Cases','حالات')}</small></span><span><ShieldCheck/><b>{passport.filter(item=>item.status==='demonstrated').length}</b><small>{say('Demonstrated','مثبتة')}</small></span><span><Star/><b>{player.xp}</b><small>XP</small></span></div></section>
   <section className="readiness-panel"><header><BriefcaseBusiness/><b>{say('Hiring readiness','الجاهزية المهنية')}</b><span>{readiness.score===null?say('Building evidence','نبني الأدلة'):`${readiness.score}%`}</span></header><p>{say('Complete professional cases to build an evidence-based profile. Local gameplay never becomes Verified.','أكمل حالات مهنية لبناء ملف قائم على الأدلة. اللعب المحلي لا يصبح «موثقًا».')}</p><Link href={`/${locale}/career`}>{say('Open Career Hub','افتح المسار المهني')}<Arrow/></Link></section>
   <section className="employer-preview-panel"><span><FileBarChart/>{say('EMPLOYER PREVIEW · DEMO','معاينة الشركات · تجريبية')}</span><h2>{say('Performance becomes evidence.','الأداء يتحول إلى دليل.')}</h2><p>{say('See how completed cases can be presented without claiming verification.','شاهد كيف تُعرض الحالات المكتملة دون ادعاء التوثيق.')}</p><Link href={`/${locale}/employers`}>{say('View preview','اعرض المعاينة')}<Arrow/></Link></section>
  </aside>
 </section><button className="command-alert" aria-label={say('Notifications','الإشعارات')}><Bell/><span>{company.pendingDocuments}</span></button></main>;
}
