import Image from 'next/image';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,BadgeCheck,BookOpenCheck,Building2,LockKeyhole,ShieldCheck,Sparkles,Target,Trophy} from 'lucide-react';
import type {Locale} from '@/types';

type Props={locale:Locale};
const copy={
 ar:{
  kicker:'CAREER LEAGUE · محاكاة مهنية محلية',title:'تعلّم المحاسبة بالشغل، وابنِ مستقبلك خطوة بخطوة',description:'ابدأ من مستواك، نفّذ حالات محاسبية حقيقية داخل المحاكاة، وشاهد مهاراتك تتكوّن من قراراتك — لا من الحفظ.',start:'ابدأ مجانًا',explore:'شاهد الرحلة',disclaimer:'تجربة محاكاة تعليمية محلية. لا تمثل توظيفًا أو مستخدمين حقيقيين.',
  facts:[['53','وحدة تعليمية'],['5','مستويات شركات'],['9','درجات مسؤولية']],
  journeyKicker:'مسار واضح بدون زحمة',journey:'رحلتك المهنية في خمس مراحل',journeyDescription:'كل مرحلة لها هدف ومسؤولية واضحة. المتاح الآن ظاهر، والمراحل المستقبلية مكتوب عليها بوضوح أنها قيد التطوير.',
  stages:[['معسكر البداية','افهم طبيعة الحسابات والقيود الأساسية.','متاح'],['ميزان للتجارة','طبّق على مستندات ومواقف عمل.','ابدأ هنا'],['شركة منظمة','مطابقة وتسويات ورقابة أوضح.','بالتقدم'],['الإقفال الشهري','تسويات ومراجعة نهاية الفترة.','قيد التطوير'],['القيادة المالية','قرارات أوسع وتأثير أكبر.','هدف مهني']],
  featuresKicker:'ثلاث أدوات، وظيفة واحدة',features:'الممارسة تتحول إلى دليل مهني مفهوم',featuresDescription:'لا تحتاج لقراءة كلام صغير داخل صورة. كل ميزة هنا مكتوبة بوضوح، ويمكن فتحها مباشرة.',
  featureCards:[['منافسة محاسبية','قارن جودة قراراتك في تحديات محلية تجريبية، بدون ادعاء لاعبين أونلاين.','ابدأ المنافسة'],['سيرة ذاتية مبنية على الأدلة','إنجازات المحاكاة تظهر منفصلة عن خبرتك الحقيقية وبصياغة قابلة للشرح.','شاهد سيرتك'],['خريطة مهارات واضحة','اعرف ما مارسته، وما أثبته، وما يزال يحتاج حالات إضافية.','تصفح المهارات']],
  storiesKicker:'نماذج توضيحية وليست تقييمات',stories:'ابدأ من مكانك الحقيقي',storiesIntro:'ثلاث شخصيات افتراضية توضّح كيف يتغير المسار حسب خبرتك الحالية.',personas:[['طالبة محاسبة','من فهم القاعدة إلى استخدامها داخل حالة.'],['خريج جديد','من الدراسة النظرية إلى خطوات عمل واضحة.'],['محاسب يعمل','من الخبرة الحالية إلى مسؤولية أكبر.']],
  finalKicker:'خطوتك التالية واضحة',final:'مستقبلك المهني يبدأ بقرار واحد جيد',finalDescription:'ابدأ بمهمة قصيرة، وابنِ ملفًا يوضح ما تستطيع فعله فعلًا داخل المحاكاة.',finalStart:'ابدأ رحلتك',finalExplore:'اكتشف الشركات',trust:['بدون بطاقة ائتمان','عربي وإنجليزي','التقدم محفوظ محليًا']
 },
 en:{
  kicker:'CAREER LEAGUE · LOCAL CAREER SIMULATION',title:'Learn accounting through work and build your career step by step',description:'Start at your level, solve realistic accounting cases, and watch your skills grow from decisions—not memorisation.',start:'Start for free',explore:'See the journey',disclaimer:'A local learning simulation. It does not represent employment or live users.',
  facts:[['53','learning modules'],['5','company tiers'],['9','responsibility levels']],
  journeyKicker:'A clear path without clutter',journey:'Your career journey in five stages',journeyDescription:'Every stage has one clear goal and responsibility. Available work is visible now; future stages are labelled honestly.',
  stages:[['Accounting Bootcamp','Understand account nature and core entries.','Available'],['Mizan Trading','Apply skills to documents and work situations.','Start here'],['Structured Company','Matching, reconciliations and stronger controls.','Unlock'],['Month-End Close','Period-end review and adjustments.','In development'],['Finance Leadership','Broader judgment and business impact.','Career goal']],
  featuresKicker:'Three tools, one purpose',features:'Practice becomes understandable career evidence',featuresDescription:'No tiny text baked into an image. Every feature is readable and opens directly.',
  featureCards:[['Accounting competition','Compare decision quality in local demo challenges without claiming live online players.','Try competition'],['Evidence-based CV','Simulation achievements remain separate from real experience and easy to explain.','View your CV'],['Clear skill map','See what you practised, demonstrated, and still need to develop.','Browse skills']],
  storiesKicker:'Illustrative examples, not reviews',stories:'Start from where you really are',storiesIntro:'Three fictional personas show how the path adapts to current experience.',personas:[['Accounting student','Move from understanding a rule to using it in a case.'],['New graduate','Turn classroom theory into a clear workflow.'],['Working accountant','Move from current experience toward wider responsibility.']],
  finalKicker:'Your next step is clear',final:'Your professional future starts with one good decision',finalDescription:'Begin with a short mission and build a profile that shows what you can actually do in the simulation.',finalStart:'Start your journey',finalExplore:'Explore companies',trust:['No credit card','Arabic and English','Progress saved locally']
 }
} as const;

const stageRoutes=['/bootcamp','/game','/career-league/companies','/game/month-end','/career-league/promotion'];
const featureRoutes=['/leaderboard','/career-profile/cv','/career-profile/skills'];
const featureImages=['/landing/competition-world-v2.webp','/landing/career-future-v2.webp','/landing/skills-world-v2.webp'];
const href=(locale:Locale,route:string)=>`/${locale}${route}`;
function Arrow({ar}:{ar:boolean}){return ar?<ArrowLeft/>:<ArrowRight/>}

export function CareerLandingV4({locale}:Props){const t=copy[locale],ar=locale==='ar';return <div className="cl4" dir={ar?'rtl':'ltr'}>
 <section className="cl4-hero" id="home" aria-labelledby="cl4-title"><div className="cl4-hero-layout"><div className="cl4-hero-copy"><span className="cl4-kicker"><Sparkles/>{t.kicker}</span><h1 id="cl4-title">{t.title}</h1><p>{t.description}</p><div className="cl4-actions"><Link className="cl4-primary" href={href(locale,'/onboarding')}>{t.start}<Arrow ar={ar}/></Link><Link className="cl4-secondary" href="#journey">{t.explore}<Target/></Link></div><small><ShieldCheck/>{t.disclaimer}</small></div><div className="cl4-hero-visual"><Image src="/landing/career-league-hero-v2.png" alt={ar?'شاب وفتاة يتقدمان عبر شركات محاسبية داخل محاكاة تعليمية':'Two learners progressing through accounting companies in a career simulation'} fill priority sizes="(max-width: 760px) 100vw, 760px"/><div className="cl4-visual-label"><Trophy/><span><b>CAREER LEAGUE</b>{ar?'تعلّم · طبّق · اثبت':'Learn · Apply · Prove'}</span></div></div></div><div className="cl4-facts">{t.facts.map(([value,label],index)=>{const Icon=[BookOpenCheck,Building2,BadgeCheck][index];return <span key={label}><Icon/><b>{value}</b><small>{label}</small></span>})}</div></section>

 <section className="cl4-journey" id="journey" aria-labelledby="cl4-journey-title"><header><span>{t.journeyKicker}</span><h2 id="cl4-journey-title">{t.journey}</h2><p>{t.journeyDescription}</p></header><div className="cl4-journey-visual" id="companies"><Image src="/landing/career-journey-world-v2.webp" alt="" fill sizes="(max-width: 1450px) 100vw, 1400px"/></div><div className="cl4-stage-grid">{t.stages.map(([title,description,status],index)=><Link href={href(locale,stageRoutes[index])} className={index===3?'future':index===4?'goal':''} key={title}><i>{index===3?<LockKeyhole/>:index===4?<Trophy/>:<span>{index+1}</span>}</i><small>{status}</small><h3>{title}</h3><p>{description}</p><Arrow ar={ar}/></Link>)}</div></section>

 <section className="cl4-features" id="competition" aria-labelledby="cl4-features-title"><header><span>{t.featuresKicker}</span><h2 id="cl4-features-title">{t.features}</h2><p>{t.featuresDescription}</p></header><div className="cl4-feature-grid">{t.featureCards.map(([title,description,cta],index)=><article key={title} id={index===2?'tools':undefined}><div className="cl4-feature-image"><Image src={featureImages[index]} alt="" fill sizes="(max-width: 760px) 92vw, 420px"/></div><div><span>0{index+1}</span><h3>{title}</h3><p>{description}</p><Link href={href(locale,featureRoutes[index])}>{cta}<Arrow ar={ar}/></Link></div></article>)}</div></section>

 <section className="cl4-stories" aria-labelledby="cl4-stories-title"><header><span>{t.storiesKicker}</span><h2 id="cl4-stories-title">{t.stories}</h2><p>{t.storiesIntro}</p></header><div className="cl4-personas">{t.personas.map(([role,description],index)=><article key={role}><div className={`cl4-persona-photo person-${index+1}`}><Image src="/landing/player-journeys-v2.png" alt="" fill sizes="96px"/></div><div><h3>{role}</h3><p>{description}</p></div></article>)}</div></section>

 <section className="cl4-final" id="about" aria-labelledby="cl4-final-title"><div className="cl4-final-layout"><div className="cl4-final-image"><Image src="/landing/career-future-v2.webp" alt="" fill sizes="(max-width: 760px) 100vw, 720px"/></div><div className="cl4-final-copy"><span>{t.finalKicker}</span><h2 id="cl4-final-title">{t.final}</h2><p>{t.finalDescription}</p><div className="cl4-final-actions"><Link href={href(locale,'/onboarding')}>{t.finalStart}<Arrow ar={ar}/></Link><Link href={href(locale,'/career-league/companies')}>{t.finalExplore}<Building2/></Link></div><div className="cl4-trust">{t.trust.map(item=><span key={item}><ShieldCheck/>{item}</span>)}</div></div></div></section>
 </div>}
