import Image from 'next/image';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,BadgeCheck,BarChart3,BookOpenCheck,BriefcaseBusiness,Building2,Check,FileCheck2,FileSearch,Gamepad2,GraduationCap,Route,ShieldCheck,Sparkles,Target,Trophy,UserRound} from 'lucide-react';
import type {Locale} from '@/types';
import {PlatformNav} from './platform-nav';

export function MarketingLanding({locale}:{locale:Locale}) {
  const ar=locale==='ar',Arrow=ar?ArrowLeft:ArrowRight,say=(en:string,a:string)=>ar?a:en;
  const paths=[
    {id:'student',icon:GraduationCap,eyebrow:say('ACCOUNTING STUDENT','طالب محاسبة'),title:say('Understand accounting before your first job.','افهم المحاسبة قبل أول وظيفة.'),copy:say('Build the foundations through transactions, documents, and your first company shift.','ابنِ الأساس من خلال معاملات ومستندات وأول وردية لك داخل الشركة.'),steps:say('Foundations → First Shift → Job Readiness','الأساسيات ← أول وردية ← الجاهزية للعمل')},
    {id:'graduate',icon:UserRound,eyebrow:say('FRESH GRADUATE','خريج محاسبة'),title:say('Turn what you studied into real accounting work.','حوّل ما درسته إلى شغل محاسبي حقيقي.'),copy:say('Practice documents, AP, AR, bank work, reconciliations, and professional decisions.','تدرّب على المستندات والموردين والعملاء والبنك والتسويات والقرارات المهنية.'),steps:say('Placement → Company Work → Career Evidence','تحديد المستوى ← شغل الشركة ← أدلة مهنية')},
    {id:'working-accountant',icon:BriefcaseBusiness,eyebrow:say('WORKING ACCOUNTANT','محاسب يعمل بالفعل'),title:say('Prepare for the company you want to move to.','استعد للشركة التي تريد الانتقال إليها.'),copy:say('Find your gaps, cross into structured accounting, and prove readiness for the next role.','اكتشف فجواتك وانتقل للمحاسبة المنظمة وأثبت جاهزيتك للدور التالي.'),steps:say('Career Gap → Corporate Bridge → Promotion','فجوة المسار ← Corporate Bridge ← ترقية')},
  ] as const;
  return <main className="platform-page marketing-page career-landing"><PlatformNav locale={locale} marketing/>
    <section className="career-hero"><div className="career-hero-copy"><span className="career-edition"><Sparkles/> DEBIT & CREDIT · CAREER LEAGUE</span><h1>{say('Your accounting career starts before the job offer.','مسارك المحاسبي يبدأ قبل عرض العمل.')}</h1><p>{say('Work inside simulated companies. Investigate real documents. Make accounting decisions. Turn every strong performance into professional evidence.','اشتغل داخل شركات محاكاة. افحص مستندات حقيقية. خُذ قرارات محاسبية. وحوّل كل أداء قوي إلى دليل مهني.')}</p><div className="career-hero-actions"><Link className="career-main-cta" href={`/${locale}/onboarding`}>{say('Start building my career','ابدأ بناء مساري')}<Arrow/></Link><a href="#experience"><Gamepad2/>{say('See the game','شاهد تجربة اللعب')}</a></div><div className="career-proof-row"><span><Check/>{say('Real accounting workflows','دورات عمل محاسبية')}</span><span><Check/>{say('Evidence-based progress','تقدم مبني على الأدلة')}</span><span><Check/>{say('Arabic & English','عربي وإنجليزي')}</span></div></div>
      <div className="career-hero-visual"><div className="hero-screen-frame"><div className="screen-top"><i/><i/><i/><span>MIZAN TRADING · LIVE SIMULATION</span></div><Image src="/marketing/career-league-game-hub.png" alt={say('Career League game hub inside Mizan Trading','مركز لعب Career League داخل شركة ميزان')} width={1440} height={900} priority/></div><div className="floating-career-card rank-card"><Trophy/><span><small>{say('CURRENT LEAGUE','الدوري الحالي')}</small><b>{say('Junior Accountant','محاسب مبتدئ')}</b></span><strong>#27</strong></div><div className="floating-career-card evidence-card"><BadgeCheck/><span><small>{say('CAREER EVIDENCE','دليل مهني')}</small><b>{say('Skill Passport updated','تم تحديث سجل المهارات')}</b></span></div></div></section>
    <section className="career-value-bar"><div><Building2/><strong>5</strong><span>{say('Company tiers','مستويات شركات')}</span></div><div><Target/><strong>9</strong><span>{say('Career goals','أهداف وظيفية')}</span></div><div><ShieldCheck/><strong>1</strong><span>{say('Evidence system','نظام أدلة موحد')}</span></div><p>{say('Simulation work is always clearly labeled. No fake employers. No fake verification.','شغل المحاكاة موضح دائمًا. لا شركات وهمية ولا توثيق مهني مزيف.')}</p></section>
    <section id="paths" className="career-paths"><header className="career-section-head"><span>{say('START FROM YOUR REAL LEVEL','ابدأ من مستواك الحقيقي')}</span><h2>{say('One career game. Your path.','لعبة مسار واحدة. بطريقتك أنت.')}</h2><p>{say('The game adapts the next mission to where you are now and where you want to go.','اللعبة تختار مهمتك التالية بناءً على مستواك الآن والمكان الذي تريد الوصول إليه.')}</p></header><div className="career-path-grid">{paths.map(({id,icon:Icon,eyebrow,title,copy,steps},index)=><article key={id}><div className="path-number">0{index+1}</div><Icon/><small>{eyebrow}</small><h3>{title}</h3><p>{copy}</p><em>{steps}</em><Link href={`/${locale}/onboarding?persona=${id}`}>{say('Build my path','ابنِ مساري')}<Arrow/></Link></article>)}</div></section>
    <section id="experience" className="work-showcase"><div className="showcase-copy"><span>{say('THIS IS THE GAME','هذه هي اللعبة')}</span><h2>{say('Your desk. Your documents. Your decision.','مكتبك. مستنداتك. قرارك.')}</h2><p>{say('A supplier invoice arrives with a problem. You inspect the source, ask for what is missing, build the entry, and live with the consequence. Knowledge appears when the work needs it.','تصلك فاتورة مورد بها مشكلة. تراجع المصدر، تطلب الناقص، تبني القيد، وترى نتيجة قرارك. المعرفة تظهر عندما يحتاجها الشغل.')}</p><ul><li><FileSearch/>{say('Inspect source documents','افحص المستندات')}</li><li><BookOpenCheck/>{say('Use accounting judgment','استخدم الحكم المحاسبي')}</li><li><BarChart3/>{say('See the business consequence','شاهد أثر القرار على الشركة')}</li></ul><Link href={`/${locale}/game/first-shift`}>{say('Enter First Shift','ادخل أول وردية')}<Arrow/></Link></div><figure className="work-screen"><Image src="/marketing/first-shift-work.png" alt={say('First Shift accounting desk gameplay','تجربة مكتب أول وردية محاسبية')} width={1680} height={945} loading="eager"/><figcaption><span>01</span>{say('Mizan Trading · First Shift','شركة ميزان · أول وردية')}</figcaption></figure></section>
    <section className="evidence-story"><header className="career-section-head"><span>{say('FROM GAMEPLAY TO OPPORTUNITY','من اللعب إلى الفرصة')}</span><h2>{say('Your work writes the story of your CV.','شغلك هو الذي يكتب قصة الـCV.')}</h2><p>{say('No manual skill claims. Qualifying case evidence updates your Skill Passport, Career Profile, role readiness, and Auto CV.','لا تضيف مهارات بلا دليل. أدلة الحالات المؤهلة تحدّث سجل المهارات والملف المهني والجاهزية والـCV تلقائيًا.')}</p></header><div className="evidence-flow"><span><Gamepad2/>GAMEPLAY</span><Arrow/><span><ShieldCheck/>EVIDENCE</span><Arrow/><span><FileCheck2/>SKILL PASSPORT</span><Arrow/><span><BriefcaseBusiness/>AUTO CV</span></div><div className="cv-showcase"><div className="cv-window"><Image src="/marketing/auto-cv.png" alt={say('Evidence-based Auto CV','سيرة ذاتية مبنية على أدلة اللعب')} width={1440} height={1439} loading="eager"/></div><aside><span>{say('AUTO CV · EVIDENCE-BASED','AUTO CV · مبني على الأدلة')}</span><h3>{say('A professional record that grows with every case.','ملف مهني يتطور مع كل حالة.')}</h3><div><ShieldCheck/><p><b>{say('Honest by design','مصمم ليكون صادقًا')}</b>{say('Mizan Trading is shown as Accounting Career Simulation, never as real employment.','تظهر Mizan Trading كخبرة محاكاة محاسبية ولا تُعرض كوظيفة حقيقية.')}</p></div><div><Route/><p><b>{say('Built for your target role','مبني للدور المستهدف')}</b>{say('Choose General Accountant, AP, AR, Treasury, GL, or Cost—and see exactly what is missing.','اختر المحاسب العام أو الموردين أو العملاء أو الخزينة أو الأستاذ العام أو التكاليف واعرف ما ينقصك.')}</p></div><Link href={`/${locale}/career-profile/cv`}>{say('Preview Auto CV','شاهد الـAuto CV')}<Arrow/></Link></aside></div></section>
    <section className="career-loop-banner"><div><span>{say('THE CAREER LOOP','دورة المسار')}</span><h2>{say('Choose the role. Close the gap. Earn the promotion.','اختر الدور. عالج الفجوة. استحق الترقية.')}</h2></div><ol><li><b>01</b>{say('Target job','الوظيفة المستهدفة')}</li><li><b>02</b>{say('Missing skills','المهارات الناقصة')}</li><li><b>03</b>{say('Career missions','مهمات المسار')}</li><li><b>04</b>{say('Promotion assessment','تقييم الترقية')}</li><li><b>05</b>{say('Next company','الشركة التالية')}</li></ol><Link href={`/${locale}/career-league/jobs`}>{say('Explore the Job Market','استكشف سوق الوظائف')}<Arrow/></Link></section>
    <section className="career-final-cta"><div><span><Sparkles/> DEBIT & CREDIT · CAREER LEAGUE</span><h2>{say('The next company will ask what you can do.','الشركة التالية ستسألك: ماذا تستطيع أن تفعل؟')}</h2><p>{say('Start small. Do the work. Build the evidence. Move up.','ابدأ من مستواك. نفّذ الشغل. ابنِ الدليل. واترقّى.')}</p><Link href={`/${locale}/onboarding`}>{say('Start my career journey','ابدأ رحلتي المهنية')}<Arrow/></Link><small>{say('Free local preview · No credit card','معاينة محلية مجانية · دون بطاقة دفع')}</small></div></section>
  </main>;
}
