'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,BookOpen,BriefcaseBusiness,Building2,Check,GraduationCap,Target,UserRound} from 'lucide-react';
import {BrowserPlatformRepository} from '@/lib/platform/repository';
import {BrowserCareerLeagueRepository} from '@/lib/career-league/repository';
import {roleForCareerGoal} from '@/lib/career-league/engine';
import type {CareerGoal,PlacementPath,PlayerPersona,WorkEnvironment} from '@/lib/career-league/model';
import {BrowserCareerProfileRepository,BrowserCvPreferencesRepository,createDefaultProfile} from '@/lib/career/repository';
import type {Locale} from '@/types';
import {PlatformNav} from './platform-nav';

const careerRepository=new BrowserCareerLeagueRepository(),platformRepository=new BrowserPlatformRepository();
export function PlatformOnboarding({locale}:{locale:Locale}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,Arrow=ar?ArrowLeft:ArrowRight,[state,setState]=useState(()=>careerRepository.get());
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('persona');if(requested==='student'||requested==='graduate'||requested==='working-accountant')setState(current=>({...current,persona:requested,workEnvironment:requested==='working-accountant'?current.workEnvironment:null}))},[]);
 const personas:[PlayerPersona,typeof GraduationCap,string,string,string,string][]=[
  ['student',GraduationCap,'Accounting Student','طالب محاسبة','Understand accounting and prepare before graduation.','افهم المحاسبة واستعد للعمل قبل التخرج.'],
  ['graduate',UserRound,'Fresh Graduate','خريج محاسبة','Turn academic knowledge into practical company work.','حوّل الدراسة إلى شغل عملي داخل الشركات.'],
  ['working-accountant',BriefcaseBusiness,'Working Accountant','محاسب يعمل حاليًا','Prove you are ready for a bigger, structured company.','اثبت أنك جاهز لشركة أكبر وأكثر تنظيمًا.'],
 ];
 const environments:[WorkEnvironment,string,string][]=[['small-business','Small Business','شركة صغيرة'],['accounting-office','Accounting Office','مكتب محاسبة'],['retail','Retail','تجزئة'],['restaurant','Restaurant','مطعم'],['trading-company','Trading Company','شركة تجارية'],['other','Other','أخرى']];
 const goals:[CareerGoal,string,string][]=[['first-job','Get first accounting job','الحصول على أول وظيفة'],['bigger-company','Move to a bigger company','الانتقال لشركة أكبر'],['general-accountant','Become General Accountant','أصبح محاسبًا عامًا'],['ap','Move into AP','الانتقال للموردين AP'],['ar','Move into AR','الانتقال للعملاء AR'],['treasury','Move into Treasury','الانتقال للخزينة'],['gl','Move into GL','الانتقال للأستاذ العام'],['cost','Move into Cost Accounting','الانتقال للتكاليف'],['corporate-accounting','Prepare for corporate accounting','الاستعداد لمحاسبة الشركات']];
 const paths:[PlacementPath,typeof BookOpen,string,string,string,string][]=[['start-basics',BookOpen,'Start from the beginning','ابدأ من البداية','Follow the foundation path before company work.','ابدأ بالأساسيات قبل شغل الشركة.'],['take-challenge',Target,'Prove what I know','أثبت ما أعرفه','Take a short work-based placement challenge.','نفّذ تحديًا قصيرًا مبنيًا على شغل حقيقي.']];
 const ready=Boolean(state.persona&&state.goal&&state.placementPath&&(state.persona!=='working-accountant'||state.workEnvironment));
 const save=()=>{if(!ready)return;const next=careerRepository.save({...state,onboardingComplete:true});const legacy=platformRepository.get();platformRepository.save({...legacy,experience:next.persona==='student'?'student':next.persona==='graduate'?'junior':'experienced',goal:'career',onboardingComplete:true});const role=roleForCareerGoal(next.goal),profileRepo=new BrowserCareerProfileRepository(),profile=profileRepo.get()??createDefaultProfile('',role);profileRepo.save({...profile,targetRoleId:role,experienceLevel:next.persona==='student'?'student':next.persona==='graduate'?'fresh-graduate':profile.experienceLevel});new BrowserCvPreferencesRepository().save({version:1,targetRoleId:role,accent:'navy',includeScores:false,updatedAt:new Date().toISOString()})};
 return <main className="platform-page onboarding-page career-onboarding"><PlatformNav locale={locale}/><section className="onboarding-card"><header><span>CAREER LEAGUE · START SMALL. PROVE YOUR SKILLS. MOVE UP.</span><h1>{say('Where are you in your accounting career?','أين أنت الآن في مسارك المحاسبي؟')}</h1><p>{say('Choose your real starting point. This personalizes the journey and never awards professional evidence by self-report.','اختر نقطة بدايتك الحقيقية. هذا يخصص الرحلة ولا يمنح أي دليل مهني من إجابتك.')}</p></header><fieldset><legend>1 · {say('Your current position','وضعك الحالي')}</legend><div>{personas.map(([id,Icon,en,a,descEn,descAr])=><button className={state.persona===id?'selected':''} onClick={()=>setState(s=>({...s,persona:id,workEnvironment:id==='working-accountant'?s.workEnvironment:null}))} key={id}><Icon/><b>{ar?a:en}</b><small>{ar?descAr:descEn}</small></button>)}</div></fieldset>{state.persona==='working-accountant'?<fieldset><legend>2 · {say('Current work environment','بيئة العمل الحالية')}</legend><div className="compact-options">{environments.map(([id,en,a])=><button className={state.workEnvironment===id?'selected':''} onClick={()=>setState(s=>({...s,workEnvironment:id}))} key={id}><Building2/><b>{ar?a:en}</b></button>)}</div></fieldset>:null}<fieldset><legend>{state.persona==='working-accountant'?'3':'2'} · {say('Career goal','هدفك المهني')}</legend><div className="compact-options career-goals">{goals.map(([id,en,a])=><button className={state.goal===id?'selected':''} onClick={()=>setState(s=>({...s,goal:id}))} key={id}><Check/><b>{ar?a:en}</b></button>)}</div></fieldset><fieldset><legend>{state.persona==='working-accountant'?'4':'3'} · {say('Choose your starting path','اختر نقطة البداية')}</legend><div>{paths.map(([id,Icon,en,a,descEn,descAr])=><button className={state.placementPath===id?'selected':''} onClick={()=>setState(s=>({...s,placementPath:id}))} key={id}><Icon/><b>{ar?a:en}</b><small>{ar?descAr:descEn}</small></button>)}</div></fieldset><Link aria-disabled={!ready} onClick={event=>{if(!ready)event.preventDefault();else save()}} className="platform-primary" href={`/${locale}${state.placementPath==='take-challenge'?'/career-league/placement':'/bootcamp'}`}>{state.placementPath==='take-challenge'?say('Take Placement Challenge','ابدأ تحدي تحديد المستوى'):say('Enter Accounting Bootcamp','ادخل معسكر البداية المحاسبي')}<Arrow/></Link><small className="onboarding-integrity">{say('Placement and self-report never create Verified evidence.','تحديد المستوى والإجابات الشخصية لا تنشئ دليلًا موثقًا.')}</small></section></main>;
}
