import type {CareerFeature,CareerOpportunity,CareerSeason,LeagueTrack,PlacementTask,PromotionAssessment,TrainingStep,VirtualCompany} from './model';
import type {SkillId} from '@/lib/career/model';

const t=(en:string,ar:string)=>({en,ar});
export const companyTiers:VirtualCompany[]=[
 {id:'mizan-trading',tier:1,name:t('Mizan Trading','ميزان للتجارة'),environment:t('Small Local Business','شركة محلية صغيرة'),simulationLabel:t('Career simulation','محاكاة مهنية'),characteristics:[t('Simple documents and cash work','مستندات بسيطة وحركة نقدية'),t('Basic supplier and customer journals','قيود موردين وعملاء أساسية')],unlock:{requiredMissionIds:[],requirements:[],promotionAssessmentId:null}},
 {id:'delta-commerce',tier:2,name:t('Delta Commerce','دلتا للتجارة'),environment:t('Structured Medium Company','شركة متوسطة منظمة'),simulationLabel:t('Fictional career simulation','محاكاة مهنية خيالية'),characteristics:[t('Formal AP and AR workflows','دورات موردين وعملاء منظمة'),t('Document matching and bank controls','مطابقة مستندات ورقابة بنكية')],unlock:{requiredMissionIds:['first-shift'],requirements:[{skillId:'document-analysis',minimum:'practiced'},{skillId:'journal-entries',minimum:'practiced'}],promotionAssessmentId:'promotion-1'}},
 {id:'horizon-industries',tier:3,name:t('Horizon Industries','هورايزن للصناعات'),environment:t('Corporate Company','شركة مؤسسية'),simulationLabel:t('Fictional corporate simulation','محاكاة مؤسسية خيالية'),characteristics:[t('Month-end close and reconciliations','إقفال شهري وتسويات'),t('Controls, reviews and reporting deadlines','رقابة ومراجعة ومواعيد تقارير')],unlock:{requiredMissionIds:['first-shift','bank-control'],requirements:[{skillId:'accounts-payable',minimum:'demonstrated'},{skillId:'accounts-receivable',minimum:'practiced'},{skillId:'bank-reconciliation',minimum:'practiced'}],promotionAssessmentId:'promotion-2'}},
 {id:'orbit-regional-group',tier:4,name:t('Orbit Regional Group','مجموعة أوربت الإقليمية'),environment:t('Regional Group','مجموعة إقليمية'),simulationLabel:t('Fictional regional simulation','محاكاة إقليمية خيالية'),characteristics:[t('English documentation and close calendar','مستندات إنجليزية وتقويم إقفال'),t('Audit requests and intercompany concepts','طلبات مراجعة ومفاهيم بين الشركات')],unlock:{requiredMissionIds:['corporate-close'],requirements:[{skillId:'month-end-closing',minimum:'demonstrated'},{skillId:'financial-statements',minimum:'practiced'}],promotionAssessmentId:'promotion-3'}},
 {id:'atlas-global-simulation',tier:5,name:t('Atlas Global Simulation','محاكاة أطلس العالمية'),environment:t('Multinational-Style Simulation','محاكاة بأسلوب الشركات متعددة الجنسيات'),simulationLabel:t('Simulation only — not employment','محاكاة فقط — ليست خبرة عمل'),characteristics:[t('Specialized roles and ERP-style workflows','أدوار متخصصة ودورات شبيهة بـERP'),t('High-control close and reporting work','إقفال وتقارير برقابة عالية')],unlock:{requiredMissionIds:['regional-close'],requirements:[{skillId:'month-end-closing',minimum:'demonstrated'},{skillId:'financial-statements',minimum:'demonstrated'},{skillId:'error-detection',minimum:'demonstrated'}],promotionAssessmentId:'promotion-4'}},
];

export const careerOpportunities:CareerOpportunity[]=[
 {id:'mizan-junior',companyId:'mizan-trading',roleId:'junior-accountant',title:t('Junior Accountant','محاسب مبتدئ'),companyName:t('Mizan Trading','ميزان للتجارة'),summary:t('Build reliable journal and document handling inside a structured trading company.','ابنِ قدرة موثوقة في القيود والمستندات داخل شركة تجارة منظمة.'),requirements:[{skillId:'document-analysis',minimum:'practiced'},{skillId:'account-classification',minimum:'practiced'},{skillId:'journal-entries',minimum:'practiced'}],trainingMissionIds:['first-shift','nature-review','journal-practice'],access:'free',fictional:true},
 {id:'horizon-general',companyId:'horizon-industries',roleId:'general-accountant',title:t('General Accountant','محاسب عام'),companyName:t('Horizon Industries','هورايزن للصناعات'),summary:t('Prepare for reconciliations, adjustments, close, and controlled reporting.','استعد للتسويات وقيود الإقفال والتقارير المنضبطة.'),requirements:[{skillId:'journal-entries',minimum:'demonstrated'},{skillId:'accounts-payable',minimum:'demonstrated'},{skillId:'accounts-receivable',minimum:'practiced'},{skillId:'bank-reconciliation',minimum:'practiced'},{skillId:'month-end-closing',minimum:'practiced'}],trainingMissionIds:['journal-practice','supplier-work','customer-work','bank-reconciliation','month-end'],access:'pro',fictional:true},
 {id:'horizon-treasury',companyId:'horizon-industries',roleId:'treasury-accountant',title:t('Treasury Accountant','محاسب خزينة'),companyName:t('Horizon Industries','هورايزن للصناعات'),summary:t('Build cash control, receipt investigation, and bank reconciliation evidence.','ابنِ أدلة في الرقابة النقدية والتحصيل وتسوية البنك.'),requirements:[{skillId:'cash-treasury',minimum:'demonstrated'},{skillId:'document-analysis',minimum:'demonstrated'},{skillId:'bank-reconciliation',minimum:'practiced'}],trainingMissionIds:['cash-control','first-shift','bank-reconciliation'],access:'pro',fictional:true},
 {id:'orbit-gl',companyId:'orbit-regional-group',roleId:'gl-accountant',title:t('GL Accountant','محاسب أستاذ عام'),companyName:t('Orbit Regional Group','مجموعة أوربت الإقليمية'),summary:t('Train for controlled close, ledger review, adjustments, and reporting.','تدرّب على الإقفال المنضبط ومراجعة الأستاذ والتسويات والتقارير.'),requirements:[{skillId:'ledger-posting',minimum:'demonstrated'},{skillId:'trial-balance',minimum:'demonstrated'},{skillId:'adjusting-entries',minimum:'demonstrated'},{skillId:'month-end-closing',minimum:'demonstrated'}],trainingMissionIds:['ledger-rescue','trial-balance-review','adjustments','month-end'],access:'pro',fictional:true},
];

export const missionRoutes:Record<string,{skillId:SkillId;route:string|null;locked:boolean;reason:{ar:string;en:string}}>={
 'first-shift':{skillId:'document-analysis',route:'/game/first-shift',locked:false,reason:t('Real source-document work builds reliable posting habits.','شغل المستندات الحقيقي يبني عادات ترحيل موثوقة.')},
 'nature-review':{skillId:'account-classification',route:'/account-guide',locked:false,reason:t('Account behavior supports reliable classification decisions.','فهم سلوك الحساب يدعم قرارات التصنيف الصحيحة.')},
 'journal-practice':{skillId:'journal-entries',route:'/practice',locked:false,reason:t('Supported journal work is essential for every accounting role.','القيود المؤيدة أساسية لكل دور محاسبي.')},
 'supplier-work':{skillId:'accounts-payable',route:'/game/suppliers',locked:false,reason:t('Supplier document control builds AP readiness.','رقابة مستندات الموردين تبني جاهزية AP.')},
 'customer-work':{skillId:'accounts-receivable',route:'/game/customers',locked:false,reason:t('Receipt investigation builds AR readiness.','التحقق من التحصيل يبني جاهزية AR.')},
 'cash-control':{skillId:'cash-treasury',route:'/game/bank',locked:false,reason:t('Cash and receipt control supports treasury work.','رقابة النقدية والتحصيل تدعم شغل الخزينة.')},
 'bank-reconciliation':{skillId:'bank-reconciliation',route:'/game/bank',locked:true,reason:t('Bank reconciliation is required for cash and corporate roles.','تسوية البنك مطلوبة لأدوار الخزينة والشركات.')},
 'adjustments':{skillId:'adjusting-entries',route:'/game/month-end',locked:true,reason:t('Adjustments support accurate period-end reporting.','قيود التسوية تدعم تقارير نهاية الفترة.')},
 'month-end':{skillId:'month-end-closing',route:'/game/month-end',locked:true,reason:t('Close discipline is central to corporate accounting.','انضباط الإقفال أساسي في محاسبة الشركات.')},
 'ledger-rescue':{skillId:'ledger-posting',route:'/ledger',locked:false,reason:t('Ledger review connects accepted entries to account balances.','مراجعة الأستاذ تربط القيود المقبولة بأرصدة الحسابات.')},
 'trial-balance-review':{skillId:'trial-balance',route:'/trial-balance',locked:false,reason:t('Trial balance review checks the integrity of posted balances.','مراجعة ميزان المراجعة تتحقق من سلامة الأرصدة المرحلة.')},
};

export const promotionAssessments:PromotionAssessment[]=[
 {id:'promotion-1',fromTier:1,toTier:2,title:t('Junior Accountant Promotion Review','مراجعة ترقية المحاسب المبتدئ'),roleId:'junior-accountant',requiredMissionIds:['first-shift'],requirements:[{skillId:'document-analysis',minimum:'practiced'},{skillId:'journal-entries',minimum:'practiced'}],tasks:[t('Review a supplier invoice file','راجع ملف فاتورة مورد'),t('Investigate a customer receipt','تحقق من سند قبض عميل'),t('Protect the ledger from unsupported posting','احمِ الدفتر من ترحيل غير مؤيد')],dimensions:['accuracy','investigation','accountingJudgment','riskAwareness','independence','documentation'],access:'free'},
 {id:'promotion-2',fromTier:2,toTier:3,title:t('General Accounting Promotion Assessment','تقييم الترقية للمحاسبة العامة'),roleId:'general-accountant',requiredMissionIds:['first-shift','bank-control'],requirements:[{skillId:'accounts-payable',minimum:'demonstrated'},{skillId:'accounts-receivable',minimum:'practiced'},{skillId:'bank-reconciliation',minimum:'practiced'}],tasks:[t('Resolve a document mismatch','حل اختلاف مستندي'),t('Make a bank control decision','اتخذ قرار رقابة بنكية'),t('Prepare a supported correction','أعد تصحيحًا مؤيدًا')],dimensions:['accuracy','investigation','accountingJudgment','riskAwareness','independence','documentation'],access:'pro'},
];

export const placementTasks:PlacementTask[]=[
 {id:'classification',area:t('Account classification','تصنيف الحساب'),scenario:t('A company buys office equipment on credit. Which pair belongs in the entry?','اشترت الشركة معدات مكتبية آجلًا. ما زوج الحسابات الصحيح؟'),options:[t('Equipment and Accounts Payable','المعدات والموردون'),t('Cash and Revenue','النقدية والإيراد'),t('Expense and Bank','المصروف والبنك')],correctIndex:0},
 {id:'effect',area:t('Transaction effect','أثر العملية'),scenario:t('A customer pays an outstanding invoice into the bank. What changes?','سدد عميل فاتورة مستحقة في البنك. ما الذي يتغير؟'),options:[t('Bank increases; receivables decrease','يزيد البنك وتنخفض العملاء'),t('Revenue and cash both decrease','ينخفض الإيراد والنقدية'),t('Payables increase','تزيد الموردون')],correctIndex:0},
 {id:'journal',area:t('Journal entry','القيد اليومي'),scenario:t('Before posting, the supplier invoice has no receiving evidence. What should you do?','قبل الترحيل لا يوجد إثبات استلام مع فاتورة المورد. ماذا تفعل؟'),options:[t('Hold and request evidence','أوقف واطلب المستند'),t('Post immediately','رحّل فورًا'),t('Delete the invoice','احذف الفاتورة')],correctIndex:0},
 {id:'documents',area:t('Document review','مراجعة المستندات'),scenario:t('Which evidence best supports goods received from a supplier?','ما المستند الأفضل لإثبات استلام بضاعة من مورد؟'),options:[t('Goods receipt note','إذن استلام'),t('Customer receipt','سند قبض عميل'),t('Payroll sheet','كشف الرواتب')],correctIndex:0},
 {id:'ledger',area:t('Basic ledger','الأستاذ الأساسي'),scenario:t('Where should an accepted journal entry appear next?','أين يجب أن يظهر القيد المقبول بعد ذلك؟'),options:[t('Relevant ledger accounts','حسابات الأستاذ المعنية'),t('Nature guide only','دليل طبيعة الحسابات فقط'),t('Unposted inbox','الوارد غير المرحّل')],correctIndex:0},
 {id:'reconciliation',area:t('Reconciliation decision','قرار تسوية'),scenario:t('The bank statement and ledger disagree. What is the professional first step?','كشف البنك لا يطابق الأستاذ. ما أول خطوة مهنية؟'),options:[t('Investigate the difference','تحقق من الفرق'),t('Force the ledger balance','غيّر رصيد الأستاذ مباشرة'),t('Ignore it until next month','تجاهله للشهر القادم')],correctIndex:0},
];

export const premiumAccess:Record<CareerFeature,'free'|'pro'>={foundation:'free','first-shift':'free','daily-challenge':'free','basic-profile':'free','career-league':'pro','corporate-bridge':'pro','company-tiers':'pro','promotion-assessments':'pro','advanced-cases':'pro',seasons:'pro','career-gap':'pro','full-passport':'pro','role-cv':'pro'};
export const careerSeasons:CareerSeason[]=[{id:'supplier-crisis-season',title:t('Supplier Crisis','أزمة المورد'),status:'active-demo',eventIds:['first-shift/supplier-invoice'],localOnly:true},{id:'closing-season',title:t('Closing Season','موسم الإقفال'),status:'planned',eventIds:[],localOnly:true}];
export const leagueTracks:LeagueTrack[]=[{id:'junior',title:t('Junior Accountant League','دوري المحاسب المبتدئ'),requiredSkills:['document-analysis','journal-entries'],demo:true},{id:'ap',title:t('AP League','دوري الموردين'),requiredSkills:['accounts-payable','supplier-documents'],demo:true},{id:'ar',title:t('AR League','دوري العملاء'),requiredSkills:['accounts-receivable','cash-treasury'],demo:true},{id:'treasury',title:t('Treasury League','دوري الخزينة'),requiredSkills:['cash-treasury','bank-reconciliation'],demo:true},{id:'gl',title:t('GL League','دوري الأستاذ العام'),requiredSkills:['ledger-posting','trial-balance'],demo:true},{id:'closing',title:t('Closing League','دوري الإقفال'),requiredSkills:['adjusting-entries','month-end-closing'],demo:true}];

export function trainingSteps(missionIds:string[]):TrainingStep[]{return missionIds.map(id=>({missionId:id,...missionRoutes[id]}))}
