import type {PerformanceDimensions} from '@/lib/cases/model';
import type {SkillId,SkillResult,SkillStatus} from '@/lib/career/model';
import {careerOpportunities,companyTiers,premiumAccess,promotionAssessments,trainingSteps} from './catalog';
import type {CareerFeature,CareerGap,CareerGoal,CareerLeagueState,CareerReputation,CompanyTierId,PlacementTask,PromotionResult,SkillRequirement} from './model';

const statusRank:Record<SkillStatus,number>={unassessed:0,practiced:1,demonstrated:2,verified:3};
export const createCareerLeagueState=():CareerLeagueState=>({version:1,persona:null,workEnvironment:null,goal:null,placementPath:null,placementScore:null,placementRecommendation:1,targetOpportunityId:null,acceptedOfferId:null,onboardingComplete:false,assessmentResults:{},updatedAt:new Date(0).toISOString()});
export function migrateCareerLeagueState(value:unknown,legacy?:{experience?:string|null;goal?:string|null;onboardingComplete?:boolean}):CareerLeagueState{const base=createCareerLeagueState();if(value&&typeof value==='object'){const row=value as Partial<CareerLeagueState>;return{...base,...row,version:1,assessmentResults:row.assessmentResults&&typeof row.assessmentResults==='object'?row.assessmentResults:{}}}if(!legacy)return base;const persona=legacy.experience==='student'?'student':legacy.experience==='junior'||legacy.experience==='experienced'?'working-accountant':legacy.experience==='beginner'?'student':null;const goal=legacy.goal==='career'?(persona==='working-accountant'?'bigger-company':'first-job'):legacy.goal==='practice'?'general-accountant':legacy.goal==='learn'?'first-job':null;return{...base,persona,goal,onboardingComplete:Boolean(legacy.onboardingComplete&&persona&&goal)}}
export const meetsRequirement=(result:SkillResult|undefined,requirement:SkillRequirement)=>statusRank[result?.status??'unassessed']>=statusRank[requirement.minimum];
export function careerGap(opportunityId:string,passport:SkillResult[]):CareerGap{const opportunity=careerOpportunities.find(item=>item.id===opportunityId)!;const strong:SkillId[]=[],developing:SkillId[]=[],missing:SkillId[]=[];for(const requirement of opportunity.requirements){const result=passport.find(item=>item.skillId===requirement.skillId);if(meetsRequirement(result,requirement))strong.push(requirement.skillId);else if(result?.status==='practiced')developing.push(requirement.skillId);else missing.push(requirement.skillId)}return{opportunityId,strong,developing,missing,met:strong.length,total:opportunity.requirements.length,ready:strong.length===opportunity.requirements.length}}
export function careerTrainingPlan(opportunityId:string,passport:SkillResult[]){const opportunity=careerOpportunities.find(item=>item.id===opportunityId)!;const gap=careerGap(opportunityId,passport),needed=new Set([...gap.developing,...gap.missing]);return trainingSteps(opportunity.trainingMissionIds).filter(step=>needed.has(step.skillId))}
export function companyUnlocked(companyId:string,passport:SkillResult[],completedMissionIds:string[],assessmentResults:CareerLeagueState['assessmentResults']){const company=companyTiers.find(item=>item.id===companyId)!;if(company.tier===1)return true;return company.unlock.requiredMissionIds.every(id=>completedMissionIds.includes(id))&&company.unlock.requirements.every(req=>meetsRequirement(passport.find(item=>item.skillId===req.skillId),req))&&(!company.unlock.promotionAssessmentId||assessmentResults[company.unlock.promotionAssessmentId]==='pass')}
export function placementResult(tasks:PlacementTask[],answers:Record<string,number>){const correct=tasks.filter(task=>answers[task.id]===task.correctIndex).length,score=Math.round(correct/tasks.length*100),recommendation:CompanyTierId=score>=85?2:score>=50?1:1;return{score,recommendation}}
export function promotionEligibility(assessmentId:string,passport:SkillResult[],completedMissionIds:string[]){const assessment=promotionAssessments.find(item=>item.id===assessmentId)!;const missingSkills=assessment.requirements.filter(req=>!meetsRequirement(passport.find(item=>item.skillId===req.skillId),req)).map(req=>req.skillId),missingMissions=assessment.requiredMissionIds.filter(id=>!completedMissionIds.includes(id));return{eligible:missingSkills.length===0&&missingMissions.length===0,missingSkills,missingMissions}}
export function evaluatePromotion(performance:PerformanceDimensions&{criticalErrors:number}):PromotionResult{const score=Math.round(performance.accuracy*.3+performance.accountingJudgment*.2+performance.investigation*.18+performance.riskAwareness*.17+performance.independence*.08+performance.documentation*.07),developmentAreas=(['accuracy','accountingJudgment','investigation','riskAwareness','independence','documentation']as const).filter(key=>performance[key]<75);return{status:score>=78&&performance.criticalErrors===0&&performance.riskAwareness>=70?'pass':'needs-practice',score,developmentAreas}}
export function careerLeagueScore(performance:Partial<PerformanceDimensions>&{firstAttemptQuality?:number;difficulty?:number;bossCompletion?:number;consistency?:number}){return Math.max(0,Math.min(1000,Math.round((performance.accuracy??0)*2.7+(performance.accountingJudgment??0)*2.2+(performance.investigation??0)*1.7+(performance.riskAwareness??0)*1.8+(performance.firstAttemptQuality??0)*.7+(performance.difficulty??1)*12+(performance.bossCompletion??0)*.35+(performance.consistency??0)*.25)))}
export const canAccess=(feature:CareerFeature,plan:'free'|'pro')=>premiumAccess[feature]==='free'||plan==='pro';
export const roleForCareerGoal=(goal:CareerGoal|null)=>goal==='ap'?'ap-accountant':goal==='ar'?'ar-accountant':goal==='treasury'?'treasury-accountant':goal==='gl'?'gl-accountant':goal==='cost'?'cost-accountant':goal==='general-accountant'||goal==='bigger-company'||goal==='corporate-accounting'?'general-accountant':'junior-accountant';
export function careerReputation(performance:Partial<PerformanceDimensions>&{criticalErrors?:number}):CareerReputation{const accuracy=performance.accuracy??0,risk=performance.riskAwareness??0,judgment=performance.accountingJudgment??0,documentation=performance.documentation??0,independence=performance.independence??0,errors=performance.criticalErrors??0;return{managerTrust:Math.round((judgment+risk)/2),booksHealth:Math.max(0,Math.round((accuracy+risk)/2-errors*10)),professionalReputation:Math.round((accuracy+judgment+documentation)/3),auditRisk:Math.min(100,Math.max(0,Math.round(100-(risk+documentation)/2+errors*15))),independence:Math.round(independence),reliability:Math.round((accuracy+documentation)/2),gameOnly:true}}
