import type{PlacementTask}from'./model';
const t=(en:string,ar:string)=>({en,ar});
export const placementTasks:PlacementTask[]=[
 {id:'g-classification',personas:['student','graduate'],area:'classification',scenario:t('Equipment was purchased on credit. Which accounts changed?','تم شراء معدات آجلًا. ما الحسابات التي تغيرت؟'),options:[t('Equipment and Accounts Payable','المعدات والموردون'),t('Cash and Sales Revenue','النقدية وإيراد المبيعات'),t('Rent Expense and Bank','مصروف الإيجار والبنك')],correctIndex:0,responsibility:t('Identify affected accounts','حدد الحسابات المتأثرة')},
 {id:'g-debit-credit',personas:['student','graduate'],area:'debit-credit',scenario:t('A customer pays an outstanding invoice into the bank. Choose the direction.','سدد عميل فاتورة مستحقة في البنك. اختر اتجاه التسجيل.'),options:[t('Debit Bank; Credit Receivables','مدين البنك؛ دائن العملاء'),t('Debit Receivables; Credit Bank','مدين العملاء؛ دائن البنك'),t('Debit Revenue; Credit Cash','مدين الإيراد؛ دائن النقدية')],correctIndex:0,responsibility:t('Translate movement into Debit and Credit','ترجم الحركة إلى مدين ودائن')},
 {id:'g-journal',personas:['student','graduate'],area:'journals',scenario:t('Rent was paid from Bank. Which entry preserves the story?','تم دفع الإيجار من البنك. أي قيد يحفظ القصة؟'),options:[t('Dr Rent Expense / Cr Bank','من حـ/ مصروف الإيجار إلى حـ/ البنك'),t('Dr Bank / Cr Rent Expense','من حـ/ البنك إلى حـ/ مصروف الإيجار'),t('Dr Cash / Cr Revenue','من حـ/ النقدية إلى حـ/ الإيراد')],correctIndex:0,responsibility:t('Build a supported journal','ابنِ قيدًا مؤيدًا')},
 {id:'g-documents',personas:['student','graduate'],area:'documents',scenario:t('A supplier invoice exists but the goods receipt note is missing. What first?','توجد فاتورة مورد لكن إذن الاستلام مفقود. ماذا تفعل أولًا؟'),options:[t('Hold and request the missing evidence','أوقف واطلب المستند الناقص'),t('Post immediately','رحّل فورًا'),t('Delete the invoice','احذف الفاتورة')],correctIndex:0,responsibility:t('Protect posting with evidence','احمِ الترحيل بالمستند')},
 {id:'g-ledger',personas:['graduate'],area:'ledger',scenario:t('An accepted journal was posted. Where should its effect now appear?','تم ترحيل قيد معتمد. أين يجب أن يظهر أثره؟'),options:[t('Relevant ledger accounts','حسابات الأستاذ المعنية'),t('The learning guide only','دليل التعلم فقط'),t('Unposted inbox','الوارد غير المرحّل')],correctIndex:0,responsibility:t('Follow the posting chain','تتبع سلسلة الترحيل')},
 {id:'g-trial',personas:['graduate'],area:'trial-balance',scenario:t('The trial balance totals agree. What can you safely conclude?','إجماليات ميزان المراجعة متساوية. ما الاستنتاج الآمن؟'),options:[t('Debits equal credits, but errors may remain','المدين يساوي الدائن وقد تظل أخطاء'),t('Every account is definitely correct','كل الحسابات صحيحة بالتأكيد'),t('No review is needed','لا حاجة لأي مراجعة')],correctIndex:0,responsibility:t('Interpret control output carefully','فسّر نتيجة الرقابة بعناية')},
 {id:'g-ap',personas:['graduate'],area:'ap',scenario:t('Invoice EGP 100,000; PO and GRN EGP 95,000. Supplier asks for payment.','فاتورة 100,000؛ أمر الشراء والاستلام 95,000. المورد يطلب السداد.'),options:[t('Investigate and hold the difference','تحقق وأوقف الفرق'),t('Pay the invoice total','ادفع كامل الفاتورة'),t('Change the PO after payment','عدّل أمر الشراء بعد السداد')],correctIndex:0,responsibility:t('Apply three-way matching','طبّق المطابقة الثلاثية')},
 {id:'g-ar',personas:['graduate'],area:'ar',scenario:t('A receipt arrives without a customer reference. What is the professional action?','وصل تحصيل دون مرجع عميل. ما التصرف المهني؟'),options:[t('Investigate before allocation','تحقق قبل التخصيص'),t('Allocate to the largest balance','خصصه لأكبر رصيد'),t('Record it as revenue again','سجله إيرادًا مرة أخرى')],correctIndex:0,responsibility:t('Control cash allocation','اضبط تخصيص التحصيل')},
 {id:'g-bank',personas:['graduate'],area:'bank',scenario:t('Ledger and bank statement disagree. What is the first step?','الأستاذ وكشف البنك غير متطابقين. ما أول خطوة؟'),options:[t('Identify and classify reconciling items','حدد وصنّف بنود التسوية'),t('Force the ledger to match','غيّر الأستاذ مباشرة'),t('Ignore it until next month','تجاهل الفرق للشهر القادم')],correctIndex:0,responsibility:t('Investigate a reconciliation','حقق في التسوية')},
 {id:'w-supplier',personas:['working-accountant'],area:'ap',scenario:t('An approved invoice has a price mismatch with the PO. The close is today.','فاتورة معتمدة بها فرق سعر عن أمر الشراء والإقفال اليوم.'),options:[t('Hold the exception and escalate with evidence','أوقف الاستثناء وصعّده بالمستندات'),t('Post because it is approved','رحّل لأنها معتمدة'),t('Edit the PO silently','عدّل أمر الشراء دون توثيق')],correctIndex:0,responsibility:t('Own an AP exception','أدر استثناء موردين')},
 {id:'w-customer',personas:['working-accountant'],area:'ar',scenario:t('One receipt could relate to two customers.','تحصيل واحد قد يخص عميلين.'),options:[t('Request remittance detail and hold allocation','اطلب بيان التحويل وأوقف التخصيص'),t('Split it equally','قسّمه بالتساوي'),t('Credit sales revenue','اجعله دائن إيراد مبيعات')],correctIndex:0,responsibility:t('Resolve an AR ambiguity','حل غموض العملاء')},
 {id:'w-bank',personas:['working-accountant'],area:'bank',scenario:t('A bank fee appears on the statement but not the ledger.','عمولة بنكية ظهرت في الكشف ولم تظهر في الأستاذ.'),options:[t('Validate then prepare a supported adjustment','تحقق ثم أعد تسوية مؤيدة'),t('Treat it as timing only','اعتبرها فرق توقيت فقط'),t('Delete it from reconciliation','احذفها من التسوية')],correctIndex:0,responsibility:t('Prepare a bank adjustment','أعد تسوية بنكية')},
 {id:'w-expense',personas:['working-accountant'],area:'classification',scenario:t('A two-year software license was charged fully to this month.','رخصة برنامج لمدة سنتين حُمّلت بالكامل على الشهر الحالي.'),options:[t('Assess prepayment treatment and materiality','قيّم المعالجة كمصروف مقدم والأهمية النسبية'),t('Keep it because cash was paid','اتركها لأن النقدية دُفعت'),t('Move it to revenue','انقلها إلى الإيراد')],correctIndex:0,responsibility:t('Review classification','راجع التصنيف')},
 {id:'w-accrual',personas:['working-accountant'],area:'accruals',scenario:t('September electricity was consumed; the invoice arrives in October.','كهرباء سبتمبر استُهلكت والفاتورة تصل في أكتوبر.'),options:[t('Accrue September using support and reverse appropriately','أثبت استحقاق سبتمبر بمستند واعكسه بالشكل المناسب'),t('Wait and record only in October','انتظر وسجلها في أكتوبر فقط'),t('Record a receivable','سجل حساب عملاء')],correctIndex:0,responsibility:t('Protect period completeness','احمِ اكتمال الفترة')},
 {id:'w-prepayment',personas:['working-accountant'],area:'prepayments',scenario:t('Annual insurance was paid on 1 July. September close begins.','تم دفع تأمين سنوي في 1 يوليو وبدأ إقفال سبتمبر.'),options:[t('Recognize elapsed expense and retain the unexpired asset','حمّل المنقضي واحتفظ بالباقي كأصل'),t('Expense the full payment again','حمّل كامل الدفعة مرة أخرى'),t('Leave cash as the balance','اترك النقدية كرصيد')],correctIndex:0,responsibility:t('Maintain a prepayment schedule','أدر جدول المصروفات المقدمة')},
 {id:'w-cutoff',personas:['working-accountant'],area:'cut-off',scenario:t('Goods were received on 30 September; invoice dated 2 October.','استُلمت البضاعة 30 سبتمبر والفاتورة بتاريخ 2 أكتوبر.'),options:[t('Assess September recognition from receipt evidence','قيّم إثبات سبتمبر من مستند الاستلام'),t('Always use invoice date','استخدم تاريخ الفاتورة دائمًا'),t('Record only when paid','سجل عند السداد فقط')],correctIndex:0,responsibility:t('Make a cut-off decision','اتخذ قرار قطع')},
 {id:'w-month-end',personas:['working-accountant'],area:'month-end',scenario:t('AP is unreconciled and management requests close sign-off.','الموردون غير مطابقين والإدارة تطلب اعتماد الإقفال.'),options:[t('Block sign-off until the material issue is resolved or escalated','أوقف الاعتماد حتى حل المشكلة الجوهرية أو تصعيدها'),t('Sign off to meet the deadline','اعتمد للحاق بالموعد'),t('Hide the difference in suspense','أخفِ الفرق في حساب معلق')],correctIndex:0,responsibility:t('Protect close readiness','احمِ جاهزية الإقفال')},
 {id:'w-documentation',personas:['working-accountant'],area:'controls',scenario:t('A manual journal has no preparer, reviewer or support.','قيد يدوي بلا مُعد أو مراجع أو مستند.'),options:[t('Return it and request complete support and approval','أعده واطلب المستند والاعتماد الكامل'),t('Post because the amount is small','رحّل لأن المبلغ صغير'),t('Add your name as both roles','اكتب اسمك كمعد ومراجع')],correctIndex:0,responsibility:t('Enforce journal control','طبّق رقابة القيود')},
 {id:'w-review',personas:['working-accountant'],area:'review',scenario:t('A junior reconciled the balance but left three old items unexplained.','سوّى محاسب مبتدئ الرصيد وترك ثلاثة بنود قديمة دون تفسير.'),options:[t('Return for investigation with clear review notes','أعده للتحقق بملاحظات مراجعة واضحة'),t('Approve because totals agree','اعتمد لأن الإجماليات متساوية'),t('Remove the old items','احذف البنود القديمة')],correctIndex:0,responsibility:t('Review another accountant’s work','راجع عمل محاسب آخر')},
];
export const tasksForPersona=(persona:PlacementTask['personas'][number])=>placementTasks.filter(task=>task.personas.includes(persona));
