import type{ConnectedMissionEdge}from'./model';const t=(en:string,ar:string)=>({en,ar});
export const connectedMissionGraph:ConnectedMissionEdge[]=[
 {id:'supplier-resolved-bank',sourceMissionId:'supplier-control',sourceOutcome:'resolved',targetMissionId:'bank-control',kind:'balance',description:t('Approved supplier payment becomes an expected bank movement.','سداد المورد المعتمد يصبح حركة متوقعة في البنك.'),value:-10000,flag:'supplier-payment-expected'},
 {id:'supplier-held-close',sourceMissionId:'supplier-control',sourceOutcome:'held',targetMissionId:'close-readiness',kind:'close-blocker',description:t('The unresolved supplier exception remains on the close issues list.','استثناء المورد غير المحلول يظل في قائمة مشكلات الإقفال.'),flag:'supplier-exception-open'},
 {id:'supplier-escalated-review',sourceMissionId:'supplier-control',sourceOutcome:'escalated',targetMissionId:'close-readiness',kind:'control',description:t('Manager review is required before the supplier item can be signed off.','مراجعة المدير مطلوبة قبل اعتماد بند المورد.'),flag:'supplier-manager-review'},
 {id:'customer-resolved-bank',sourceMissionId:'customer-control',sourceOutcome:'resolved',targetMissionId:'bank-control',kind:'balance',description:t('Allocated customer cash becomes an expected bank deposit.','تحصيل العميل المخصص يصبح إيداعًا متوقعًا في البنك.'),value:5000,flag:'customer-deposit-expected'},
 {id:'customer-held-bank',sourceMissionId:'customer-control',sourceOutcome:'held',targetMissionId:'bank-control',kind:'queue',description:t('Unapplied cash must be investigated during bank control.','النقدية غير المخصصة يجب التحقق منها أثناء رقابة البنك.'),value:5000,flag:'unapplied-cash-open'},
 {id:'bank-resolved-close',sourceMissionId:'bank-control',sourceOutcome:'resolved',targetMissionId:'close-readiness',kind:'control',description:t('Bank reconciliation is signed off and no longer blocks close.','تم اعتماد تسوية البنك ولم تعد تعطل الإقفال.'),flag:'bank-reconciliation-cleared'},
 {id:'bank-held-close',sourceMissionId:'bank-control',sourceOutcome:'held',targetMissionId:'close-readiness',kind:'close-blocker',description:t('The unresolved bank difference blocks month-end close.','فرق البنك غير المحلول يمنع الإقفال الشهري.'),flag:'bank-difference-open'},
];
