import type {BootcampInteraction,BootcampMission} from './model';

const t=(en:string,ar:string)=>({en,ar});
const item=(id:string,en:string,ar:string,descriptionEn:string,descriptionAr:string,correct=true):BootcampInteraction=>({id,label:t(en,ar),description:t(descriptionEn,descriptionAr),correct});

export const bootcampMissions:BootcampMission[]=[
 {id:'business-world',order:1,title:t('What Is a Business?','ما هي المنشأة؟'),subtitle:t('Walk through a working business','استكشف منشأة تعمل فعلًا'),brief:t('Find the people, resources and flows that make the business work.','اكتشف الأشخاص والموارد والحركات التي تجعل المنشأة تعمل.'),mechanic:'explore',interactions:[item('owner','Owner','المالك','Provides direction and capital.','يوفر القرار ورأس المال.'),item('cash','Cash','النقدية','A resource the business controls.','مورد تسيطر عليه المنشأة.'),item('customers','Customers','العملاء','Buy goods or services.','يشترون السلع أو الخدمات.'),item('suppliers','Suppliers','الموردون','Provide goods and services.','يوفرون السلع والخدمات.'),item('products','Products & Services','المنتجات والخدمات','What the business offers.','ما تقدمه المنشأة للسوق.'),item('expenses','Expenses','المصروفات','Resources consumed to operate.','موارد تُستهلك لتشغيل المنشأة.')],skills:['business-basics'],evidenceRule:'practice-only'},
 {id:'missing-story',order:2,title:t('Why Accounting Exists','لماذا توجد المحاسبة؟'),subtitle:t('Repair the missing financial story','أصلح القصة المالية الناقصة'),brief:t('The desk is full of activity, but nothing was recorded. Recover the evidence.','المكتب مليء بالحركة، لكن لا شيء مسجل. استعد المستندات.'),mechanic:'repair',interactions:[item('cash-payment','Cash payment','دفعة نقدية','Records money leaving the business.','تسجل خروج أموال من المنشأة.'),item('customer-receipt','Customer receipt','سند قبض عميل','Records money collected from a customer.','يسجل المبلغ المحصل من عميل.'),item('supplier-invoice','Supplier invoice','فاتورة مورد','Records what was supplied and owed.','تسجل ما تم توريده والمبلغ المستحق.'),item('expense-voucher','Expense voucher','سند مصروف','Supports an operating payment.','يؤيد دفعة تشغيلية.'),item('purchase-file','Purchase file','ملف شراء','Connects request, receipt and invoice.','يربط الطلب والاستلام والفاتورة.')],skills:['accounting-purpose','document-awareness'],evidenceRule:'practice-only'},
 {id:'transaction-radar',order:3,title:t('Transaction Radar','رادار العملية المالية'),subtitle:t('Spot what changes the business','اكتشف ما يغيّر المنشأة'),brief:t('Tag events that create a measurable financial change. Leave plans and conversations unrecorded.','حدد الأحداث التي تصنع تغيرًا ماليًا قابلًا للقياس، واترك الخطط والمحادثات دون تسجيل.'),mechanic:'classify',interactions:[item('investment','Owner invests cash','المالك يضخ نقدية','Cash and capital change.','تتغير النقدية ورأس المال.'),item('purchase','Inventory is purchased','تم شراء مخزون','Resources or obligations change.','تتغير الموارد أو الالتزامات.'),item('sale','A sale is completed','تمت عملية بيع','Revenue and another account change.','يتغير الإيراد وحساب آخر.'),item('receipt','Customer pays','العميل يسدد','Bank or cash and receivables change.','يتغير البنك أو النقدية والعملاء.'),item('supplier-payment','Supplier is paid','تم سداد المورد','Cash and payables change.','تتغير النقدية والموردون.'),item('expense','Rent is paid','تم دفع الإيجار','Expense and cash change.','يتغير المصروف والنقدية.'),item('quote','A supplier sends a price quote','أرسل المورد عرض سعر','A quote alone does not record a transaction.','عرض السعر وحده لا يسجل عملية.',false),item('meeting','The team discusses next month','الفريق يناقش الشهر القادم','A discussion alone creates no accounting entry.','المناقشة وحدها لا تنشئ قيدًا.',false)],skills:['transaction-analysis'],evidenceRule:'practice-only'},
 {id:'equation-builder',order:4,title:t('Build the Accounting Equation','ابنِ المعادلة المحاسبية'),subtitle:t('Assets = Liabilities + Equity','الأصول = الالتزامات + حقوق الملكية'),brief:t('The owner invests EGP 50,000. Put the value where it belongs without using Debit or Credit yet.','استثمر المالك 50,000 جنيه. ضع القيمة في مكانها الصحيح دون استخدام مدين ودائن بعد.'),mechanic:'build-equation',interactions:[item('asset-cash','Place EGP 50,000 in Cash','ضع 50,000 جنيه في النقدية','Cash becomes a company asset.','تصبح النقدية أصلًا للمنشأة.'),item('equity-capital','Place EGP 50,000 in Capital','ضع 50,000 جنيه في رأس المال','The owner claim increases equally.','يزداد حق المالك بالقيمة نفسها.')],skills:['accounting-equation'],evidenceRule:'practice-only'},
 {id:'account-city',order:5,title:t('Enter Account City','ادخل مدينة الحسابات'),subtitle:t('Six families. One accounting system.','ست عائلات. نظام محاسبي واحد.'),brief:t('Unlock every district, then continue into the full Account City whenever you want to explore its 197 accounts.','افتح كل حي، ثم ادخل مدينة الحسابات الكاملة لاستكشاف حساباتها الـ197.'),mechanic:'districts',accountCityRoute:'/account-guide?return=bootcamp',interactions:[item('assets','Assets District','حي الأصول','Resources controlled by the business.','موارد تسيطر عليها المنشأة.'),item('liabilities','Liabilities District','حي الالتزامات','Amounts the business owes.','مبالغ مستحقة على المنشأة.'),item('equity','Equity District','حي حقوق الملكية','The owners’ residual interest.','حق الملاك المتبقي.'),item('revenue','Revenue District','حي الإيرادات','Value earned from business activity.','قيمة تحققت من نشاط المنشأة.'),item('expenses','Expenses District','حي المصروفات','Resources consumed to earn revenue.','موارد استهلكت لتحقيق الإيراد.'),item('contra','Contra District','منطقة الحسابات المقابلة','Accounts that offset related balances.','حسابات تخفض رصيد حساب مرتبط.')],skills:['account-classification'],evidenceRule:'practice-only'},
 {id:'movement-lab',order:6,title:t('Increase and Decrease Lab','مختبر الزيادة والنقص'),subtitle:t('Understand movement before labels','افهم الحركة قبل المصطلحات'),brief:t('Follow what rises and falls across the business before translating movement into Debit and Credit.','تتبع ما يزيد وما ينخفض قبل ترجمة الحركة إلى مدين ودائن.'),mechanic:'movement',interactions:[item('cash-in','Customer cash received → Cash increases','تحصيل من عميل ← النقدية تزيد','Money enters the business.','النقدية تدخل المنشأة.'),item('payable-in','Buy on credit → Payables increase','شراء آجل ← الموردون تزيد','The business now owes the supplier.','أصبح على المنشأة التزام للمورد.'),item('expense-in','Use electricity → Expense increases','استهلاك كهرباء ← المصروف يزيد','The period consumes a service.','استهلكت الفترة خدمة.'),item('receivable-down','Customer pays → Receivables decrease','العميل يسدد ← العملاء تنخفض','The outstanding claim is collected.','تم تحصيل الحق المستحق.'),item('cash-down','Pay supplier → Cash decreases','سداد المورد ← النقدية تنخفض','Money leaves the business.','تخرج النقدية من المنشأة.')],skills:['transaction-analysis'],evidenceRule:'practice-only'},
 {id:'debit-credit',order:7,title:t('Translate Movement','ترجم الحركة المحاسبية'),subtitle:t('Debit and Credit are recording directions','مدين ودائن اتجاهان للتسجيل'),brief:t('Connect each familiar movement to its recording side. No memorization without a business story.','اربط كل حركة مفهومة باتجاه تسجيلها، دون حفظ منفصل عن قصة العملية.'),mechanic:'connect',interactions:[item('asset-debit','Asset increases → Debit','زيادة الأصل ← مدين','Cash received increases an asset on the Debit side.','استلام النقدية يزيد الأصل في الجانب المدين.'),item('asset-credit','Asset decreases → Credit','نقص الأصل ← دائن','Cash paid decreases an asset on the Credit side.','دفع النقدية يخفض الأصل في الجانب الدائن.'),item('liability-credit','Liability increases → Credit','زيادة الالتزام ← دائن','Buying on credit increases payables.','الشراء الآجل يزيد الموردين.'),item('revenue-credit','Revenue increases → Credit','زيادة الإيراد ← دائن','A completed sale increases revenue.','البيع المكتمل يزيد الإيراد.'),item('expense-debit','Expense increases → Debit','زيادة المصروف ← مدين','Consumed services increase expense.','الخدمات المستهلكة تزيد المصروف.')],skills:['debit-credit'],evidenceRule:'practice-only'},
 {id:'document-dock',order:8,title:t('Document Dock','رصيف المستندات'),subtitle:t('No evidence, no confident posting','لا ترحيل واثق دون دليل'),brief:t('Place the core source documents in the accounting file and understand what each one proves.','ضع المستندات الأساسية في الملف المحاسبي وافهم ما يثبته كل مستند.'),mechanic:'documents',interactions:[item('invoice','Invoice','فاتورة','Shows goods/services and requested amount.','توضح السلع أو الخدمات والمبلغ المطلوب.'),item('receipt','Receipt','إيصال قبض','Supports money received.','يؤيد مبلغًا تم تحصيله.'),item('voucher','Payment Voucher','سند صرف','Authorizes and supports a payment.','يعتمد ويؤيد عملية دفع.'),item('bank-advice','Bank Advice','إشعار بنكي','Supports a bank movement.','يؤيد حركة بنكية.'),item('po','Purchase Order','أمر شراء','Shows what was authorized.','يوضح ما تم التصريح بشرائه.'),item('grn','Goods Receipt Note','إذن استلام','Shows what was actually received.','يوضح ما تم استلامه فعليًا.')],skills:['document-analysis'],evidenceRule:'practice-only'},
 {id:'first-journal',order:9,title:t('Build Your First Journal','ابنِ أول قيد'),subtitle:t('Two lines. One balanced story.','سطران. قصة واحدة متوازنة.'),brief:t('Record the owner investment with a date, reference, Debit line and Credit line.','سجل استثمار المالك بتاريخ ومرجع وسطر مدين وسطر دائن.'),mechanic:'journal',interactions:[item('date','Set transaction date','حدد تاريخ العملية','Every journal needs a period.','كل قيد يحتاج فترة.'),item('reference','Attach owner investment reference','أرفق مرجع استثمار المالك','A reference connects the journal to evidence.','المرجع يربط القيد بالدليل.'),item('debit-cash','Debit Cash — EGP 50,000','مدين: النقدية — 50,000 جنيه','Cash increased.','زادت النقدية.'),item('credit-capital','Credit Capital — EGP 50,000','دائن: رأس المال — 50,000 جنيه','Owner equity increased.','زادت حقوق المالك.'),item('balanced','Confirm Debit = Credit','أكد تساوي المدين والدائن','The entry balances at EGP 50,000.','القيد متوازن عند 50,000 جنيه.')],skills:['journal-entries'],evidenceRule:'practice-only'},
 {id:'mizan-boss',order:10,title:t('Boss: Start Mizan Trading','الزعيم: ابدأ العمل في ميزان'),subtitle:t('Prove the foundation through six transactions','طبّق الأساس من خلال ست عمليات'),brief:t('Build the account pair for each transaction. Finish the file to unlock Mizan Trading.','ابنِ زوج الحسابات لكل عملية، وأنهِ الملف لفتح شركة ميزان.'),mechanic:'boss',interactions:[],entries:[
  {id:'owner-cash',story:t('Owner invests EGP 50,000 cash.','استثمر المالك 50,000 جنيه نقدًا.'),debit:'Cash',credit:'Capital',amount:50000},
  {id:'equipment-credit',story:t('Buy equipment for EGP 20,000 on credit.','شراء معدات بـ20,000 جنيه آجلًا.'),debit:'Office Equipment',credit:'Accounts Payable',amount:20000},
  {id:'cash-sale',story:t('Complete a cash sale for EGP 8,000.','إتمام بيع نقدي بقيمة 8,000 جنيه.'),debit:'Cash',credit:'Sales Revenue',amount:8000},
  {id:'customer-collection',story:t('Collect EGP 5,000 from a customer.','تحصيل 5,000 جنيه من عميل.'),debit:'Bank',credit:'Accounts Receivable',amount:5000},
  {id:'rent-payment',story:t('Pay EGP 3,000 rent in cash.','دفع إيجار 3,000 جنيه نقدًا.'),debit:'Rent Expense',credit:'Cash',amount:3000},
  {id:'supplier-payment',story:t('Pay EGP 10,000 to a supplier from Bank.','سداد 10,000 جنيه لمورد من البنك.'),debit:'Accounts Payable',credit:'Bank',amount:10000},
 ],skills:['transaction-analysis','account-classification','debit-credit','journal-entries'],evidenceRule:'practice-only'},
];

export const bootcampMissionIds=bootcampMissions.map(item=>item.id);
export const getBootcampMission=(id:string)=>bootcampMissions.find(item=>item.id===id)??null;
