import {bootcampMissionIds,bootcampMissions,getBootcampMission} from './catalog';
import type {BootcampMissionId,BootcampState} from './model';

const validMission=(value:unknown):value is BootcampMissionId=>typeof value==='string'&&bootcampMissionIds.includes(value as BootcampMissionId);
export const createBootcampState=():BootcampState=>({version:1,currentMissionId:'business-world',completedMissionIds:[],interactionProgress:{},attempts:{},bossCompleted:false,mizanUnlocked:false,completedAt:null});
export function migrateBootcampState(value:unknown):BootcampState{const base=createBootcampState();if(!value||typeof value!=='object')return base;const row=value as Partial<BootcampState>,completed=Array.isArray(row.completedMissionIds)?row.completedMissionIds.filter(validMission):[],progress=Object.fromEntries(bootcampMissions.map(mission=>[mission.id,Array.isArray(row.interactionProgress?.[mission.id])?row.interactionProgress![mission.id]!.filter(id=>mission.interactions.some(item=>item.id===id)||mission.entries?.some(item=>item.id===id)):[]]));return{...base,currentMissionId:validMission(row.currentMissionId)?row.currentMissionId:bootcampMissions.find(item=>!completed.includes(item.id))?.id??'mizan-boss',completedMissionIds:[...new Set(completed)],interactionProgress:progress,attempts:row.attempts&&typeof row.attempts==='object'?row.attempts:{},bossCompleted:completed.includes('mizan-boss'),mizanUnlocked:completed.includes('mizan-boss'),completedAt:completed.includes('mizan-boss')&&typeof row.completedAt==='string'?row.completedAt:null}}
export const isBootcampMissionUnlocked=(state:BootcampState,id:BootcampMissionId)=>{const mission=getBootcampMission(id);return Boolean(mission&&(mission.order===1||state.completedMissionIds.includes(bootcampMissions[mission.order-2].id)))};
export const bootcampMissionReady=(state:BootcampState,id:BootcampMissionId)=>{const mission=getBootcampMission(id);if(!mission)return false;const required=mission.entries?.map(item=>item.id)??mission.interactions.filter(item=>item.correct).map(item=>item.id),done=state.interactionProgress[id]??[];return required.every(item=>done.includes(item))};
export function recordBootcampInteraction(state:BootcampState,id:BootcampMissionId,interactionId:string,correct:boolean):BootcampState{const mission=getBootcampMission(id),known=mission?.interactions.some(item=>item.id===interactionId)||mission?.entries?.some(item=>item.id===interactionId);if(!mission||!known||!isBootcampMissionUnlocked(state,id)||state.completedMissionIds.includes(id))return state;if(!correct)return{...state,attempts:{...state.attempts,[id]:(state.attempts[id]??0)+1}};return{...state,currentMissionId:id,interactionProgress:{...state.interactionProgress,[id]:[...new Set([...(state.interactionProgress[id]??[]),interactionId])]}}}
export function completeBootcampMission(state:BootcampState,id:BootcampMissionId,now=Date.now()):BootcampState{if(!isBootcampMissionUnlocked(state,id)||!bootcampMissionReady(state,id))return state;const completed=[...new Set([...state.completedMissionIds,id])],next=bootcampMissions.find(item=>!completed.includes(item.id));return{...state,completedMissionIds:completed,currentMissionId:next?.id??id,bossCompleted:completed.includes('mizan-boss'),mizanUnlocked:completed.includes('mizan-boss'),completedAt:completed.includes('mizan-boss')?state.completedAt??new Date(now).toISOString():null}}
export const bootcampProgress=(state:BootcampState)=>Math.round(state.completedMissionIds.length/bootcampMissions.length*100);
