import type{ChallengeSeed,CompetitionStanding,LocalPlayerProfile,OfflineCompetitionResult}from'./model';
export const competitionScore=(input:{accuracy:number;investigation:number;riskAwareness:number;judgment:number;firstAttempt:boolean;difficulty:number;assistanceUsed:number})=>Math.max(0,Math.min(1000,Math.round(input.accuracy*3+input.judgment*2.3+input.investigation*1.8+input.riskAwareness*1.9+(input.firstAttempt?55:0)+input.difficulty*15-input.assistanceUsed*22)));
const hash=(value:string)=>{let result=2166136261;for(let i=0;i<value.length;i++){result^=value.charCodeAt(i);result=Math.imul(result,16777619)}return(result>>>0).toString(16).padStart(8,'0')};
export function dailyChallenge(date:string,level:number,track:string):ChallengeSeed{const seed=hash(`${date}|${level}|${track}|career-league-v1`);return{challengeId:`daily-${date}-${level}-${track}`,challengeVersion:1,rulesetVersion:1,seed,caseId:`career-daily-${Number.parseInt(seed.slice(0,4),16)%7}`,difficulty:Math.max(1,Math.min(5,Math.ceil(level/2))),issuedFor:date,localOnly:true}}
export function createOfflineResult(input:Omit<OfflineCompetitionResult,'schema'|'packageId'|'checksum'|'localOnly'>):OfflineCompetitionResult{const payload=JSON.stringify(input),packageId=`result-${hash(payload)}`,base={schema:'debit-credit-offline-result-v1' as const,packageId,...input,localOnly:true as const};return{...base,checksum:hash(JSON.stringify(base))}}
export function verifyOfflineResult(value:unknown):value is OfflineCompetitionResult{if(!value||typeof value!=='object')return false;const row=value as OfflineCompetitionResult,c=row.challenge;if(row.schema!=='debit-credit-offline-result-v1'||row.localOnly!==true||!c||c.localOnly!==true||typeof row.packageId!=='string'||typeof row.profileId!=='string'||typeof row.displayName!=='string'||typeof row.completedAt!=='string'||typeof c.challengeId!=='string'||typeof c.seed!=='string'||!Number.isInteger(c.challengeVersion)||c.challengeVersion<1||!Number.isInteger(c.rulesetVersion)||c.rulesetVersion<1||![row.score,row.accuracy,row.investigation,row.riskAwareness,row.assistanceUsed].every(Number.isFinite)||row.score<0||row.score>1000||[row.accuracy,row.investigation,row.riskAwareness].some(n=>n<0||n>100)||row.assistanceUsed<0)return false;const{checksum,...base}=row;return checksum===hash(JSON.stringify(base))}
export function localDuel(a:OfflineCompetitionResult,b:OfflineCompetitionResult){const comparable=a.challenge.challengeId===b.challenge.challengeId&&a.challenge.challengeVersion===b.challenge.challengeVersion&&a.challenge.rulesetVersion===b.challenge.rulesetVersion&&a.challenge.seed===b.challenge.seed;if(!comparable)return{comparable:false,winnerProfileId:null,reason:'challenge-mismatch' as const};const winner=a.score===b.score?(a.accuracy===b.accuracy?null:a.accuracy>b.accuracy?a.profileId:b.profileId):a.score>b.score?a.profileId:b.profileId;return{comparable:true,winnerProfileId:winner,reason:winner?'professional-score' as const:'tie' as const}}
export function weeklyLeague(profiles:LocalPlayerProfile[],results:OfflineCompetitionResult[],level:number,track:LocalPlayerProfile['track']):CompetitionStanding[]{return profiles.filter(profile=>profile.level===level&&profile.track===track).map(profile=>{const rows=results.filter(result=>result.profileId===profile.id&&verifyOfflineResult(result)),score=rows.reduce((sum,row)=>sum+row.score,0),accuracy=rows.length?Math.round(rows.reduce((sum,row)=>sum+row.accuracy,0)/rows.length):0;return{profileId:profile.id,displayName:profile.displayName,level,track,score,accuracy,resultCount:rows.length,gameTitle:gameTitle(score,rows.length),localOnly:true as const}}).sort((a,b)=>b.score-a.score||b.accuracy-a.accuracy||a.profileId.localeCompare(b.profileId))}
export const gameTitle=(score:number,resultCount:number)=>resultCount===0?'New Challenger':score>=2200?'Control Guardian':score>=1400?'Evidence Builder':score>=700?'Careful Processor':'Career Starter';
