import type{LocalPlayerProfile,MultiProfileState}from'./model';
export const MULTI_PROFILE_KEY='debit-credit-multi-profile-v1';
export const PROFILE_SCOPED_KEYS=['debit-credit-world-v2','debit-credit-platform-v1','debit-credit-career-league-v1','debit-credit-career-profile-v1','debit-credit-skill-evidence-v1','debit-credit-cv-preferences-v1','debit-credit-cv-history-v1','debit-credit-bootcamp-v1','debit-credit-placement-v1','debit-credit-career-content-v1','debit-credit-company-progression-v1','debit-credit-bank-reconciliation-v1'];
const now=()=>new Date().toISOString(),defaultProfile=(data:Record<string,string>={}):LocalPlayerProfile=>({id:'default-local',displayName:'Local Accountant',persona:'student',level:1,track:'foundation',createdAt:new Date(0).toISOString(),updatedAt:now(),data});
export function migrateMultiProfileState(value:unknown,legacyData:Record<string,string>={}):MultiProfileState{if(!value||typeof value!=='object')return{version:1,activeProfileId:'default-local',profiles:[defaultProfile(legacyData)]};const row=value as Partial<MultiProfileState>,profiles=Array.isArray(row.profiles)?row.profiles.filter(item=>item&&typeof item.id==='string'&&typeof item.displayName==='string').map(item=>({...item,data:item.data&&typeof item.data==='object'?item.data:{}})):[];const safe=profiles.length?profiles:[defaultProfile(legacyData)],active=safe.some(item=>item.id===row.activeProfileId)?row.activeProfileId!:safe[0].id;return{version:1,activeProfileId:active,profiles:safe}}
export class BrowserMultiProfileRepository{
 private store(){return typeof window==='undefined'?null:window.localStorage}
 private capture(){const store=this.store(),data:Record<string,string>={};if(store)for(const key of PROFILE_SCOPED_KEYS){const value=store.getItem(key);if(value!==null)data[key]=value}return data}
 private restore(data:Record<string,string>){const store=this.store();if(store)for(const key of PROFILE_SCOPED_KEYS){const value=data[key];if(value===undefined)store.removeItem(key);else store.setItem(key,value)}}
 get(){const store=this.store();if(!store)return migrateMultiProfileState(null);try{return migrateMultiProfileState(JSON.parse(store.getItem(MULTI_PROFILE_KEY)??'null'),this.capture())}catch{return migrateMultiProfileState(null,this.capture())}}
 save(state:MultiProfileState){const next=migrateMultiProfileState(state);this.store()?.setItem(MULTI_PROFILE_KEY,JSON.stringify(next));return next}
 create(input:{displayName:string;persona:LocalPlayerProfile['persona'];level:number;track:LocalPlayerProfile['track']}){const state=this.get(),id=`local-${Date.now()}-${state.profiles.length+1}`,profile:LocalPlayerProfile={id,...input,createdAt:now(),updatedAt:now(),data:{}},profiles=state.profiles.map(item=>item.id===state.activeProfileId?{...item,data:this.capture(),updatedAt:now()}:item);this.restore({});return this.save({...state,activeProfileId:id,profiles:[...profiles,profile]})}
 rename(id:string,displayName:string){const state=this.get(),name=displayName.trim().slice(0,60);if(!name)return state;return this.save({...state,profiles:state.profiles.map(profile=>profile.id===id?{...profile,displayName:name,updatedAt:now()}:profile)})}
 delete(id:string){const state=this.get();if(state.profiles.length<=1||state.activeProfileId===id)return state;return this.save({...state,profiles:state.profiles.filter(profile=>profile.id!==id)})}
 switch(id:string){const state=this.get();if(!state.profiles.some(profile=>profile.id===id)||state.activeProfileId===id)return state;const profiles=state.profiles.map(profile=>profile.id===state.activeProfileId?{...profile,data:this.capture(),updatedAt:now()}:profile),target=profiles.find(profile=>profile.id===id)!;this.restore(target.data);return this.save({...state,profiles,activeProfileId:id})}
 export(){const state=this.get();return JSON.stringify({schema:'debit-credit-local-profiles-v1',exportedAt:now(),state:{...state,profiles:state.profiles.map(profile=>profile.id===state.activeProfileId?{...profile,data:this.capture()}:profile)}},null,2)}
 import(serialized:string){const parsed=JSON.parse(serialized)as{schema?:string;state?:unknown};if(parsed.schema!=='debit-credit-local-profiles-v1'||!parsed.state||typeof parsed.state!=='object')throw new Error('Unsupported local profile package');const state=parsed.state as Partial<MultiProfileState>;if(!Array.isArray(state.profiles)||state.profiles.length===0||state.profiles.length>30||state.profiles.some(profile=>!profile||typeof profile.id!=='string'||typeof profile.displayName!=='string'||!profile.data||typeof profile.data!=='object'||Object.entries(profile.data).some(([key,value])=>!PROFILE_SCOPED_KEYS.includes(key)||typeof value!=='string')))throw new Error('Invalid local profile package');const result=this.save(migrateMultiProfileState(state)),active=result.profiles.find(profile=>profile.id===result.activeProfileId)!;this.restore(active.data);return result}
}
