import{firstShiftCases}from'@/lib/cases/first-shift-cases';import{dailyChallenge}from'./engine';import type{ChallengeSeed,LocalPlayerProfile}from'./model';
export type LeagueId='foundation'|'practical'|'general'|'advanced-locked'|'leadership-locked';
export interface CompetitionChallenge{seed:ChallengeSeed;league:LeagueId;caseId:string;title:{en:string;ar:string};context:{en:string;ar:string};documents:{id:string;title:{en:string;ar:string};summary:{en:string;ar:string}}[];amount:number;debit:string;credit:string;approved:boolean;boss:boolean}
export interface ScoreDimensions{accuracy:number;judgment:number;investigation:number;riskAwareness:number;documentation:number;firstAttempt:number;consistency:number}
export interface RankedResult{schema:2;attemptId:string;profileId:string;displayName:string;league:LeagueId;challengeId:string;challengeVersion:number;scoringVersion:1;seed:string;caseId:string;date:string;score:number;dimensions:ScoreDimensions;ranked:boolean;boss:boolean;completedAt:string;unverified:true}
export interface Duel{version:1;id:string;challenge:CompetitionChallenge;playerA:string;playerB:string;resultA:RankedResult|null;resultB:RankedResult|null;complete:boolean;ranked:boolean}
export interface CompetitionState{version:2;results:RankedResult[];duel:Duel|null}
export const emptyCompetition=():CompetitionState=>({version:2,results:[],duel:null});
export function leagueForProfile(profile:LocalPlayerProfile):LeagueId{return profile.level<=1||profile.persona==='student'?'foundation':profile.level<=3?'practical':profile.level<=5?'general':profile.level<=7?'advanced-locked':'leadership-locked'}
const caseContent=firstShiftCases.map(item=>({id:item.id,title:item.title,context:item.businessContext,documents:item.documents.map(doc=>({id:doc.id,title:doc.title,summary:doc.summary})),debit:item.id==='supplier-invoice'?'equipment':item.id==='customer-receipt'?'bank':'officeExpense',credit:item.id==='supplier-invoice'?'suppliers':item.id==='customer-receipt'?'customers':'cash',amount:item.id==='supplier-invoice'?100000:item.id==='customer-receipt'?75000:2500}));
const bankContent={id:'bank-fee-adjustment',title:{en:'Bank charge review',ar:'مراجعة رسوم بنكية'},context:{en:'The statement contains a 250 EGP bank fee absent from the cash book. Inspect both records and prepare a supported book adjustment.',ar:'كشف البنك يتضمن رسومًا بقيمة ٢٥٠ جنيهًا غير موجودة بدفتر النقدية. افحص السجلين وأعد تعديلًا مؤيدًا.'},documents:[{id:'statement-fee',title:{en:'Bank statement BNK-329',ar:'كشف البنك BNK-329'},summary:{en:'The bank debited 250 EGP on 29 September.',ar:'خصم البنك ٢٥٠ جنيهًا في ٢٩ سبتمبر.'}},{id:'cash-book',title:{en:'Mizan cash book',ar:'دفتر نقدية ميزان'},summary:{en:'No corresponding bank-charge entry appears in the book.',ar:'لا يظهر قيد رسوم بنكية مقابل في الدفتر.'}}],debit:'bank-charges',credit:'bank',amount:250};
export function approvedChallenge(date:string,profile:LocalPlayerProfile,boss=false):CompetitionChallenge|null{const league=leagueForProfile(profile);if(league==='advanced-locked'||league==='leadership-locked')return null;const seed=dailyChallenge(date,league==='foundation'?1:league==='practical'?2:4,league);const index=boss?0:Number.parseInt(seed.seed.slice(0,4),16)%caseContent.length,content=league==='general'?bankContent:caseContent[index];return{seed:{...seed,challengeId:`${boss?'boss':'daily'}-${date}-${league}`,caseId:content.id},league,caseId:content.id,title:content.title,context:content.context,documents:content.documents,amount:content.amount,debit:content.debit,credit:content.credit,approved:league!=='foundation',boss}}
export interface ChallengeAnswer{inspected:string[];action:'post'|'hold'|'investigate';debit:string;credit:string;amount:number;attempts:number}
export function scoreChallenge(challenge:CompetitionChallenge,answer:ChallengeAnswer,profile:LocalPlayerProfile,ranked:boolean,completedAt:string):RankedResult{const allDocs=challenge.documents.every(doc=>answer.inspected.includes(doc.id)),accountCorrect=answer.debit===challenge.debit&&answer.credit===challenge.credit&&answer.amount===challenge.amount,judgment=answer.action==='post'&&allDocs?100:answer.action==='hold'&&!allDocs?80:answer.action==='investigate'&&!allDocs?75:0,accuracy=accountCorrect?100:0,investigation=Math.round(answer.inspected.filter(id=>challenge.documents.some(doc=>doc.id===id)).length/challenge.documents.length*100),riskAwareness=answer.action==='post'&&!allDocs?0:100,documentation=allDocs?100:investigation,firstAttempt=answer.attempts===1?100:0,dimensions={accuracy,judgment,investigation,riskAwareness,documentation,firstAttempt,consistency:100},score=Math.round(accuracy*.30+judgment*.22+investigation*.18+riskAwareness*.12+documentation*.08+firstAttempt*.05+100*.05);return{schema:2,attemptId:`${profile.id}:${challenge.seed.challengeId}:${challenge.seed.challengeVersion}:${completedAt}`,profileId:profile.id,displayName:profile.displayName,league:challenge.league,challengeId:challenge.seed.challengeId,challengeVersion:challenge.seed.challengeVersion,scoringVersion:1,seed:challenge.seed.seed,caseId:challenge.caseId,date:challenge.seed.issuedFor,score,dimensions,ranked:ranked&&challenge.approved,boss:challenge.boss,completedAt,unverified:true}}
export function addCompetitionResult(state:CompetitionState,result:RankedResult):CompetitionState{const duel=state.duel;if(duel&&!duel.resultA&&result.profileId===duel.playerA&&result.challengeId===duel.challenge.seed.challengeId)return state;const incoming=duel?.resultA&&!duel.resultB&&result.profileId===duel.playerB&&result.challengeId===duel.challenge.seed.challengeId?[duel.resultA,result]:[result];let results=state.results;for(const row of incoming){const prior=results.some(item=>item.profileId===row.profileId&&item.challengeId===row.challengeId&&item.challengeVersion===row.challengeVersion&&item.scoringVersion===row.scoringVersion&&item.ranked);results=[...results,{...row,ranked:row.ranked&&!prior}]}return{...state,results}}
export function beginDuel(challenge:CompetitionChallenge,a:LocalPlayerProfile,b:LocalPlayerProfile):Duel{return{version:1,id:`duel:${a.id}:${b.id}:${challenge.seed.challengeId}`,challenge,playerA:a.id,playerB:b.id,resultA:null,resultB:null,complete:false,ranked:leagueForProfile(a)===leagueForProfile(b)&&challenge.approved}}
export function recordDuel(d:Duel,result:RankedResult):Duel{if(result.challengeId!==d.challenge.seed.challengeId||result.challengeVersion!==d.challenge.seed.challengeVersion||result.seed!==d.challenge.seed.seed)return d;if(!d.resultA&&result.profileId===d.playerA)return{...d,resultA:result};if(d.resultA&&!d.resultB&&result.profileId===d.playerB)return{...d,resultB:result,complete:true};return d}
export function duelComparison(d:Duel){if(!d.complete||!d.resultA||!d.resultB)return null;const delta=d.resultA.score-d.resultB.score,winner=Math.abs(delta)<.5?null:delta>0?d.playerA:d.playerB;return{winner,draw:winner===null,scoreA:d.resultA.score,scoreB:d.resultB.score,dimensionsA:d.resultA.dimensions,dimensionsB:d.resultB.dimensions,ranked:d.ranked}}
export function weekOf(date:string){const day=new Date(`${date}T00:00:00Z`),weekday=(day.getUTCDay()+6)%7;day.setUTCDate(day.getUTCDate()-weekday);return day.toISOString().slice(0,10)}
export function weeklyStandings(profiles:LocalPlayerProfile[],results:RankedResult[],league:LeagueId,date:string){const week=weekOf(date),rows=profiles.filter(profile=>leagueForProfile(profile)===league).map(profile=>{const own=results.filter(result=>result.profileId===profile.id&&result.league===league&&result.ranked&&weekOf(result.date)===week);return{profileId:profile.id,name:profile.displayName,points:own.reduce((sum,result)=>sum+result.score,0),challenges:own.length,accuracy:own.length?Math.round(own.reduce((sum,result)=>sum+result.dimensions.accuracy,0)/own.length):0,demo:false as const}});return rows.sort((a,b)=>b.points-a.points||b.accuracy-a.accuracy||a.profileId.localeCompare(b.profileId))}
export function streakDays(results:RankedResult[],profileId:string){const dates=[...new Set(results.filter(row=>row.profileId===profileId&&row.ranked).map(row=>row.date))].sort().reverse();let best=0,run=0,current=0,previous='';for(const day of dates){if(!previous||Math.round((Date.parse(previous)-Date.parse(day))/86400000)===1)run++;else{if(!current)current=run;run=1}best=Math.max(best,run);previous=day}return{current:current||run,best}}
export function gameAwards(results:RankedResult[],profileId:string,duel:Duel|null){const own=results.filter(row=>row.profileId===profileId),ranked=own.filter(row=>row.ranked),awards:string[]=[];if(duel?.complete&&(duel.playerA===profileId||duel.playerB===profileId))awards.push('First Duel');if(ranked.some(row=>row.score===100))awards.push('First Perfect Case');if(ranked.some(row=>row.boss))awards.push('Boss Case');if(streakDays(results,profileId).best>=3)awards.push('Three-Day Streak');if(ranked.filter(row=>row.dimensions.riskAwareness===100).length>=3)awards.push('Risk Guardian');if(ranked.filter(row=>row.dimensions.investigation===100).length>=3)awards.push('Document Detective');return awards}
