"use client";
import Link from "next/link";
import { Award, Check, ChevronLeft, ChevronRight, LockKeyhole, Map, ShieldCheck, Sparkles, Star, Zap } from "lucide-react";
import { usePlayer } from "@/components/game/use-player";
import { learningLevels } from "@/data/game";
import { recordGameActivity } from "@/lib/game/progress";
import type { Locale } from "@/types";
export function LearningMap({locale}:{locale:Locale}){const ar=locale==="ar",Arrow=ar?ChevronLeft:ChevronRight,player=usePlayer();const markClassic=()=>recordGameActivity("lesson","classic-account-nature",100,["account-classification","debit-credit"]);return <section className="map-page"><header><span><Map/>{ar?"خريطة اللعبة المحاسبية":"ACCOUNTING GAME MAP"}</span><h1>{ar?"طريقك من الأساسيات إلى الاحتراف":"Your path from foundations to professional mode"}</h1><p>{ar?"كل مستوى يجمع تعلمًا وتطبيقًا ومهمة وتقييمًا. أكمل الأدلة المطلوبة لتفتح المستوى التالي.":"Every level combines learning, practice, a mission, and assessment. Complete evidence to unlock what comes next."}</p></header><div className="map-summary"><span><b>{player.level}</b><small>{ar?"المستوى الحالي":"Current level"}</small></span><span><b>{player.xp}</b><small>XP</small></span><span><b>{player.careerReadiness}%</b><small>{ar?"جاهزية العمل":"Career readiness"}</small></span><span><b>{player.certificates.length}</b><small>{ar?"شهادات":"Certificates"}</small></span></div><div className="map-track">{learningLevels.map(level=>{const locked=level.id>player.level,complete=level.id<player.level,current=level.id===player.level;return <article className={`${locked?"locked":""} ${current?"current":""} ${complete?"complete":""}`} key={level.id}><div className="map-level-node">{complete?<Check/>:locked?<LockKeyhole/>:level.id}</div><div className="map-level-card"><header><div><small>{ar?"المستوى":"LEVEL"} {level.id}</small><h2>{ar?level.titleAr:level.titleEn}</h2><p>{ar?level.descriptionAr:level.descriptionEn}</p></div>{current&&<span><Sparkles/>{ar?"أنت هنا":"YOU ARE HERE"}</span>}</header><div className="map-steps">{level.steps.map((step,index)=>{const activityKind=step.kind==="classic"?"lesson":step.kind,done=Boolean(player.activities[`${activityKind}:${step.id}`]);return <div className={done?"done":""} key={step.id}><span>{done?<Check/>:index+1}</span><div><small>{step.kind==="classic"?(ar?"وحدة كلاسيكية محمية":"PROTECTED CLASSIC MODULE"):step.kind}</small><b>{ar?step.titleAr:step.titleEn}</b></div>{!locked&&<Link href={`/${locale}${step.route}`}>{done?(ar?"راجع":"Review"):(ar?"ابدأ":"Start")}<Arrow/></Link>}{locked&&<LockKeyhole/>}{step.kind==="classic"&&!done&&!locked&&<button onClick={markClassic}>{ar?"تأكيد الإكمال بعد العودة":"Mark complete after return"}</button>}</div>})}</div><footer><span><Award/>{ar?level.rewardAr:level.rewardEn}</span><strong><Zap/> {level.id===8?"PRO":"+ XP"}</strong></footer></div></article>})}</div><aside className="map-rule"><ShieldCheck/><div><h2>{ar?"رحلة واحدة، تقدم واحد":"One journey, one progression"}</h2><p>{ar?"نتائج الدروس والتدريب وMoney Flow والمهام والمحقق والساحة تغذي نفس مستوى اللاعب ومصفوفة المهارات.":"Lessons, practice, Money Flow, Missions, Detective, and Arena all feed the same player level and skill matrix."}</p></div><Star/></aside></section>}

