"use client";
import Link from "next/link";
import { Award, CheckCircle2, LockKeyhole, Medal, ShieldCheck, Sparkles } from "lucide-react";
import { usePlayer } from "@/components/game/use-player";
import { skillLabels } from "@/data/game";
import { masteryBand } from "@/lib/game/engine";
import type { Locale } from "@/types";
export function SkillsDashboard({locale}:{locale:Locale}){const ar=locale==="ar",player=usePlayer();return <section className="skills-page"><header><span><ShieldCheck/>{ar?"مهارات مثبتة بالأداء":"PERFORMANCE-BASED SKILLS"}</span><h1>{ar?"مهاراتك وشهاداتك":"Skills & certificates"}</h1><p>{ar?"لا توجد مهارة وهمية: كل نتيجة هنا مشتقة من دروس أو تدريب أو مهمة أو قضية أو أداء داخل الساحة.":"Nothing is fabricated: every score derives from lessons, practice, missions, cases, or Arena performance."}</p></header><div className="skills-board">{Object.entries(player.skillScores).map(([id,score])=><article key={id}><div><span>{score>=75?<CheckCircle2/>:<Sparkles/>}</span><strong>{score}%</strong></div><h2>{skillLabels[id as keyof typeof skillLabels][ar?"ar":"en"]}</h2><p>{ar?({beginner:"مبتدئ",intermediate:"متوسط",advanced:"متقدم",mastered:"متقن"}[masteryBand(score)]):masteryBand(score)}</p><i><b style={{width:`${score}%`}}/></i></article>)}</div><section className="certificate-road"><header><Award/><div><small>{ar?"شهادات قائمة على متطلبات":"REQUIREMENT-BASED CERTIFICATES"}</small><h2>{ar?"أثبت المهارة قبل إصدار الشهادة":"Prove the skill before the certificate"}</h2></div></header>{[["accounting-foundations",2,60,"أساسيات المحاسبة","Accounting Fundamentals"],["journal-entries",3,70,"القيود اليومية","Journal Entries"],["full-accounting-cycle",8,80,"الدورة المحاسبية الكاملة","Full Accounting Cycle"]].map(([id,level,score,a,e])=>{const earned=player.certificates.includes(String(id));return <article className={earned?"earned":""} key={String(id)}>{earned?<Medal/>:<LockKeyhole/>}<div><b>Debit & Credit — {ar?a:e}</b><small>{ar?`المتطلبات: المستوى ${level} ودرجة المهارة المطلوبة ${score}%`:`Requirements: level ${level} and ${score}% required skill score`}</small></div><span>{earned?(ar?"مكتسبة":"Earned"):(ar?"مقفلة":"Locked")}</span></article>})}<p>{ar?"هذه شهادات مهارة وإكمال داخل المنصة وليست اعتمادًا مهنيًا خارجيًا.":"These are platform skill and completion certificates, not external professional accreditation."}</p></section><Link className="skills-profile-link" href={`/${locale}/profile`}>{ar?"عرض الملف المهني الكامل":"View full professional profile"}</Link></section>}

