"use client";
import Link from "next/link";
import { Award, CheckCircle2, LockKeyhole, Medal, ShieldCheck, Target } from "lucide-react";
import { usePlayer } from "@/components/game/use-player";
import { skillLabels } from "@/data/game";
import { masteryBand } from "@/lib/game/engine";
import type { Locale } from "@/types";
const branches = [
  {ar:"أساس المحاسب",en:"Accounting foundations",skills:["fundamentals","account-classification","debit-credit","transaction-analysis"]},
  {ar:"الدورة المحاسبية",en:"Accounting cycle",skills:["journal-entries","ledger-posting","trial-balance","adjustments","financial-statements"]},
  {ar:"المهارات الاحترافية",en:"Professional mastery",skills:["error-detection","business-cases","accuracy","speed"]},
] as const;
export function SkillsDashboard({locale}:{locale:Locale}){const ar=locale==="ar",player=usePlayer();return <section className="skills-page"><header><span><ShieldCheck/>{ar?"مهارات مثبتة بالأداء":"PERFORMANCE-BASED SKILLS"}</span><h1>{ar?"شجرة مهارات المحاسب":"Accountant skill tree"}</h1><p>{ar?"ابنِ مهاراتك عبر ثلاثة مسارات. حل المهام، اجمع أدلة الأداء، وافتح شاراتك وشهاداتك.":"Build your abilities across three branches. Solve missions, earn skill evidence, and unlock your badges and certificates."}</p></header><div className="skill-tree">{branches.map((branch,index)=><section className="skill-branch" key={branch.en}><header><ShieldCheck/><span><small>{ar?"المسار":"BRANCH"} 0{index+1}</small><h2>{ar?branch.ar:branch.en}</h2></span></header><div className="skills-board">{branch.skills.map(id=>{const score=player.skillScores[id];return <article className={score?"earned":"unearned"} key={id}><div><span>{score>=75?<CheckCircle2/>:<LockKeyhole/>}</span><strong>{score}%</strong></div><h2>{skillLabels[id as keyof typeof skillLabels][ar?"ar":"en"]}</h2><p>{score===0?(ar?"لم تُكتسب بعد":"Not yet earned"):ar?({beginner:"مبتدئ",intermediate:"متوسط",advanced:"متقدم",mastered:"متقن"}[masteryBand(score)]):masteryBand(score)}</p><i><b style={{width:`${score}%`}}/></i><Link href={`/${locale}/${id==="error-detection"?"detective":id==="business-cases"?"missions":"practice"}`}><Target size={15}/>{ar?"تدرب لاكتساب المهارة":"Play to build this skill"}</Link></article>})}</div></section>)}</div><section className="certificate-road"><header><Award/><div><small>{ar?"شهادات قائمة على متطلبات":"REQUIREMENT-BASED CERTIFICATES"}</small><h2>{ar?"أثبت المهارة قبل إصدار الشهادة":"Prove the skill before the certificate"}</h2></div></header>{[["accounting-foundations",2,60,"أساسيات المحاسبة","Accounting Fundamentals"],["journal-entries",3,70,"القيود اليومية","Journal Entries"],["full-accounting-cycle",8,80,"الدورة المحاسبية الكاملة","Full Accounting Cycle"]].map(([id,level,score,a,e])=>{const earned=player.certificates.includes(String(id));return <article className={earned?"earned":""} key={String(id)}>{earned?<Medal/>:<LockKeyhole/>}<div><b>Debit & Credit — {ar?a:e}</b><small>{ar?`المتطلبات: المستوى ${level} ودرجة المهارة المطلوبة ${score}%`:`Requirements: level ${level} and ${score}% required skill score`}</small></div><span>{earned?(ar?"مكتسبة":"Earned"):(ar?"مقفلة":"Locked")}</span></article>})}<p>{ar?"هذه شهادات مهارة وإكمال داخل المنصة وليست اعتمادًا مهنيًا خارجيًا.":"These are platform skill and completion certificates, not external professional accreditation."}</p></section><Link className="skills-profile-link" href={`/${locale}/profile`}>{ar?"عرض الملف المهني الكامل":"View full professional profile"}</Link></section>}
