"use client";
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { FileText, Swords, Trophy, Zap } from 'lucide-react';
import { arcadeDraft,arcadeModes,arcadeQuestions,hideMemory,revealMemory,startArcadeRound,submitArcade,type ArcadeKind } from '@/lib/campaign/arcade';
import { startMission,unlocked } from '@/lib/campaign/director';
import { missions } from '@/lib/campaign/content';
import { useGame } from '@/lib/campaign/store';
import { JournalBuilder } from './journal-builder';
import type { Locale } from '@/types';
export function ArcadePanel({locale}:{locale:Locale}){const {state:s,change}=useGame(),r=s.arcade;const [now,setNow]=useState(0);const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en;useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(id);},[]);useEffect(()=>{if(r&&!r.finished&&now>r.startedAt+arcadeModes[r.kind].seconds*1000)change(st=>submitArcade(st,'timeout',now));},[now,r,change]);const mode=r?arcadeModes[r.kind]:null;const q=r&&!r.finished?arcadeQuestions(r.kind)[r.index]:null;const total=r?arcadeQuestions(r.kind).length:0;const week=Math.floor(now/(7*86400000));const bosses=missions.filter(m=>m.boss&&unlocked(s,m));const boss=bosses.length?bosses[week%bosses.length]:null;return <>
 <div className="scene-heading"><div><p className="eyebrow">ARCADE / {say('10 PLAYABLE MODES','١٠ أنماط لعب')}</p><h1>{say('One break. A sharper accountant.','استراحة قصيرة. محاسب أشطر.')}</h1><p>{say('Personal bests. Real decisions. No pretend global ranking.','أفضل أرقامك. قرارات فعلية. من غير ترتيب عالمي وهمي.')}</p></div><Swords size={42}/></div>
 {(!r||r.finished)&&<div className="arcade-lobby">{(Object.entries(arcadeModes) as [ArcadeKind,typeof arcadeModes.sort][]).map(([kind,m])=><button key={kind} className="arcade-cabinet" onClick={()=>change(st=>startArcadeRound(st,kind,`${kind}:${new Date().toISOString().slice(0,10)}`))}>{kind==='sort'?<FileText/>:<Zap/>}<small>{m.seconds}s · {say('DIFFICULTY','الصعوبة')} {m.difficulty}/3</small><h2>{m.title[locale]}</h2><span>{say('Best','أفضل نتيجة')}: {s.arcadeBest[kind]??0}%</span><b>{say('PLAY →','العب ←')}</b></button>)}<div className="weekly-boss"><Trophy/><div><h2>{say('Weekly boss practice','تدريب مواجهة الأسبوع')}</h2><p>{boss?boss.title[locale]:say('Clear your first desk to unlock boss cases.','خلّص أول مكتب عشان تفتح المواجهات.')}</p>{boss&&<Link className="quiet-button" href={`/${locale}`} onClick={()=>change(st=>startMission(st,boss.id))}>{s.active?say('Resume active shift','كمّل الوردية الحالية'):say('Enter this week’s case','ادخل مواجهة الأسبوع')}</Link>}</div></div></div>}
 {r&&!r.finished&&q&&mode&&<section className="arcade-board"><div className="mission-rail"><span>{mode.title[locale]} · {r.index+1}/{total}</span><span>{Math.max(0,mode.seconds-Math.floor(((now||r.startedAt)-r.startedAt)/1000))}s</span><span>COMBO ×{r.combo}</span></div><div className="flying-document" key={`${r.kind}-${r.index}`}><FileText/><p>{q.prompt[locale]}</p></div>
 {r.kind==='memory'&&!r.memoryReviewed?<div className="memory-board"><p>{say('Flip all three effect cards. Memorize their positions, then hide them and pick the matching effect.','اقلب كروت التأثير الثلاثة. افتكر أماكنهم، خبّيهم، واختار التأثير المطابق.')}</p><div className="decision-options">{q.options?.map(([,label],i)=><button key={i} onClick={()=>change(st=>revealMemory(st,i))}>{r.memoryOpen?.includes(i)?label[locale]:`${say('Card','كارت')} ${i+1}`}</button>)}</div><button disabled={r.memoryOpen?.length!==3} className="play-button" onClick={()=>change(hideMemory)}>{say('Hide & match','خبّي وطابق')}</button></div>:
 q.journal?<div className="arcade-entry"><JournalBuilder locale={locale} draft={r.draft??''} onChange={draft=>change(st=>arcadeDraft(st,draft))}/><button className="play-button" onClick={()=>change(st=>submitArcade(st,r.draft??''))}>{say('Post entry','رحّل القيد')}</button></div>:
 q.options?<div className="decision-options">{q.options.map(([id,label],i)=><button key={id} onClick={()=>change(st=>submitArcade(st,id))}>{r.kind==='memory'?`${say('Card','كارت')} ${i+1}`:label[locale]}</button>)}</div>:<div className="arcade-entry"><label>{say('Difference · EGP','الفرق · جنيه')}<input aria-label={say('Difference','الفرق')} type="number" inputMode="decimal" value={r.draft??''} onChange={e=>change(st=>arcadeDraft(st,e.target.value))}/></label><button className="play-button" onClick={()=>change(st=>submitArcade(st,r.draft??''))}>{say('Verify','تحقق')}</button></div>}
 {r.answers.length>0&&<p role="status">{r.answers.at(-1)?.correct?say('Correct. Keep the combo!','صح. كمّل السلسلة!'):arcadeQuestions(r.kind)[r.index-1]?.feedback[locale]}</p>}</section>}
 {r?.finished&&<section className="arcade-result" role="status"><Trophy/><h2>{Math.round(r.correct/total*100)}%</h2><p>{r.correct}/{total} · {say('Best combo','أفضل سلسلة')}: {r.bestCombo}</p><p>{say('70% earns a daily reward once per mode. All decisions remain in your practice evidence; arcade repetitions do not inflate career readiness.','٧٠٪ تكسبك مكافأة يومية مرة لكل نمط. كل القرارات محفوظة كأدلة تدريب؛ تكرار الساحة مش بيضخم الجاهزية المهنية.')}</p><details><summary>{say('Review this run','راجع الجولة')}</summary>{r.answers.map((a,i)=><p key={i}>{i+1}. {a.correct?'✓':'✕'} {arcadeQuestions(r.kind)[i].feedback[locale]}</p>)}</details></section>}
 </>;}
