"use client";
import Image from 'next/image';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import { AlertTriangle,BadgeCheck,Banknote,BookOpen,BriefcaseBusiness,Building2,Calculator,Check,ChevronRight,CircleDollarSign,ClipboardList,Coins,FileCheck2,FileText,Languages,LockKeyhole,PenLine,Plus,ReceiptText,RotateCcw,Sparkles,Target,Trophy,X,Zap } from 'lucide-react';
import { CinematicChapterIntro } from './cinematic-chapter-intro';
import { firstDayIntro,storyCharacters } from '@/lib/campaign/first-day-story';
import { accountLabel,closeFirstDayDocument,completeFirstDayIntro,DOCUMENT_REWARD,enterFirstDayDesk,FIRST_DAY_INTRO_VERSION,firstDayCompany,firstDayDocuments,firstDayProgress,firstDayReaction,markFirstDayCompletionSeen,selectFirstDayDocument,submitFirstDayDocument,type FirstDayDocument,type FirstDayDocumentId } from '@/lib/campaign/first-day';
import { useGame } from '@/lib/campaign/store';
import type { Account,GameState } from '@/lib/campaign/model';
import type { Locale } from '@/types';

export function FirstDayScreen({locale}:{locale:Locale}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,{state,ready,change}=useGame(),progress=firstDayProgress(state),company=firstDayCompany(state);
 const [active,setActive]=useState<FirstDayDocumentId|null>(null);const restored=useRef(false);
 useEffect(()=>{if(!ready||restored.current)return;restored.current=true;if(progress.selected)setActive(progress.selected);},[ready,progress.selected]);
 if(!ready)return <div className="first-day-loading">{say('Preparing your first day…','بنجهّز أول يوم ليك…')}</div>;
 if(progress.introVersion<FIRST_DAY_INTRO_VERSION)return <CinematicChapterIntro chapter={firstDayIntro} locale={locale} variant="intro" onComplete={()=>change(completeFirstDayIntro)} onSkip={()=>{}}/>;
 if(!progress.deskEntered)return <ManagerBriefing locale={locale} onContinue={()=>change(enterFirstDayDesk)}/>;
 if(progress.rewarded&&!progress.completionSeen&&!active)return <ShiftComplete locale={locale} state={state} onContinue={()=>change(markFirstDayCompletionSeen)}/>;
 const completeCount=progress.completed.length,doc=firstDayDocuments.find(item=>item.id===active),manager=storyCharacters['finance-manager'];
 const openDocument=(id:FirstDayDocumentId)=>{window.dispatchEvent(new CustomEvent('debit-credit-sound-event',{detail:{type:'paper-open',documentId:id}}));change(current=>selectFirstDayDocument(current,id));setActive(id);};
 const closeDocument=()=>{change(closeFirstDayDocument);setActive(null);};
 const submit=(id:FirstDayDocumentId,draft:string,hints:number)=>{let correct=false;change(current=>{const result=submitFirstDayDocument(current,id,draft,Date.now(),hints);correct=result.correct;return result.state;});window.dispatchEvent(new CustomEvent('debit-credit-sound-event',{detail:{type:correct?'correct-answer':'wrong-answer',documentId:id}}));return correct;};
 const stages=[say('Arrival','الوصول'),say('Meet Manager','قابل المدير'),say("Today's Shift",'وردية اليوم'),say('Solve the Problem','حل المشكلة'),say('End of Day','نهاية اليوم')];
 const currentStage=progress.rewarded?4:completeCount>0||active?3:2;
 return <div className="first-day fd-shift-world" dir={ar?'rtl':'ltr'}>
  <header className="fd-game-hud"><Link className="fd-brand" href={`/${locale}`}><span><i/><i/><i/></span><strong>Debit & Credit<sup>™</sup><small>by Money Coder</small></strong></Link><div className="fd-hud-chapter"><small>{say('CURRENT CHAPTER','الفصل الحالي')}</small><b>{say('Chapter 1 · First Day','الفصل ١ · أول يوم')}</b></div><div className="fd-hud-stats"><span><Zap/>{state.xp} XP</span><span><Coins/>{state.coins}</span><span><BriefcaseBusiness/>{say('Trainee','متدرب')}</span><Link href={`/${ar?'en':'ar'}`} aria-label={say('Switch to Arabic','التبديل للإنجليزية')}><Languages/>{ar?'EN':'AR'}</Link></div></header>
  <main className="fd-shift-shell">
   <nav className="fd-story-rail" aria-label={say('Chapter progress','تقدم الفصل')}>{stages.map((label,index)=><span className={index<currentStage?'done':index===currentStage?'current':''} key={label}><i>{index<currentStage?<Check/>:index+1}</i><b>{label}</b></span>)}</nav>
   <section className="fd-current-mission"><div className="fd-manager-portrait"><Image src="/game/first-day-cinematic.png" alt="" fill sizes="110px"/></div><div><small>{manager.name[locale]} · {manager.role[locale]}</small><h1>{completeCount===0?say('Choose where you want to start.','اختار عايز تبدأ منين.'):completeCount<3?say('Good. Choose your next document.','تمام. اختار المستند اللي بعده.'):say('The desk is clear. Let’s close the day.','المكتب خلص. يلا نقفل اليوم.')}</h1><p>{completeCount===0?say('Three documents are waiting on your desk. Inspect one and decide how it belongs in the books.','قدامك ٣ مستندات على المكتب. افحص واحد وقرر مكانه الصح في الدفاتر.'):completeCount<3?say(`${3-completeCount} work items remain. Every decision changes Mizan’s live balances.`,`فاضل ${3-completeCount} مستند. كل قرار بيغيّر أرصدة ميزان مباشرة.`):say('Every accepted entry is saved. Finish the final review when you are ready.','كل قيد معتمد اتحفظ. ابدأ مراجعة نهاية اليوم لما تكون جاهز.')}</p></div><div className="fd-mission-count"><b>{completeCount}/3</b><small>{say('RECORDED','اتسجل')}</small></div></section>
   <div className="fd-play-layout">
    <section className="fd-accounting-desk" aria-label={say("Today's accounting desk",'مكتب محاسبة اليوم')}>
     <div className="fd-desk-heading"><span><ClipboardList/></span><div><small>{say("TODAY'S SHIFT · MIZAN TRADING",'وردية اليوم · ميزان للتجارة')}</small><h2>{say('Three real work items are waiting','٣ مستندات حقيقية في انتظارك')}</h2></div><b>{company.pendingDocuments} {say('pending','معلّق')}</b></div>
     <div className="fd-desk-surface"><span className="fd-desk-note">{say('Check source → classify → record','راجع المصدر ← صنّف ← سجّل')}</span><Calculator className="fd-prop-calculator"/><PenLine className="fd-prop-pen"/><BookOpen className="fd-prop-journal"/>
      <div className={`fd-work-items remaining-${company.pendingDocuments}`}>{firstDayDocuments.filter(item=>!progress.completed.includes(item.id)).map((item,index)=>{const hasError=(progress.mistakes[item.id]??0)>0;return <button className={`fd-work-document ${item.accent} ${hasError?'has-error':''}`} onClick={()=>openDocument(item.id)} key={item.id}><span className="fd-paper-clip"/><header><i>{index+1}</i><span><small>{item.number}</small><b>{item.title[locale]}</b></span>{hasError?<AlertTriangle/>:null}</header><div className="fd-document-body"><strong>{item.party[locale]}</strong><small>{item.date[locale]}</small>{item.details.slice(0,2).map(row=><p key={row.label.en}><span>{row.label[locale]}</span><b>{row.value[locale]}</b></p>)}<hr/><b>{item.amount.toLocaleString(locale)} {say('EGP','جنيه')}</b></div><footer>{hasError?say('Needs correction','محتاج تصحيح'):say('Open document','افتح المستند')}<ChevronRight/></footer></button>;})}</div>
      <div className="fd-document-tray"><FileText/><span>{company.pendingDocuments}</span><small>{say('IN TRAY','في الوارد')}</small></div><div className="fd-processed-tray"><FileCheck2/><span>{completeCount}</span><small>{say('PROCESSED','تمت المعالجة')}</small></div>
     </div>
    </section>
    <aside className="fd-live-company"><header><span><Building2/></span><div><small>{say('LIVE COMPANY STATE','حالة الشركة المباشرة')}</small><h2>Mizan Trading</h2></div><i className={company.ledgerErrors?'warning':'healthy'}>{company.ledgerErrors?say('Review needed','مراجعة مطلوبة'):say('Books healthy','الدفاتر سليمة')}</i></header><div className="fd-live-grid"><LiveMetric icon={<ClipboardList/>} label={say('Pending documents','مستندات معلقة')} value={String(company.pendingDocuments)}/><LiveMetric icon={<FileCheck2/>} label={say('Pending entries','قيود معلقة')} value={String(company.pendingEntries)}/><LiveMetric icon={<Banknote/>} label={say('Cash balance','رصيد الصندوق')} value={money(company.cash,locale)}/><LiveMetric icon={<Building2/>} label={say('Bank balance','رصيد البنك')} value={money(company.bank,locale)}/><LiveMetric icon={<ReceiptText/>} label={say('Supplier balance','رصيد الموردين')} value={money(company.supplierBalance,locale)}/><LiveMetric icon={<CircleDollarSign/>} label={say('Customer balance','رصيد العملاء')} value={money(company.customerBalance,locale)}/></div><div className="fd-month-close"><span><b>{say('Month-end progress','تقدم إقفال الشهر')}</b><small>{company.monthEndProgress}%</small></span><i><b style={{width:`${company.monthEndProgress}%`}}/></i></div>{company.ledgerErrors>0&&<div className="fd-ledger-alert" role="status"><AlertTriangle/><span><b>{company.ledgerErrors} {say('unresolved ledger error','خطأ غير محلول في الدفتر')}</b><small>{money(company.unreconciledAmount,locale)} {say('needs reconciliation','يحتاج مطابقة')}</small></span></div>}<blockquote>“{say('I only approve entries that explain what changed.','باعتمد بس القيد اللي يشرح إيه اللي اتغيّر.')}”<small>{manager.name[locale]}</small></blockquote></aside>
   </div>
   <section className="fd-quiet-progress"><span><Sparkles/><b>{say('Skill earned by playing','مهارة مكتسبة باللعب')}</b><small>{say(`Journal Entries +${completeCount*4}`,`القيود اليومية +${completeCount*4}`)}</small></span><span><Target/><b>{say('Current mission','المهمة الحالية')}</b><small>{say(`${company.pendingEntries} entries left`,`${company.pendingEntries} قيود متبقية`)}</small></span><span><Trophy/><b>{say('Shift reward','مكافأة الوردية')}</b><small>+300 XP · +150 {say('Coins','عملة')}</small></span></section>
   {progress.completionSeen&&<section className="fd-chapter-teaser"><div><small>{say('NEXT · LOCKED','التالي · مقفول')}</small><h2>{say('Chapter 2 — THE MISSING MONEY','الفصل ٢ — المال المفقود')}</h2><p>{say('One number will not match. Find the missing money.','رقم واحد مش هيتطابق. اكتشف أين اختفى المال.')}</p></div><LockKeyhole/><span>{say('Awaiting your review. Chapter 2 is not implemented.','في انتظار مراجعتك. الفصل ٢ لم يتم تنفيذه.')}</span></section>}
  </main>
  {doc&&<DocumentInteraction key={doc.id} locale={locale} doc={doc} completed={progress.completed.includes(doc.id)} onClose={closeDocument} onSubmit={(draft,hints)=>submit(doc.id,draft,hints)}/>}
 </div>;
}

function ManagerBriefing({locale,onContinue}:{locale:Locale;onContinue:()=>void}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,manager=storyCharacters['finance-manager'];
 return <section className="fd-manager-scene" dir={ar?'rtl':'ltr'}><Image src="/game/first-day-cinematic.png" fill priority sizes="100vw" alt=""/><div className="fd-manager-scene-shade"/><div className="fd-briefing-card"><header><b>OK</b><span><strong>{manager.name[locale]}</strong><small>{manager.role[locale]}</small></span></header><h1>{say('Welcome to Mizan Trading.','أهلًا بيك في ميزان للتجارة.')}</h1><p>{say('Today is your first day. Three transactions from yesterday still need to be recorded. Inspect each source, decide what changed, and keep the books balanced.','النهارده أول يوم ليك. عندنا ٣ معاملات من امبارح لسه محتاجة تتسجل. افحص كل مستند، قرر إيه اللي اتغيّر، وخلي الدفاتر متوازنة.')}</p><button onClick={onContinue}>{say('SHOW ME THE DESK','ورّيني المكتب')}<ChevronRight/></button></div><div className="fd-briefing-caption"><small>{say('8:45 AM · FINANCE OFFICE','٨:٤٥ صباحًا · الإدارة المالية')}</small><b>{say('Your decisions change the company.','قراراتك تغيّر حالة الشركة.')}</b></div></section>;
}

function ShiftComplete({locale,state,onContinue}:{locale:Locale;state:GameState;onContinue:()=>void}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,attempts=state.evidence.filter(item=>item.missionId==='first-day'),correct=attempts.filter(item=>item.correct).length,hints=attempts.reduce((sum,item)=>sum+item.hintsUsed,0),accuracy=attempts.length?Math.round(correct/attempts.length*100):100;
 return <section className="fd-shift-complete" dir={ar?'rtl':'ltr'}><Image src="/game/first-day-cinematic.png" fill priority sizes="100vw" alt=""/><div className="fd-complete-shade"/><div className="fd-complete-card" role="status"><span className="fd-complete-trophy"><Trophy/></span><small>{say('SHIFT COMPLETE · CHAPTER 1','اكتملت الوردية · الفصل ١')}</small><h1>{say('The books are balanced.','الدفاتر اتزنت.')}</h1><p>“{say('Good work. You did not just answer questions—you completed a real accounting shift.','شغل كويس. إنت ما جاوبتش أسئلة وبس—إنت خلّصت وردية محاسبية حقيقية.')}”</p><div className="fd-shift-results"><span><b>{accuracy}%</b><small>{say('Accuracy','الدقة')}</small></span><span><b>{attempts.length}</b><small>{say('Attempts','المحاولات')}</small></span><span><b>{hints}</b><small>{say('Hints','التلميحات')}</small></span></div><div className="fd-shift-reward"><Zap/>+300 XP <Coins/>+150 {say('Coins','عملة')}</div><div className="fd-next-case"><LockKeyhole/><span><small>{say('CHAPTER 2 · LOCKED','الفصل ٢ · مقفول')}</small><b>{say('THE MISSING MONEY','المال المفقود')}</b><p>{say('One number will not match. Find out why.','رقم واحد مش هيتطابق. اكتشف السبب.')}</p></span></div><button onClick={onContinue}>{say('CONTINUE STORY','واصل القصة')}<ChevronRight/></button></div></section>;
}

function money(value:number,locale:Locale){return `${value.toLocaleString(locale)} EGP`;}
function LiveMetric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="fd-live-metric"><span>{icon}</span><small>{label}</small><b>{value}</b></div>;}

type DeskLine={account:Account|'';side:'debit'|'credit'|'';amount:number};
const tokenAccounts:Account[]=['cash','bank','equipment','customers','suppliers','officeExpense','capital','revenue'];
function toDraft(lines:DeskLine[]):string{return JSON.stringify(lines.map(line=>({account:line.account,debit:line.side==='debit'?line.amount:0,credit:line.side==='credit'?line.amount:0})));}

function DocumentInteraction({locale,doc,completed,onClose,onSubmit}:{locale:Locale;doc:FirstDayDocument;completed:boolean;onClose:()=>void;onSubmit:(draft:string,hints:number)=>boolean}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,[phase,setPhase]=useState<'inspect'|'record'|'result'>(completed?'result':'inspect'),[lines,setLines]=useState<DeskLine[]>([{account:'',side:'',amount:0}]),[activeLine,setActiveLine]=useState(0),[outcome,setOutcome]=useState<'correct'|'wrong'|null>(completed?'correct':null),[hint,setHint]=useState(false),[wasCompleted]=useState(completed);const dialogRef=useRef<HTMLElement>(null),reaction=firstDayReaction(doc.id,outcome==='correct',locale);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialogRef.current?.querySelector<HTMLElement>('button')?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
 const update=(index:number,patch:Partial<DeskLine>)=>setLines(current=>current.map((line,lineIndex)=>lineIndex===index?{...line,...patch}:line));
 const submit=()=>{const correct=onSubmit(toDraft(lines),hint?1:0);setOutcome(correct?'correct':'wrong');if(correct)setPhase('result');};
 return <div className="fd-modal-backdrop"><section ref={dialogRef} className={`fd-workbench-modal ${outcome??''}`} role="dialog" aria-modal="true" aria-label={doc.title[locale]}><button className="fd-close" onClick={onClose} aria-label={say('Close','إغلاق')}><X/></button><header className="fd-workbench-head"><span className={doc.accent}><FileText/></span><div><small>{doc.number} · {doc.date[locale]}</small><h2>{doc.title[locale]}</h2><p>{doc.subtitle[locale]}</p></div><div className="fd-workflow-steps"><span className={phase==='inspect'?'current':'done'}>1 {say('Inspect','افحص')}</span><span className={phase==='record'?'current':phase==='result'?'done':''}>2 {say('Build entry','ركّب القيد')}</span><span className={phase==='result'?'current':''}>3 {say('Consequence','النتيجة')}</span></div></header>
  {phase==='inspect'&&<div className="fd-inspection-stage"><div className="fd-full-document"><header><b>{doc.party[locale]}</b><span>{doc.number}</span></header><small>{doc.subtitle[locale]}</small>{doc.details.map(row=><p key={row.label.en}><span>{row.label[locale]}</span><strong>{row.value[locale]}</strong></p>)}<footer><span>{say('TOTAL','الإجمالي')}</span><b>{doc.amount.toLocaleString(locale)} {say('EGP','جنيه')}</b></footer></div><aside><small>{say('DOCUMENT DECISION','قرار المستند')}</small><h3>{say('What should you do with this document?','تعمل إيه بالمستند ده؟')}</h3><p>{say('Inspect the source, purpose, amount, and payment method before you touch the journal.','راجع المصدر والغرض والمبلغ وطريقة السداد قبل ما تبدأ القيد.')}</p><button onClick={()=>setPhase('record')}><PenLine/>{say('Record transaction','سجّل العملية')}</button><Link href={`/${locale}/account-guide?return=first-day&document=${doc.id}`} target="_blank" rel="noreferrer"><BookOpen/>{say('Open Accounting Manual','افتح دليل الحسابات')}</Link><button className="secondary" onClick={()=>setHint(true)}><Sparkles/>{say('Ask Mr. Kareem for a hint','اسأل أ/ كريم عن تلميح')}</button>{hint&&<div className="fd-manager-hint"><b>OK</b><span>{doc.id==='supplier-invoice'?say('Ask: what did the company receive, and what does it owe?','اسأل نفسك: الشركة استلمت إيه وبقى عليها إيه؟'):doc.id==='customer-receipt'?say('No new revenue was earned. This settles an old customer balance.','مفيش إيراد جديد. ده تحصيل لرصيد عميل قديم.'):say('The office used something and paid cash immediately.','المكتب استهلك حاجة ودفع نقدًا فورًا.')}</span></div>}</aside></div>}
  {phase==='record'&&<div className="fd-journal-game"><div className="fd-journal-instruction"><span><PenLine/></span><div><small>{say('ACCOUNTING PUZZLE','لغز محاسبي')}</small><h3>{say('Place the accounts on the correct side','حط الحسابات في الطرف الصح')}</h3><p>{say('Select an entry line, choose an account token, then place its amount in Debit or Credit.','اختار سطر القيد، وبعدها قطعة الحساب، وحدد مدين أو دائن واكتب المبلغ.')}</p></div></div><div className="fd-account-tokens" aria-label={say('Available accounts','الحسابات المتاحة')}>{tokenAccounts.map(account=><button className={lines[activeLine]?.account===account?'selected':''} onClick={()=>update(activeLine,{account})} key={account}><span>{accountLabel(account,locale).slice(0,1)}</span>{accountLabel(account,locale)}</button>)}</div><div className="fd-entry-board"><header><b>{say('JOURNAL ENTRY','القيد اليومي')}</b><span>{say('Debit must equal credit','المدين لازم يساوي الدائن')}</span></header>{lines.map((line,index)=><article className={activeLine===index?'active':''} onClick={()=>setActiveLine(index)} key={index}><button className="fd-line-account" onClick={()=>setActiveLine(index)}>{line.account?accountLabel(line.account,locale):say('Choose account token','اختار قطعة الحساب')}</button><div className="fd-side-choice"><button className={line.side==='debit'?'selected':''} onClick={()=>update(index,{side:'debit'})}>{say('DEBIT','مدين')}</button><button className={line.side==='credit'?'selected':''} onClick={()=>update(index,{side:'credit'})}>{say('CREDIT','دائن')}</button></div><label><span>EGP</span><input aria-label={`${say('Amount line','مبلغ السطر')} ${index+1}`} type="number" inputMode="decimal" min="0" value={line.amount||''} onChange={event=>update(index,{amount:Number(event.target.value)})} placeholder={say('Enter amount','اكتب المبلغ')}/></label></article>)}{lines.length<2&&<button className="fd-add-line" onClick={()=>{setLines(current=>[...current,{account:'',side:'',amount:0}]);setActiveLine(1);}}><Plus/>{say('Add second line','أضف السطر الثاني')}</button>}<JournalTotals locale={locale} lines={lines}/></div>{outcome==='wrong'&&<div className="fd-story-consequence" role="alert"><AlertTriangle/><div><small>{say('COMPANY CONSEQUENCE','أثر الخطأ على الشركة')}</small><h3>{reaction.impact}</h3><p>“{reaction.message}”</p><b>{storyCharacters['finance-manager'].name[locale]}</b></div></div>}<div className="fd-workbench-actions"><button onClick={submit}><FileCheck2/>{say('Submit entry','اعتمد القيد')}</button><button className="secondary" onClick={()=>setPhase('inspect')}><RotateCcw/>{say('Recheck document','راجع المستند')}</button></div></div>}
  {phase==='result'&&<div className="fd-entry-success" role="status"><span><BadgeCheck/></span><small>{say('ENTRY BALANCED','القيد متوازن')}</small><h3>{say('Document recorded in Mizan’s books','المستند اتسجل في دفاتر ميزان')}</h3><div>{doc.expected.map(line=><p key={line.account}><b>{accountLabel(line.account,locale)}</b><span>{(line.debit||line.credit).toLocaleString(locale)} {line.debit?say('Debit','مدين'):say('Credit','دائن')}</span></p>)}</div><CompanyImpact doc={doc} locale={locale}/><ul><li><Check/>{say('Entry balanced','القيد متوازن')}</li><li><Check/>{say('Document leaves the active desk','المستند خرج من المكتب النشط')}</li><li><Check/>{reaction.message}</li></ul>{!wasCompleted&&<p className="fd-reward-pop"><Zap/>+{DOCUMENT_REWARD.xp} XP <Coins/>+{DOCUMENT_REWARD.coins}</p>}<div className="fd-manager-result"><b>OK</b><p>“{reaction.message}”</p></div><button onClick={onClose}>{say('Return to desk','ارجع للمكتب')}<ChevronRight/></button></div>}
 </section></div>;
}

function JournalTotals({locale,lines}:{locale:Locale;lines:DeskLine[]}){const ar=locale==='ar',debit=lines.filter(line=>line.side==='debit').reduce((sum,line)=>sum+line.amount,0),credit=lines.filter(line=>line.side==='credit').reduce((sum,line)=>sum+line.amount,0),balanced=debit>0&&debit===credit;return <footer className={balanced?'balanced':''}><span>{ar?'إجمالي المدين':'Total debit'}<b>{debit.toLocaleString(locale)}</b></span><span>{ar?'إجمالي الدائن':'Total credit'}<b>{credit.toLocaleString(locale)}</b></span><strong>{balanced?<><Check/>{ar?'متوازن':'Balanced'}</>:<>{ar?'الفرق':'Difference'}: {Math.abs(debit-credit).toLocaleString(locale)}</>}</strong></footer>;}

function CompanyImpact({doc,locale}:{doc:FirstDayDocument;locale:Locale}){const ar=locale==='ar',rows=doc.id==='supplier-invoice'?[[ar?'المعدات':'Equipment',1250000,1350000],[ar?'الموردون':'Suppliers',730000,830000]]:doc.id==='customer-receipt'?[[ar?'البنك':'Bank',480000,555000],[ar?'العملاء':'Customers',320000,245000]]:[[ar?'الصندوق':'Cash',250000,247500],[ar?'صافي الربح':'Net profit',85000,82500]];return <section className="fd-company-impact"><small>{ar?'أثر حقيقي على الشركة':'REAL COMPANY IMPACT'}</small>{rows.map(([label,before,after])=><p key={String(label)}><b>{label}</b><span>{Number(before).toLocaleString(locale)} → <strong>{Number(after).toLocaleString(locale)} EGP</strong></span></p>)}</section>;}
