'use client';

import Link from 'next/link';
import {ArrowLeft,ArrowRight,BookOpen,BriefcaseBusiness,Building2,Calculator,Check,ChevronRight,ClipboardCheck,Coins,FileCheck2,FileText,GraduationCap,LibraryBig,LockKeyhole,ShieldCheck,Sparkles,Trophy,Zap} from 'lucide-react';
import {firstDayDocuments,type FirstDayDocumentId} from '@/lib/campaign/first-day';
import {firstShiftMissionProgress} from '@/lib/campaign/first-shift-hub';
import type {GameState} from '@/lib/campaign/model';
import type {Locale} from '@/types';
import {SimulationSound} from './simulation-sound';

type Props={locale:Locale;state:GameState;inactive:boolean;pendingDocuments:number;ledgerErrors:number;processedAnimation:FirstDayDocumentId|null;onOpenCase:(id:FirstDayDocumentId)=>void;onOpenJournal:()=>void;onOpenLedger:()=>void;onOpenCalculator:()=>void};
type Portal={id:string;number:number;title:{ar:string;en:string};description:{ar:string;en:string};tone:string;icon:typeof FileText;done:boolean;locked:boolean;onOpen:()=>void};

export function FirstShiftMissionHub({locale,state,inactive,pendingDocuments,ledgerErrors,processedAnimation,onOpenCase,onOpenJournal,onOpenLedger,onOpenCalculator}:Props){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,Arrow=ar?ArrowLeft:ArrowRight,mission=firstShiftMissionProgress(state),firstPending=firstDayDocuments.find(item=>!mission.cases.find(entry=>entry.id===item.id)?.done),journalCount=state.journal.filter(entry=>entry.id.startsWith('first-day/')).length;
 const portals:Portal[]=[
  ...firstDayDocuments.map((item,index)=>({id:item.id,number:index+1,title:item.title,description:{ar:["راجع الفاتورة والمستندات قبل إثبات الالتزام.","طابق التحصيل مع مستند العميل والبنك.","تحقق من سند الصرف وفترة المصروف."][index],en:['Review invoice support before posting the liability.','Match the receipt to customer and bank evidence.','Check the voucher and expense period.'][index]},tone:['blue','teal','amber'][index],icon:index===0?FileText:index===1?Coins:ClipboardCheck,done:mission.cases[index].done,locked:false,onOpen:()=>onOpenCase(item.id)})),
  {id:'journal',number:4,title:{ar:'دفتر اليومية',en:'Journal'},description:{ar:'راجع القيود التي سجّلتها خلال الوردية.',en:'Review the entries you posted during the shift.'},tone:'violet',icon:BookOpen,done:mission.journalComplete,locked:false,onOpen:onOpenJournal},
  {id:'ledger',number:5,title:{ar:'دفتر الأستاذ',en:'Ledger'},description:{ar:'تتبّع أثر القيود داخل حسابات الشركة.',en:'Trace the entries through company accounts.'},tone:'gold',icon:LibraryBig,done:mission.ledgerComplete,locked:journalCount===0,onOpen:onOpenLedger},
 ];
 const start=()=>firstPending?onOpenCase(firstPending.id):!mission.journalComplete?onOpenJournal:onOpenLedger();
 return <section className="shift-home fsh-shell" dir={ar?'rtl':'ltr'} inert={inactive}>
  <header className="fsh-topbar"><Link href={`/${locale}`} className="fsh-brand"><span aria-hidden="true" className="fsh-brand-mark">▂▅▇</span><span>Debit &amp; Credit<small>by Money Coder</small></span></Link><nav aria-label={say('First Shift navigation','تنقل أول وردية')}><span className="active"><BriefcaseBusiness/>{say('First Shift','أول وردية')}</span><Link href={`/${locale}/account-guide?return=first-day`}><BookOpen/>{say('Account guide','دليل الحسابات')}</Link><Link href={`/${locale}/career-league/map`}><GraduationCap/>{say('Career map','المسار المهني')}</Link></nav><div className="fsh-top-actions"><span className="fsh-xp"><Zap/>{state.xp} XP</span><SimulationSound locale={locale}/><Link href={`/${ar?'en':'ar'}`} aria-label={say('Switch to Arabic','التبديل للإنجليزية')}>{ar?'EN':'AR'}</Link></div></header>
  <main className="fsh-content"><div className="fsh-world"><section className="fsh-hero" aria-labelledby="fsh-title"><div className="fsh-hero-copy"><span className="fsh-eyebrow"><Sparkles/>{say('A real journey through accounting','رحلة عملية في عالم المحاسبة')}</span><h1 id="fsh-title">{say('Your first shift.','أول وردية لك')}</h1><p>{say('Learn · investigate · post · grow in your role.','تعلّم · افحص · قيّد · وتقدّم في مستواك')}</p><button className="fsh-start" onClick={start}><span>{firstPending?say('Start the next case','ابدأ المهمة التالية'):mission.journalComplete?say('Open the ledger','افتح دفتر الأستاذ'):say('Review the journal','راجع دفتر اليومية')}</span><Arrow/></button></div><div className="fsh-hero-side"><div className="fsh-company"><span><Building2/></span><div><b>Mizan Trading</b><small>{say('Accounting department','مكتب الحسابات')}</small></div></div><MissionProgressPanel locale={locale} level={mission.level} completed={mission.completedCount} total={mission.total}/><div className="fsh-books-health"><ShieldCheck/><span>{ledgerErrors?say('Review required before closing','الدفاتر تحتاج مراجعة قبل الإقفال'):say('Accepted books are protected','القيود المقبولة محمية')}</span></div></div><div className="fsh-skyline" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></section>
  <section className="fsh-journey" aria-labelledby="fsh-journey-title"><div className="fsh-section-heading"><div><small>{say('YOUR ACCOUNTING JOURNEY','رحلتك داخل مكتب الحسابات')}</small><h2 id="fsh-journey-title">{say('Five clear stops. One real first shift.','خمس محطات واضحة. وردية حقيقية واحدة.')}</h2></div><span>{say('Choose a file to begin','اختر ملفًا لتبدأ')} <Arrow/></span></div><div className="fsh-portal-grid">{portals.map(portal=><MissionPortalCard key={portal.id} locale={locale} portal={portal}/>)}</div></section>
  <div className="fsh-info-grid"><section className="fsh-os" role="region" aria-label={say('Mizan accounting system','نظام ميزان المحاسبي')}><div className="fsh-panel-title"><span><Building2/></span><div><small>MIZAN TRADING</small><h2>Mizan OS</h2></div><b>{pendingDocuments} {say('files in inbox','ملفات في الوارد')}</b></div><ul>{portals.map(portal=><li key={portal.id}><span className={portal.done?'done':''}>{portal.done?<Check/>:portal.locked?<LockKeyhole/>:null}</span><b>{portal.title[locale]}</b><em>{portal.done?'1/1':'0/1'}</em></li>)}</ul><p className="fsh-processed-tray">{say('PROCESSED TRAY','درج تمت المعالجة')} <b>{mission.cases.filter(item=>item.done).length}</b></p></section><MissionRewardsPanel locale={locale} state={state}/></div>
  <MissionHowItWorks locale={locale}/><footer className="fsh-footer"><span><ShieldCheck/>{say('Local-first simulation. Your accepted journal remains safe.','محاكاة محلية. اليومية المقبولة تظل آمنة.')}</span><div><button onClick={onOpenCalculator} aria-label={say('Open calculator','افتح الآلة الحاسبة')}><Calculator/>{say('Calculator','الآلة الحاسبة')}</button><Link href={`/${locale}/game/bank-reconciliation`}>{say('Next workpaper: Bank Reconciliation','ملف عمل لاحق: التسوية البنكية')}<ChevronRight/></Link></div></footer></div></main>
  {processedAnimation&&<div className="fsh-filed-toast" role="status"><FileCheck2/>{say('File posted and moved to processed work','تم تسجيل الملف ونقله للمعالجة')}</div>}
  {state.storageWarning&&<p className="fsh-storage-warning" role="alert">{say('Storage unavailable. Keep this tab open to retain progress.','التخزين غير متاح. اترك الصفحة مفتوحة للحفاظ على تقدمك.')}</p>}
 </section>;
}

function MissionPortalCard({locale,portal}:{locale:Locale;portal:Portal}){const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,Icon=portal.icon,Arrow=ar?ArrowLeft:ArrowRight;return <article className={`fsh-portal tone-${portal.tone} ${portal.done?'is-done':''} ${portal.locked?'is-locked':''}`}><div className="fsh-portal-top"><span className="fsh-portal-index">{portal.number.toString().padStart(2,'0')}</span><span className="fsh-portal-status">{portal.done?<><Check/>{say('Completed','مكتملة')}</>:portal.locked?<><LockKeyhole/>{say('Locked','مقفلة')}</>:say('Available','متاحة')}</span></div><h3>{portal.title[locale]}</h3><div className="fsh-portal-art" aria-hidden="true"><div className="fsh-portal-arch"><span className="fsh-portal-document"><span className="fsh-document-heading"><Icon/><b>{portal.title[locale]}</b></span><span className="fsh-document-line"/><span className="fsh-document-line"/><span className="fsh-document-line"/><span className="fsh-document-stamp"><Check/></span></span></div><span className="fsh-portal-pedestal"/></div><p>{portal.description[locale]}</p><button onClick={portal.onOpen} disabled={portal.locked} aria-label={`${portal.title[locale]} · ${portal.done?say('Review','راجع'):portal.locked?say('Locked','مقفلة'):say('Open document','افتح المستند')}`}><span>{portal.done?say('Review','راجع'):portal.locked?say('After the first entry','بعد أول قيد'):say('Start mission','ابدأ المهمة')}</span><Arrow/></button></article>}

function MissionProgressPanel({locale,level,completed,total}:{locale:Locale;level:number;completed:number;total:number}){const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en;return <section className="fsh-progress" aria-label={say('Shift progress','تقدم الوردية')}><div><span>{say('Level','المستوى')} <b>{level}</b></span><strong>{completed}/{total} {say('stops complete','محطات مكتملة')}</strong></div><div className="fsh-progress-track" role="progressbar" aria-label={say('Shift progress','تقدم الوردية')} aria-valuemin={0} aria-valuemax={total} aria-valuenow={completed}><i style={{width:`${completed/total*100}%`}}/></div><small>{say('Progress comes from completed work, not just opening a screen.','التقدم يعتمد على العمل المكتمل، وليس مجرد فتح الشاشة.')}</small></section>}

function MissionRewardsPanel({locale,state}:{locale:Locale;state:GameState}){const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en;const rewards=[{icon:Zap,title:say('Game XP','نقاط XP'),detail:say(`${state.xp} earned so far`,`${state.xp} مكتسبة حتى الآن`)},{icon:BriefcaseBusiness,title:say('Practical experience','خبرة عملية'),detail:say('Source-driven casework','حالات مبنية على مستندات')},{icon:GraduationCap,title:say('Accounting skills','مهارات محاسبية'),detail:say('Evidence follows case quality','الدليل يتبع جودة العمل')},{icon:Trophy,title:say('Journal mastery','إتقان القيود'),detail:say('Protected accepted entries','قيود مقبولة محمية')}];return <section className="fsh-rewards"><div className="fsh-panel-title"><span><Trophy/></span><div><small>{say('WHAT YOU GAIN','ثمرة هذه الرحلة')}</small><h2>{say('Your journey rewards','مكافآتك في هذه الرحلة')}</h2></div></div><div className="fsh-reward-grid">{rewards.map(item=>{const Icon=item.icon;return <article key={item.title}><span><Icon/></span><div><b>{item.title}</b><small>{item.detail}</small></div></article>})}</div><p>{say('Professional evidence is separate from game points and remains unverified local practice.','الدليل المهني منفصل عن نقاط اللعب، ويظل ممارسة محلية غير موثقة خارجيًا.')}</p></section>}

function MissionHowItWorks({locale}:{locale:Locale}){const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en;const steps=[{title:say('Understand the case','افهم الحالة'),description:say('Read the business context.','اقرأ السيناريو التجاري.'),icon:FileText},{title:say('Inspect the source','افحص المستند'),description:say('Check invoice and support.','راجع الفاتورة والسند.'),icon:ClipboardCheck},{title:say('Choose the treatment','اختر المعالجة'),description:say('Decide accounts and sides.','حدد الحسابات والاتجاه.'),icon:BriefcaseBusiness},{title:say('Post in the journal','قيّد في اليومية'),description:say('Record a balanced entry.','سجّل قيدًا متوازنًا.'),icon:BookOpen},{title:say('See your progress','حقّق التقدم'),description:say('Review impact and evidence.','راجع الأثر والدليل.'),icon:Trophy}];return <section className="fsh-how" aria-labelledby="fsh-how-title"><div className="fsh-section-heading"><div><small>{say('HOW THE SHIFT WORKS','طريقة اللعب')}</small><h2 id="fsh-how-title">{say('From your first file to a protected ledger','من أول ملف إلى دفتر آمن')}</h2></div></div><ol>{steps.map((item,index)=>{const Icon=item.icon;return <li key={item.title}><span className="fsh-how-number">{index+1}</span><Icon/><div><b>{item.title}</b><small>{item.description}</small></div></li>})}</ol></section>}
