"use client";
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {AlertTriangle,BadgeCheck,BookOpen,Check,ChevronRight,ClipboardCheck,Coins,FileCheck2,FileSearch,FileText,PenLine,Plus,RotateCcw,Sparkles,X,Zap} from 'lucide-react';
import {accountLabel,DOCUMENT_REWARD,firstDayReaction,type FirstDayDocument} from '@/lib/campaign/first-day';
import {storyCharacters} from '@/lib/campaign/first-day-story';
import type{Account}from'@/lib/campaign/model';
import type{AccountingCaseAction,AccountingCaseDefinition,AccountingCaseRuntime,CaseActionResult,CasePerformance}from'@/lib/cases/model';
import type{Locale}from'@/types';

type DeskLine={account:Account|'';side:'debit'|'credit'|'';amount:number};
const tokenAccounts:Account[]=['cash','bank','equipment','customers','suppliers','officeExpense','capital','revenue'];
const toDraft=(lines:DeskLine[])=>JSON.stringify(lines.map(line=>({account:line.account,debit:line.side==='debit'?line.amount:0,credit:line.side==='credit'?line.amount:0})));
function restoreDraft(draft?:string):DeskLine[]|null{if(!draft)return null;try{const rows=JSON.parse(draft)as unknown;if(!Array.isArray(rows)||!rows.length||rows.length>2)return null;const lines=rows.map(row=>{if(!row||typeof row!=='object')throw new Error('Invalid draft');const value=row as Partial<DeskLine>,account=typeof value.account==='string'&&(tokenAccounts as readonly string[]).includes(value.account)?value.account as Account:'';return{account,side:value.side==='debit'||value.side==='credit'?value.side:'',amount:Number.isFinite(value.amount)?Math.max(0,Number(value.amount)):0}satisfies DeskLine});return lines.some(line=>line.account||line.side||line.amount)?lines:null}catch{return null}}

export function FirstDayCaseWorkbench({locale,doc,caseDefinition,runtime,performance,completed,initialDraft,initialHint,pendingAfter,onClose,onDraftChange,onInspect,onAction,onHelp,onSubmit}:{locale:Locale;doc:FirstDayDocument;caseDefinition:AccountingCaseDefinition;runtime:AccountingCaseRuntime;performance:CasePerformance;completed:boolean;initialDraft?:string;initialHint?:boolean;pendingAfter:number;onClose:()=>void;onDraftChange:(draft:string,hintUsed:boolean)=>void;onInspect:(documentId:string)=>void;onAction:(action:AccountingCaseAction)=>CaseActionResult;onHelp:()=>number;onSubmit:(draft:string,hints:number)=>boolean}){
 const restored=restoreDraft(initialDraft),ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,[phase,setPhase]=useState<'inspect'|'decision'|'record'|'result'>(completed?'result':restored?'record':'inspect'),[lines,setLines]=useState<DeskLine[]>(restored??[{account:'',side:'',amount:0}]),[activeLine,setActiveLine]=useState(0),[outcome,setOutcome]=useState<'correct'|'wrong'|null>(completed?'correct':null),[helpLevel,setHelpLevel]=useState(Math.max(runtime.managerHelpCount,initialHint?1:0)),[selectedEvidence,setSelectedEvidence]=useState(caseDefinition.primaryDocumentId),[decisionMessage,setDecisionMessage]=useState(''),[submitting,setSubmitting]=useState(false),[wasCompleted]=useState(completed);const dialogRef=useRef<HTMLElement>(null),submittingRef=useRef(false),reaction=firstDayReaction(doc.id,outcome==='correct',locale),inspected=new Set(runtime.inspectedDocumentIds),required=caseDefinition.documents.filter(item=>item.required),inspectedCount=required.filter(item=>inspected.has(item.id)).length,evidence=caseDefinition.documents.find(item=>item.id===selectedEvidence)??caseDefinition.documents[0];
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialogRef.current?.querySelector<HTMLElement>('button')?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();if(event.key==='Tab'&&dialogRef.current){const items=Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button,a,input,select')).filter(item=>!item.hasAttribute('disabled'));const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[onClose]);
 const update=(index:number,patch:Partial<DeskLine>)=>{const next=lines.map((line,i)=>i===index?{...line,...patch}:line);setLines(next);onDraftChange(JSON.stringify(next),helpLevel>0)};
 const addLine=()=>{const next=[...lines,{account:'',side:'',amount:0}as DeskLine];setLines(next);onDraftChange(JSON.stringify(next),helpLevel>0)};
 const inspectDocument=(id:string)=>{setSelectedEvidence(id);onInspect(id)};
 const askKareem=()=>{const level=onHelp();setHelpLevel(level);onDraftChange(JSON.stringify(lines),true)};
 const chooseAction=(action:AccountingCaseAction)=>{const result=onAction(action),actionLabel=caseDefinition.actions.find(item=>item.id===action)?.label[locale]??action;if(result.readyToPost){setDecisionMessage('');setPhase('record');return}if(action==='post')setDecisionMessage(say(`The file is missing ${result.missingDocumentIds.length} required review item(s). Open them before posting.`,`الملف لسه ناقص مراجعة ${result.missingDocumentIds.length} مستند مؤيد. افتحهم قبل الترحيل.`));else setDecisionMessage(say(`${actionLabel} recorded. The ledger remains unchanged while you continue the review.`,`تم تسجيل قرار «${actionLabel}». الدفتر لم يتغير ويمكنك استكمال المراجعة.`))};
 const submit=()=>{if(submittingRef.current)return;submittingRef.current=true;setSubmitting(true);const correct=onSubmit(toDraft(lines),helpLevel);setOutcome(correct?'correct':'wrong');if(correct)setPhase('result');window.setTimeout(()=>{submittingRef.current=false;setSubmitting(false)},0)};
 const steps:[string,string][]=[['Case file','ملف الحالة'],['Decision','القرار'],['Post','الترحيل'],['Impact','الأثر']];
 return <div className="fd-modal-backdrop"><section ref={dialogRef} className={`fd-workbench-modal fd-case-workbench ${outcome??''}`} role="dialog" aria-modal="true" aria-label={doc.title[locale]}><button className="fd-close" onClick={onClose} aria-label={say('Close','إغلاق')}><X/></button>
  <header className="fd-workbench-head"><span className={doc.accent}><FileText/></span><div><small>{caseDefinition.accountingReference} · {doc.date[locale]}</small><h2>{caseDefinition.title[locale]}</h2><p>{caseDefinition.businessContext[locale]}</p></div><div className="fd-workflow-steps">{steps.map(([en,a],index)=>{const names=['inspect','decision','record','result'],current=names.indexOf(phase),done=index<current;return <span className={index===current?'current':done?'done':''} key={en}>{done?<Check/>:index+1} {say(en,a)}</span>})}</div></header>
  <Link className="fd-workbench-manual" href={`/${locale}/account-guide?return=first-day&document=${doc.id}`} target="_blank" rel="noopener noreferrer"><BookOpen/>{say('Nature of Accounts · reference','طبيعة الحسابات · المرجع')}</Link>
  {phase==='inspect'&&<div className="fd-case-file"><section className="fd-evidence-desk"><header><div><small>{say('CASE FILE','ملف الحالة')}</small><h3>{caseDefinition.managerRequest[locale]}</h3></div><b>{inspectedCount}/{required.length} {say('reviewed','تمت مراجعتها')}</b></header><div className="fd-evidence-tabs" aria-label={say('Case documents','مستندات الحالة')}>{caseDefinition.documents.map(item=><button className={`${item.id===selectedEvidence?'selected':''} ${inspected.has(item.id)?'inspected':''}`} onClick={()=>inspectDocument(item.id)} key={item.id}><FileSearch/><span><b>{item.title[locale]}</b><small>{item.reference}</small></span>{inspected.has(item.id)&&<Check/>}</button>)}</div><article className="fd-evidence-sheet"><header><span>{evidence.reference}</span><b>{evidence.title[locale]}</b></header><p>{evidence.summary[locale]}</p>{evidence.facts.map(fact=><dl key={fact.label.en}><dt>{fact.label[locale]}</dt><dd>{fact.value[locale]}</dd></dl>)}<footer><ClipboardCheck/>{evidence.required?say('Required for this review','مطلوب للمراجعة'):say('Supporting context','معلومة مساعدة')}</footer></article></section><aside className="fd-case-brief"><small>{say('KAREEM · WORK REQUEST','أ/ كريم · طلب العمل')}</small><h3>{caseDefinition.managerRequest[locale]}</h3><p>{say('Review the file, then choose the business action you can defend.','راجع الملف، وبعدها اختار قرار العمل اللي تقدر تبرره.')}</p><button onClick={()=>setPhase('decision')}><ClipboardCheck/>{say('Choose case action','اختر قرار الحالة')}</button><button className="secondary" onClick={askKareem}><Sparkles/>{say('Ask Kareem for guidance','اطلب توجيه من كريم')}</button>{helpLevel>0&&<div className="fd-manager-hint" role="status"><b>OK</b><span>{caseDefinition.managerGuidance[Math.min(helpLevel-1,caseDefinition.managerGuidance.length-1)][locale]}</span></div>}</aside></div>}
  {phase==='decision'&&<div className="fd-case-decision"><header><small>{say('PROFESSIONAL JUDGMENT','الحكم المهني')}</small><h3>{say('What should happen to this file now?','إيه الإجراء المناسب للملف دلوقتي؟')}</h3><p>{say('Your choice is recorded. Posting is available only after the required evidence has been reviewed.','قرارك بيتسجل. الترحيل متاح بعد مراجعة المستندات المطلوبة.')}</p></header><div>{caseDefinition.actions.map(action=><button onClick={()=>chooseAction(action.id)} key={action.id}><span>{action.id==='post'?<FileCheck2/>:action.id==='hold'?<AlertTriangle/>:<FileSearch/>}</span><b>{action.label[locale]}</b><small>{action.description[locale]}</small></button>)}</div>{decisionMessage&&<p className="fd-decision-feedback" role="status">{decisionMessage}</p>}<footer><button className="secondary" onClick={()=>setPhase('inspect')}><RotateCcw/>{say('Return to case file','ارجع لملف الحالة')}</button><button className="secondary" onClick={askKareem}><Sparkles/>{say('Ask Kareem','اسأل كريم')}</button></footer></div>}
  {phase==='record'&&<div className="fd-journal-game"><div className="fd-journal-instruction"><span><PenLine/></span><div><small>{say('POSTING WORKPAPER','ورقة عمل الترحيل')}</small><h3>{say('Prepare the entry that supports your posting decision','جهّز القيد المؤيد لقرار الترحيل')}</h3><p>{say('Use the reviewed case file. The system checks accounting meaning as well as debit and credit equality.','استخدم ملف الحالة اللي راجعته. النظام بيراجع المعنى المحاسبي مع تساوي المدين والدائن.')}</p></div></div><div className="fd-account-tokens" aria-label={say('Available accounts','الحسابات المتاحة')}>{tokenAccounts.map(account=><button className={lines[activeLine]?.account===account?'selected':''} onClick={()=>update(activeLine,{account})} key={account}><span>{accountLabel(account,locale).slice(0,1)}</span>{accountLabel(account,locale)}</button>)}</div><div className="fd-entry-board"><header><b>{say('JOURNAL ENTRY','القيد اليومي')}</b><span>{caseDefinition.accountingReference}</span></header>{lines.map((line,index)=><article className={activeLine===index?'active':''} onClick={()=>setActiveLine(index)} key={index}><button className="fd-line-account" onClick={()=>setActiveLine(index)}>{line.account?accountLabel(line.account,locale):say('Choose account','اختار الحساب')}</button><div className="fd-side-choice"><button className={line.side==='debit'?'selected':''} onClick={()=>update(index,{side:'debit'})}>{say('DEBIT','مدين')}</button><button className={line.side==='credit'?'selected':''} onClick={()=>update(index,{side:'credit'})}>{say('CREDIT','دائن')}</button></div><label><span>EGP</span><input aria-label={`${say('Amount line','مبلغ السطر')} ${index+1}`} type="number" inputMode="decimal" min="0" value={line.amount||''} onChange={event=>update(index,{amount:Number(event.target.value)})} placeholder={say('Enter amount','اكتب المبلغ')}/></label></article>)}{lines.length<2&&<button className="fd-add-line" onClick={()=>{addLine();setActiveLine(1)}}><Plus/>{say('Add second line','أضف السطر الثاني')}</button>}<JournalTotals locale={locale} lines={lines}/></div>{outcome==='wrong'&&<div className="fd-story-consequence" role="alert"><AlertTriangle/><div><small>{say('POSTING STOPPED · LEDGER PROTECTED','تم إيقاف الترحيل · الدفتر محمي')}</small><h3>{reaction.impact}</h3><p>“{reaction.message}”</p><b>{storyCharacters['finance-manager'].name[locale]}</b></div></div>}<div className="fd-workbench-actions"><button disabled={submitting} onClick={submit}><FileCheck2/>{say('Post to journal','رحّل إلى اليومية')}</button><button className="secondary" onClick={()=>setPhase('inspect')}><RotateCcw/>{say('Recheck case file','راجع ملف الحالة')}</button></div></div>}
  {phase==='result'&&<div className="fd-entry-success" role="status"><span><BadgeCheck/></span><small>{say('CASE POSTED · CONTROL COMPLETE','تم الترحيل · الرقابة مكتملة')}</small><h3>{say(`${doc.title.en} resolved`,`${doc.title.ar} تمت معالجتها`)}</h3><div>{doc.expected.map(line=><p key={line.account}><b>{accountLabel(line.account,locale)}</b><span>{(line.debit||line.credit).toLocaleString(locale)} {line.debit?say('Debit','مدين'):say('Credit','دائن')}</span></p>)}</div><CompanyImpact doc={doc} locale={locale} pendingAfter={pendingAfter}/><section className="fd-case-performance"><span><b>{performance.investigation}%</b><small>{say('Investigation','التحقيق')}</small></span><span><b>{performance.accountingJudgment}%</b><small>{say('Judgment','الحكم المهني')}</small></span><span><b>{performance.managerAssistance}</b><small>{say('Manager assistance','مساعدة المدير')}</small></span></section>{!wasCompleted&&<p className="fd-reward-pop"><small>{say('Secondary game reward','مكافأة لعب ثانوية')}</small><Zap/>+{DOCUMENT_REWARD.xp} XP <Coins/>+{DOCUMENT_REWARD.coins}</p>}<div className="fd-manager-result"><b>OK</b><p>“{reaction.message}”</p></div><button onClick={onClose}>{say('File in Processed · return to desk','ضعه في المعالج وارجع للمكتب')}<ChevronRight/></button></div>}
 </section></div>;
}

function JournalTotals({locale,lines}:{locale:Locale;lines:DeskLine[]}){const ar=locale==='ar',debit=lines.filter(line=>line.side==='debit').reduce((sum,line)=>sum+line.amount,0),credit=lines.filter(line=>line.side==='credit').reduce((sum,line)=>sum+line.amount,0),balanced=debit>0&&debit===credit;return <footer className={balanced?'balanced':''}><span>{ar?'إجمالي المدين':'Total debit'}<b>{debit.toLocaleString(locale)}</b></span><span>{ar?'إجمالي الدائن':'Total credit'}<b>{credit.toLocaleString(locale)}</b></span><strong>{balanced?<><Check/>{ar?'متوازن':'Balanced'}</>:<>{ar?'الفرق':'Difference'}: {Math.abs(debit-credit).toLocaleString(locale)}</>}</strong></footer>}
function CompanyImpact({doc,locale,pendingAfter}:{doc:FirstDayDocument;locale:Locale;pendingAfter:number}){const ar=locale==='ar',rows=doc.id==='supplier-invoice'?[[ar?'المعدات':'Equipment',1250000,1350000],[ar?'الموردون':'Suppliers',730000,830000]]:doc.id==='customer-receipt'?[[ar?'البنك':'Bank',480000,555000],[ar?'العملاء':'Customers',320000,245000]]:[[ar?'الصندوق':'Cash',250000,247500],[ar?'صافي الربح':'Net profit',85000,82500]];return <section className="fd-company-impact"><small>{ar?'أثر فعلي على دفاتر الشركة':'POSTED COMPANY IMPACT'}</small><p><b>{ar?'المستندات المعلقة':'Pending documents'}</b><span>{pendingAfter+1} → <strong>{pendingAfter}</strong></span></p><p><b>{ar?'القيود المعلقة':'Pending entries'}</b><span>{pendingAfter+1} → <strong>{pendingAfter}</strong></span></p>{rows.map(([label,before,after])=><p key={String(label)}><b>{label}</b><span>{Number(before).toLocaleString(locale)} → <strong>{Number(after).toLocaleString(locale)} EGP</strong></span></p>)}</section>}
