"use client";
import '@/app/first-shift-scene.css';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import { AlertTriangle,BadgeCheck,BookOpen,BriefcaseBusiness,Building2,Calculator,Check,ChevronRight,Coins,FileCheck2,FileText,LockKeyhole,PenLine,Plus,RotateCcw,Sparkles,Trophy,X,Zap } from 'lucide-react';
import { CinematicChapterIntro } from './cinematic-chapter-intro';
import { firstDayIntro,storyCharacters } from '@/lib/campaign/first-day-story';
import { accountLabel,closeFirstDayDocument,completeFirstDayIntro,DOCUMENT_REWARD,enterFirstDayDesk,FIRST_DAY_INTRO_VERSION,firstDayCompany,firstDayDocuments,firstDayProgress,firstDayReaction,markFirstDayCompletionSeen,selectFirstDayDocument,submitFirstDayDocument,type FirstDayDocument,type FirstDayDocumentId } from '@/lib/campaign/first-day';
import { useGame } from '@/lib/campaign/store';
import type { Account,GameState } from '@/lib/campaign/model';
import type { Locale } from '@/types';

export function FirstDayScreen({locale}:{locale:Locale}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,{state,ready,change}=useGame(),progress=firstDayProgress(state),company=firstDayCompany(state);
 const [active,setActive]=useState<FirstDayDocumentId|null>(null),[queuedProcessed,setQueuedProcessed]=useState<FirstDayDocumentId|null>(null),[processedAnimation,setProcessedAnimation]=useState<FirstDayDocumentId|null>(null);const restored=useRef(false);const [mobileIndex,setMobileIndex]=useState(0),[tool,setTool]=useState<'journal'|'ledger'|'calculator'|null>(null);const swipeStart=useRef<number|null>(null);
 useEffect(()=>{if(!processedAnimation)return;const timer=window.setTimeout(()=>setProcessedAnimation(null),1350);return()=>window.clearTimeout(timer);},[processedAnimation]);
 useEffect(()=>{if(!ready||restored.current)return;restored.current=true;if(progress.selected)setActive(progress.selected);},[ready,progress.selected]);
 if(!ready)return <div className="first-day-loading">{say('Preparing your first day…','بنجهّز أول يوم ليك…')}</div>;
 if(progress.introVersion<FIRST_DAY_INTRO_VERSION)return <CinematicChapterIntro chapter={firstDayIntro} locale={locale} variant="intro" onComplete={()=>change(completeFirstDayIntro)} onSkip={()=>{}}/>;
 if(!progress.deskEntered)return <ManagerBriefing locale={locale} onContinue={()=>change(enterFirstDayDesk)}/>;
 if(progress.rewarded&&!progress.completionSeen&&!active&&!processedAnimation)return <ShiftComplete locale={locale} state={state} onContinue={()=>change(markFirstDayCompletionSeen)}/>;
 const completeCount=progress.completed.length,doc=firstDayDocuments.find(item=>item.id===active),manager=storyCharacters['finance-manager'];
 const openDocument=(id:FirstDayDocumentId)=>{window.dispatchEvent(new CustomEvent('debit-credit-sound-event',{detail:{type:'paper-open',documentId:id}}));change(current=>selectFirstDayDocument(current,id));setActive(id);};
 const closeDocument=()=>{change(closeFirstDayDocument);setActive(null);if(queuedProcessed){setProcessedAnimation(queuedProcessed);setQueuedProcessed(null);}};
 const submit=(id:FirstDayDocumentId,draft:string,hints:number)=>{let correct=false;change(current=>{const result=submitFirstDayDocument(current,id,draft,Date.now(),hints);correct=result.correct;return result.state;});if(correct)setQueuedProcessed(id);window.dispatchEvent(new CustomEvent('debit-credit-sound-event',{detail:{type:correct?'correct-answer':'wrong-answer',documentId:id}}));return correct;};
 const stages=[say('Arrival','الوصول'),say('Meet Kareem','مقابلة كريم'),say('First Shift','وردية اليوم'),say("Something's Wrong",'في حاجة غلط'),say('End of Day','نهاية اليوم')];
 const pending=firstDayDocuments.filter(item=>!progress.completed.includes(item.id));
 const selectedMobile=pending[Math.min(mobileIndex,Math.max(0,pending.length-1))];
 const movePaper=(direction:number)=>setMobileIndex(current=>(Math.min(current,Math.max(0,pending.length-1))+direction+pending.length)%Math.max(1,pending.length));
 return <div className="first-day shift-scene" dir={ar?'rtl':'ltr'}>
  <div className="shift-home" inert={!!doc||!!tool}>
   <header className="scene-hud">
    <Link className="scene-brand" href={`/${locale}`}><span aria-hidden="true">▂▅▇</span><b>Debit & Credit<small>by Money Coder</small></b></Link>
    <nav className="scene-story" aria-label={say('Chapter progress','تقدم الفصل')}>{stages.map((label,index)=><span className={index<2?'done':index===2?'current':'locked'} aria-current={index===2?'step':undefined} key={label}>{index<2?<Check/>:index===2?<i>1</i>:<LockKeyhole/>}<small>{label}</small></span>)}</nav>
    <div className="scene-player"><Link className="scene-manual-link" href={`/${locale}/account-guide?return=first-day`} target="_blank" rel="noopener noreferrer"><BookOpen/>{say('Nature of Accounts','طبيعة الحسابات')}</Link><span><Coins/>{state.coins}</span><span><Zap/>{state.xp} XP</span><Link href={`/${ar?'en':'ar'}`} aria-label={say('Switch to Arabic','التبديل للإنجليزية')}>{ar?'EN':'AR'}</Link></div>
   </header>
   <main className="scene-desk" aria-label={say("Today's accounting desk",'مكتب محاسبة اليوم')}>
    <div className="scene-office-mark"><Building2/><div><b>Mizan Trading</b><small>{say('FINANCE OFFICE · 09:13 AM','مكتب الحسابات · ٩:١٣ صباحًا')}</small></div></div>
    <div className="scene-assignment"><small>{say('CHAPTER 01 / FIRST DAY','الفصل ٠١ / أول يوم')}</small><h1>{say('Your first shift.','أول وردية ليك.')}</h1><p>{say('Inspect. Decide. Record.','افحص. قرر. سجّل.')}</p></div>
    <aside className="scene-manager"><div className="scene-portrait"><Image src="/arena/cfo-mentor.png" alt="" fill sizes="52px"/></div><div><small>{manager.name[locale]} · {manager.role[locale]}</small><h2>{completeCount===0?say('Choose a document and begin.','اختار مستند وابدأ.'):completeCount<3?say('Good. Clear the next paper.','تمام. خلّص الورقة اللي بعدها.'):say('Every entry tells a story. Well done.','كل قيد بيحكي قصة. شغل ممتاز.')}</h2></div></aside>
    <LaptopMission locale={locale} progress={progress.completed}/>
    <button className="scene-book journal" onClick={()=>setTool('journal')}>{say('Journal','دفتر اليومية')}<small>{state.journal.filter(entry=>entry.id.startsWith('first-day/')).length} {say('entries','قيود')}</small></button>
    <button className="scene-book ledger" onClick={()=>setTool('ledger')}>{say('General Ledger','دفتر الأستاذ')}</button>
    <button className="scene-calculator" aria-label={say('Open calculator','افتح الآلة الحاسبة')} onClick={()=>setTool('calculator')}><span>{say('Calculate','احسب')}</span></button>
    <div className="scene-inbox"><b>{company.pendingDocuments}</b><span>{say('INBOX','الوارد')}</span></div>
    <div className={`scene-processed fd-processed-tray ${processedAnimation?'receiving':''}`} aria-live="polite"><div className="scene-filed-papers" aria-hidden="true">{progress.completed.map((id,index)=><i key={id} style={{transform:`translateY(${-index*5}px) rotate(${index*3-3}deg)`}}>✓</i>)}</div><b>{completeCount}</b><span>{say('PROCESSED TRAY','درج تمت المعالجة')}</span></div>
    <div className="scene-papers" onTouchStart={event=>{swipeStart.current=event.touches[0].clientX;}} onTouchEnd={event=>{if(swipeStart.current===null)return;const distance=event.changedTouches[0].clientX-swipeStart.current;if(Math.abs(distance)>45)movePaper((ar?distance:-distance)>0?1:-1);swipeStart.current=null;}}>
     {pending.map(item=>{const index=firstDayDocuments.indexOf(item),hasError=(progress.mistakes[item.id]??0)>0;return <button key={item.id} data-document={item.id} className={`scene-paper ${item.accent} paper-${index} ${selectedMobile?.id===item.id?'mobile-active':''}`} onClick={()=>openDocument(item.id)} aria-label={`${item.title[locale]} · ${say('Open document','افتح المستند')}`}>
      <span className="scene-clip" aria-hidden="true"/><span className="scene-paper-brand"><Building2/> Mizan Trading <i>{index+1}</i></span>
      <h2>{item.title[locale]}</h2><small className="scene-paper-subtitle">{item.subtitle[locale]}</small>
      <div className="scene-paper-party"><b>{item.party[locale]}</b><span>{item.number}</span></div>
      <div className="scene-paper-lines"><p><span>{say('Date','التاريخ')}</span><b>{item.date[locale]}</b></p>{item.details.slice(-2).map(row=><p key={row.label.en}><span>{row.label[locale]}</span><b>{row.value[locale]}</b></p>)}</div>
      <div className="scene-paper-total"><small>{say('TOTAL / EGP','الإجمالي / جنيه')}</small><strong>{item.amount.toLocaleString(locale)}</strong></div>
      <span className="scene-paper-hint">{hasError?<AlertTriangle/>:<PenLine/>}{hasError?say('Review correction','راجع التصحيح'):say('Inspect document','افحص المستند')}<ChevronRight/></span>
     </button>;})}
    </div>
    {processedAnimation&&<div className={`scene-transfer fd-paper-transfer ${processedAnimation}`} aria-hidden="true"><FileCheck2/><b>{say('RECORDED','تم التسجيل')}</b></div>}
    <div className="scene-sticky">{say('Check the source.','راجع المصدر.')}<br/>{say('Let the numbers tell the story.','سيب الأرقام تحكي.')}<span>✓</span></div>
    <div className="scene-desk-caption">{pending.length?say('Pick up a paper to begin','اختار مستند لتبدأ'):say('A clear desk. Balanced books.','مكتب خلصان. ودفاتر متوازنة.')}<span>↗</span></div>
    <div className="scene-mobile-actions">{pending.length>0&&<><button onClick={()=>movePaper(-1)} aria-label={say('Previous document','المستند السابق')}>‹</button><button onClick={()=>openDocument(selectedMobile.id)}>{say('Inspect document','افحص المستند')} <small>{Math.min(mobileIndex+1,pending.length)}/{pending.length}</small></button><button onClick={()=>movePaper(1)} aria-label={say('Next document','المستند التالي')}>›</button></>}</div>
    <div className="scene-mobile-tools"><button onClick={()=>setTool('journal')}><BookOpen/>{say('Journal','اليومية')}</button><button onClick={()=>setTool('ledger')}><Building2/>{say('Ledger','الأستاذ')}</button><button onClick={()=>setTool('calculator')}><Calculator/>{say('Calculator','الحاسبة')}</button></div>
   </main>
   <footer className="scene-company" aria-label={say('Company status','حالة الشركة')}>
    <span className="scene-company-name"><Building2/><b>Mizan</b></span>
    <span><small>{say('Cash balance','رصيد الصندوق')}</small><b>{money(company.cash,locale)}</b></span><span><small>{say('Bank balance','رصيد البنك')}</small><b>{money(company.bank,locale)}</b></span>
    <span className="scene-pending"><small>{say('Pending documents','مستندات معلقة')}</small><b>{company.pendingDocuments}</b></span><span><small>{say('Month-end progress','تقدم إقفال الشهر')}</small><b>{company.monthEndProgress}%</b></span>
    <span className={`scene-books-health ${company.ledgerErrors?'has-errors':''}`}>{company.ledgerErrors?<AlertTriangle/>:<Check/>}{company.ledgerErrors?say('Review needed','مراجعة مطلوبة'):say('Books healthy','الدفاتر سليمة')}</span>
   </footer>
   {state.storageWarning&&<p className="scene-storage-warning" role="alert">{say('Storage unavailable. Keep this tab open to retain progress.','التخزين غير متاح. اترك الصفحة مفتوحة للحفاظ على تقدمك.')}</p>}
   {progress.completionSeen&&<div className="scene-next"><LockKeyhole/><small>{say('NEXT · LOCKED','التالي · مقفول')}</small><h2>{say('Chapter 2 — THE MISSING MONEY','الفصل ٢ — المال المفقود')}</h2></div>}
  </div>
  {doc&&<DocumentInteraction key={doc.id} locale={locale} doc={doc} completed={progress.completed.includes(doc.id)} pendingAfter={company.pendingDocuments} onClose={closeDocument} onSubmit={(draft,hints)=>submit(doc.id,draft,hints)}/>}
  {tool&&<DeskTool tool={tool} locale={locale} state={state} onClose={()=>setTool(null)}/>}
 </div>;
}

function ManagerBriefing({locale,onContinue}:{locale:Locale;onContinue:()=>void}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,manager=storyCharacters['finance-manager'];
 return <section className="fd-manager-scene" dir={ar?'rtl':'ltr'}><Image src="/game/first-day-cinematic.png" fill priority sizes="100vw" alt=""/><div className="fd-manager-scene-shade"/><div className="fd-briefing-card"><header><b>OK</b><span><strong>{manager.name[locale]}</strong><small>{manager.role[locale]}</small></span></header><h1>{say('Welcome to Mizan Trading.','أهلًا بيك في ميزان للتجارة.')}</h1><p>{say('Today is your first day. Three transactions from yesterday still need to be recorded. Inspect each source, decide what changed, and keep the books balanced.','النهارده أول يوم ليك. عندنا ٣ معاملات من امبارح لسه محتاجة تتسجل. افحص كل مستند، قرر إيه اللي اتغيّر، وخلي الدفاتر متوازنة.')}</p><button onClick={onContinue}>{say('SHOW ME THE DESK','ورّيني المكتب')}<ChevronRight/></button></div><div className="fd-briefing-caption"><small>{say('8:45 AM · FINANCE OFFICE','٨:٤٥ صباحًا · الإدارة المالية')}</small><b>{say('Your decisions change the company.','قراراتك تغيّر حالة الشركة.')}</b></div></section>;
}

function LaptopMission({locale,progress}:{locale:Locale;progress:FirstDayDocumentId[]}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en;
 return <section className="scene-laptop" aria-label={say('Mizan accounting system','نظام ميزان المحاسبي')}><header><span><Building2/></span><div><b>Mizan OS</b><small>{say('FIRST SHIFT · LIVE','الوردية الأولى · مباشر')}</small></div><i>{progress.length}/3</i></header><div className="fd-laptop-progress"><span><b style={{width:`${progress.length/3*100}%`}}/></span><small>{say(`${3-progress.length} documents in inbox`,`${3-progress.length} مستند في الوارد`)}</small></div><ul>{firstDayDocuments.map(item=><li className={progress.includes(item.id)?'done':''} key={item.id}>{progress.includes(item.id)?<Check/>:<FileText/>}<span><b>{item.title[locale]}</b><small>{progress.includes(item.id)?say('Posted to journal','تم ترحيله للدفتر'):say('Waiting for review','بانتظار المراجعة')}</small></span></li>)}</ul><footer><span>OK</span><p>“{say('Every entry should explain what changed.','كل قيد لازم يشرح إيه اللي اتغيّر.')}”</p></footer></section>;
}

function ShiftComplete({locale,state,onContinue}:{locale:Locale;state:GameState;onContinue:()=>void}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,attempts=state.evidence.filter(item=>item.missionId==='first-day'),correct=attempts.filter(item=>item.correct).length,hints=attempts.reduce((sum,item)=>sum+item.hintsUsed,0),accuracy=attempts.length?Math.round(correct/attempts.length*100):100,firstAttempts=attempts.filter(item=>item.independentCompletion).length;
 return <section className="fd-shift-complete" dir={ar?'rtl':'ltr'}><Image src="/game/first-day-cinematic.png" fill priority sizes="100vw" alt=""/><div className="fd-complete-shade"/><div className="fd-complete-card" role="status"><span className="fd-complete-trophy"><Trophy/></span><small>{say('FIRST DAY COMPLETE · CHAPTER 1','اكتمل أول يوم · الفصل ١')}</small><h1>{say('The books are balanced.','الدفاتر اتزنت.')}</h1><p>“{say('Good work. You did not just answer questions—you completed a real accounting shift.','شغل كويس. إنت ما جاوبتش أسئلة وبس—إنت خلّصت وردية محاسبية حقيقية.')}”</p><div className="fd-shift-results"><span><b>3/3</b><small>{say('Documents','المستندات')}</small></span><span><b>{accuracy}%</b><small>{say('Accuracy','الدقة')}</small></span><span><b>{firstAttempts}/3</b><small>{say('First attempt','من أول محاولة')}</small></span><span><b>{hints}</b><small>{say('Hints','التلميحات')}</small></span></div><div className="fd-shift-reward"><Zap/>+300 XP <Coins/>+150 {say('Coins','عملة')}</div><div className="fd-evidence-added"><BriefcaseBusiness/><span><small>{say('PROFESSIONAL EVIDENCE ADDED','تمت إضافة أدلة مهنية')}</small><b>{say('Journal Entries · Document Analysis · Account Classification','القيود اليومية · تحليل المستندات · تصنيف الحسابات')}</b></span><Link href={`/${locale}/career-profile/skills`}>{say('View Skill Passport','افتح جواز المهارات')}</Link></div><div className="fd-next-case"><LockKeyhole/><span><small>{say('CHAPTER 2 · LOCKED','الفصل ٢ · مقفول')}</small><b>{say('THE MISSING MONEY','المال المفقود')}</b><p>{say('One number will not match. Find out why.','رقم واحد مش هيتطابق. اكتشف السبب.')}</p></span></div><button onClick={onContinue}>{say('CONTINUE STORY','واصل القصة')}<ChevronRight/></button></div></section>;
}

function money(value:number,locale:Locale){return `${value.toLocaleString(locale)} EGP`;}

type DeskLine={account:Account|'';side:'debit'|'credit'|'';amount:number};
const tokenAccounts:Account[]=['cash','bank','equipment','customers','suppliers','officeExpense','capital','revenue'];
function toDraft(lines:DeskLine[]):string{return JSON.stringify(lines.map(line=>({account:line.account,debit:line.side==='debit'?line.amount:0,credit:line.side==='credit'?line.amount:0})));}

function DocumentInteraction({locale,doc,completed,pendingAfter,onClose,onSubmit}:{locale:Locale;doc:FirstDayDocument;completed:boolean;pendingAfter:number;onClose:()=>void;onSubmit:(draft:string,hints:number)=>boolean}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,[phase,setPhase]=useState<'inspect'|'record'|'result'>(completed?'result':'inspect'),[lines,setLines]=useState<DeskLine[]>([{account:'',side:'',amount:0}]),[activeLine,setActiveLine]=useState(0),[outcome,setOutcome]=useState<'correct'|'wrong'|null>(completed?'correct':null),[hint,setHint]=useState(false),[wasCompleted]=useState(completed);const dialogRef=useRef<HTMLElement>(null),reaction=firstDayReaction(doc.id,outcome==='correct',locale);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialogRef.current?.querySelector<HTMLElement>('button')?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();if(event.key==='Tab'&&dialogRef.current){const items=Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button,a,input,select')).filter(item=>!item.hasAttribute('disabled'));const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
 const update=(index:number,patch:Partial<DeskLine>)=>setLines(current=>current.map((line,lineIndex)=>lineIndex===index?{...line,...patch}:line));
 const submit=()=>{const correct=onSubmit(toDraft(lines),hint?1:0);setOutcome(correct?'correct':'wrong');if(correct)setPhase('result');};
 return <div className="fd-modal-backdrop"><section ref={dialogRef} className={`fd-workbench-modal ${outcome??''}`} role="dialog" aria-modal="true" aria-label={doc.title[locale]}><button className="fd-close" onClick={onClose} aria-label={say('Close','إغلاق')}><X/></button><header className="fd-workbench-head"><span className={doc.accent}><FileText/></span><div><small>{doc.number} · {doc.date[locale]}</small><h2>{doc.title[locale]}</h2><p>{doc.subtitle[locale]}</p></div><div className="fd-workflow-steps"><span className={phase==='inspect'?'current':'done'}>1 {say('Inspect','افحص')}</span><span className={phase==='record'?'current':phase==='result'?'done':''}>2 {say('Build entry','ركّب القيد')}</span><span className={phase==='result'?'current':''}>3 {say('Consequence','النتيجة')}</span></div></header>
  <Link className="fd-workbench-manual" href={`/${locale}/account-guide?return=first-day&document=${doc.id}`} target="_blank" rel="noopener noreferrer"><BookOpen/>{say("Nature of Accounts · reference","طبيعة الحسابات · المرجع")}</Link>
  {phase==='inspect'&&<div className="fd-inspection-stage"><div className="fd-full-document"><header><b>{doc.party[locale]}</b><span>{doc.number}</span></header><small>{doc.subtitle[locale]}</small>{doc.details.map(row=><p key={row.label.en}><span>{row.label[locale]}</span><strong>{row.value[locale]}</strong></p>)}<footer><span>{say('TOTAL','الإجمالي')}</span><b>{doc.amount.toLocaleString(locale)} {say('EGP','جنيه')}</b></footer></div><aside><small>{say('DOCUMENT DECISION','قرار المستند')}</small><h3>{say('What should you do with this document?','تعمل إيه بالمستند ده؟')}</h3><p>{say('Inspect the source, purpose, amount, and payment method before you touch the journal.','راجع المصدر والغرض والمبلغ وطريقة السداد قبل ما تبدأ القيد.')}</p><button onClick={()=>setPhase('record')}><PenLine/>{say('Record transaction','سجّل العملية')}</button><Link href={`/${locale}/account-guide?return=first-day&document=${doc.id}`} target="_blank" rel="noreferrer"><BookOpen/>{say('Open Accounting Manual','افتح دليل الحسابات')}</Link><button className="secondary" onClick={()=>setHint(true)}><Sparkles/>{say('Ask Mr. Kareem for a hint','اسأل أ/ كريم عن تلميح')}</button>{hint&&<div className="fd-manager-hint"><b>OK</b><span>{doc.id==='supplier-invoice'?say('Ask: what did the company receive, and what does it owe?','اسأل نفسك: الشركة استلمت إيه وبقى عليها إيه؟'):doc.id==='customer-receipt'?say('No new revenue was earned. This settles an old customer balance.','مفيش إيراد جديد. ده تحصيل لرصيد عميل قديم.'):say('The office used something and paid cash immediately.','المكتب استهلك حاجة ودفع نقدًا فورًا.')}</span></div>}</aside></div>}
  {phase==='record'&&<div className="fd-journal-game"><div className="fd-journal-instruction"><span><PenLine/></span><div><small>{say('ACCOUNTING PUZZLE','لغز محاسبي')}</small><h3>{say('Place the accounts on the correct side','حط الحسابات في الطرف الصح')}</h3><p>{say('Select an entry line, choose an account token, then place its amount in Debit or Credit.','اختار سطر القيد، وبعدها قطعة الحساب، وحدد مدين أو دائن واكتب المبلغ.')}</p></div></div><div className="fd-account-tokens" aria-label={say('Available accounts','الحسابات المتاحة')}>{tokenAccounts.map(account=><button className={lines[activeLine]?.account===account?'selected':''} onClick={()=>update(activeLine,{account})} key={account}><span>{accountLabel(account,locale).slice(0,1)}</span>{accountLabel(account,locale)}</button>)}</div><div className="fd-entry-board"><header><b>{say('JOURNAL ENTRY','القيد اليومي')}</b><span>{say('Debit must equal credit','المدين لازم يساوي الدائن')}</span></header>{lines.map((line,index)=><article className={activeLine===index?'active':''} onClick={()=>setActiveLine(index)} key={index}><button className="fd-line-account" onClick={()=>setActiveLine(index)}>{line.account?accountLabel(line.account,locale):say('Choose account token','اختار قطعة الحساب')}</button><div className="fd-side-choice"><button className={line.side==='debit'?'selected':''} onClick={()=>update(index,{side:'debit'})}>{say('DEBIT','مدين')}</button><button className={line.side==='credit'?'selected':''} onClick={()=>update(index,{side:'credit'})}>{say('CREDIT','دائن')}</button></div><label><span>EGP</span><input aria-label={`${say('Amount line','مبلغ السطر')} ${index+1}`} type="number" inputMode="decimal" min="0" value={line.amount||''} onChange={event=>update(index,{amount:Number(event.target.value)})} placeholder={say('Enter amount','اكتب المبلغ')}/></label></article>)}{lines.length<2&&<button className="fd-add-line" onClick={()=>{setLines(current=>[...current,{account:'',side:'',amount:0}]);setActiveLine(1);}}><Plus/>{say('Add second line','أضف السطر الثاني')}</button>}<JournalTotals locale={locale} lines={lines}/></div>{outcome==='wrong'&&<div className="fd-story-consequence" role="alert"><AlertTriangle/><div><small>{say('COMPANY CONSEQUENCE','أثر الخطأ على الشركة')}</small><h3>{reaction.impact}</h3><p>“{reaction.message}”</p><b>{storyCharacters['finance-manager'].name[locale]}</b></div></div>}<div className="fd-workbench-actions"><button onClick={submit}><FileCheck2/>{say('Submit entry','اعتمد القيد')}</button><button className="secondary" onClick={()=>setPhase('inspect')}><RotateCcw/>{say('Recheck document','راجع المستند')}</button></div></div>}
  {phase==='result'&&<div className="fd-entry-success" role="status"><span><BadgeCheck/></span><small>{say('ENTRY BALANCED','القيد متوازن')}</small><h3>{say(`${doc.title.en} recorded successfully`,`${doc.title.ar} اتسجلت بنجاح`)}</h3><div>{doc.expected.map(line=><p key={line.account}><b>{accountLabel(line.account,locale)}</b><span>{(line.debit||line.credit).toLocaleString(locale)} {line.debit?say('Debit','مدين'):say('Credit','دائن')}</span></p>)}</div><CompanyImpact doc={doc} locale={locale} pendingAfter={pendingAfter}/><ul><li><Check/>{say('Entry balanced','القيد متوازن')}</li><li><Check/>{say('Document is moving to Processed','المستند بيتنقل لدرج تمت المعالجة')}</li><li><Check/>{reaction.message}</li></ul>{!wasCompleted&&<p className="fd-reward-pop"><Zap/>+{DOCUMENT_REWARD.xp} XP <Coins/>+{DOCUMENT_REWARD.coins}</p>}<div className="fd-manager-result"><b>OK</b><p>“{reaction.message}”</p></div><button onClick={onClose}>{say('Return to Desk','ارجع للمكتب')}<ChevronRight/></button></div>}
 </section></div>;
}

function JournalTotals({locale,lines}:{locale:Locale;lines:DeskLine[]}){const ar=locale==='ar',debit=lines.filter(line=>line.side==='debit').reduce((sum,line)=>sum+line.amount,0),credit=lines.filter(line=>line.side==='credit').reduce((sum,line)=>sum+line.amount,0),balanced=debit>0&&debit===credit;return <footer className={balanced?'balanced':''}><span>{ar?'إجمالي المدين':'Total debit'}<b>{debit.toLocaleString(locale)}</b></span><span>{ar?'إجمالي الدائن':'Total credit'}<b>{credit.toLocaleString(locale)}</b></span><strong>{balanced?<><Check/>{ar?'متوازن':'Balanced'}</>:<>{ar?'الفرق':'Difference'}: {Math.abs(debit-credit).toLocaleString(locale)}</>}</strong></footer>;}

function CompanyImpact({doc,locale,pendingAfter}:{doc:FirstDayDocument;locale:Locale;pendingAfter:number}){const ar=locale==='ar',rows=doc.id==='supplier-invoice'?[[ar?'المعدات':'Equipment',1250000,1350000],[ar?'الموردون':'Suppliers',730000,830000]]:doc.id==='customer-receipt'?[[ar?'البنك':'Bank',480000,555000],[ar?'العملاء':'Customers',320000,245000]]:[[ar?'الصندوق':'Cash',250000,247500],[ar?'صافي الربح':'Net profit',85000,82500]];return <section className="fd-company-impact"><small>{ar?'أثر حقيقي على الشركة':'REAL COMPANY IMPACT'}</small><p><b>{ar?'المستندات المعلقة':'Pending documents'}</b><span>{pendingAfter+1} → <strong>{pendingAfter}</strong></span></p><p><b>{ar?'القيود المعلقة':'Pending entries'}</b><span>{pendingAfter+1} → <strong>{pendingAfter}</strong></span></p>{rows.map(([label,before,after])=><p key={String(label)}><b>{label}</b><span>{Number(before).toLocaleString(locale)} → <strong>{Number(after).toLocaleString(locale)} EGP</strong></span></p>)}</section>;}

function DeskTool({tool,locale,state,onClose}:{tool:'journal'|'ledger'|'calculator';locale:Locale;state:GameState;onClose:()=>void}){
 const ar=locale==='ar',say=(en:string,a:string)=>ar?a:en,company=firstDayCompany(state),ref=useRef<HTMLElement>(null);
 const [a,setA]=useState(''),[b,setB]=useState(''),[operation,setOperation]=useState('+');
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const dialog=ref.current;dialog?.querySelector<HTMLElement>('button')?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();if(event.key==='Tab'&&dialog){const items=Array.from(dialog.querySelectorAll<HTMLElement>('button,input,select,a'));const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
 const result=operation==='+'?Number(a)+Number(b):operation==='-'?Number(a)-Number(b):operation==='×'?Number(a)*Number(b):Number(b)===0?null:Number(a)/Number(b);
 const rows=[[say('Cash balance','رصيد الصندوق'),company.cash],[say('Bank balance','رصيد البنك'),company.bank],[say('Supplier balance','رصيد الموردين'),company.supplierBalance],[say('Customer balance','رصيد العملاء'),company.customerBalance],[say('Pending entries','قيود معلقة'),company.pendingEntries],[say('Unresolved errors','أخطاء غير محلولة'),company.ledgerErrors]] as const;
 return <div className="fd-modal-backdrop"><section ref={ref} className="scene-tool" role="dialog" aria-modal="true" aria-label={tool==='journal'?say('Journal','دفتر اليومية'):tool==='ledger'?say('General Ledger','دفتر الأستاذ'):say('Calculator','الآلة الحاسبة')}><button className="fd-close" onClick={onClose} aria-label={say('Close','إغلاق')}><X/></button><h2>{tool==='journal'?say('Journal','دفتر اليومية'):tool==='ledger'?say('General Ledger','دفتر الأستاذ'):say('Calculator','الآلة الحاسبة')}</h2>
 {tool==='journal'&&(state.journal.filter(entry=>entry.id.startsWith('first-day/')).length?state.journal.filter(entry=>entry.id.startsWith('first-day/')).map(entry=><div className="scene-tool-entry" key={entry.id}><b>{entry.documentIds.join(' · ')}</b>{entry.lines.map((line,index)=><p key={index}><span>{accountLabel(line.account,locale)}</span><b>{money(line.debit||line.credit,locale)} · {line.debit?say('Debit','مدين'):say('Credit','دائن')}</b></p>)}</div>):<p>{say('The journal is empty. Record a document to write your first entry.','الدفتر لسه فاضي. سجّل مستند عشان تضيف أول قيد.')}</p>)}
 {tool==='ledger'&&rows.map(([label,value])=><p className="scene-ledger-row" key={label}><span>{label}</span><b>{value.toLocaleString(locale)}</b></p>)}
 {tool==='calculator'&&<><label>{say('First number','الرقم الأول')}<input type="number" value={a} onChange={event=>setA(event.target.value)}/></label><label>{say('Operation','العملية')}<select value={operation} onChange={event=>setOperation(event.target.value)}>{['+','-','×','÷'].map(op=><option key={op}>{op}</option>)}</select></label><label>{say('Second number','الرقم الثاني')}<input type="number" value={b} onChange={event=>setB(event.target.value)}/></label><output aria-live="polite">{result===null?say('Cannot divide by zero','لا يمكن القسمة على صفر'):result.toLocaleString(locale)}</output></>}
 </section></div>;
}
