"use client";
import Link from 'next/link';
import { ArcadePanel } from './arcade-panel';
import { JournalBuilder } from './journal-builder';
import { FirstDayScreen } from './first-day-screen';
import { useEffect, useRef, useState } from 'react';
import { Archive, BookOpen, Briefcase, Calculator, Check, ChevronRight, Coins, FileText, Flag, Flame, Lock, ShieldCheck, Swords, Trophy, X, Zap } from 'lucide-react';
import { accounts, categories, chapters, documents, getMission, missions } from '@/lib/campaign/content';
import { activeStage, balances, candidateEvidence, company, continueMission, editDraft, evidenceSummary, inspectDocument, nextMission, startMission, streak, submitStage, unlocked, upgradeOffice, recordHint } from '@/lib/campaign/director';
import { archiveLegacyEducation, useGame } from '@/lib/campaign/store';
import type { Account, Words } from '@/lib/campaign/model';
import type { Locale } from '@/types';

export function GameApp({locale,view='office'}:{locale:Locale;view?:'office'|'campaign'|'arena'|'profile'|'employer'}){return view==='office'?<FirstDayScreen locale={locale}/>:<LegacyGameApp locale={locale} view={view}/>;}
function LegacyGameApp({locale,view}:{locale:Locale;view:'office'|'campaign'|'arena'|'profile'|'employer'}){
 const {state:s,ready,change}=useGame();const ar=locale==='ar';const t=(v:Words)=>v[locale];const say=(en:string,arText:string)=>ar?arText:en;
 const dialogRef=useRef<HTMLElement>(null);
 const [object,setObject]=useState<string|null>(null);const [calc,setCalc]=useState({a:'',b:'',op:'+'});
 useEffect(()=>{archiveLegacyEducation();},[]);
 useEffect(()=>{if(!object)return;const previous=document.activeElement as HTMLElement|null;const dialog=dialogRef.current;dialog?.querySelector<HTMLElement>('button')?.focus();const handler=(event:KeyboardEvent)=>{if(event.key==='Escape')setObject(null);if(event.key==='Tab'&&dialog){const items=Array.from(dialog.querySelectorAll<HTMLElement>('button,a,input,select')).filter(el=>!el.hasAttribute('disabled'));const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus();};},[object]);

 const m=s.active?getMission(s.active.missionId):null;const stage=activeStage(s);const world=company(s);const summary=evidenceSummary(s);const next=nextMission(s);const chapter=m?.chapter??next?.chapter??8;
 const launch=()=>{if(!s.active&&next)change(st=>startMission(st,next.id));};
 const nav=[['',Briefcase,say('Office','المكتب')],['campaign',Flag,say('Campaign','الحكاية')],['arena',Swords,say('Arena','الساحة')],['profile',ShieldCheck,say('Profile','ملفي')]] as const;
 if(!ready)return <div className="office-loading">{say('Opening your desk…','بنفتح مكتبك…')}</div>;
 return <div className={`mizan-game ${s.upgrades.includes('lamp')?'office-lit':''} ${s.upgrades.includes('organizer')?'office-organized':''} ${s.active?'playing':''}`} dir={ar?'rtl':'ltr'}>
  <header className="mizan-top"><Link href={`/${locale}`} className="mizan-brand">D<span>&</span>C <small>by Money Coder</small></Link><span className="company-wordmark">MIZAN <small>{say('TRADING · YOUR COMPANY','للتجارة · شركتك')}</small></span><Link className="language-switch" href={`/${locale}/account-guide`} target="_blank" rel="noopener noreferrer">{say("Nature of Accounts","طبيعة الحسابات")}</Link><Link className="language-switch" href={`/${ar?'en':'ar'}${view==='office'?'':`/${view==='employer'?'companies':view}`}`}>{ar?'EN':'عربي'}</Link></header>
  {view!=='employer'&&<div className="player-hud"><span><Flag size={15}/>{say('CH','فصل')} {chapter}/8</span><span><Zap size={15}/>{s.xp} XP</span><span><Coins size={15}/>{s.coins}</span><span><Flame size={15}/>{streak(s)}</span><span className="rank-label">{summary.ready?say('Junior Accountant Ready','جاهز كمحاسب مبتدئ'):say('Accounting trainee','متدرب محاسبة')}</span></div>}
  {s.storageWarning&&<p role="alert">{say('Browser storage is unavailable. Progress will be lost if you close this tab.','تخزين المتصفح غير متاح. لو قفلت الصفحة التقدم هيتفقد.')}</p>}
  <main className="mizan-main">
  {view==='office'&&<>
   <div className="scene-heading"><div><p className="eyebrow">{say('DAY','يوم')} {chapter} / {t(chapters[chapter-1])}</p><h1>{m?t(m.title):say('Your shift is waiting.','ورديتك مستنياك.')}</h1></div>{!m&&next&&<button className="play-button header-play" onClick={launch}>{say('START SHIFT','ابدأ الوردية')}</button>}<span className="shift-status"><i/>{say('Mizan is open','ميزان فاتحة')}</span></div>
   <section className="office-scene" aria-label={say('Interactive accounting desk','مكتب المحاسبة التفاعلي')}>
    <div className="office-window"><div className="city-skyline"/><span>MIZAN / {say('FINANCE OFFICE','مكتب الحسابات')}</span></div>
    <div className="manager-message"><span className="avatar">OM</span><div><small>{m?t(m.speaker):say('Omar · Finance manager','عمر · المدير المالي')}</small><p>{m?t(m.message):next?t(next.message):say('The month is closed. Your evidence file is ready to review.','الشهر اتقفل. ملف أدائك جاهز للمراجعة.')}</p></div></div>
    <div className="desk-surface">
     <button className="desk-object tray-object" onClick={()=>{launch();setObject('documents');}}><span className="paper-stack"><FileText/><b>{stage?.documentIds?.length??3}</b></span><strong>{say('INCOMING','الوارد')}</strong><small>{say('Inspect the evidence','افتح المستندات')}</small></button>
     <button className="desk-object journal-object" onClick={()=>setObject('journal')}><BookOpen/><strong>{say('JOURNAL','اليومية')}</strong><small>{s.journal.length} {say('accepted entries','قيود مقبولة')}</small></button>
     <button className="desk-object ledger-object" onClick={()=>setObject('ledger')}><Archive/><strong>{say('LEDGER','الأستاذ')}</strong><small>INV-014 → {say('balances','أرصدة')}</small></button>
     <button className="desk-object cash-object" onClick={()=>setObject('cash')}><Coins/><strong>{world.cash.toLocaleString(locale)}</strong><small>{say('CASH DRAWER · EGP','الصندوق · جنيه')}</small></button>
     <button className="desk-object bank-object" onClick={()=>setObject('bank')}><FileText/><strong>{say('BANK','البنك')}</strong><small>{world.bank.toLocaleString(locale)} {say('EGP','جنيه')}</small></button>
     <button className="desk-object calculator-object" onClick={()=>setObject('calculator')}><Calculator/><strong>{say('CALCULATOR','الآلة الحاسبة')}</strong></button>
    </div>
    <div className="desk-bottom"><span>{say('Supplier debt','مديونية الموردين')}: {(-world.balances.suppliers).toLocaleString(locale)}</span><span>{say('Loss so far','الخسارة الحالية')}: {world.loss.toLocaleString(locale)}</span><span>{s.reconciled.includes('cash')?'✓ ':''}{say('Accepted transactions only','عمليات مقبولة فقط')}</span></div>
   </section>
   {!m&&<section className="shift-start"><div><p className="eyebrow">{next?t(next.title):say('CAMPAIGN COMPLETE','الحكاية اكتملت')}</p><h2>{next?say('Make this desk yours.','المكتب ده مسؤوليتك.'):say('Review your career evidence.','راجع أدلة مهاراتك.')}</h2><p>{say('Inspect. Decide. Record. See what changes.','افحص. قرر. سجّل. وشوف النتيجة.')}</p></div>{next?<button className="play-button" onClick={launch}>{say('START SHIFT','ابدأ الوردية')} <ChevronRight/></button>:<Link className="play-button" href={`/${locale}/profile`}>{say('Open career card','افتح بطاقة المسار')}</Link>}</section>}
   {m&&stage&&s.active&&<section className={`mission-console ${s.active.feedback??''}`} aria-label={say('Active mission','المهمة الحالية')}>
    <div className="mission-rail"><span>{m.boss?<Trophy/>:<Briefcase/>}{m.boss?say('BOSS CASE','مواجهة'):say('LIVE TASK','مهمة شغالة')}</span><span>{s.active.stage+1}/{m.stages.length} · {m.difficulty===1?say('Easy','سهل'):m.difficulty===2?say('Medium','متوسط'):say('Hard','صعب')}</span><span>+{m.reward.xp} XP / +{m.reward.coins} <Coins size={15}/></span></div>
    <div className="stage-track">{m.stages.map((st,i)=><span key={st.id} className={i<s.active!.stage?'done':i===s.active!.stage?'current':''}/>)}</div>
    <div className="task-title"><span className="task-number">{String(s.active.stage+1).padStart(2,'0')}</span><div><h2>{t(stage.title)}</h2><p>{t(stage.prompt)}</p></div></div>
    {stage.documentIds&&<div className="evidence-strip">{stage.documentIds.map(id=>{const d=documents.find(d=>d.id===id)!;return <button key={id} onClick={()=>{change(st=>inspectDocument(st,id));setObject(id);}}><FileText/><span>{id}<small>{t(d.title)}</small></span>{s.active?.inspected.includes(id)&&<Check/>}</button>;})}</div>}
    {!s.active.passed&&<div className="task-controls">
     {stage.kind==='inspect'&&<p>{say('Open every paper above, then accept the file.','افتح كل ورقة فوق، وبعدين اقبل الملف.')}</p>}
     {stage.kind==='sort'&&stage.documentIds?.map((id,i)=><label className="sort-row" key={id}><span>{t(documents.find(d=>d.id===id)!.title)}</span><select aria-label={id} value={s.active!.draft.split(',')[i]??''} onChange={e=>{const a=s.active!.draft.split(',');a[i]=e.target.value;change(st=>editDraft(st,Array.from({length:stage.documentIds!.length},(_,j)=>a[j]??'').join(',')));}}><option value="">{say('Choose tray','اختار الدرج')}</option>{categories.map(([id,label])=><option key={id} value={id}>{t(label)}</option>)}</select></label>)}
     {stage.kind==='choice'&&<div className="decision-options">{stage.options?.map(o=><button aria-pressed={s.active!.draft===o.id} className={s.active!.draft===o.id?'selected':''} key={o.id} onClick={()=>change(st=>editDraft(st,o.id))}>{t(o.label)}</button>)}</div>}
     {stage.kind==='number'&&<label className="number-answer">{say('Control amount · EGP','مبلغ الرقابة · جنيه')}<input inputMode="decimal" type="number" value={s.active.draft} onChange={e=>change(st=>editDraft(st,e.target.value))} placeholder="0"/></label>}
     {stage.kind==='journal'&&<JournalBuilder locale={locale} draft={s.active.draft} onChange={draft=>change(st=>editDraft(st,draft))}/>}
    </div>}
    {s.active.feedback&&<div className={`consequence ${s.active.feedback}`} role="status"><strong>{s.active.passed?say('Accepted. The company file is updated.','مقبول. ملف الشركة اتحدّث.'):say('Hold the approval. Something is wrong.','وقف الاعتماد. فيه حاجة غلط.')}</strong><p>{s.active.passed?say('This result is saved. Continue to your next responsibility.','النتيجة محفوظة. كمّل للمسؤولية التالية.'):t(stage.consequence)}</p></div>}
    {s.active.hints>0&&<p className="hint-text">{t(stage.hint)} <small>({say('Help recorded','المساعدة مسجلة')})</small></p>}
    <div className="mission-actions">{s.active.passed?<button className="play-button" onClick={()=>change(st=>continueMission(st))}>{s.active.stage===m.stages.length-1?say('FINISH SHIFT · CLAIM REWARD','سلّم الوردية · استلم المكافأة'):say('CONTINUE','كمّل')}<ChevronRight/></button>:<button className="play-button" onClick={()=>change(st=>submitStage(st))}>{stage.kind==='inspect'?say('ACCEPT FILE','اقبل الملف'):say('CHECK MY WORK','راجع شغلي')}<Check/></button>}<button className="quiet-button" disabled={s.active.passed} onClick={()=>change(st=>recordHint(st))}>{say('Ask Omar','اسأل عمر')}</button><Link className="quiet-button" onClick={()=>change(st=>recordHint(st))} href={`/${locale}/account-guide`}>{say('Accounting manual','دليل الحسابات')}</Link><small>{say('Auto-saved · retries and help are recorded','محفوظ تلقائيًا · الإعادات والمساعدة مسجلة')}</small></div>
   </section>}
   {!m&&Object.keys(s.completed).length>0&&<div className="recent-unlock"><Trophy/><span>{say('Desk cleared. New responsibilities unlocked. Replay a case on the campaign map to improve mastery.','المكتب اتسلّم. مسؤوليات جديدة اتفتحت. تقدر تعيد مواجهة من الحكاية لتحسين الإتقان.')}</span></div>}
  </>}
  {view==='campaign'&&<><div className="scene-heading"><div><p className="eyebrow">MIZAN / {say('YOUR STORY','حكايتك')}</p><h1>{say('From your first desk to the CFO’s door.','من أول مكتب لحد باب المدير المالي.')}</h1></div></div><div className="story-map">{chapters.map((c,i)=><section className={`story-chapter ${i+1===chapter?'active':''}`} key={c.en}><div className="chapter-marker">{i+1<chapter?<Check/>:i+1}</div><div className="chapter-world"><span className="eyebrow">{say('CHAPTER','فصل')} 0{i+1}</span><h2>{t(c)}</h2><div className="chapter-missions">{missions.filter(m=>m.chapter===i+1).map(m=>{const open=unlocked(s,m),r=s.completed[m.id];return <div className={`story-node ${r?'complete':''} ${!open?'locked':''}`} key={m.id}><span>{!open?<Lock/>:m.boss?<Trophy/>:<Briefcase/>}</span><div><strong>{t(m.title)}</strong><small>{r?`${r.bestScore}% · ${'★'.repeat(r.stars)} · ${say('first','الأولى')} ${r.firstScore}%`:open?say('Ready at your desk','جاهزة على مكتبك'):say('Previous case mastery ≥70% required','مطلوب إتقان المواجهة السابقة ≥٧٠٪')}</small></div>{open?<Link href={`/${locale}`} onClick={()=>change(st=>startMission(st,m.id))}>{s.active?say('Resume','كمّل'):r?say('Replay','إعادة'):say('Play','العب')}<ChevronRight/></Link>:null}</div>;})}</div></div></section>)}</div></>}
  {view==='arena'&&<ArcadePanel locale={locale}/>}
  {(view==='profile'||view==='employer')&&<><div className="scene-heading"><div><p className="eyebrow">{view==='employer'?say('EMPLOYER PREVIEW · LOCAL / UNVERIFIED','معاينة صاحب العمل · محلي / غير موثق'):say('GAME PROFILE','ملف اللعبة')}</p><h1>{s.name||say('Mizan’s next accountant','محاسب ميزان القادم')}</h1><p>{view==='profile'?say('Your game progress and in-game performance. Professional identity and CV live in Career Profile.','تقدمك وأداؤك داخل اللعبة. الهوية المهنية والسيرة الذاتية موجودتان في الملف المهني.'):say('Gameplay evidence, not an accredited qualification or hiring guarantee.','أدلة أداء داخل اللعبة، مش اعتماد مهني أو ضمان توظيف.')}</p></div><ShieldCheck size={48}/></div>
   {view==='profile'&&<label className="player-name">{say('Player name','اسم اللاعب')}<input value={s.name} maxLength={60} onChange={e=>change(st=>({...st,name:e.target.value}))}/></label>}
   <div className="career-scoreboard"><span><b>{summary.readiness}%</b>{say('In-game mastery','إتقان داخل اللعبة')}</span><span><b>{summary.independent}%</b>{say('Independent first attempts','محاولات أولى مستقلة')}</span><span><b>{summary.accuracy}%</b>{say('First-attempt accuracy','دقة المحاولة الأولى')}</span><span><b>{summary.bosses}/8</b>{say('Bosses mastered','مواجهات متقنة')}</span></div>
   <section className="evidence-file"><h2>{say('What your work proves','شغلك بيثبت إيه')}</h2>{Object.entries(summary.skills).map(([id,v])=><div className="skill-evidence" key={id}><strong>{({analysis:say('Transaction analysis','تحليل العمليات'),journal:say('Journal entries','القيود اليومية'),posting:say('Ledger & trial balance','الأستاذ وميزان المراجعة'),reconciliation:say('Reconciliation','التسويات والمطابقة'),adjustments:say('Adjustments','قيود التسوية'),statements:say('Financial statements','القوائم المالية'),investigation:say('Error detection','اكتشاف الأخطاء')} as Record<string,string>)[id]}</strong><meter min="0" max="100" value={v.score}/><b>{v.score}%</b><small>{v.count} {say('unique activities','أنشطة فريدة')} · {v.independent} {say('independent','مستقلة')} · {v.hard} {say('hard passed','صعبة ناجحة')}</small></div>)}</section>
   <section className="evidence-file"><h2>{say('Promotion file','ملف الترقية')}</h2><p>{summary.ready?say('Junior Accountant Ready · in-game achievement unlocked.','جاهز كمحاسب مبتدئ · إنجاز داخل اللعبة اتفتح.'):say('Promotion requires the full month-end file, ≥70% first-run score and ≥80% readiness. XP cannot buy it.','الترقية تتطلب ملف نهاية الشهر، ≥٧٠٪ في أول جولة و≥٨٠٪ جاهزية. نقاط XP مش بديل.')}</p><p>{say('Final file','الملف النهائي')}: {s.completed['month-end-file']?.firstScore??'—'}% · {say('Recorded hints','التلميحات المسجلة')}: {summary.hints}</p><button className="quiet-button" onClick={()=>{const blob=new Blob([JSON.stringify(candidateEvidence(s),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='debit-credit-skill-evidence.json';a.click();URL.revokeObjectURL(url);}}>{say('Export my evidence JSON','نزّل أدلة أدائي JSON')}</button>{summary.ready&&<button className="quiet-button" onClick={()=>window.print()}>{say('Print achievement record (not accredited)','اطبع سجل الإنجاز (غير معتمد)')}</button>}</section>
   {view==='profile'&&<section className="office-shop"><h2>{say('Make the office yours','طوّر مكتبك')}</h2>{(['lamp','organizer'] as const).map(id=><button key={id} disabled={s.upgrades.includes(id)||s.coins<50} onClick={()=>change(st=>upgradeOffice(st,id))}>{id==='lamp'?say('Desk lighting','إضاءة المكتب'):say('Document organizer','منظّم المستندات')} · {s.upgrades.includes(id)?'✓':'50 ◉'}</button>)}<Link href={`/${locale}/career-profile`}>{say('Open Professional Career Profile','افتح الملف المهني الاحترافي')}</Link></section>}
   {view==='employer'&&<p className="employer-disclaimer">{say('Only this browser’s player is shown. No accounts, recruitment, sharing service or live candidate search. Future challenges require server-validated attempts and consent.','المعروض لاعب المتصفح ده فقط. مفيش حسابات شركات أو توظيف أو خدمة مشاركة أو بحث حي. التحديات المستقبلية تحتاج تحقق بالخادم وموافقة اللاعب.')}</p>}
   <details className="evidence-file"><summary>{say('Attempt history — first and later attempts','سجل المحاولات — الأولى وما بعدها')} ({s.evidence.length})</summary>{s.evidence.slice(-80).map((e,i)=><p key={i}><code>{e.activityId}</code> · {e.correct?'✓':'✕'} · {e.score}% · {e.completionTime.toFixed(0)}s · {say('hints','تلميحات')} {e.hintsUsed} · {e.mode}</p>)}</details>
  </>}
  </main>
  <nav className="office-nav" aria-label={say('Game navigation','تنقل اللعبة')}>{nav.map(([path,Icon,label])=><Link key={path} href={`/${locale}${path?`/${path}`:''}`} aria-current={(view==='office'&&!path)||view===path?'page':undefined}><Icon/><span>{label}</span></Link>)}</nav>
  {object&&<div className="desk-modal-backdrop" onClick={()=>setObject(null)}><section ref={dialogRef} className="desk-modal" role="dialog" aria-modal="true" aria-label={say('Desk object','عنصر المكتب')} onClick={e=>e.stopPropagation()}><button className="close-object" aria-label={say('Close','إغلاق')} onClick={()=>setObject(null)}><X/></button>
   {documents.find(d=>d.id===object)?(()=>{const d=documents.find(d=>d.id===object)!;return <article className="real-document"><p>MIZAN / {d.id}</p><h2>{t(d.title)}</h2><small>{t(d.issuer)}</small><hr/><p>{t(d.detail)}</p><strong>{d.amount.toLocaleString(locale)} {say('EGP','جنيه')}</strong><div className="document-stamp">{say('SOURCE EVIDENCE','مستند أصلي')}</div><button className="play-button" onClick={()=>setObject(null)}>{say('Back to task','ارجع للمهمة')}</button></article>;})():null}
   {object==='documents'&&<><h2>{say('Incoming documents','المستندات الواردة')}</h2>{(activeStage(s)?.documentIds??['CAP-001','INV-014','RENT-01']).map(id=><button className="document-list-item" key={id} onClick={()=>{change(st=>inspectDocument(st,id));setObject(id);}}><FileText/>{id} · {t(documents.find(d=>d.id===id)!.title)}</button>)}</>}
   {(object==='journal'||object==='ledger')&&<><h2>{object==='journal'?say('Accepted journal','اليومية المقبولة'):say('Company balances','أرصدة الشركة')}</h2>{object==='journal'?s.journal.map(j=><div className="journal-record" key={j.id}><strong>{j.documentIds.join(' / ')}</strong>{j.lines.map(l=><p key={l.account}>{t(accounts[l.account])} · {l.debit||l.credit} {l.debit?say('Dr','مدين'):say('Cr','دائن')}</p>)}</div>):Object.entries(balances(s)).filter(([,v])=>v!==0).map(([a,v])=><p key={a}>{t(accounts[a as Account])}: {Math.abs(v).toLocaleString(locale)} {v>0?say('Dr','مدين'):say('Cr','دائن')}</p>)}{!s.journal.length&&<p>{say('No accepted entries yet. Your first document starts here.','لسه مفيش قيود مقبولة. البداية بأول مستند.')}</p>}</>}
   {(object==='cash'||object==='bank')&&<><h2>{object==='cash'?say('Cash drawer','الصندوق'):say('Bank position','موقف البنك')}</h2><div className="cash-count">{(object==='cash'?world.cash:world.bank).toLocaleString(locale)} <small>EGP</small></div><p>{say('Balance derived from your accepted journal entries. Draft mistakes never silently overwrite the books.','الرصيد محسوب من قيودك المقبولة. غلطات المسودة مش بتتكتب خفية في الدفاتر.')}</p></>}
   {object==='calculator'&&<><h2>{say('Desk calculator','حاسبة المكتب')}</h2><div className="desk-calculator"><input aria-label={say('First number','الرقم الأول')} type="number" value={calc.a} onChange={e=>setCalc({...calc,a:e.target.value})}/><select aria-label={say('Operation','العملية')} value={calc.op} onChange={e=>setCalc({...calc,op:e.target.value})}><option>+</option><option>-</option><option>×</option></select><input aria-label={say('Second number','الرقم الثاني')} type="number" value={calc.b} onChange={e=>setCalc({...calc,b:e.target.value})}/><output>{calc.op==='+'?Number(calc.a)+Number(calc.b):calc.op==='-'?Number(calc.a)-Number(calc.b):Number(calc.a)*Number(calc.b)}</output></div></>}
  </section></div>}
 </div>;
}
