export type LocalizedText={ar:string;en:string};
export type SkillId='accounting-fundamentals'|'account-classification'|'debit-credit'|'document-analysis'|'journal-entries'|'ledger-posting'|'trial-balance'|'error-detection'|'bank-reconciliation'|'accounts-payable'|'accounts-receivable'|'cash-treasury'|'adjusting-entries'|'financial-statements'|'month-end-closing'|'inventory-accounting'|'cost-accounting'|'expense-recognition'|'supplier-documents';
export type SkillStatus='unassessed'|'practiced'|'demonstrated'|'verified';
export type EvidenceSource='game'|'mission'|'boss_case'|'arena'|'verified_assessment';
export type EvidenceIntegrity='practice'|'demonstrated'|'verified_local_beta'|'verified_server';
export type EvidenceDifficulty=1|2|3;
export type RoleId='junior-accountant'|'general-accountant'|'ap-accountant'|'ar-accountant'|'treasury-accountant'|'cost-accountant'|'inventory-accountant'|'gl-accountant'|'junior-auditor';
export type Visibility='private'|'link'|'companies_future';
export type WorkType='onsite'|'hybrid'|'remote'|'flexible';
export type ExperienceLevel='student'|'fresh-graduate'|'junior'|'mid'|'senior';
export interface EducationRecord{id:string;institution:string;degree:string;field:string;graduationYear:string}
export interface ExperienceRecord{id:string;company:string;title:string;startDate:string;endDate:string;current:boolean;description:string}
export interface CareerPrivacy{visibility:Visibility;showEmail:boolean;showPhone:boolean;showLocation:boolean;showEducation:boolean;showExperience:boolean;showSkillScores:boolean;showSimulationResults:boolean}
export interface CareerProfile{version:1;localCandidateId:string;slug:string;fullName:string;headline:string;targetRoleId:RoleId;country:string;location:string;email:string;phone:string;linkedIn:string;portfolio:string;education:EducationRecord[];experience:ExperienceRecord[];graduationYear:string;experienceLevel:ExperienceLevel;yearsOfExperience:number;languages:string[];employmentStatus:string;openToWork:boolean;preferredWorkType:WorkType;preferredLocation:string;summary:string;privacy:CareerPrivacy;onboardingStep:number;completed:boolean;updatedAt:string}
export interface SkillEvidence{version:1;projectionVersion?:1|2;evidenceId:string;localCandidateId:string;activityId:string;activityType:'document'|'case'|'mission'|'arena'|'assessment';chapterId:number;missionId:string;skillId:SkillId;roleRelevance:RoleId[];difficulty:EvidenceDifficulty;score:number;accuracy:number;firstAttemptCorrect:boolean|null;attempts:number;hintsUsed:number;independentCompletion:boolean;criticalErrors:number;completedAt:string;source:EvidenceSource;assessmentIntegrity:EvidenceIntegrity;titleAr:string;titleEn:string;caseId?:string|null;attemptId?:string|null;scenarioVersion?:number|null;rubricVersion?:number|null;inspectedEvidence?:string[];decisionTrace?:string[];performance?:Partial<Record<'accuracy'|'independence'|'investigation'|'riskAwareness'|'documentation'|'accountingJudgment',number>>;rationaleAr?:string;rationaleEn?:string}
export interface SkillResult{skillId:SkillId;status:SkillStatus;score:number|null;confidence:'insufficient'|'developing'|'strong'|'extensive';evidenceCount:number;uniqueActivities:number;successfulActivities:number}
export interface RoleReadiness{roleId:RoleId;score:number|null;coverage:number;status:'not_enough_evidence'|'developing'|'ready';evaluatedSkills:number}
export interface CvPreferences{version:1;targetRoleId:RoleId;accent:'navy'|'blue'|'green';includeScores:boolean;updatedAt:string}
export interface CvDocument{targetRoleId:RoleId;headline:string;summary:string;skills:SkillResult[];evidence:SkillEvidence[];sections:string[]}
export interface FutureAssessmentReference{assessmentId:string;attemptId:string;assessmentVersion:string;verifiedAccountingScore:number|null;criticalErrors:number;independentAccuracy:number|null;timeUsedSeconds:number|null;integrity:'verified_local_beta'|'verified_server'}
export interface FutureHiringReference{candidateId:string;companyId:string;jobId:string;applicationId:string;challengeId:string;assessmentId:string;shortlistStatus:string;interviewStatus:string}
