import type{CareerProfile,CvPreferences,RoleId,SkillEvidence}from'./model';
export const CAREER_PROFILE_KEY='debit-credit-career-profile-v1',SKILL_EVIDENCE_KEY='debit-credit-skill-evidence-v1',CV_PREFERENCES_KEY='debit-credit-cv-preferences-v1',LOCAL_CANDIDATE_KEY='debit-credit-local-candidate-id-v1';
export interface CareerProfileRepository{get():CareerProfile|null;save(profile:CareerProfile):void;clear():void}
export interface SkillEvidenceRepository{getAll():SkillEvidence[];merge(evidence:SkillEvidence[]):SkillEvidence[];clear():void}
export interface CvPreferencesRepository{get():CvPreferences|null;save(value:CvPreferences):void}
const storage=()=>typeof window==='undefined'?null:window.localStorage;
export function getOrCreateLocalCandidateId(){const s=storage();if(!s)return'local-preview';const current=s.getItem(LOCAL_CANDIDATE_KEY);if(current)return current;const id=`local_${typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)}`;s.setItem(LOCAL_CANDIDATE_KEY,id);return id}
export function createDefaultProfile(name='',role:RoleId='junior-accountant'):CareerProfile{const id=getOrCreateLocalCandidateId();return{version:1,localCandidateId:id,slug:`candidate-${id.replace(/[^a-z0-9]/gi,'').slice(-10).toLowerCase()}`,fullName:name,headline:'',targetRoleId:role,country:'',location:'',email:'',phone:'',linkedIn:'',portfolio:'',education:[],experience:[],graduationYear:'',experienceLevel:'fresh-graduate',yearsOfExperience:0,languages:[],employmentStatus:'',openToWork:false,preferredWorkType:'flexible',preferredLocation:'',summary:'',privacy:{visibility:'private',showEmail:false,showPhone:false,showLocation:true,showEducation:true,showExperience:true,showSkillScores:true,showSimulationResults:true},onboardingStep:1,completed:false,updatedAt:new Date().toISOString()}}
export class BrowserCareerProfileRepository implements CareerProfileRepository{get(){try{const raw=storage()?.getItem(CAREER_PROFILE_KEY);return raw?JSON.parse(raw)as CareerProfile:null}catch{return null}}save(profile:CareerProfile){storage()?.setItem(CAREER_PROFILE_KEY,JSON.stringify({...profile,version:1,updatedAt:new Date().toISOString()}))}clear(){storage()?.removeItem(CAREER_PROFILE_KEY)}}
export class BrowserSkillEvidenceRepository implements SkillEvidenceRepository{getAll(){try{const raw=storage()?.getItem(SKILL_EVIDENCE_KEY);return raw?JSON.parse(raw)as SkillEvidence[]:[]}catch{return[]}}merge(incoming:SkillEvidence[]){const map=new Map(this.getAll().map(e=>[e.evidenceId,e]));for(const e of incoming)map.set(e.evidenceId,e);const result=[...map.values()].sort((a,b)=>a.completedAt.localeCompare(b.completedAt));storage()?.setItem(SKILL_EVIDENCE_KEY,JSON.stringify(result));return result}clear(){storage()?.removeItem(SKILL_EVIDENCE_KEY)}}
export class BrowserCvPreferencesRepository implements CvPreferencesRepository{get(){try{const raw=storage()?.getItem(CV_PREFERENCES_KEY);return raw?JSON.parse(raw)as CvPreferences:null}catch{return null}}save(value:CvPreferences){storage()?.setItem(CV_PREFERENCES_KEY,JSON.stringify(value))}}
