export type BankSide='statement'|'book';
export type DifferenceKind='timing'|'book-adjustment'|'investigate';
export type BankAccount='bank'|'bank-charges'|'accounts-receivable';
export interface BankTransaction{id:string;side:BankSide;date:string;reference:string;description:{en:string;ar:string};amount:number;matchId?:string;difference?:DifferenceKind}
export interface BankJournal{itemId:string;debit:BankAccount;credit:BankAccount;amount:number}
export interface BankWorkpaper{version:1;matches:Record<string,string>;classifications:Record<string,DifferenceKind>;journals:BankJournal[];attempts:number;completedAt:string|null;firstAttemptQualified:boolean}
export const bankScenario={id:'mizan-bank-recon-v1',version:1,openingBalance:100000,statementBalance:125750,bookBalance:125000,transactions:[
 {id:'s-receipt',side:'statement',date:'2026-09-03',reference:'BNK-301',description:{en:'Customer transfer — Delta',ar:'تحويل عميل — دلتا'},amount:40000,matchId:'b-receipt'},
 {id:'s-supplier',side:'statement',date:'2026-09-05',reference:'BNK-305',description:{en:'Supplier payment — Atlas',ar:'سداد مورد — أطلس'},amount:-18000,matchId:'b-supplier'},
 {id:'s-fee',side:'statement',date:'2026-09-29',reference:'BNK-329',description:{en:'Bank service charge',ar:'رسوم خدمة بنكية'},amount:-250,difference:'book-adjustment'},
 {id:'s-direct',side:'statement',date:'2026-09-30',reference:'BNK-330',description:{en:'Direct customer deposit',ar:'إيداع مباشر من عميل'},amount:4000,difference:'book-adjustment'},
 {id:'b-receipt',side:'book',date:'2026-09-03',reference:'GL-108',description:{en:'Delta receipt',ar:'تحصيل دلتا'},amount:40000,matchId:'s-receipt'},
 {id:'b-supplier',side:'book',date:'2026-09-05',reference:'GL-112',description:{en:'Atlas payment',ar:'سداد أطلس'},amount:-18000,matchId:'s-supplier'},
 {id:'b-transit',side:'book',date:'2026-09-30',reference:'GL-130',description:{en:'Deposit in transit',ar:'إيداع بالطريق'},amount:6000,difference:'timing'},
 {id:'b-cheque',side:'book',date:'2026-09-30',reference:'GL-131',description:{en:'Outstanding cheque',ar:'شيك لم يُصرف'},amount:-3000,difference:'timing'},
] as BankTransaction[]};
export const newBankWorkpaper=():BankWorkpaper=>({version:1,matches:{},classifications:{},journals:[],attempts:0,completedAt:null,firstAttemptQualified:false});
export const bankItem=(id:string)=>bankScenario.transactions.find(item=>item.id===id);
export function matchBankItems(work:BankWorkpaper,statementId:string,bookId:string):BankWorkpaper{const a=bankItem(statementId),b=bankItem(bookId);if(!a||!b||a.side!=='statement'||b.side!=='book'||a.id===b.id||Object.values(work.matches).includes(bookId))return work;return{...work,matches:{...work.matches,[statementId]:bookId}}}
export function classifyBankItem(work:BankWorkpaper,id:string,kind:DifferenceKind):BankWorkpaper{const item=bankItem(id);if(!item||item.matchId)return work;return{...work,classifications:{...work.classifications,[id]:kind}}}
export function setBankJournal(work:BankWorkpaper,journal:BankJournal):BankWorkpaper{const item=bankItem(journal.itemId);if(!item||item.side!=='statement'||!item.difference||!Number.isFinite(journal.amount)||journal.amount<=0)return work;return{...work,journals:[...work.journals.filter(row=>row.itemId!==journal.itemId),journal]}}
export function bankReconciliation(work:BankWorkpaper){const matched=bankScenario.transactions.filter(item=>item.side==='statement'&&item.matchId).every(item=>work.matches[item.id]===item.matchId);const classification=bankScenario.transactions.filter(item=>item.difference).every(item=>work.classifications[item.id]===item.difference);const fee=work.journals.find(row=>row.itemId==='s-fee'),direct=work.journals.find(row=>row.itemId==='s-direct');const feeCorrect=fee?.debit==='bank-charges'&&fee.credit==='bank'&&fee.amount===250,directCorrect=direct?.debit==='bank'&&direct.credit==='accounts-receivable'&&direct.amount===4000;const adjustedStatement=bankScenario.statementBalance+(work.classifications['b-transit']==='timing'?6000:0)-(work.classifications['b-cheque']==='timing'?3000:0),adjustedBook=bankScenario.bookBalance+(directCorrect?4000:0)-(feeCorrect?250:0);return{matched,classification,journalsCorrect:Boolean(feeCorrect&&directCorrect),adjustedStatement,adjustedBook,difference:adjustedStatement-adjustedBook,reconciled:matched&&classification&&Boolean(feeCorrect&&directCorrect)&&adjustedStatement===adjustedBook}}
export function submitBankWorkpaper(work:BankWorkpaper,at=new Date().toISOString()):BankWorkpaper{if(work.completedAt&&bankReconciliation(work).reconciled)return work;const result=bankReconciliation(work),attempts=work.attempts+1;return{...work,attempts,completedAt:result.reconciled?at:work.completedAt,firstAttemptQualified:result.reconciled&&attempts===1}}
export function restoreBankWorkpaper(raw:string|null):BankWorkpaper{if(!raw)return newBankWorkpaper();try{const value=JSON.parse(raw)as Partial<BankWorkpaper>;if(value.version!==1||!value.matches||!value.classifications||!Array.isArray(value.journals))return newBankWorkpaper();return{...newBankWorkpaper(),...value}}catch{return newBankWorkpaper()}}
