"use client";
import Link from "next/link";
import { ArrowRight, Award, Check, Coins, FileSearch, Flame, Gift, Play, ShieldCheck, Swords, Target, Trophy, Zap } from "lucide-react";
import { usePlayer } from "@/components/game/use-player";
import { WorldMap } from "@/components/game/world-map";
import { learningLevels, levelThresholds, skillLabels } from "@/data/game";
import { missions } from "@/data/missions";
import type { Locale } from "@/types";

export function ProductLanding({locale}:{locale:Locale}) {
  const ar=locale==="ar", player=usePlayer(), level=learningLevels[player.level-1];
  const mission=missions.find(item=>!player.activities[`mission:${item.id}`])??missions[0];
  const today=new Date().toISOString().slice(0,10), daily=Object.values(player.activities).filter(item=>item.completedAt.startsWith(today));
  const skills=Object.entries(player.skillScores).sort(([,a],[,b])=>b-a).slice(0,3);
  const nextReward=[
    ["first-step","شارة الخطوة الأولى","First Step badge","أكمل أي نشاط لفتح أول شارة.","Complete any activity to unlock your first badge."],
    ["journal-master","شارة خبير القيود","Journal Master badge","حقق 80% في مهارة القيود اليومية.","Reach 80% in Journal Entries."],
    ["accounting-detective","شارة المحقق المحاسبي","Accounting Detective badge","حقق 80% في اكتشاف الأخطاء.","Reach 80% in Error Detection."],
    ["seven-day-streak","شارة المثابرة","7-Day Streak badge","العب 7 أيام متتالية.","Play for 7 consecutive days."],
  ].find(([id])=>!player.badges.includes(id));
  const url=(path:string)=>`/${locale}${path}`;
  return <div className="game-command">
    <header className="command-title"><div><span className="world-eyebrow">DEBIT & CREDIT / {ar?"رحلة المحاسب":"ACCOUNTANT CAMPAIGN"}</span><h1>{ar?"مركز قيادة اللاعب":"Player command center"}</h1></div><Link href={url("/profile")} className="world-rank"><ShieldCheck/>{ar?"المستوى":"LEVEL"} {player.level}</Link></header>
    <div className="command-layout">
      <section className="world-panel command-map"><header className="world-panel-title"><span><Target/>{ar?"خريطة الرحلة":"Learning map"}</span><Link href={url("/learning-map")}>{ar?"استكشف":"Explore"}<ArrowRight/></Link></header><WorldMap locale={locale}/><footer className="map-loot"><Trophy/><span>{ar?"المحطة الحالية":"CURRENT CHECKPOINT"}<b>{ar?level.titleAr:level.titleEn}</b></span><strong>{player.level}/8</strong></footer></section>
      <div className="command-core">
        <section className="world-panel player-console"><header><div className="world-avatar">{player.displayName.slice(0,1).toUpperCase()}<span>{player.level}</span></div><div><small className="world-eyebrow">{ar?"مرحبًا بعودتك، محاسب":"WELCOME BACK, ACCOUNTANT"}</small><h2>{player.displayName}</h2><p>{ar?level.titleAr:level.titleEn}</p></div></header><div className="console-stats"><div><Zap/><b>{player.xp}</b><small>XP</small></div><div><Coins/><b>{player.coins}</b><small>{ar?"عملات":"Coins"}</small></div><div><Flame/><b>{player.streak}</b><small>{ar?"أيام متتالية":"Day streak"}</small></div><div><Trophy/><b>{player.badges.length}</b><small>{ar?"شارات":"Badges"}</small></div></div><div className="world-progress"><span><b>{ar?"التقدم للمستوى التالي":"Progress to next level"}</b><strong>{player.levelProgress}%</strong></span><i><b style={{width:`${player.levelProgress}%`}}/></i><small>{player.level===8?(ar?"وصلت للوضع الاحترافي":"Professional mode reached"):`${levelThresholds[player.level]-player.xp} XP ${ar?"لفتح المستوى التالي":"to next unlock"}`}</small></div></section>
        <section className="world-panel active-quest"><header className="world-panel-title"><span><Target/>{ar?"المهمة الحالية":"CURRENT MISSION"}</span><em>{mission.difficulty==="beginner"?(ar?"مبتدئ":"Beginner"):(ar?"متوسط":"Intermediate")}</em></header><div className="quest-body"><div className="quest-seal"><ShieldCheck/><small>CASE {mission.caseNumber}</small></div><div><h2>{ar?mission.titleAr:mission.titleEn}</h2><p>{ar?mission.descriptionAr:mission.descriptionEn}</p></div></div><div className="quest-rewards"><span><Zap/>+100 XP</span><span><Coins/>+35</span><small>{mission.estimatedMinutes} {ar?"دقائق":"min"}</small></div><Link className="world-button" href={url(`/missions/${mission.slug}`)}><Play/>{ar?"ابدأ المهمة":"Start mission"}<ArrowRight/></Link></section>
        <section className="world-panel continue-quest"><div className="quest-icon"><Play/></div><div><small className="world-eyebrow">{ar?"أكمل تقدمك":"CONTINUE LEARNING"}</small><h2>{ar?player.currentObjective.titleAr:player.currentObjective.titleEn}</h2><span>+{player.currentObjective.rewardXp} XP · +{player.currentObjective.rewardCoins} {ar?"عملات":"coins"}</span></div><Link className="world-button" href={url(player.currentObjective.route)}>{ar?"متابعة":"Continue"}<ArrowRight/></Link></section>
        <section className="world-panel daily-quests"><header className="world-panel-title"><span><Flame/>{ar?"تحديات اليوم":"Today's challenges"}</span><b>{["lesson","practice","mission"].filter(kind=>daily.some(item=>item.kind===kind)).length}/3</b></header>{[["lesson",player.currentObjective.route,ar?"خطوة جديدة في رحلتك":"Take your next learning step","20"],["practice","/practice",ar?"وازن قيدًا يوميًا":"Balance a journal entry","30"],["mission","/missions",ar?"حل حالة عملية":"Solve a business case","100"]].map(([kind,route,label,xp])=><Link href={url(route)} key={kind}><span className={daily.some(item=>item.kind===kind)?"quest-check done":"quest-check"}>{daily.some(item=>item.kind===kind)?<Check/>:<Target/>}</span><b>{label}</b><small>+{xp} XP</small><ArrowRight/></Link>)}</section>
      </div>
      <aside className="command-side">
        <section className="world-panel reward-vault"><header className="world-panel-title"><span><Gift/>{ar?"خزنة الإنجازات":"Achievement vault"}</span></header><div className="reward-emblem"><Trophy/></div><small className="world-eyebrow">{nextReward?(ar?"المكافأة التالية":"NEXT REWARD"):(ar?"المجموعة مكتملة":"COLLECTION COMPLETE")}</small><h2>{nextReward?nextReward[ar?1:2]:(ar?"كل الشارات مفتوحة":"All badges unlocked")}</h2><p>{nextReward?nextReward[ar?3:4]:`${player.badges.length} ${ar?"شارات مكتسبة من أدائك":"badges earned through play"}`}</p><Link href={url("/profile")}>{ar?"افتح مجموعتك":"Open collection"}<ArrowRight/></Link></section>
        <Link className="world-panel mode-tile detective-mode" href={url("/detective")}><div className="mode-art"><FileSearch/><span>?</span></div><span className="world-eyebrow">{ar?"وضع التحقيق":"DETECTIVE MODE"}</span><h2>{ar?"الأرقام تخفي قصة":"The numbers hide a story"}</h2><p>{ar?"اجمع الأدلة. اكتشف الخطأ. أغلق القضية.":"Gather evidence. Find the error. Close the case."}</p><footer><span>+160 XP</span><b>{ar?"افتح الملف":"Investigate"}<ArrowRight/></b></footer></Link>
        <section className="world-panel skill-loadout"><header className="world-panel-title"><span><Award/>{ar?"المهارات والشهادات":"Skills & certificates"}</span></header>{skills.map(([id,score])=><div key={id}><span className={score?"skill-token earned":"skill-token"}><ShieldCheck/></span><span><b>{skillLabels[id as keyof typeof skillLabels][ar?"ar":"en"]}</b><small>{score?`${score}%`:(ar?"اكتسبها باللعب":"Earn through play")}</small></span></div>)}<Link href={url("/skills")}>{ar?"افتح شجرة المهارات":"Open skill tree"}<ArrowRight/></Link></section>
      </aside>
    </div>
    <section className="world-endgame">{[[Swords,"/arena","ARENA",ar?"ادخل الساحة":"Enter the Arena"],[Flame,"/arena/daily",ar?"التحدي اليومي":"DAILY CHALLENGE",ar?"اختبر نفسك اليوم":"Make today count"],[Trophy,"/leaderboard",ar?"لوحة الصدارة":"LEADERBOARD",ar?"تنافس على القمة":"Climb the ranks"],[ShieldCheck,"/career",ar?"المسار المهني":"CAREER PATH",`${player.careerReadiness}% ${ar?"جاهزية العمل":"career readiness"}`]].map(([Icon,path,label,title],i)=>{const Symbol=Icon as typeof Swords;return <Link href={url(String(path))} key={i}><Symbol/><span><small>{String(label)}</small><b>{String(title)}</b></span><ArrowRight/></Link>})}</section>
  </div>;
}
