import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpenCheck, BriefcaseBusiness, FileSearch, GitBranch, GraduationCap, ListChecks, Target, TrendingUp } from "lucide-react";
import type { Locale } from "@/types";

const features = [
  [BookOpenCheck,"افهم المدين والدائن","Learn debit & credit"], [ListChecks,"أتقن طبيعة الحسابات","Understand account nature"], [GitBranch,"تتبّع حركة الأموال","Follow money flow"], [GraduationCap,"ابنِ القيود اليومية","Build journal entries"],
  [Target,"أنجز مهامًا واقعية","Complete missions"], [FileSearch,"حقق في الأخطاء","Investigate accounting errors"], [BriefcaseBusiness,"ادخل بيئة العمل","Enter the Arena"], [TrendingUp,"تابع تطور مهاراتك","Track your skills"],
] as const;
export function ProductLanding({locale}:{locale:Locale}) { const ar=locale==='ar', Arrow=ar?ArrowLeft:ArrowRight; return <div className="dc-landing"><section className="dc-hero"><div><span className="dc-kicker">{ar?'تعليم محاسبي تفاعلي':'INTERACTIVE ACCOUNTING EDUCATION'}</span><h1>Debit <em>&</em> Credit</h1><h2>{ar?'تعلّم المحاسبة بالتطبيق':'Learn Accounting by Doing'}</h2><p>{ar?'منصة تدريب عملية تساعدك على فهم طبيعة الحسابات وحركة الأموال وبناء القيود، ثم تختبر قراراتك في مهام وتحقيقات ومحاكاة مهنية.':'A hands-on learning platform for account nature, money movement, journal entries, missions, investigations, and professional simulation.'}</p><small>by Money Coder</small><div className="dc-actions"><Link href={`/${locale}/learn`}>{ar?'ابدأ التعلّم':'Start Learning'}<Arrow/></Link><Link href={`/${locale}/arena`}>{ar?'ادخل الساحة':'Enter the Arena'}<BriefcaseBusiness/></Link></div></div><div className="dc-hero-card" aria-label={ar?'خريطة المسار':'Journey preview'}><span>01</span><b>{ar?'طبيعة الحساب':'Account nature'}</b><i/><span>02</span><b>{ar?'حركة الأموال':'Money flow'}</b><i/><span>03</span><b>{ar?'القيد اليومي':'Journal entry'}</b><i/><span>07</span><b>{ar?'جاهزية العمل':'Career readiness'}</b></div></section><section className="dc-feature-section"><header><span>{ar?'تدريب متكامل':'A COMPLETE PRACTICE SYSTEM'}</span><h2>{ar?'لا تشاهد المحاسبة فقط. مارسها.':'Don’t just watch accounting. Practice it.'}</h2></header><div>{features.map(([Icon,a,e])=><article key={e}><Icon/><h3>{ar?a:e}</h3><p>{ar?'شرح واضح، تفاعل عملي، وتغذية راجعة فورية.':'Clear instruction, hands-on interaction, and immediate feedback.'}</p></article>)}</div></section></div>; }
