"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Award, BookOpenCheck, BriefcaseBusiness, Building2, Check, ChevronRight, CircleDot, Coins, Crosshair, FileSearch, Flame, LockKeyhole, Map, Medal, Play, ShieldCheck, Sparkles, Swords, Target, Trophy, Zap } from "lucide-react";
import { usePlayer } from "@/components/game/use-player";
import { learningLevels, levelThresholds, skillLabels } from "@/data/game";
import { missions } from "@/data/missions";
import type { Locale } from "@/types";

export function ProductLanding({locale}:{locale:Locale}){
  const ar=locale==="ar",Arrow=ar?ArrowLeft:ArrowRight,player=usePlayer(),today=new Date().toISOString().slice(0,10),todayActivities=Object.values(player.activities).filter(item=>item.completedAt.startsWith(today));
  const mission=missions.find(item=>!player.activities[`mission:${item.id}`])??missions[0],currentLevel=learningLevels[player.level-1],nextThreshold=player.level===8?player.xp:levelThresholds[player.level];
  const topSkills=Object.entries(player.skillScores).sort(([,a],[,b])=>b-a).slice(0,4);
  const quick=[[Map,"learning-map","خريطة التعلم","Learning Map"],[BookOpenCheck,"practice","التدريب","Practice"],[ShieldCheck,"missions","المهام","Missions"],[FileSearch,"detective","المحقق","Detective"],[Swords,"arena","الساحة","Arena"],[Award,"skills","المهارات","Skills"]] as const;
  return <div className="command-center">
    <section className="command-hero"><div className="command-copy"><span><Sparkles/>{ar?"لعبة محاسبية تبني مستقبلك":"THE ACCOUNTING GAME THAT BUILDS YOUR CAREER"}</span><h1>{ar?<>العب. اتعلم المحاسبة. <em>واتوظف.</em></>:<>Play. Learn Accounting. <em>Get Hired.</em></>}</h1><p>{ar?"رحلة واحدة تربط التعلم بالتدريب والمهام الواقعية والتحقيق والساحة، وتحول أداءك إلى مهارات قابلة للقياس وملف مهني يمكن للشركات اكتشافه.":"One connected journey from lessons and practice to real missions, investigations, competition, measurable skills, and a talent profile companies can discover."}</p><div className="dc-actions"><Link href={`/${locale}${player.xp?player.currentObjective.route:"/learning-map"}`}><Play/>{player.xp?(ar?"أكمل رحلتك":"Continue journey"):(ar?"ابدأ اللعب والتعلم":"Start playing")}</Link><Link href={`/${locale}/companies`}><Building2/>{ar?"للشركات":"For companies"}</Link></div></div>
      <div className="player-card"><header><div className="player-avatar">{player.displayName.slice(0,1).toUpperCase()}</div><div><small>{ar?"مرحبًا بعودتك":"WELCOME BACK"}</small><h2>{player.displayName}</h2><p>{ar?currentLevel.titleAr:currentLevel.titleEn}</p></div><strong>{ar?"المستوى":"LVL"} {player.level}</strong></header><div className="level-meter"><span><b>{player.xp} XP</b><small>{player.level===8?(ar?"أعلى مستوى":"MAX LEVEL"):`${nextThreshold-player.xp} ${ar?"للمستوى التالي":"TO NEXT LEVEL"}`}</small></span><i><b style={{width:`${player.levelProgress}%`}}/></i></div><div className="player-mini-stats"><span><Zap/><b>{player.xp}</b><small>XP</small></span><span><Coins/><b>{player.coins}</b><small>{ar?"عملة":"Coins"}</small></span><span><Flame/><b>{player.streak}</b><small>{ar?"سلسلة":"Streak"}</small></span><span><Medal/><b>{player.badges.length}</b><small>{ar?"شارات":"Badges"}</small></span></div></div>
    </section>
    <section className="command-grid"><article className="current-mission"><header><span><Crosshair/>{ar?"المهمة الحالية":"CURRENT MISSION"}</span><em>{mission.difficulty}</em></header><div><small>{mission.caseNumber}</small><h2>{ar?mission.titleAr:mission.titleEn}</h2><p>{ar?mission.descriptionAr:mission.descriptionEn}</p><div className="mission-rewards"><span><Zap/>+100 XP</span><span><Coins/>+35</span><span>{mission.estimatedMinutes} {ar?"دقيقة":"min"}</span></div><Link href={`/${locale}/missions/${mission.slug}`}>{ar?"ابدأ المهمة":"Start mission"}<Arrow/></Link></div></article>
      <article className="current-objective"><header><Target/><span><small>{ar?"هدفك التالي":"NEXT OBJECTIVE"}</small><h2>{ar?player.currentObjective.titleAr:player.currentObjective.titleEn}</h2></span></header><p>{ar?"كل خطوة مكتملة تفتح محتوى أصعب وتضيف دليلًا جديدًا إلى ملف مهاراتك.":"Every completed step unlocks harder content and adds new evidence to your skill profile."}</p><div><span><Zap/>+{player.currentObjective.rewardXp} XP</span><span><Coins/>+{player.currentObjective.rewardCoins}</span></div><Link href={`/${locale}${player.currentObjective.route}`}>{ar?"نفّذ الهدف":"Do objective"}<Arrow/></Link></article>
    </section>
    <section className="command-section"><header><div><span>{ar?"رحلة واحدة · 8 مستويات":"ONE JOURNEY · 8 LEVELS"}</span><h2>{ar?"خريطة تعلم المحاسبة":"Your accounting learning map"}</h2></div><Link href={`/${locale}/learning-map`}>{ar?"عرض الخريطة":"View map"}<Arrow/></Link></header><div className="level-preview">{learningLevels.map(level=>{const state=level.id<player.level?"done":level.id===player.level?"current":"locked";return <article className={state} key={level.id}><span>{state==="done"?<Check/>:state==="locked"?<LockKeyhole/>:level.id}</span><small>{ar?"المستوى":"LEVEL"} {level.id}</small><b>{ar?level.titleAr:level.titleEn}</b><i/></article>})}</div></section>
    <section className="command-lower"><article className="today-card"><header><CircleDot/><div><small>{ar?"أهداف اليوم":"TODAY'S OBJECTIVES"}</small><h2>{ar?"ابنِ عادة المحاسب":"Build your accounting habit"}</h2></div><strong>{Math.min(3,todayActivities.length)}/3</strong></header>{[["lesson",ar?"أكمل درسًا واحدًا":"Complete one lesson"],["practice",ar?"حل تحدي تدريب":"Solve one practice"],["mission",ar?"أنجز مهمة عملية":"Complete one mission"]].map(([kind,label])=><div key={kind} className={todayActivities.some(item=>item.kind===kind)?"done":""}><span>{todayActivities.some(item=>item.kind===kind)?<Check/>:<CircleDot/>}</span><b>{label}</b></div>)}</article>
      <article className="skills-glance"><header><Trophy/><div><small>{ar?"تقدم المهارات":"SKILL PROGRESS"}</small><h2>{ar?"أداؤك المثبت":"Demonstrated performance"}</h2></div></header>{topSkills.map(([id,score])=><div key={id}><span><b>{skillLabels[id as keyof typeof skillLabels][ar?"ar":"en"]}</b><small>{score}%</small></span><i><b style={{width:`${score}%`}}/></i></div>)}<Link href={`/${locale}/skills`}>{ar?"كل المهارات والشهادات":"All skills & certificates"}<Arrow/></Link></article>
      <article className="readiness-card"><BriefcaseBusiness/><small>{ar?"جاهزية العمل":"CAREER READINESS"}</small><strong>{player.careerReadiness}%</strong><h2>{player.careerReadiness>=80?(ar?"جاهز لمهام Junior Accountant":"Junior Accountant Ready"):(ar?"تبني جاهزيتك المهنية":"Building professional readiness")}</h2><p>{ar?"محسوبة من تقدم المستويات والدقة والمهام والتحقيق والساحة والاستمرارية — وليست وعدًا بالتوظيف.":"Calculated from levels, accuracy, missions, investigations, Arena performance, and consistency—not a job guarantee."}</p><Link href={`/${locale}/career`}>{ar?"افتح المسار المهني":"Open career mode"}<ChevronRight/></Link></article>
    </section>
    <section className="quick-section"><header><span>{ar?"كل شيء داخل نفس اللعبة":"EVERYTHING IN ONE GAME"}</span><h2>{ar?"اختر وضع اللعب دون أن تفقد مكانك":"Choose a mode without losing your journey"}</h2></header><div>{quick.map(([Icon,path,a,e])=><Link href={`/${locale}/${path}`} key={path}><Icon/><b>{ar?a:e}</b><Arrow/></Link>)}</div></section>
    <section className="talent-cta"><div><span>{ar?"من اللعب إلى فرصة مهنية":"FROM PLAY TO OPPORTUNITY"}</span><h2>{ar?"أداء حقيقي. مهارات مثبتة. مواهب يمكن اكتشافها.":"Real performance. Verified skills. Discoverable talent."}</h2><p>{ar?"تتعرف الشركات على المتعلمين من خلال الدقة والحالات العملية وحل المشكلات، وليس درجات Quiz فقط.":"Companies discover learners through accuracy, practical cases, and problem solving—not quiz marks alone."}</p></div><Link href={`/${locale}/companies`}><Building2/>{ar?"استكشف بوابة الشركات":"Explore employer portal"}</Link></section>
  </div>;
}
